# Generated by Django 5.1.4 on 2026-09-01 14:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_documentflotte_course_km_depart_course_km_retour'),
    ]

    operations = [
        migrations.CreateModel(
            name='PleinCarburant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('societe_id', models.UUIDField()),
                ('camion_id', models.UUIDField(blank=True, null=True)),
                ('engin_id', models.UUIDField(blank=True, null=True)),
                ('course_id', models.UUIDField(blank=True, null=True)),
                ('date_plein', models.DateField()),
                ('litres', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_litre_usd', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('montant_usd', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('compteur', models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True)),
                ('fournisseur', models.CharField(blank=True, max_length=128, null=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'plein_carburant',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='engin',
            name='consommation_l_heure',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
