# Generated by Django 5.1.4 on 2026-09-04 11:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_pleincarburant_engin_consommation_l_heure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('societe_id', models.UUIDField()),
                ('numero', models.CharField(max_length=16)),
                ('categorie', models.CharField(blank=True, max_length=64, null=True)),
                ('tarif_nuit_usd', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('capacite', models.IntegerField(default=2)),
                ('etat', models.CharField(default='libre', max_length=16)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chambre',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LigneSejour',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sejour_id', models.UUIDField()),
                ('date_ligne', models.DateField()),
                ('designation', models.CharField(max_length=255)),
                ('qte', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('montant_usd', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('origine', models.CharField(default='divers', max_length=16)),
                ('facture_pos_id', models.UUIDField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ligne_sejour',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sejour',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('societe_id', models.UUIDField()),
                ('numero', models.CharField(max_length=32)),
                ('chambre_id', models.UUIDField()),
                ('tiers_id', models.UUIDField(blank=True, null=True)),
                ('client_nom', models.CharField(max_length=128)),
                ('client_telephone', models.CharField(blank=True, max_length=32, null=True)),
                ('nb_personnes', models.IntegerField(default=1)),
                ('date_arrivee', models.DateField()),
                ('date_depart_prevue', models.DateField()),
                ('date_depart', models.DateField(blank=True, null=True)),
                ('tarif_nuit_usd', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('statut', models.CharField(default='reservee', max_length=16)),
                ('source', models.CharField(default='directe', max_length=16)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('facture_id', models.UUIDField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sejour',
                'managed': True,
            },
        ),
    ]
