# Generated by Django 5.1.4 on 2026-09-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_cuisine_inventaires'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='nature',
            field=models.CharField(default='marchandise', max_length=20),
        ),
    ]
