# Generated by Django 5.1.4 on 2026-09-15 00:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_rh_lien_compte_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='rhcontrat',
            name='remuneration',
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name='RHDecompte',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_by', models.UUIDField()),
                ('updated_by', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_depart', models.DateField()),
                ('motif', models.CharField(max_length=30)),
                ('parametres', models.JSONField(default=dict)),
                ('resultat', models.JSONField(default=dict)),
                ('statut', models.CharField(default='preparation', max_length=24)),
                ('controle_note', models.TextField(blank=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.rhagent')),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.rhcontrat')),
                ('societe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.societe')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RHSimulation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_by', models.UUIDField()),
                ('updated_by', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=180)),
                ('parametres', models.JSONField(default=dict)),
                ('resultat', models.JSONField(default=dict)),
                ('societe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.societe')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
