# Generated by Django 5.1.4 on 2026-09-20 12:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_rh_paie_mensuelle'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='ReceptionInter',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('societe_id', models.UUIDField()),
                        ('commande_id', models.UUIDField()),
                        ('numero', models.CharField(max_length=32)),
                        ('date_reception', models.DateField()),
                        ('note', models.CharField(blank=True, max_length=255, null=True)),
                        ('statut', models.CharField(default='confirmee', max_length=16)),
                        ('confirme_par', models.UUIDField(blank=True, null=True)),
                        ('date_confirmation', models.DateTimeField(blank=True, null=True)),
                        ('created_by', models.UUIDField(blank=True, null=True)),
                        ('created_at', models.DateTimeField(blank=True, null=True)),
                    ],
                    options={
                        'db_table': 'reception_inter',
                        'managed': True,
                        'indexes': [],
                        'constraints': [],
                    },
                ),
                migrations.CreateModel(
                    name='LigneReceptionInter',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('reception_id', models.UUIDField()),
                        ('ligne_commande_id', models.UUIDField()),
                        ('qte_bon', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                        ('qte_mauvais', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                        ('qte_manquante', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                    ],
                    options={
                        'db_table': 'ligne_reception_inter',
                        'managed': True,
                        'indexes': [],
                        'constraints': [],
                    },
                ),
            ],
        ),
    ]
