# Generated by Django 5.1.4 on 2026-09-01 11:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArretPrestationEngin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prestation_id', models.UUIDField()),
                ('nature', models.CharField(default='Pause', max_length=32)),
                ('debut', models.CharField(max_length=5)),
                ('fin', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'arret_prestation_engin',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Engin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('societe_id', models.UUIDField()),
                ('nom', models.CharField(max_length=128)),
                ('categorie', models.CharField(blank=True, max_length=64, null=True)),
                ('immatriculation', models.CharField(blank=True, max_length=64, null=True)),
                ('tarif_mensuel_usd', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('tarif_heure_supp_usd', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('statut', models.CharField(default='disponible', max_length=16)),
                ('motif_immobilisation', models.CharField(blank=True, max_length=255, null=True)),
                ('immobilise_depuis', models.DateField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'engin',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PrestationEngin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('societe_id', models.UUIDField()),
                ('engin_id', models.UUIDField()),
                ('date_prestation', models.DateField()),
                ('poste', models.CharField(default='jour', max_length=8)),
                ('operateur', models.CharField(blank=True, max_length=128, null=True)),
                ('heure_debut', models.CharField(max_length=5)),
                ('heure_fin', models.CharField(max_length=5)),
                ('index_debut', models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True)),
                ('index_fin', models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True)),
                ('affectation', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'prestation_engin',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='interventioncamion',
            name='date_prevue',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interventioncamion',
            name='engin_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interventioncamion',
            name='camion_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
