# Generated by Django 5.1.4 on 2026-09-01 13:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_arretprestationengin_engin_prestationengin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanEntretien',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('societe_id', models.UUIDField()),
                ('camion_id', models.UUIDField(blank=True, null=True)),
                ('engin_id', models.UUIDField(blank=True, null=True)),
                ('libelle', models.CharField(max_length=128)),
                ('periodicite_type', models.CharField(default='heures', max_length=16)),
                ('periodicite_valeur', models.DecimalField(decimal_places=1, max_digits=12)),
                ('derniere_date', models.DateField(blank=True, null=True)),
                ('derniere_valeur', models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'plan_entretien',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='interventioncamion',
            name='plan_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
