# Generated by Django 5.1.4 on 2026-09-01 14:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_role_maintenancier'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentFlotte',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('societe_id', models.UUIDField()),
                ('camion_id', models.UUIDField(blank=True, null=True)),
                ('engin_id', models.UUIDField(blank=True, null=True)),
                ('chauffeur_id', models.UUIDField(blank=True, null=True)),
                ('type_document', models.CharField(default='autre', max_length=32)),
                ('libelle', models.CharField(max_length=128)),
                ('numero', models.CharField(blank=True, max_length=64, null=True)),
                ('date_emission', models.DateField(blank=True, null=True)),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'document_flotte',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='course',
            name='km_depart',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='km_retour',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True),
        ),
    ]
