# Generated by Django 5.1.4 on 2026-09-04 16:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_role_receptionniste'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('societe_id', models.UUIDField()),
                ('code', models.CharField(max_length=20)),
                ('libelle', models.CharField(max_length=128)),
                ('type', models.CharField(default='dedie', max_length=16)),
                ('actif', models.BooleanField(default=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'depot',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LigneTransfertDepot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transfert_id', models.UUIDField()),
                ('article_id', models.UUIDField()),
                ('qte', models.DecimalField(decimal_places=3, max_digits=18)),
                ('valeur', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
            ],
            options={
                'db_table': 'ligne_transfert_depot',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StockDepot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('depot_id', models.UUIDField()),
                ('article_id', models.UUIDField()),
                ('qte', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('valeur', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
            ],
            options={
                'db_table': 'stock_depot',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TransfertDepot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('societe_id', models.UUIDField()),
                ('numero', models.CharField(max_length=32)),
                ('depot_source_id', models.UUIDField()),
                ('depot_cible_id', models.UUIDField()),
                ('date_transfert', models.DateField()),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'transfert_depot',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='depot_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pointvente',
            name='depot_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
