# Generated by Django 5.1.4 on 2026-09-04 16:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_depot_central_backfill'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsommationCuisine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('societe_id', models.UUIDField()),
                ('numero', models.CharField(max_length=32)),
                ('depot_id', models.UUIDField()),
                ('date_conso', models.DateField()),
                ('cout_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('ca_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('nb_plats', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ecriture_id', models.UUIDField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'consommation_cuisine',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FicheTechnique',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('societe_id', models.UUIDField()),
                ('article_id', models.UUIDField()),
                ('portions', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fiche_technique',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InventaireDepot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('societe_id', models.UUIDField()),
                ('numero', models.CharField(max_length=32)),
                ('depot_id', models.UUIDField()),
                ('date_inventaire', models.DateField()),
                ('valeur_theorique', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('valeur_reelle', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('ecart_valeur', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('ecriture_id', models.UUIDField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inventaire_depot',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LigneConsommationCuisine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consommation_id', models.UUIDField()),
                ('article_id', models.UUIDField()),
                ('qte', models.DecimalField(decimal_places=4, max_digits=18)),
                ('valeur', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
            ],
            options={
                'db_table': 'ligne_consommation_cuisine',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LigneFicheTechnique',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fiche_id', models.UUIDField()),
                ('ingredient_article_id', models.UUIDField()),
                ('qte', models.DecimalField(decimal_places=4, max_digits=18)),
            ],
            options={
                'db_table': 'ligne_fiche_technique',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LigneInventaireDepot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inventaire_id', models.UUIDField()),
                ('article_id', models.UUIDField()),
                ('qte_theorique', models.DecimalField(decimal_places=3, max_digits=18)),
                ('qte_reelle', models.DecimalField(decimal_places=3, max_digits=18)),
                ('cump', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('ecart_qte', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('ecart_valeur', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
            ],
            options={
                'db_table': 'ligne_inventaire_depot',
                'managed': True,
            },
        ),
    ]
