# Generated by Django 5.1.4 on 2026-09-15 00:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rh_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='RHDette',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_by', models.UUIDField()),
                ('updated_by', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nature', models.CharField(max_length=30)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=18)),
                ('devise', models.CharField(max_length=3)),
                ('salaire_reference', models.DecimalField(decimal_places=2, max_digits=18)),
                ('plafond_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('echeancier', models.JSONField(default=list)),
                ('motif', models.TextField()),
                ('statut', models.CharField(default='attente_dfi', max_length=24)),
                ('decisions', models.JSONField(default=list)),
                ('verse_at', models.DateTimeField(blank=True, null=True)),
                ('mouvement_id', models.UUIDField(blank=True, null=True)),
                ('ecriture_id', models.UUIDField(blank=True, null=True)),
                ('accord', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.rhdocument')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.rhagent')),
                ('avance_source', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.avance')),
                ('demande', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.rhdemande')),
                ('societe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.societe')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RHPolitique',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_by', models.UUIDField()),
                ('updated_by', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plafond_avance_pct', models.DecimalField(decimal_places=2, default=30, max_digits=5)),
                ('delai_recouvrement_jours', models.PositiveIntegerField(default=30)),
                ('societe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.societe')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('societe',), name='rh_politique_societe_unique')],
            },
        ),
    ]
