# Generated by Django 5.1.4 on 2026-09-15 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_rh_accords_remboursement'),
    ]

    operations = [
        migrations.AddField(
            model_name='rhagent',
            name='tiers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.tiers'),
        ),
        migrations.AddConstraint(
            model_name='rhagent',
            constraint=models.UniqueConstraint(fields=('societe', 'tiers'), name='rh_tiers_unique'),
        ),
    ]
