# Generated by Django 5.1.4 on 2026-09-15 09:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_rh_simulations_decomptes'),
    ]

    operations = [
        migrations.CreateModel(
            name='RHBulletin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_by', models.UUIDField()),
                ('updated_by', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('saisie', models.JSONField(default=dict)),
                ('resultat', models.JSONField(default=dict)),
                ('empreinte_sources', models.CharField(max_length=64)),
                ('ecriture_id', models.UUIDField(blank=True, null=True)),
                ('net_comptable_usd', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.rhagent')),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.rhcontrat')),
                ('societe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.societe')),
            ],
        ),
        migrations.CreateModel(
            name='RHPaiement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_by', models.UUIDField()),
                ('updated_by', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mode', models.CharField(max_length=12)),
                ('date', models.DateField()),
                ('reference', models.CharField(max_length=64)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=18)),
                ('devise', models.CharField(max_length=3)),
                ('ecriture_id', models.UUIDField()),
                ('mouvement_id', models.UUIDField(blank=True, null=True)),
                ('bulletin', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.rhbulletin')),
                ('compte_bancaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.comptebancaire')),
                ('societe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.societe')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RHPaieMois',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_by', models.UUIDField()),
                ('updated_by', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mois', models.CharField(max_length=7)),
                ('parametres', models.JSONField(default=dict)),
                ('statut', models.CharField(default='brouillon', max_length=20)),
                ('decisions', models.JSONField(default=list)),
                ('societe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.societe')),
            ],
        ),
        migrations.AddField(
            model_name='rhbulletin',
            name='periode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.rhpaiemois'),
        ),
        migrations.CreateModel(
            name='RHRetenue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_by', models.UUIDField()),
                ('updated_by', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=18)),
                ('montant_usd', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('mois_echeance', models.CharField(max_length=7)),
                ('bulletin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.rhbulletin')),
                ('dette', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.rhdette')),
                ('societe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.societe')),
            ],
        ),
        migrations.AddConstraint(
            model_name='rhpaiemois',
            constraint=models.UniqueConstraint(fields=('societe', 'mois'), name='rh_paie_mois_unique'),
        ),
        migrations.AddConstraint(
            model_name='rhbulletin',
            constraint=models.UniqueConstraint(fields=('periode', 'agent'), name='rh_bulletin_mois_agent_unique'),
        ),
        migrations.AddConstraint(
            model_name='rhretenue',
            constraint=models.UniqueConstraint(fields=('bulletin', 'dette'), name='rh_retenue_bulletin_dette_unique'),
        ),
    ]
