# Generated by Django 5.1.4 on 2026-09-20 13:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_audit_protection'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperAdministrateur',
            fields=[
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='core.utilisateur')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changer_mot_de_passe', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'super_administrateur',
            },
        ),
        migrations.CreateModel(
            name='PermissionModule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module', models.CharField(max_length=32)),
                ('consulter', models.BooleanField(default=True)),
                ('creer', models.BooleanField(default=True)),
                ('modifier', models.BooleanField(default=True)),
                ('supprimer', models.BooleanField(default=True)),
                ('executer', models.BooleanField(default=True)),
                ('exporter', models.BooleanField(default=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.utilisateur')),
            ],
            options={
                'db_table': 'permission_module',
                'constraints': [models.UniqueConstraint(fields=('utilisateur', 'module'), name='permission_utilisateur_module_unique')],
            },
        ),
    ]
