'use client';
import { ScreenTitle } from './screen-presentation';
import { useCallback, useRef, useState } from 'react';
import { validateVatDraft, vatColumns, vatDraft, vatRows, type VatDraft, type VatFile, type VatState } from '../../lib/vat-data';
import { DataTable } from './data-table';
import { Field } from './field';
import { dateTime, Dialog, ErrorNotice, message, number, ReportPreview, today, useResource, type Report, type ScreenProps } from './shared';

export function AccountingVat({ bridge, state }: ScreenProps) {
  const [month, setMonth] = useState(today().slice(0, 7)), [tab, setTab] = useState('taux'), [edit, setEdit] = useState(false), [notice, setNotice] = useState(''), [preview, setPreview] = useState<Report | null>(null);
  const query = `?societe_id=${state.companyId}&mois=${month}`;
  const load = useCallback(async () => { const [current, file] = await Promise.all([bridge.api<VatState>('/comptabilite/tva-mensuelle' + query), bridge.api<VatFile>('/comptabilite/tva-mensuelle/dossier' + query)]); return { current, file }; }, [bridge, query]);
  const result = useResource(load), disabled = result.busy || !!result.error, data = result.data;
  const report = (snapshot: VatState, file?: VatFile): Report => ({ title: `TVA ${snapshot.mois} — ${file ? `état enregistré v${file.revision}` : 'état courant'}`, subtitle: `${snapshot.du} au ${snapshot.au} · USD · ${file ? `Sauvegardé le ${dateTime(file.updated_at)}` : 'Calcul à la dernière actualisation'}`, columns: vatColumns, rows: vatRows(snapshot), note: `${snapshot.note} Collectée validée : ${number(snapshot.totaux.valide.collectee)} USD ; déductible comptabilisée : ${number(snapshot.totaux.valide.deductible)} USD ; solde des mouvements : ${number(snapshot.solde_mouvements_usd)} USD. ${file ? `Crédit antérieur vérifié : ${file.donnees.credit_anterieur_cdf === '' || file.donnees.credit_anterieur_cdf == null ? 'non renseigné' : number(file.donnees.credit_anterieur_cdf) + ' CDF'}. Montant déclaré : ${file.donnees.montant_declare_cdf === '' || file.donnees.montant_declare_cdf == null ? 'non renseigné' : number(file.donnees.montant_declare_cdf) + ' CDF'}. Référence du dépôt : ${file.donnees.reference_depot || 'non renseignée'} ; date : ${file.donnees.date_depot || 'non renseignée'}. Notes : ${file.donnees.notes || 'aucune'}.` : ''} Document de préparation interne ; aucun dépôt ni paiement transmis à la DGI.` });
  return <><div className="audit-head"><div><ScreenTitle>TVA mensuelle</ScreenTitle><p className="muted">Dossier préparatoire de la société active</p></div><button className="btn" disabled={result.busy} onClick={result.refresh}><i className="ti ti-refresh" aria-hidden="true" /> Actualiser</button></div><div className="business-toolbar"><Field label="Mois de déclaration" type="month" required value={month} onChange={value => { if (/^\d{4}-\d{2}$/.test(value)) { setMonth(value); setNotice(''); } }} /><button className="btn" disabled={disabled || !data} onClick={() => setPreview(report(data!.current))}>État courant PDF / Excel</button><button className="btn" disabled={disabled || !data?.file.donnees.etat} onClick={() => setPreview(report(data!.file.donnees.etat!, data!.file))}>État enregistré PDF / Excel</button><button className="btn btn-primary" disabled={disabled || !data} onClick={() => setEdit(true)}>Préparer / modifier le dossier</button></div><ErrorNotice error={result.error} />{result.busy && <p role="status">Lecture du mois et du dossier…</p>}{notice && <p className="business-success" role="status">{notice}</p>}
    {data && !disabled && <><p className="banner">{data.current.note} Le dossier est conservé dans l’ERP ; aucun dépôt ni paiement n’est transmis à la DGI.</p><div className="caisse-cards">{[['TVA collectée — validée', data.current.totaux.valide.collectee], ['TVA déductible comptabilisée', data.current.totaux.valide.deductible], ['Solde des mouvements TVA', data.current.solde_mouvements_usd]].map(([label, value]) => <article className="caisse-card" key={label}><p>{label}</p><strong>{number(value)} USD</strong></article>)}</div><p className="muted">Pièces en attente exclues des indicateurs : collectée {number(data.current.totaux.en_attente.collectee)} USD · déductible {number(data.current.totaux.en_attente.deductible)} USD. Comptes suivis : {data.current.comptes.collectee} / {data.current.comptes.deductible} et subdivisions.</p>
      <article className="card"><div className="card-body"><h3>{data.file.revision ? `Dossier enregistré — version ${data.file.revision}` : 'Dossier à préparer'}</h3><p>{data.file.updated_at ? `Dernière sauvegarde : ${dateTime(data.file.updated_at)}` : 'Aucune sauvegarde pour ce mois.'}</p><p>{data.file.donnees.reference_depot ? `Dépôt renseigné : ${data.file.donnees.reference_depot} · ${data.file.donnees.date_depot}` : 'Dépôt non renseigné.'}</p><p className="muted">L’état enregistré conserve les chiffres de la dernière sauvegarde. L’état courant tient compte des écritures présentes maintenant.</p></div></article>
      <div className="business-toolbar" role="group" aria-label="Détails TVA">{[['taux', 'Ventilation par taux'], ['lignes', 'Écritures TVA'], ['factures', 'Factures commerciales']].map(([key, label]) => <button className={`btn ${tab === key ? 'btn-primary' : ''}`} key={key} aria-pressed={tab === key} onClick={() => setTab(key)}>{label}</button>)}</div>
      {tab === 'taux' && <><p className="muted">Les avoirs diminuent les montants. Les lignes sans TVA restent à qualifier : exonération, taux zéro… Les frais de facture sont inclus. Cette ventilation commerciale ne remplace pas le contrôle des autres modules et régularisations.</p><DataTable bridge={bridge} state={state} title="TVA — ventilation commerciale par taux" subtitle={`Mois ${month} · État courant · USD`} columns={['Opérations', 'Taux', 'Base HT USD', 'TVA USD']} rows={data.current.ventilation_taux.map(v => [v.sens === 'achats' ? 'Achats' : 'Ventes', Number(v.taux) === 0 ? 'Sans TVA — à qualifier' : `${number(v.taux)} %`, Number(v.ht_usd), Number(v.tva_usd)])} reportNote={data.current.note} /></>}
      {tab === 'lignes' && <DataTable bridge={bridge} state={state} title="Écritures TVA" subtitle={`Mois ${month} · Validées et en attente · USD`} columns={vatColumns} rows={vatRows(data.current)} reportNote={data.current.note} />}
      {tab === 'factures' && <DataTable bridge={bridge} state={state} title="Factures du dossier TVA" subtitle={`Mois ${month} · Factures commerciales non annulées et avoirs · USD`} columns={['Date', 'Numéro', 'Nature', 'Tiers', 'Statut', 'HT USD', 'TVA USD']} rows={data.current.factures.map(f => [f.date, f.numero, ({ vente: 'Vente', achat: 'Achat', avoir_vente: 'Avoir vente', avoir_achat: 'Avoir achat' } as Record<string, string>)[f.type] || f.type, f.tiers, f.statut, Number(f.ht_usd), Number(f.tva_usd)])} reportNote={data.current.note} />}
    </>}
    {edit && data && <VatEditor bridge={bridge} state={state} month={month} file={data.file} onClose={() => setEdit(false)} onSaved={revision => { setEdit(false); setNotice(`Dossier enregistré — version ${revision}.`); result.refresh(); }} />}
    {preview && <ReportPreview bridge={bridge} state={state} report={preview} onClose={() => setPreview(null)} />}
  </>;
}
function VatEditor({ bridge, state, month, file, onClose, onSaved }: ScreenProps & { month: string; file: VatFile; onClose: () => void; onSaved: (revision: number) => void }) {
  const [draft, setDraft] = useState(vatDraft(file)), [busy, setBusy] = useState(false), [error, setError] = useState(''), [failed, setFailed] = useState(false); const pending = useRef(false);
  const change = (key: keyof VatDraft, value: string) => setDraft(old => ({ ...old, [key]: value }));
  return <Dialog bridge={bridge} title={`Dossier TVA — ${month}`} busy={busy} onClose={onClose} footer={close => <><button className="btn" disabled={busy} onClick={close}>Fermer sans enregistrer</button><button className="btn btn-primary" disabled={busy || failed} type="submit" form="vat-file">Enregistrer le dossier et l’état courant</button></>}><p className="banner">Renseignez les montants de la déclaration vérifiée en CDF. Aucune conversion USD/CDF ni déductibilité n’est présumée. Cette sauvegarde remplace l’état enregistré du mois avec les chiffres recalculés au moment de l’enregistrement.</p><form id="vat-file" onSubmit={async e => { e.preventDefault(); if (pending.current || failed) return; setError(''); let payload; try { payload = validateVatDraft(draft, today()); } catch (e) { setError(message(e)); return; } pending.current = true; setBusy(true); try { const saved = await bridge.api<VatFile>(`/comptabilite/tva-mensuelle/dossier?societe_id=${state.companyId}&mois=${month}`, { method: 'POST', body: { ...payload, revision: file.revision } }); onSaved(saved.revision); } catch (e) { setError(message(e) + ' Fermez puis actualisez le dossier avant de reprendre la saisie.'); setFailed(true); } finally { pending.current = false; setBusy(false); } }}><fieldset className="business-fieldset" disabled={busy || failed}><div className="business-form-grid"><Field label="Crédit antérieur vérifié (CDF)" type="number" min="0" step="0.01" value={draft.credit_anterieur_cdf} onChange={v => change('credit_anterieur_cdf', v)} /><Field label="Montant déclaré à payer (CDF)" type="number" min="0" step="0.01" value={draft.montant_declare_cdf} onChange={v => change('montant_declare_cdf', v)} /><Field label="Référence du dépôt déjà effectué" maxLength={120} value={draft.reference_depot} onChange={v => change('reference_depot', v)} /><Field label="Date du dépôt" type="date" max={today()} value={draft.date_depot} onChange={v => change('date_depot', v)} /></div><label className="business-field">Justificatifs contrôlés, exonérations, régularisations et conversion retenue<textarea className="form-input" rows={5} maxLength={10000} value={draft.notes} onChange={e => change('notes', e.target.value)} /></label></fieldset><ErrorNotice error={error} /></form></Dialog>;
}
