'use client';
import { ScreenTitle } from './screen-presentation';
import { useCallback, useState } from 'react';
import { accountingStatuses, ledgerColumns, ledgerNote, ledgerRows, type BalanceData, type Entry, type LedgerAccount } from '../../lib/accounting-data';
import { EntryEditor, entryReport } from './accounting-entry';
import { DataTable } from './data-table';
import { Field } from './field';
import { Dialog, ErrorNotice, ReportPreview, number, today, useResource, type ScreenProps, type Report } from './shared';

function StatusFilter({ value, onChange }: { value: string; onChange: (value: string) => void }) {
  return <label className="business-field">Statut des écritures<select className="form-select" value={value} onChange={e => onChange(e.target.value)}>{Object.entries(accountingStatuses).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label>;
}
export function Balance({ bridge, state }: ScreenProps) {
  const [yearInput, setYearInput] = useState(today().slice(0, 4)), [year, setYear] = useState(yearInput), [status, setStatus] = useState(''), [classe, setClasse] = useState(''), [formError, setFormError] = useState('');
  const load = useCallback(() => bridge.api<BalanceData>(`/comptabilite/balance?${new URLSearchParams({ societe_id: state.companyId!, annee: year, statut: status, classe })}`), [bridge, state.companyId, year, status, classe]);
  const result = useResource(load), disabled = result.busy || !!result.error;
  const [editing, setEditing] = useState(false), [saved, setSaved] = useState<Entry | null>(null), [preview, setPreview] = useState<Report | null>(null), [account, setAccount] = useState<string | null>(null);
  const data = result.data, subtitle = `Exercice ${year} · ${accountingStatuses[status]} · ${classe ? `Classe ${classe}` : 'Toutes classes'} · USD`;
  const columns = ['Compte', 'Intitulé', 'Débit USD', 'Crédit USD', 'Solde débiteur USD', 'Solde créditeur USD', `Solde ${Number(year) - 1} USD`];
  const rows = data?.lignes.map(l => [l.compte, l.intitule, l.debit, l.credit, l.solde_debiteur, l.solde_crediteur, l.solde_n1]) || [];
  const note = 'Les mouvements de l’exercice et le solde N−1 sont présentés séparément, sans ajout automatique du solde N−1 aux mouvements N. La balance filtrée sur une classe peut présenter un écart sans que la balance générale soit déséquilibrée.';
  return <><div className="audit-head"><div><ScreenTitle>Balance générale</ScreenTitle><p className="muted">{subtitle}</p></div><div className="audit-actions"><button className="btn" disabled={result.busy} onClick={result.refresh}><i className="ti ti-refresh" aria-hidden="true" /> Actualiser</button><button className="btn" onClick={() => bridge.navigate('grand-livre')}>Grand livre</button><button className="btn btn-primary" onClick={() => setEditing(true)}>Saisir une écriture</button></div></div>
    <div className="business-toolbar"><form className="business-toolbar" onSubmit={e => { e.preventDefault(); if (!/^\d{4}$/.test(yearInput) || Number(yearInput) < 1900 || Number(yearInput) > 9999) { setFormError('Indiquez un exercice entre 1900 et 9999.'); return; } setFormError(''); setYear(yearInput); }}><Field label="Exercice" type="number" min={1900} max={9999} required value={yearInput} onChange={setYearInput} /><button className="btn" type="submit">Afficher l’exercice</button></form><StatusFilter value={status} onChange={setStatus} /><label className="business-field">Classe de comptes<select className="form-select" value={classe} onChange={e => setClasse(e.target.value)}><option value="">Toutes classes</option>{[1, 2, 3, 4, 5, 6, 7, 8, 9].map(c => <option key={c}>{c}</option>)}</select></label></div>
    <ErrorNotice error={formError || result.error} />{result.busy && <p role="status">Lecture de la balance…</p>}{saved && <p role="status" className="business-success">{saved.numero} enregistrée. <button className="btn btn-sm" onClick={() => setPreview(entryReport(saved))}>Pièce PDF / Excel</button></p>}
    <p className="banner">{status === '' ? 'Toutes les écritures sont incluses, y compris celles en attente de validation. ' : ''}{note}</p>
    {data && <><div className="caisse-cards">{[['Total débit', `${number(data.total_debit)} USD`], ['Total crédit', `${number(data.total_credit)} USD`], ['Écart du périmètre', `${number(data.total_debit - data.total_credit)} USD`], ['Comptes mouvementés', data.lignes.length]].map(([label, value]) => <article key={label} className="caisse-card"><p className="muted">{label}</p><strong>{disabled ? '—' : value}</strong></article>)}</div><p className={data.equilibre ? 'business-success' : 'banner'}>{disabled ? 'Actualisation du périmètre…' : classe ? `Classe ${classe} : ${data.equilibre ? 'totaux égaux' : 'écart débit / crédit sur cette classe'}` : data.equilibre ? 'Balance équilibrée' : 'Balance déséquilibrée — à contrôler'}</p>
      <button className="btn" disabled={disabled} onClick={() => setPreview({ title: 'Balance générale', subtitle, columns, rows: [...rows, ['', 'TOTAL DU PÉRIMÈTRE', data.total_debit, data.total_credit, data.lignes.reduce((s, l) => s + l.solde_debiteur, 0), data.lignes.reduce((s, l) => s + l.solde_crediteur, 0), data.lignes.reduce((s, l) => s + l.solde_n1, 0)]], note })}>Balance complète PDF / Excel</button>
      <DataTable key={`${year}-${status}-${classe}`} bridge={bridge} state={state} title="Comptes de la balance" subtitle={subtitle} reportNote={note} disabled={disabled} columns={columns} rows={rows} actions={row => <button className="btn btn-sm" disabled={disabled} onClick={() => setAccount(String(row[0]))}>Mouvements du compte</button>} />
    </>}{editing && <EntryEditor bridge={bridge} state={state} onClose={() => setEditing(false)} onSaved={entry => { setSaved(entry); setEditing(false); result.refresh(); }} />}{preview && <ReportPreview bridge={bridge} state={state} report={preview} onClose={() => setPreview(null)} />}{account && <AccountMovements bridge={bridge} state={state} account={account} status={status} onClose={() => setAccount(null)} />}</>;
}
export function GrandLedger({ bridge, state }: ScreenProps) {
  const [prefixInput, setPrefixInput] = useState(''), [prefix, setPrefix] = useState(''), [status, setStatus] = useState(''), [editing, setEditing] = useState(false), [saved, setSaved] = useState<Entry | null>(null), [selected, setSelected] = useState<LedgerAccount | null>(null), [preview, setPreview] = useState<Report | null>(null);
  const load = useCallback(() => bridge.api<LedgerAccount[]>(`/comptabilite/grand-livre?${new URLSearchParams({ societe_id: state.companyId!, compte: prefix, statut: status })}`), [bridge, state.companyId, prefix, status]);
  const result = useResource(load), disabled = result.busy || !!result.error, data = result.data;
  const subtitle = `Tout l’historique · ${accountingStatuses[status]} · ${prefix ? `Comptes commençant par ${prefix}` : 'Tous comptes'} · USD`;
  return <><div className="audit-head"><div><ScreenTitle>Grand livre</ScreenTitle><p className="muted">{subtitle}</p></div><div className="audit-actions"><button className="btn" disabled={result.busy} onClick={result.refresh}><i className="ti ti-refresh" aria-hidden="true" /> Actualiser</button><button className="btn" onClick={() => bridge.navigate('balance')}>Balance générale</button><button className="btn btn-primary" onClick={() => setEditing(true)}>Saisir une écriture</button></div></div>
    <div className="business-toolbar"><form className="business-toolbar" onSubmit={e => { e.preventDefault(); setPrefix(prefixInput.trim()); }}><Field label="Compte ou début de compte" value={prefixInput} onChange={setPrefixInput} placeholder="Ex. 401 ou 57" /><button className="btn" type="submit">Afficher les comptes</button><button className="btn" type="button" onClick={() => { setPrefix(''); setPrefixInput(''); }}>Tous les comptes</button></form><StatusFilter value={status} onChange={setStatus} /></div><ErrorNotice error={result.error} />{result.busy && <p role="status">Lecture des mouvements comptables…</p>}{saved && <p className="business-success" role="status">{saved.numero} enregistrée. <button className="btn btn-sm" onClick={() => setPreview(entryReport(saved))}>Pièce PDF / Excel</button></p>}<p className="banner">{ledgerNote} {status === '' && 'Les écritures en attente sont incluses et identifiées.'}</p>
    {data && <><div className="caisse-cards"><article className="caisse-card"><p className="muted">Comptes</p><strong>{disabled ? '—' : data.length}</strong></article><article className="caisse-card"><p className="muted">Mouvements</p><strong>{disabled ? '—' : data.reduce((n, a) => n + a.mouvements.length, 0)}</strong></article></div><button className="btn" disabled={disabled || !data.length} onClick={() => setPreview({ title: 'Grand livre détaillé', subtitle, columns: ledgerColumns, rows: ledgerRows(data), note: ledgerNote })}>Tous les mouvements PDF / Excel</button><DataTable key={`${prefix}-${status}`} bridge={bridge} state={state} title="Comptes du grand livre" subtitle={subtitle} reportNote={ledgerNote} disabled={disabled} columns={['Compte', 'Intitulé', 'Mouvements', 'Débit USD', 'Crédit USD', 'Solde USD']} rows={data.map(a => [a.compte, a.intitule, a.mouvements.length, a.mouvements.reduce((s, m) => s + m.debit, 0), a.mouvements.reduce((s, m) => s + m.credit, 0), a.solde])} actions={row => <button className="btn btn-sm" disabled={disabled} onClick={() => setSelected(data.find(a => a.compte === row[0])!)}>Consulter les mouvements</button>} /></>}
    {selected && <Dialog bridge={bridge} title={`${selected.compte} — ${selected.intitule}`} onClose={() => setSelected(null)}><LedgerDetails bridge={bridge} state={state} account={selected} subtitle={subtitle} /></Dialog>}{editing && <EntryEditor bridge={bridge} state={state} onClose={() => setEditing(false)} onSaved={entry => { setSaved(entry); setEditing(false); result.refresh(); }} />}{preview && <ReportPreview bridge={bridge} state={state} report={preview} onClose={() => setPreview(null)} />}</>;
}
function LedgerDetails({ bridge, state, account, subtitle }: ScreenProps & { account: LedgerAccount; subtitle: string }) {
  return <><p className="banner">{ledgerNote}</p><p><b>Solde : {number(Math.abs(account.solde))} USD {account.solde > 0 ? 'débiteur' : account.solde < 0 ? 'créditeur' : ''}</b></p><DataTable bridge={bridge} state={state} title={`Grand livre ${account.compte}`} subtitle={subtitle} reportNote={ledgerNote} columns={ledgerColumns.slice(2)} rows={ledgerRows([account]).map(r => r.slice(2))} /></>;
}
function AccountMovements({ bridge, state, account, status, onClose }: ScreenProps & { account: string; status: string; onClose: () => void }) {
  const load = useCallback(() => bridge.api<LedgerAccount[]>(`/comptabilite/grand-livre?${new URLSearchParams({ societe_id: state.companyId!, compte: account, statut: status })}`), [bridge, state.companyId, account, status]);
  const result = useResource(load), selected = result.data?.find(a => a.compte === account);
  return <Dialog bridge={bridge} title={`Mouvements du compte ${account} · Tout l’historique`} onClose={onClose}><ErrorNotice error={result.error} />{result.busy && <p role="status">Lecture du compte…</p>}{result.error && <button className="btn" onClick={result.refresh}>Réessayer</button>}{selected && !result.busy && !result.error && <LedgerDetails bridge={bridge} state={state} account={selected} subtitle={`Tout l’historique · ${accountingStatuses[status]} · USD`} />}{result.data && !selected && <p>Aucun mouvement pour ce compte.</p>}</Dialog>;
}
