'use client';
import { ScreenTitle } from './screen-presentation';
import { useCallback, useRef, useState } from 'react';
import { entryPayload, entryTotals, partyLabel, type Account, type Entry, type EntryLine, type Journal, type Party } from '../../lib/accounting-data';
import { AccountingPartyPicker } from './accounting-party';
import { Field } from './field';
import { Dialog, ErrorNotice, ReportPreview, message, number, today, useResource, type Report, type ScreenProps } from './shared';

export function entryReport(entry: Entry): Report {
  return { title: `Écriture comptable ${entry.numero}`, subtitle: `${entry.date} · Journal ${entry.journal} · ${entry.statut === 'valide' ? 'Validée' : entry.statut} · Montants USD`, columns: ['Compte', 'Intitulé', 'Tiers', 'Libellé ligne', 'Débit USD', 'Crédit USD'], rows: [...entry.lignes.map(l => [l.compte, l.intitule, l.tiers || '', l.libelle || '', l.sens === 'D' ? l.montant_usd : 0, l.sens === 'C' ? l.montant_usd : 0]), ['', 'TOTAL', '', '', entry.montant, entry.montant]], note: `${entry.libelle}${entry.piece ? ` · Référence : ${entry.piece}` : ''}. Document comptable ; ne constitue pas une preuve de paiement.` };
}
export function AccountingEntry({ bridge, state }: ScreenProps) {
  const [editing, setEditing] = useState(false), [saved, setSaved] = useState<Entry | null>(null), [preview, setPreview] = useState(false);
  return <><div className="audit-head"><div><ScreenTitle>Saisie d’écritures</ScreenTitle><p className="muted">Opérations diverses en USD · Société active</p></div><div className="audit-actions"><button className="btn" onClick={() => bridge.navigate('balance')}>Balance générale</button><button className="btn" onClick={() => bridge.navigate('grand-livre')}>Grand livre</button><button className="btn btn-primary" onClick={() => setEditing(true)}>Nouvelle écriture</button></div></div>
    <p className="banner">La saisie manuelle existante enregistre une écriture directement validée, réservée au comptable / DFI. Vérifiez la date, les comptes, les tiers et l’équilibre avant de confirmer. Les opérations des autres modules conservent leurs propres circuits de validation.</p>
    {saved ? <article className="card"><div className="card-body"><p className="business-success" role="status">{saved.numero} enregistrée et validée · {number(saved.montant)} USD au débit et au crédit.</p><p>{saved.date} · {saved.libelle}</p><button className="btn" onClick={() => setPreview(true)}>Pièce PDF / Excel / imprimer</button></div></article> : <p>Préparez vos lignes de débit et de crédit dans le même formulaire. Aucune ligne incomplète ne sera ignorée.</p>}
    {editing && <EntryEditor bridge={bridge} state={state} onClose={() => setEditing(false)} onSaved={e => { setSaved(e); setEditing(false); }} />}{preview && saved && <ReportPreview bridge={bridge} state={state} report={entryReport(saved)} onClose={() => setPreview(false)} />}
  </>;
}
export function EntryEditor({ bridge, state, onClose, onSaved }: ScreenProps & { onClose: () => void; onSaved: (entry: Entry) => void }) {
  const load = useCallback(async () => { const [accounts, journals, parties] = await Promise.all([bridge.api<Account[]>(`/comptabilite/plan-comptable?societe_id=${state.companyId}`), bridge.api<Journal[]>(`/comptabilite/journaux?societe_id=${state.companyId}`), bridge.api<Party[]>(`/tiers?societe_id=${state.companyId}`)]); return { accounts, journals, parties }; }, [bridge, state.companyId]);
  const result = useResource(load), [busy, setBusy] = useState(false);
  return <Dialog bridge={bridge} title="Nouvelle écriture comptable" busy={busy} onClose={onClose} footer={close => <><button className="btn" disabled={busy} onClick={close}>Fermer</button>{result.data && !result.error && <button className="btn btn-primary" disabled={busy || result.busy} type="submit" form="accounting-entry">Vérifier l’écriture</button>}</>}><ErrorNotice error={result.error} />{result.error && <button className="btn" onClick={result.refresh}>Réessayer le chargement</button>}{result.busy && <p role="status">Lecture du plan comptable, des journaux et des tiers…</p>}{result.data && !result.error && !result.busy && <EntryForm bridge={bridge} state={state} {...result.data} onSaved={onSaved} onBusy={setBusy} />}</Dialog>;
}
function EntryForm({ bridge, state, accounts, journals, parties: initialParties, onSaved, onBusy }: ScreenProps & { accounts: Account[]; journals: Journal[]; parties: Party[]; onSaved: (entry: Entry) => void; onBusy: (busy: boolean) => void }) {
  const activeJournals = journals.filter(j => j.actif);
  const [journal, setJournal] = useState(activeJournals.find(j => j.code === 'OD')?.code || activeJournals[0]?.code || ''), [day, setDay] = useState(today), [label, setLabel] = useState(''), [reference, setReference] = useState('');
  const [lines, setLines] = useState<EntryLine[]>([{ key: 1, sens: 'D', compte: '', tiers_id: '', libelle: '', montant: '' }, { key: 2, sens: 'C', compte: '', tiers_id: '', libelle: '', montant: '' }]), [parties, setParties] = useState(initialParties), [partyLine, setPartyLine] = useState<number | null>(null), [error, setError] = useState(''), [review, setReview] = useState(false), [busy, setBusy] = useState(false), [uncertain, setUncertain] = useState(false);
  const sequence = useRef(2), pending = useRef(false), totals = entryTotals(lines);
  const update = (key: number, patch: Partial<EntryLine>) => setLines(old => old.map(l => l.key === key ? { ...l, ...patch } : l));
  const payload = () => entryPayload(lines, accounts, parties, state.companyId!, journal, day, label, reference);
  const save = async () => { if (pending.current || uncertain) return; pending.current = true; setBusy(true); onBusy(true); setError(''); try { const entry = await bridge.api<Entry>(`/comptabilite/ecritures/saisie?societe_id=${state.companyId}`, { method: 'POST', body: payload() }); onSaved(entry); } catch (cause) { const status = (cause as { status?: number }).status; setError(message(cause)); if (!status || status >= 500) setUncertain(true); setReview(false); } finally { pending.current = false; setBusy(false); onBusy(false); } };
  return <><form id="accounting-entry" onSubmit={e => { e.preventDefault(); if (busy || uncertain) return; setError(''); try { payload(); setReview(true); } catch (cause) { setError(message(cause)); } }}>
    <ErrorNotice error={error} />{uncertain && <p className="business-error">Le résultat de l’enregistrement est incertain. Fermez cette fenêtre et contrôlez le grand livre avant de saisir à nouveau cette opération.</p>}
    <fieldset className="business-fieldset" disabled={busy || uncertain}><div className="business-form-grid"><label className="business-field">Journal<select className="form-select" required value={journal} onChange={e => setJournal(e.target.value)}><option value="">Choisir un journal</option>{activeJournals.map(j => <option key={j.id} value={j.code}>{j.code} — {j.libelle}</option>)}</select></label><Field label="Date de l’écriture" type="date" required value={day} onChange={setDay} /><Field label="Libellé de l’écriture" required value={label} onChange={setLabel} maxLength={500} /><Field label="Référence de la pièce (facultative)" value={reference} onChange={setReference} maxLength={100} /></div>
      {lines.map((line, index) => <fieldset className="accounting-entry-line" key={line.key}><legend>Ligne {index + 1}</legend><div className="business-form-grid"><label className="business-field">Sens ligne {index + 1}<select className="form-select" value={line.sens} onChange={e => update(line.key, { sens: e.target.value as 'D' | 'C' })}><option value="D">Débit</option><option value="C">Crédit</option></select></label><label className="business-field">Compte ligne {index + 1}<select className="form-select" required value={line.compte} onChange={e => update(line.key, { compte: e.target.value })}><option value="">Choisir un compte</option>{accounts.map(a => <option key={a.id} value={a.numero}>{a.numero} — {a.intitule}{a.actif ? '' : ' (inactif)'}</option>)}</select></label><Field label={`Montant USD ligne ${index + 1}`} type="number" min="0.01" step="0.01" required value={line.montant} onChange={v => update(line.key, { montant: v })} /><Field label={`Libellé ligne ${index + 1}`} value={line.libelle} maxLength={500} onChange={v => update(line.key, { libelle: v })} /></div><p className="muted">Tiers : {line.tiers_id ? partyLabel(parties.find(p => p.id === line.tiers_id)!) : 'Aucun tiers'}</p><div className="business-toolbar"><button className="btn btn-sm" type="button" onClick={() => setPartyLine(line.key)}>Choisir / créer un tiers · ligne {index + 1}</button>{line.tiers_id && <button className="btn btn-sm" type="button" onClick={() => update(line.key, { tiers_id: '' })}>Retirer le tiers · ligne {index + 1}</button>}<button className="btn btn-sm" type="button" disabled={lines.length <= 2} onClick={() => setLines(old => old.filter(l => l.key !== line.key))}>Retirer la ligne {index + 1}</button></div></fieldset>)}
      <button className="btn" type="button" onClick={() => setLines(old => [...old, { key: ++sequence.current, sens: 'D', compte: '', tiers_id: '', libelle: '', montant: '' }])}>Ajouter une ligne</button>
    </fieldset><p className={totals.balanced ? 'business-success' : 'banner'} role="status">Débit : {number(totals.debit)} USD · Crédit : {number(totals.credit)} USD · Écart : {number(totals.difference)} USD{totals.balanced ? ' · Équilibrée' : ' · À compléter ou corriger'}</p><p className="muted">L’enregistrement sera directement validé selon le fonctionnement actuel de la saisie manuelle.</p>
  </form>
    {partyLine !== null && <AccountingPartyPicker bridge={bridge} state={state} parties={parties} onClose={() => setPartyLine(null)} onSelected={p => { setParties(old => [...old.filter(t => t.id !== p.id), p]); update(partyLine, { tiers_id: p.id }); setPartyLine(null); }} />}
    {review && <Dialog bridge={bridge} title="Confirmer l’écriture comptable" busy={busy} onClose={() => setReview(false)} footer={close => <><button className="btn" disabled={busy} onClick={close}>Revenir à la saisie</button><button className="btn btn-primary" disabled={busy} onClick={save}>Enregistrer l’écriture validée</button></>}><p><b>{label}</b> · {day} · Journal {journal}</p><p>{lines.length} lignes · Débit {number(totals.debit)} USD = Crédit {number(totals.credit)} USD.</p><p>Cette confirmation inscrit immédiatement l’écriture validée dans la comptabilité de {state.companies.find(c => c.id === state.companyId)?.nom}.</p></Dialog>}
  </>;
}
