'use client';
import { ScreenTitle } from './screen-presentation';
import { useCallback, useRef, useState } from 'react';
import type { Account, Journal } from '../../lib/accounting-data';
import { DataTable } from './data-table';
import { Field } from './field';
import { Dialog, ErrorNotice, message, useResource, type ScreenProps } from './shared';

interface AccountConfig { comptes: { cle: string; libelle: string; valeur: string; defaut: string; intitule: string }[]; tva_taux_defaut: number }
interface ReviewConfig { revue_achats: boolean; revue_ventes: boolean }
const journalTypes: Record<string, string> = { od: 'Opérations diverses', achat: 'Achats', vente: 'Ventes', banque: 'Banque', caisse: 'Caisse', ouverture: 'À-nouveaux' };

export function AccountingPlan({ bridge, state }: ScreenProps) {
  const load = useCallback(async () => {
    const suffix = `?societe_id=${state.companyId}`;
    const [accounts, journals, config, review] = await Promise.all([bridge.api<Account[]>('/comptabilite/plan-comptable' + suffix), bridge.api<Journal[]>('/comptabilite/journaux' + suffix), bridge.api<AccountConfig>('/comptabilite/comptes-config' + suffix), bridge.api<ReviewConfig>('/comptabilite/revue-config' + suffix)]);
    return { accounts, journals, config, review };
  }, [bridge, state.companyId]);
  const result = useResource(load), data = result.data, disabled = result.busy || !!result.error;
  const [tab, setTab] = useState('comptes'), [classe, setClasse] = useState(''), [active, setActive] = useState(''), [account, setAccount] = useState<Account | 'new' | null>(null), [journal, setJournal] = useState(false), [config, setConfig] = useState(false), [review, setReview] = useState(false), [success, setSuccess] = useState('');
  const saved = (text: string) => { setAccount(null); setJournal(false); setConfig(false); setReview(false); setSuccess(text); result.refresh(); };
  return <><div className="audit-head"><div><ScreenTitle>Plan comptable & journaux</ScreenTitle><p className="muted">Comptes et paramètres propres à la société active</p></div><button className="btn" disabled={result.busy} onClick={result.refresh}><i className="ti ti-refresh" aria-hidden="true" /> Actualiser</button></div><div className="business-toolbar" role="group" aria-label="Rubriques du plan comptable">{[['comptes', 'Comptes'], ['journaux', 'Journaux'], ['config', 'Comptes automatiques & TVA']].map(([key, label]) => <button className={`btn ${tab === key ? 'btn-primary' : ''}`} aria-pressed={tab === key} key={key} onClick={() => setTab(key)}>{label}</button>)}</div><ErrorNotice error={result.error} />{result.busy && <p role="status">Lecture du plan et des paramètres…</p>}{success && <p className="business-success" role="status">{success}</p>}
    {data && <>{tab === 'comptes' && <><div className="business-toolbar"><label className="business-field">Classe<select className="form-select" value={classe} onChange={e => setClasse(e.target.value)}><option value="">Toutes classes</option>{Array.from(new Set(data.accounts.map(a => a.classe))).sort().map(c => <option key={c} value={c}>Classe {c}</option>)}</select></label><label className="business-field">État des comptes<select className="form-select" value={active} onChange={e => setActive(e.target.value)}><option value="">Actifs et inactifs</option><option value="oui">Actifs</option><option value="non">Inactifs</option></select></label><button className="btn btn-primary" disabled={disabled} onClick={() => setAccount('new')}>Nouveau compte</button></div><DataTable key={`${classe}-${active}`} bridge={bridge} state={state} title="Plan comptable" subtitle={`${classe ? `Classe ${classe}` : 'Toutes classes'} · ${active === 'oui' ? 'Actifs' : active === 'non' ? 'Inactifs' : 'Actifs et inactifs'}`} disabled={disabled} columns={['Compte', 'Intitulé', 'Classe', 'Auxiliaire', 'État']} rows={data.accounts.filter(a => (!classe || a.classe === classe) && (!active || a.actif === (active === 'oui'))).map(a => [a.numero, a.intitule, a.classe, a.auxiliaire ? 'Oui' : 'Non', a.actif ? 'Actif' : 'Inactif'])} actions={row => <button className="btn btn-sm" disabled={disabled} onClick={() => setAccount(data.accounts.find(a => a.numero === row[0])!)}><i className="ti ti-edit" aria-hidden="true" /> Modifier</button>} /></>}
      {tab === 'journaux' && <><button className="btn btn-primary" disabled={disabled} onClick={() => setJournal(true)}>Nouveau journal</button><DataTable bridge={bridge} state={state} title="Journaux comptables" subtitle="Société active" disabled={disabled} columns={['Code', 'Libellé', 'Type', 'État']} rows={data.journals.map(j => [j.code, j.libelle, journalTypes[j.type] || j.type, j.actif ? 'Actif' : 'Inactif'])} /></>}
      {tab === 'config' && <><p className="banner">Ces paramètres pilotent les prochaines écritures automatiques. Les modifications des comptes et de la TVA sont enregistrées séparément des règles de validation.</p><button className="btn" disabled={disabled} onClick={() => setConfig(true)}>Modifier les comptes et la TVA</button><DataTable bridge={bridge} state={state} title="Comptes des opérations automatiques" subtitle={`TVA par défaut : ${data.config.tva_taux_defaut} % · Société active`} disabled={disabled} columns={['Utilisation', 'Compte', 'Intitulé']} rows={data.config.comptes.map(c => [c.libelle, c.valeur, c.intitule || 'Absent du plan — à contrôler'])} /><article className="card"><div className="card-body"><h3>Revue comptable</h3><p>Achats : {data.review.revue_achats ? 'validation comptable requise' : 'comptabilisation directe'}.</p><p>Ventes à crédit : {data.review.revue_ventes ? 'validation comptable requise' : 'comptabilisation directe'}.</p><p className="muted">Les ventes POS / comptant conservent leur traitement direct.</p><button className="btn" disabled={disabled} onClick={() => setReview(true)}>Modifier les règles de validation</button></div></article></>}
      {account && <AccountEditor bridge={bridge} state={state} account={account === 'new' ? null : account} accounts={data.accounts} onClose={() => setAccount(null)} onSaved={() => saved('Compte enregistré.')} />}
      {journal && <JournalEditor bridge={bridge} state={state} journals={data.journals} onClose={() => setJournal(false)} onSaved={() => saved('Journal créé.')} />}
      {config && <AccountConfigEditor bridge={bridge} state={state} config={data.config} accounts={data.accounts} onClose={() => setConfig(false)} onSaved={() => saved('Comptes automatiques et TVA enregistrés. Les règles de validation sont inchangées.')} />}
      {review && <ReviewEditor bridge={bridge} state={state} review={data.review} onClose={() => setReview(false)} onSaved={() => saved('Règles de validation enregistrées.')} />}
    </>}
  </>;
}
type EditorProps = ScreenProps & { onClose: () => void; onSaved: () => void };
function AccountEditor({ bridge, state, account, accounts, onClose, onSaved }: EditorProps & { account: Account | null; accounts: Account[] }) {
  const [code, setCode] = useState(account?.numero || ''), [label, setLabel] = useState(account?.intitule || ''), [aux, setAux] = useState(account?.auxiliaire || false), [active, setActive] = useState(account?.actif ?? true), [busy, setBusy] = useState(false), [error, setError] = useState(''); const pending = useRef(false);
  return <Dialog bridge={bridge} title={account ? `Compte ${account.numero}` : 'Nouveau compte'} busy={busy} onClose={onClose} footer={close => <><button className="btn" disabled={busy} onClick={close}><i className="ti ti-x" aria-hidden="true" /> Annuler</button><button className="btn btn-primary" type="submit" form="account-editor" disabled={busy}><i className="ti ti-device-floppy" aria-hidden="true" /> Enregistrer</button></>}><form id="account-editor" onSubmit={async e => { e.preventDefault(); if (pending.current) return; setError(''); if (!label.trim() || !code.trim()) { setError('Numéro et intitulé requis.'); return; } if (!account && accounts.some(a => a.numero === code.trim())) { setError('Ce numéro de compte existe déjà dans le plan.'); return; } pending.current = true; setBusy(true); try { await bridge.api(account ? `/comptabilite/plan-comptable/${account.id}` : `/comptabilite/plan-comptable?societe_id=${state.companyId}`, { method: account ? 'PATCH' : 'POST', body: account ? { intitule: label.trim(), actif: active } : { numero: code.trim(), intitule: label.trim(), auxiliaire: aux } }); onSaved(); } catch (cause) { setError(message(cause)); } finally { pending.current = false; setBusy(false); } }}><fieldset className="business-fieldset" disabled={busy}><Field label="Numéro de compte" required readOnly={!!account} maxLength={20} value={code} onChange={setCode} /><Field label="Intitulé du compte" required maxLength={255} value={label} onChange={setLabel} />{account ? <><p className="muted">{account.auxiliaire ? 'Compte auxiliaire' : 'Compte général'}</p><label className="business-check"><input type="checkbox" checked={active} onChange={e => setActive(e.target.checked)} /> Compte actif</label></> : <label className="business-check"><input type="checkbox" checked={aux} onChange={e => setAux(e.target.checked)} /> Compte auxiliaire (ventilé par tiers)</label>}</fieldset><ErrorNotice error={error} /></form></Dialog>;
}
function JournalEditor({ bridge, state, journals, onClose, onSaved }: EditorProps & { journals: Journal[] }) {
  const [code, setCode] = useState(''), [label, setLabel] = useState(''), [kind, setKind] = useState('od'), [busy, setBusy] = useState(false), [error, setError] = useState(''); const pending = useRef(false);
  return <Dialog bridge={bridge} title="Nouveau journal" busy={busy} onClose={onClose} footer={close => <><button className="btn" disabled={busy} onClick={close}><i className="ti ti-x" aria-hidden="true" /> Annuler</button><button className="btn btn-primary" type="submit" form="journal-editor" disabled={busy}>Créer le journal</button></>}><form id="journal-editor" onSubmit={async e => { e.preventDefault(); if (pending.current) return; setError(''); if (!code.trim() || !label.trim()) { setError('Code et libellé requis.'); return; } if (journals.some(j => j.code === code.trim().toUpperCase())) { setError('Ce code de journal existe déjà.'); return; } pending.current = true; setBusy(true); try { await bridge.api(`/comptabilite/journaux?societe_id=${state.companyId}`, { method: 'POST', body: { code: code.trim().toUpperCase(), libelle: label.trim(), type: kind } }); onSaved(); } catch (cause) { setError(message(cause)); } finally { pending.current = false; setBusy(false); } }}><fieldset className="business-fieldset" disabled={busy}><Field label="Code du journal" required maxLength={10} value={code} onChange={setCode} /><Field label="Libellé du journal" required maxLength={255} value={label} onChange={setLabel} /><label className="business-field">Type de journal<select className="form-select" value={kind} onChange={e => setKind(e.target.value)}>{Object.entries(journalTypes).map(([code, label]) => <option key={code} value={code}>{label}</option>)}</select></label></fieldset><ErrorNotice error={error} /></form></Dialog>;
}
function AccountConfigEditor({ bridge, state, config, accounts, onClose, onSaved }: EditorProps & { config: AccountConfig; accounts: Account[] }) {
  const [values, setValues] = useState(Object.fromEntries(config.comptes.map(c => [c.cle, c.valeur]))), [tva, setTva] = useState(String(config.tva_taux_defaut)), [busy, setBusy] = useState(false), [error, setError] = useState(''); const pending = useRef(false);
  return <Dialog bridge={bridge} title="Comptes automatiques et TVA" busy={busy} onClose={onClose} footer={close => <><button className="btn" disabled={busy} onClick={close}><i className="ti ti-x" aria-hidden="true" /> Annuler</button><button className="btn btn-primary" type="submit" form="account-config" disabled={busy}>Enregistrer comptes et TVA</button></>}><form id="account-config" onSubmit={async e => { e.preventDefault(); if (pending.current) return; setError(''); if (!tva.trim() || !Number.isFinite(Number(tva)) || Number(tva) < 0 || Number(tva) > 100) { setError('Le taux doit être compris entre 0 et 100 %.'); return; } pending.current = true; setBusy(true); try { await bridge.api(`/comptabilite/comptes-config?societe_id=${state.companyId}`, { method: 'POST', body: { config: Object.fromEntries(Object.entries(values).filter(([, value]) => value.trim()).map(([key, value]) => [key, value.trim()])), tva_taux_defaut: Number(tva) } }); onSaved(); } catch (cause) { setError(message(cause)); } finally { pending.current = false; setBusy(false); } }}><p className="banner">Ces comptes sont utilisés par les prochaines opérations. Vérifiez chaque correspondance ; les comptes absents du plan sont signalés.</p><fieldset className="business-fieldset" disabled={busy}><datalist id="config-account-list">{accounts.map(a => <option key={a.id} value={a.numero}>{a.intitule}</option>)}</datalist><div className="business-form-grid">{config.comptes.map(c => <div key={c.cle}><Field label={c.libelle} list="config-account-list" maxLength={20} value={values[c.cle]} onChange={v => setValues(old => ({ ...old, [c.cle]: v }))} /><p className="muted">{accounts.find(a => a.numero === values[c.cle].trim())?.intitule || (values[c.cle].trim() ? 'Compte absent du plan — à contrôler' : 'Vide : valeur existante conservée')}</p></div>)}</div><Field label="Taux de TVA par défaut (%)" required type="number" min={0} max={100} step="any" value={tva} onChange={setTva} /><p className="muted">Utilisé lorsqu’aucun taux n’est précisé sur l’article ou la ligne. Les taux particuliers et exonérations des articles restent inchangés.</p></fieldset><ErrorNotice error={error} /></form></Dialog>;
}
function ReviewEditor({ bridge, state, review, onClose, onSaved }: EditorProps & { review: ReviewConfig }) {
  const [purchases, setPurchases] = useState(review.revue_achats), [sales, setSales] = useState(review.revue_ventes), [busy, setBusy] = useState(false), [error, setError] = useState(''); const pending = useRef(false);
  return <Dialog bridge={bridge} title="Règles de validation comptable" busy={busy} onClose={onClose} footer={close => <><button className="btn" disabled={busy} onClick={close}><i className="ti ti-x" aria-hidden="true" /> Annuler</button><button className="btn btn-primary" disabled={busy} onClick={async () => { if (pending.current) return; pending.current = true; setBusy(true); setError(''); try { await bridge.api(`/comptabilite/revue-config?societe_id=${state.companyId}`, { method: 'POST', body: { revue_achats: purchases, revue_ventes: sales } }); onSaved(); } catch (cause) { setError(message(cause)); } finally { pending.current = false; setBusy(false); } }}>Enregistrer les règles</button></>}><p className="banner">Une case cochée impose la revue du comptable avant validation des prochaines pièces concernées. Une case décochée autorise leur comptabilisation directe.</p><fieldset className="business-fieldset" disabled={busy}><label className="business-check"><input type="checkbox" checked={purchases} onChange={e => setPurchases(e.target.checked)} /> Achats (factures et réceptions) : validation requise</label><label className="business-check"><input type="checkbox" checked={sales} onChange={e => setSales(e.target.checked)} /> Ventes à crédit : validation requise</label></fieldset><p>Les ventes POS / comptant restent directes. Les comptes automatiques et le taux de TVA ne sont pas modifiés par ce bouton.</p><ErrorNotice error={error} /></Dialog>;
}
