'use client';
import { useRef, useState } from 'react';
import { partyLabel, type Party } from '../../lib/accounting-data';
import { Dialog, ErrorNotice, message, normalize, type ScreenProps } from './shared';
import { Field } from './field';

export function AccountingPartyPicker({ bridge, state, parties, onClose, onSelected, allowedKind, beneficiaries = false }: ScreenProps & { parties: Party[]; beneficiaries?: boolean; allowedKind?: 'client' | 'fournisseur'; onClose: () => void; onSelected: (party: Party) => void }) {
  const [search, setSearch] = useState(''), [creating, setCreating] = useState(false), [code, setCode] = useState(''), [name, setName] = useState(''), [kind, setKind] = useState<string>(allowedKind || (beneficiaries ? 'agent' : 'fournisseur')), [busy, setBusy] = useState(false), [error, setError] = useState(''), [confirmable, setConfirmable] = useState(false), [confirmed, setConfirmed] = useState(false);
  const pending = useRef(false);
  const reset = () => { setConfirmed(false); setConfirmable(false); setError(''); };
  const matches = parties.filter(p => !allowedKind || p.type === allowedKind).filter(p => creating ? (code && normalize(p.code) === normalize(code)) || (name.length >= 2 && normalize(p.nom).includes(normalize(name))) : normalize(partyLabel(p)).includes(normalize(search)));
  return <Dialog bridge={bridge} title={creating ? (allowedKind === 'client' ? 'Créer un client' : beneficiaries ? 'Créer un bénéficiaire' : 'Créer un client ou fournisseur') : 'Choisir un tiers'} busy={busy} onClose={onClose} footer={close => <><button className="btn" disabled={busy} onClick={close}><i className="ti ti-x" aria-hidden="true" /> Annuler</button>{creating ? <button key="submit-party" className="btn btn-primary" type="submit" form="accounting-party" disabled={busy}>Créer et sélectionner</button> : <button key="create-party" type="button" className="btn btn-primary" onClick={() => setCreating(true)}>{allowedKind === 'client' ? 'Créer un client' : beneficiaries ? 'Créer un bénéficiaire' : 'Créer un client ou fournisseur'}</button>}</>}>
    <p className="banner">{state.companies.find(c => c.id === state.companyId)?.nom} · {allowedKind ? 'Les fiches de ce type accessibles à la société sont sélectionnables, y compris les fiches partagées.' : 'Les agents et les fiches partagées existantes sont sélectionnables.'} Toute nouvelle fiche créée ici appartient à cette société.</p>
    <form id="accounting-party" onSubmit={async e => { e.preventDefault(); if (!creating || pending.current) return; setError(''); pending.current = true; setBusy(true); try { const p = await bridge.api<Party>(`${beneficiaries ? '/beneficiaires' : '/commercial/tiers'}?societe_id=${state.companyId}`, { method: 'POST', body: { type: kind, code: code.trim(), nom: name.trim(), confirmer_homonyme: confirmable && confirmed } }); onSelected(p); } catch (cause) { setError(message(cause)); const flag = (cause as { data?: { can_confirm_similar?: boolean | string } }).data?.can_confirm_similar; setConfirmable(flag === true || flag === 'True'); } finally { pending.current = false; setBusy(false); } }}>
      <fieldset className="business-fieldset" disabled={busy}>{creating ? <div className="business-form-grid"><label className="business-field">Type de fiche<select className="form-select" value={kind} disabled={!!allowedKind} onChange={e => { setKind(e.target.value); reset(); }}>{beneficiaries && <option value="agent">Agent</option>}<option value="fournisseur">Fournisseur</option><option value="client">Client</option></select></label><Field label="Code du tiers" required maxLength={32} value={code} onChange={v => { setCode(v); reset(); }} /><Field label="Nom du tiers" required minLength={2} maxLength={255} value={name} onChange={v => { setName(v); reset(); }} /></div> : <Field label="Rechercher un tiers par nom ou code" type="search" value={search} onChange={setSearch} />}
        <div className="business-matches">{matches.slice(0, 40).map(p => <button className="btn" type="button" key={p.id} disabled={!p.actif} onClick={() => onSelected(p)}>{partyLabel(p)}</button>)}{!matches.length && <p>Aucune fiche correspondante.</p>}{matches.length > 40 && <p>Affinez la recherche pour retrouver les autres fiches.</p>}</div><ErrorNotice error={error} />{confirmable && <label className="business-check"><input type="checkbox" checked={confirmed} onChange={e => setConfirmed(e.target.checked)} /> J’ai vérifié qu’il s’agit d’un tiers distinct malgré ce nom similaire.</label>}
      </fieldset>
    </form>
  </Dialog>;
}
