'use client';
import { Fragment, useCallback, useEffect, useId, useRef, useState } from 'react';
import type { Account } from '../../lib/accounting-data';
import type { AnalyticAxis } from '../../lib/analytic-data';
import { reviewColumns, reviewPayload, reviewRows, type ReviewDraft, type ReviewEntry } from '../../lib/accounting-review-data';
import { Attachments } from './attachments';
import { Field } from './field';
import { entryReport } from './accounting-entry';
import { ErrorNotice, message, number, normalize, ReportPreview, useResource, type ScreenProps } from './shared';
const money=(n:number)=>new Intl.NumberFormat('fr-FR',{minimumFractionDigits:2,maximumFractionDigits:2}).format(n)+' USD';
const icons:Record<string,string>={Caisse:'ti-cash',POS:'ti-device-desktop-analytics',Banque:'ti-building-bank',Achat:'ti-shopping-cart',Vente:'ti-tag',Transfert:'ti-arrows-exchange'};
export function AccountingReview({ bridge, state }: ScreenProps) {
  const load = useCallback(async () => { const suffix = `?societe_id=${state.companyId}`; const [entries, accounts, axes] = await Promise.all([bridge.api<ReviewEntry[]>('/comptabilite/ecritures' + suffix), bridge.api<Account[]>('/comptabilite/plan-comptable' + suffix), bridge.api<AnalyticAxis[]>('/analytique/axes' + suffix)]); return { entries, accounts, axes }; }, [bridge, state.companyId]);
  const result=useResource(load),data=result.data,disabled=result.busy||!!result.error;
  const [search,setSearch]=useState(''),[provenance,setProvenance]=useState(''),[minimum,setMinimum]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[notice,setNotice]=useState(''),[report,setReport]=useState(false),[dirty,setDirty]=useState<Record<string,boolean>>({});
  const onDirty=useCallback((id:string,value:boolean)=>setDirty(old=>old[id]===value?old:{...old,[id]:value}),[]);
  const changed=Object.values(dirty).some(Boolean);
  const entries=data?.entries.filter(e=>(!provenance||(e.provenance||'Divers')===provenance)&&(!minimum||e.montant>=Number(minimum))&&(!from||e.date>=from)&&(!to||e.date<=to)&&normalize(search).split(/\s+/).every(word=>normalize(`${e.numero} ${e.libelle} ${e.piece||''} ${e.source||''} ${e.journal} ${e.lignes.map(l=>`${l.compte} ${l.tiers||''}`).join(' ')}`).includes(word)))||[];
  const groups=Array.from(new Set(data?.entries.map(e=>e.provenance||'Divers'))).sort();
  return <><ErrorNotice error={result.error}/>{result.busy&&<p role="status">Lecture des pièces en attente…</p>}{notice&&<p className="business-success" role="status">{notice}</p>}
    <div className="card pc-filters"><div className="card-body tw:flex tw:flex-wrap tw:items-center tw:gap-2.5"><label className="pc-search"><span className="sr-only">Rechercher les pièces</span><input className="form-input" type="search" placeholder="🔍 N°, libellé, compte, tiers, réf. pièce…" value={search} onChange={e=>setSearch(e.target.value)}/></label><label><span className="sr-only">Provenance</span><select className="form-select" value={provenance} onChange={e=>setProvenance(e.target.value)}><option value="">Toutes provenances</option>{groups.map(g=><option key={g}>{g}</option>)}</select></label><label className="pc-min"><span className="sr-only">Montant minimum USD</span><input className="form-input right" type="number" min="0" step="0.01" placeholder="Montant ≥" value={minimum} onChange={e=>setMinimum(e.target.value)}/></label><label className="pc-date"><span className="sr-only">Du</span><input className="form-input" type="date" aria-label="Du" value={from} onInput={e=>setFrom(e.currentTarget.value)} onChange={e=>setFrom(e.target.value)}/></label><label className="pc-date"><span className="sr-only">Au</span><input className="form-input" type="date" aria-label="Au" value={to} onInput={e=>setTo(e.currentTarget.value)} onChange={e=>setTo(e.target.value)}/></label>{(search||provenance||minimum||from||to)&&<button type="button" className="btn btn-sm" onClick={()=>{setSearch('');setProvenance('');setMinimum('');setFrom('');setTo('');}}><i className="ti ti-x" aria-hidden="true"/>Effacer</button>}<span className="muted pc-filter-count" role="status"><b>{entries.length}</b> / {data?.entries.length||0} pièce(s) · {money(entries.reduce((n,e)=>n+e.montant,0))}</span></div></div>
    {data&&groups.map(group=>{const visible=entries.filter(e=>(e.provenance||'Divers')===group);return <section className="pc-group" key={group} hidden={!visible.length}><h2 className="pc-group-hdr"><i className={`ti ${icons[group]||'ti-folder'}`} aria-hidden="true"/>{group}<span className="muted">· {visible.length} · {money(visible.reduce((n,e)=>n+e.montant,0))}</span></h2>{data.entries.filter(e=>(e.provenance||'Divers')===group).map(entry=><ReviewPiece key={entry.id} bridge={bridge} state={state} entry={entry} accounts={data.accounts} axes={data.axes} hidden={!entries.includes(entry)} disabled={disabled} onDirty={onDirty} onSaved={text=>{setNotice(text);result.refresh();}}/>)}</section>;})}
    {data&&!entries.length&&<div className="empty"><i className={`ti ${data.entries.length?'ti-filter-off':'ti-checks'}`} aria-hidden="true"/>{data.entries.length?'Aucune pièce ne correspond aux filtres.':'Aucune pièce comptable en attente — tout est validé.'}</div>}
    <div className="pc-footer tw:flex tw:flex-wrap tw:gap-2"><button type="button" className="btn btn-sm" disabled={result.busy||changed} onClick={result.refresh}><i className="ti ti-refresh" aria-hidden="true"/>Actualiser</button><button type="button" className="btn btn-sm" disabled={disabled||!entries.length} onClick={()=>setReport(true)}><i className="ti ti-printer" aria-hidden="true"/>Rapport PDF / Excel</button>{changed&&<span className="muted">Des modifications sont préparées : validez la pièce ou annulez sa saisie avant de quitter.</span>}</div>
    {report&&<ReportPreview bridge={bridge} state={state} report={{title:'Pièces en attente de validation',subtitle:`${provenance||'Toutes provenances'} · ${from||'Début historique'} au ${to||'Aujourd’hui et dates futures'} · Recherche : ${search||'aucune'}`,columns:reviewColumns,rows:reviewRows(entries),note:'Données enregistrées : les changements préparés non validés sont exclus.'}} onClose={()=>setReport(false)}/>}</>;
}
function ReviewPiece({bridge,state,entry:loadedEntry,accounts,axes,hidden,disabled,onDirty,onSaved}:ScreenProps&{entry:ReviewEntry;accounts:Account[];axes:AnalyticAxis[];hidden:boolean;disabled:boolean;onDirty:(id:string,dirty:boolean)=>void;onSaved:(text:string)=>void}) {
  const [open,setOpen]=useState(false),[entry,setEntry]=useState(loadedEntry),listId=useId();
  const [drafts, setDrafts] = useState<Record<string, ReviewDraft>>(Object.fromEntries(entry.lignes.map(l => [l.id, { compte: l.compte, parts: null, allocation: null }]))), [confirm, setConfirm] = useState(false), [busy, setBusy] = useState(false), [failed, setFailed] = useState(false), [error, setError] = useState(''), [attachments, setAttachments] = useState(false), [preview, setPreview] = useState(false);
  const sequence = useRef(0), pending = useRef(false), activeAxes = axes.filter(a => a.actif && a.sections.some(s => s.actif));
  const update = (id: string, values: Partial<ReviewDraft>) => { setConfirm(false); setDrafts(old => ({ ...old, [id]: { ...old[id], ...values } })); };
  const validate = async () => {
    setOpen(true);
    if (pending.current || failed) return; setError(''); let payload;
    try { payload = reviewPayload(entry, drafts, accounts, axes); } catch (e) { setError(message(e)); return; }
    if (!confirm) { setConfirm(true); return; }
    pending.current = true; setBusy(true);
    try {
      await bridge.api(`/comptabilite/ecritures/${entry.id}/valider`, { method: 'POST', body: payload.body });
      void bridge.refreshAccountingBadge();
      const incomplete: string[] = [];
      for (const allocation of payload.ventilations) { try { await bridge.api('/analytique/ventiler', { method: 'POST', body: { societe_id: state.companyId, ...allocation } }); } catch (e) { incomplete.push(`${entry.lignes.find(l => l.id === allocation.ligne_id)?.compte} : ${message(e)}`); } }
      onSaved(`${entry.numero} validée. ${payload.body.reclassements.length} reclassement(s), ${payload.body.splits.length} éclatement(s). ${incomplete.length ? `Attention : analytique à terminer dans le menu Analytique (${incomplete.join(' ; ')}). La pièce comptable est déjà validée.` : `${payload.ventilations.length} ventilation(s) appliquée(s).`}`);
    } catch (e) { setError(message(e) + ' Annulez les modifications préparées si nécessaire, puis actualisez la liste avant toute nouvelle tentative.'); setFailed(true); }
    finally { pending.current = false; setBusy(false); }
  };
  const dirty=entry.lignes.some(l=>drafts[l.id].compte!==l.compte||drafts[l.id].parts!==null||drafts[l.id].allocation!==null);
  // Une réponse fraîche réarme les cartes non modifiées après un refus.
  // Garder la version d'origine avec les brouillons des autres pièces : leur
  // contrôle de concurrence doit porter sur la version réellement relue.
  useEffect(()=>{
    if(dirty||pending.current)return;
    setEntry(loadedEntry);
    setDrafts(Object.fromEntries(loadedEntry.lignes.map(l=>[l.id,{compte:l.compte,parts:null,allocation:null}])));
    setFailed(false);setConfirm(false);setError('');
  },[loadedEntry]);
  useEffect(()=>{onDirty(entry.id,dirty||busy);return()=>onDirty(entry.id,false);},[entry.id,dirty,busy,onDirty]);
  useEffect(()=>{if(!dirty&&!busy)return;const release=bridge.holdNavigation();const leave=(e:BeforeUnloadEvent)=>{e.preventDefault();};window.addEventListener('beforeunload',leave);return()=>{release();window.removeEventListener('beforeunload',leave);};},[bridge,dirty,busy]);
  const reset=()=>{setDrafts(Object.fromEntries(entry.lignes.map(l=>[l.id,{compte:l.compte,parts:null,allocation:null}])));setConfirm(false);setError('');};
  return <article className={`pc-piece${open?' open':''}`} hidden={hidden} aria-label={`Pièce ${entry.numero}`}><div className="pc-head"><button type="button" className="pc-toggle" aria-expanded={open} aria-controls={listId+'-body'} onClick={()=>setOpen(v=>!v)}><i className="ti ti-chevron-right chev" aria-hidden="true"/><span className="num-cell">{entry.numero}</span><span className="muted pc-entry-date">{entry.date}</span>{entry.journal&&<span className="tag">{entry.journal}</span>}<span className="pc-lib">{entry.libelle}{entry.piece&&<small className="muted"> · pièce {entry.piece}</small>}</span></button><button type="button" className="btn btn-sm" disabled={busy} aria-label={`Justificatifs · ${entry.numero}`} title="Justificatifs" onClick={()=>setAttachments(true)}><i className="ti ti-paperclip" aria-hidden="true"/>{entry.nb_pj>0?entry.nb_pj:null}</button><span className="pc-mt">{money(entry.montant)}</span><button type="button" className="btn btn-sm btn-success" disabled={disabled||busy||failed} onClick={validate}><i className="ti ti-check" aria-hidden="true"/>{busy?'Validation…':confirm?'Confirmer':'Valider'}</button></div>
    <div className="pc-body" id={listId+'-body'}><datalist id={listId}>{accounts.map(a=><option key={a.id} value={a.numero}>{a.intitule}</option>)}</datalist><fieldset className="business-fieldset" disabled={disabled||busy||failed}><div className="pc-lines-wrap"><table className="pc-lines"><thead><tr><th>Sens</th><th>Compte d’imputation</th><th>Libellé</th><th>Tiers</th><th className="right">Montant</th><th><span className="sr-only">Actions de la ligne</span></th></tr></thead><tbody>{entry.lignes.map((line,i)=>{const draft=drafts[line.id],axis=activeAxes.find(a=>a.id===draft.allocation?.axe_id);return <Fragment key={line.id}><tr><td><span className={`pill ${line.sens==='D'?'pc-debit':'pc-credit'}`}>{line.sens==='D'?'Débit':'Crédit'}</span></td><td><label><span className="sr-only">Compte de la ligne {i+1} · {entry.numero}</span><input className="form-input pc-compte" list={listId} value={draft.compte} disabled={!!draft.parts} onChange={e=>update(line.id,{compte:e.target.value})}/></label><div className="pc-cint muted">{accounts.find(a=>a.numero===draft.compte)?.intitule||'Compte à vérifier'}</div></td><td className="muted">{line.libelle||entry.libelle}</td><td>{line.tiers||'—'}</td><td className="right">{money(line.montant_usd)}</td><td className="pc-line-actions">{!draft.parts&&activeAxes.length>0&&'67'.includes(draft.compte[0]||'_')&&<button type="button" className="btn btn-sm" aria-label={`Analytique de la ligne ${i+1} · ${entry.numero}`} title="Ventilation analytique" onClick={()=>update(line.id,{allocation:draft.allocation?null:{axe_id:activeAxes[0].id,rows:[{key:sequence.current++,section_id:'',montant:String(line.montant_usd)}]}})}><i className="ti ti-chart-pie" aria-hidden="true"/></button>}<button type="button" className="btn btn-sm" disabled={!!draft.allocation} aria-label={`Éclater la ligne ${i+1} · ${entry.numero}`} title="Éclater sur plusieurs comptes" onClick={()=>update(line.id,{parts:draft.parts?null:[{key:sequence.current++,compte_numero:draft.compte,montant:String(line.montant_usd),libelle:line.libelle||''},{key:sequence.current++,compte_numero:'',montant:'',libelle:''}]})}><i className="ti ti-arrows-split-2" aria-hidden="true"/></button></td></tr>{(draft.parts||draft.allocation)&&<tr><td colSpan={6}><div className="split-box">
      {draft.parts && <><p className="muted">Le tiers et le sens d’origine sont conservés sur chaque part. La répartition analytique des lignes éclatées se traite après validation dans le menu Analytique.</p>{draft.parts.map((part, j) => <div className="business-form-grid" key={part.key}><Field label={`Compte ${i + 1}.${j + 1}`} list={listId} value={part.compte_numero} onChange={compte_numero => update(line.id, { parts: draft.parts!.map(p => p.key === part.key ? { ...p, compte_numero } : p) })} /><Field label={`Montant ${i + 1}.${j + 1} USD`} type="number" step="0.01" min="0.01" value={part.montant} onChange={montant => update(line.id, { parts: draft.parts!.map(p => p.key === part.key ? { ...p, montant } : p) })} /><Field label={`Libellé ${i + 1}.${j + 1}`} value={part.libelle} onChange={libelle => update(line.id, { parts: draft.parts!.map(p => p.key === part.key ? { ...p, libelle } : p) })} /><button type="button" className="btn btn-sm" onClick={() => update(line.id, { parts: draft.parts!.filter(p => p.key !== part.key) })}>Retirer la part {j + 1}</button></div>)}<button type="button" className="btn btn-sm" onClick={() => update(line.id, { parts: [...draft.parts!, { key: sequence.current++, compte_numero: '', montant: '', libelle: '' }] })}>Ajouter un compte</button><p>Réparti : {number(draft.parts.reduce((s, p) => s + (Number(p.montant) || 0), 0))} / {number(line.montant_usd)} USD</p></>}
      {draft.allocation && <><p className="banner">La répartition préparée remplacera celle de cette ligne sur l’axe choisi, après validation comptable. Si son enregistrement échoue, la pièce restera validée et la répartition devra être terminée dans Analytique.</p><label className="business-field">Axe de la ligne {i + 1}<select className="form-select" value={draft.allocation.axe_id} onChange={e => update(line.id, { allocation: { axe_id: e.target.value, rows: [] } })}>{activeAxes.map(a => <option key={a.id} value={a.id}>{a.code} — {a.libelle}</option>)}</select></label>{draft.allocation.rows.map((row, j) => <div className="business-form-grid" key={row.key}><label className="business-field">Section {i + 1}.{j + 1}<select className="form-select" value={row.section_id} onChange={e => update(line.id, { allocation: { ...draft.allocation!, rows: draft.allocation!.rows.map(r => r.key === row.key ? { ...r, section_id: e.target.value } : r) } })}><option value="">Choisir</option>{axis?.sections.filter(s => s.actif).map(s => <option key={s.id} value={s.id}>{s.code} — {s.libelle}</option>)}</select></label><Field label={`Analytique ${i + 1}.${j + 1} USD`} type="number" min="0.01" step="0.01" value={row.montant} onChange={montant => update(line.id, { allocation: { ...draft.allocation!, rows: draft.allocation!.rows.map(r => r.key === row.key ? { ...r, montant } : r) } })} /><button className="btn btn-sm" type="button" onClick={() => update(line.id, { allocation: { ...draft.allocation!, rows: draft.allocation!.rows.filter(r => r.key !== row.key) } })}>Retirer la section {j + 1}</button></div>)}<button type="button" className="btn btn-sm" onClick={() => update(line.id, { allocation: { ...draft.allocation!, rows: [...draft.allocation!.rows, { key: sequence.current++, section_id: '', montant: '' }] } })}>Ajouter une section</button></>}
</div></td></tr>}</Fragment>;})}</tbody></table></div></fieldset>
    <p className="pc-hint muted"><i className="ti ti-info-circle" aria-hidden="true"/> Corrigez le compte, éclatez une ligne (<i className="ti ti-arrows-split-2" aria-hidden="true"/>), ventilez en analytique (<i className="ti ti-chart-pie" aria-hidden="true"/>), joignez les preuves (<i className="ti ti-paperclip" aria-hidden="true"/>) — puis validez.</p><ErrorNotice error={error}/>{confirm&&<p className="business-success" role="status">Les comptes et montants sont cohérents. Relisez puis cliquez sur Confirmer pour valider la pièce.</p>}<div className="pc-detail-tools"><button type="button" className="btn btn-sm" disabled={busy} onClick={()=>setPreview(true)}><i className="ti ti-printer" aria-hidden="true"/>Imprimer la pièce</button>{dirty&&<button type="button" className="btn btn-sm" disabled={busy} onClick={reset}>Annuler les modifications préparées</button>}</div></div>
    {attachments&&<Attachments bridge={bridge} state={state} documentType="ecriture" documentId={entry.id} title={`Justificatifs — ${entry.numero}`} onClose={()=>setAttachments(false)}/>} {preview&&<ReportPreview bridge={bridge} state={state} report={entryReport(entry)} onClose={()=>setPreview(false)}/>}</article>;
}
