'use client';
import { ScreenTitle } from './screen-presentation';
import { useCallback, useEffect, useRef, useState, type ReactNode } from 'react';
import { partyLabel, type Account, type Party } from '../../lib/accounting-data';
import { matchingColumns, matchingRows, selectionTotals, statementAmount, verifyMatchingSelection, type BankingData, type MatchingData, type MatchingLine, type Reconciliation } from '../../lib/reconciliation-data';
import { DataTable } from './data-table';
import { Field } from './field';
import { Dialog, ErrorNotice, ReportPreview, message, number, today, useResource, type Report, type ScreenProps } from './shared';

function AccountFilter({ value, setValue, accounts, onApply }: { value: string; setValue: (value: string) => void; accounts: Account[]; onApply: () => void }) {
  return <form className="business-toolbar" onSubmit={e => { e.preventDefault(); if (value.trim()) onApply(); }}><Field label="Compte à consulter" required list="matching-accounts" value={value} onChange={setValue} /><datalist id="matching-accounts">{accounts.map(a => <option key={a.id} value={a.numero}>{a.intitule}</option>)}</datalist><button className="btn" type="submit">Afficher le compte</button></form>;
}
function Confirmation({ bridge, title, children, actionLabel, run, onClose, onSaved }: { bridge: ScreenProps['bridge']; title: string; children: ReactNode; actionLabel: string; run: () => Promise<string>; onClose: () => void; onSaved: (message: string) => void }) {
  const [busy, setBusy] = useState(false), [error, setError] = useState(''), [failed, setFailed] = useState(false), pending = useRef(false);
  return <Dialog bridge={bridge} title={title} busy={busy} onClose={onClose} footer={close => <><button className="btn" disabled={busy} onClick={close}>Fermer</button><button className="btn btn-primary" disabled={busy || failed} onClick={async () => { if (pending.current || failed) return; pending.current = true; setBusy(true); try { onSaved(await run()); } catch (cause) { setError(message(cause)); setFailed(true); } finally { pending.current = false; setBusy(false); } }}>{actionLabel}</button></>}>
    {children}<ErrorNotice error={error} />{failed && <p className="banner">Fermez cette fenêtre pour relire la situation actuelle avant toute nouvelle tentative.</p>}
  </Dialog>;
}
export function Matching({ bridge, state }: ScreenProps) {
  const [input, setInput] = useState('421'), [account, setAccount] = useState('421'), [party, setParty] = useState(''), [unmatched, setUnmatched] = useState(false), [selection, setSelection] = useState<string[]>([]), [confirm, setConfirm] = useState(false), [undo, setUndo] = useState<string | null>(null), [success, setSuccess] = useState('');
  const path = `/comptabilite/lettrage?${new URLSearchParams({ societe_id: state.companyId!, compte: account, tiers_id: party, non_lettres: String(unmatched) })}`;
  const load = useCallback(async () => { const [data, accounts, parties] = await Promise.all([bridge.api<MatchingData>(path), bridge.api<Account[]>(`/comptabilite/plan-comptable?societe_id=${state.companyId}`), bridge.api<Party[]>(`/tiers?societe_id=${state.companyId}`)]); return { data, accounts, parties }; }, [bridge, state.companyId, path]);
  const result = useResource(load), disabled = result.busy || !!result.error, data = result.data?.data;
  useEffect(() => { setSelection([]); }, [result.data]);
  const selected = data?.lignes.filter(l => selection.includes(l.id) && !l.lettrage) || [], totals = selectionTotals(selected);
  const close = () => { setConfirm(false); setUndo(null); result.refresh(); };
  const saved = (text: string) => { setSuccess(text); setSelection([]); close(); };
  const subtitle = `Compte ${account} · ${party ? (result.data?.parties.find(p => p.id === party) ? partyLabel(result.data.parties.find(p => p.id === party)!) : 'Tiers sélectionné') : 'Tous les tiers'} · ${unmatched ? 'Non lettrées' : 'Lettrées et non lettrées'} · Tout l’historique`;
  return <><div className="audit-head"><div><ScreenTitle>Lettrage des tiers</ScreenTitle><p className="muted">Associer les débits et crédits d’un même compte</p></div><button className="btn" disabled={result.busy} onClick={result.refresh}><i className="ti ti-refresh" aria-hidden="true" /> Actualiser</button></div><ErrorNotice error={result.error} />{result.busy && <p role="status">Lecture des mouvements et lettrages…</p>}{success && <p className="business-success" role="status">{success}</p>}
    {result.data && <><div className="business-toolbar"><AccountFilter value={input} setValue={setInput} accounts={result.data.accounts} onApply={() => { setSelection([]); setAccount(input.trim()); }} /><label className="business-field">Tiers<select className="form-select" value={party} onChange={e => { setSelection([]); setParty(e.target.value); }}><option value="">Tous les tiers</option>{result.data.parties.map(p => <option key={p.id} value={p.id}>{partyLabel(p)}</option>)}</select></label><label className="business-check"><input type="checkbox" checked={unmatched} onChange={e => { setSelection([]); setUnmatched(e.target.checked); }} /> Lignes non lettrées seulement</label></div>
      <div className="caisse-cards">{[['Solde du compte / tiers', data!.solde], ['Solde non lettré', data!.solde_non_lettre]].map(([label, value]) => <article className="caisse-card" key={label}><p className="muted">{label}</p><strong>{disabled ? '—' : `${number(value)} USD`}</strong></article>)}</div>
      <p className="banner">Les montants et statuts d’origine sont conservés. Le lettrage associe les lignes ; il ne valide pas les écritures en attente. Une annulation retire le code sur tout le groupe du compte, y compris ses lignes masquées par les filtres.</p>
      <DataTable bridge={bridge} state={state} key={path} title={`Lettrage ${account}`} subtitle={subtitle} disabled={disabled} columns={matchingColumns} rows={matchingRows(data!.lignes)} actions={(_, index) => { const l = data!.lignes[index]; return l.lettrage ? <button className="btn btn-sm" disabled={disabled} onClick={() => setUndo(l.lettrage!)}>Annuler {l.lettrage}</button> : <label className="business-check"><input type="checkbox" aria-label={`Sélectionner ${l.piece} · ligne ${index + 1}`} disabled={disabled} checked={selection.includes(l.id)} onChange={e => setSelection(old => e.target.checked ? [...old, l.id] : old.filter(id => id !== l.id))} /> Sélectionner</label>; }} />
      <div className="business-toolbar"><p role="status">{selected.length} lignes sélectionnées · Débit {number(totals.debit)} · Crédit {number(totals.credit)} · Écart {number(totals.difference)} USD</p><button className="btn" disabled={disabled || !selection.length} onClick={() => setSelection([])}>Vider la sélection</button><button className="btn btn-primary" disabled={disabled || !totals.balanced} onClick={() => setConfirm(true)}>Lettrer la sélection</button></div><p className="muted">La sélection peut inclure des lignes d’autres pages ou masquées par la recherche. Relisez le récapitulatif avant de confirmer.</p>
    </>}
    {confirm && <Confirmation bridge={bridge} title="Confirmer le lettrage" actionLabel="Confirmer le lettrage" onClose={close} onSaved={saved} run={async () => { const fresh = await bridge.api<MatchingData>(path); const ids = verifyMatchingSelection(selected, fresh.lignes); if (!selectionTotals(selected).balanced) throw new Error('La sélection doit être équilibrée.'); const r = await bridge.api<{ code: string; lignes: number }>('/comptabilite/lettrage', { method: 'POST', body: { societe_id: state.companyId, ligne_ids: ids } }); return `Lettrage ${r.code} enregistré : ${r.lignes} lignes.`; }}><p>Compte {account} · Débit {number(totals.debit)} = Crédit {number(totals.credit)} USD.</p>{new Set(selected.map(l => l.tiers || 'Sans tiers')).size > 1 && <p className="banner">Plusieurs tiers figurent dans cette sélection. Vérifiez qu’ils doivent bien être rapprochés ensemble.</p>}<SelectionSummary lines={selected} /></Confirmation>}
    {undo && <Confirmation bridge={bridge} title={`Annuler le lettrage ${undo}`} actionLabel="Confirmer l’annulation du lettrage" onClose={close} onSaved={saved} run={async () => { const r = await bridge.api<{ delettre: number }>('/comptabilite/delettrage', { method: 'POST', body: { societe_id: state.companyId, compte: account, code: undo } }); return `Lettrage ${undo} annulé : ${r.delettre} lignes libérées.`; }}><p>Le code {undo} sera retiré de toutes ses lignes du compte {account}, même si certaines ne sont pas affichées. Les écritures et leurs montants restent conservés.</p></Confirmation>}
  </>;
}
function SelectionSummary({ lines }: { lines: MatchingLine[] }) {
  return <div className="business-table"><table><thead><tr><th>Date</th><th>Pièce</th><th>Libellé / tiers</th><th>Statut</th><th>Débit USD</th><th>Crédit USD</th></tr></thead><tbody>{lines.map(l => <tr key={l.id}><td>{l.date}</td><td>{l.piece}</td><td>{l.libelle}{l.tiers ? ` · ${l.tiers}` : ''}</td><td>{l.statut === 'valide' ? 'Validée' : l.statut === 'en_attente' ? 'En attente' : l.statut}</td><td className="right">{number(l.debit)}</td><td className="right">{number(l.credit)}</td></tr>)}</tbody></table></div>;
}
export function BankReconciliation({ bridge, state }: ScreenProps) {
  const [input, setInput] = useState('521'), [account, setAccount] = useState('521'), [selection, setSelection] = useState<string[]>([]), [preparing, setPreparing] = useState(false), [undo, setUndo] = useState<Reconciliation | null>(null), [preview, setPreview] = useState<Report | null>(null), [success, setSuccess] = useState('');
  const path = `/comptabilite/rapprochement/a-pointer?${new URLSearchParams({ societe_id: state.companyId!, compte: account })}`;
  const load = useCallback(async () => { const [data, accounts, history] = await Promise.all([bridge.api<BankingData>(path), bridge.api<Account[]>(`/comptabilite/plan-comptable?societe_id=${state.companyId}`), bridge.api<Reconciliation[]>(`/comptabilite/rapprochement?${new URLSearchParams({ societe_id: state.companyId!, compte: account })}`)]); return { data, accounts, history }; }, [bridge, state.companyId, account, path]);
  const result = useResource(load), disabled = result.busy || !!result.error, data = result.data?.data;
  useEffect(() => { setSelection([]); }, [result.data]);
  const selected = data?.lignes.filter(l => selection.includes(l.id)) || [], totals = selectionTotals(selected);
  const close = () => { setPreparing(false); setUndo(null); result.refresh(); };
  const saved = (text: string) => { setSuccess(text); setSelection([]); close(); };
  return <><div className="audit-head"><div><ScreenTitle>Rapprochement bancaire</ScreenTitle><p className="muted">Pointage des lignes et comparaison au relevé · USD</p></div><button className="btn" disabled={result.busy} onClick={result.refresh}><i className="ti ti-refresh" aria-hidden="true" /> Actualiser</button></div><ErrorNotice error={result.error} />{result.busy && <p role="status">Lecture du compte bancaire…</p>}{success && <p className="business-success" role="status">{success}</p>}
    {result.data && data && <><AccountFilter value={input} setValue={setInput} accounts={result.data.accounts} onApply={() => { setSelection([]); setAccount(input.trim()); }} /><h3>{account} — {data.intitule}</h3><div className="caisse-cards">{[['Solde comptable', data.solde_comptable], ['Déjà rapproché', data.solde_rapproche], ['Reste à pointer', data.solde_comptable - data.solde_rapproche]].map(([label, value]) => <article className="caisse-card" key={label}><p className="muted">{label}</p><strong>{disabled ? '—' : `${number(value)} USD`}</strong></article>)}</div><p className="banner">Les soldes portent sur tout l’historique du compte, selon le calcul existant. Le rapprochement peut conserver un écart à analyser ; il ne crée pas d’écriture de régularisation et ne valide pas les pièces en attente.</p>
      <DataTable bridge={bridge} state={state} key={path} title={`Lignes à pointer ${account}`} subtitle="Tout l’historique · Lignes non rapprochées · USD" disabled={disabled} columns={matchingColumns.slice(0, -1)} rows={matchingRows(data.lignes).map(r => r.slice(0, -1))} actions={(_, index) => { const l = data.lignes[index]; return <label className="business-check"><input type="checkbox" aria-label={`Pointer ${l.piece} · ligne ${index + 1}`} disabled={disabled} checked={selection.includes(l.id)} onChange={e => setSelection(old => e.target.checked ? [...old, l.id] : old.filter(id => id !== l.id))} /> Pointer</label>; }} />
      <div className="business-toolbar"><p role="status">{selected.length} lignes sélectionnées · Solde du lot {number(totals.difference)} USD</p><button className="btn" disabled={disabled || !selection.length} onClick={() => setSelection([])}>Vider la sélection</button><button className="btn btn-primary" disabled={disabled} onClick={() => setPreparing(true)}>Préparer le rapprochement</button></div><p className="muted">La sélection est conservée sur les autres pages et lors d’une recherche. Relisez les lignes avant d’enregistrer.</p>
      <DataTable bridge={bridge} state={state} title="Historique des rapprochements" subtitle={`Compte ${account} · Instantanés enregistrés · USD`} disabled={disabled} columns={['Date du relevé', 'Solde du relevé', 'Solde comptable', 'Solde pointé', 'Écart', 'Statut']} rows={result.data.history.map(r => [r.date_releve, r.solde_releve, r.solde_comptable, r.solde_rapproche, r.ecart, r.statut === 'cloture' ? 'Clôturé' : r.statut])} actions={(_, index) => { const r = result.data!.history[index]; return <div className="business-toolbar"><button className="btn btn-sm" disabled={disabled} onClick={() => setPreview({ title: `Rapprochement bancaire ${r.compte}`, subtitle: `Relevé du ${r.date_releve} · ${r.statut === 'cloture' ? 'Clôturé' : r.statut} · USD`, columns: ['Indicateur', 'Montant USD'], rows: [['Solde relevé', r.solde_releve], ['Solde comptable', r.solde_comptable], ['Solde rapproché cumulé', r.solde_rapproche], ['Écart', r.ecart]], note: 'Instantané au moment de l’enregistrement. Un écart n’est pas une écriture de régularisation.' })}>Rapport</button><button className="btn btn-sm" disabled={disabled} onClick={() => setUndo(r)}>Annuler / dépointer</button></div>; }} />
      {preparing && <BankingForm bridge={bridge} state={state} data={data} selected={selected} path={path} onClose={close} onSaved={saved} />}
    </>}
    {undo && <Confirmation bridge={bridge} title={`Annuler le rapprochement du ${undo.date_releve}`} actionLabel="Confirmer l’annulation du rapprochement" onClose={close} onSaved={saved} run={async () => { const r = await bridge.api<{ lignes_depointees: number }>(`/comptabilite/rapprochement/${undo.id}/annuler`, { method: 'POST' }); return `Rapprochement annulé : ${r.lignes_depointees} lignes à nouveau disponibles.`; }}><p>Cette opération supprime ce rapprochement de l’historique et libère ses lignes pour un nouveau pointage, conformément au fonctionnement existant. Les écritures comptables sont conservées. Les autres rapprochements ne sont pas recalculés.</p></Confirmation>}
    {preview && <ReportPreview bridge={bridge} state={state} report={preview} onClose={() => setPreview(null)} />}
  </>;
}
function BankingForm({ bridge, state, data, selected, path, onClose, onSaved }: ScreenProps & { data: BankingData; selected: MatchingLine[]; path: string; onClose: () => void; onSaved: (text: string) => void }) {
  const [day, setDay] = useState(today), [balance, setBalance] = useState(''), [review, setReview] = useState(false), [error, setError] = useState('');
  const pointed = Math.round((data.solde_rapproche + selectionTotals(selected).difference) * 100) / 100;
  const amount = balance.trim() && Number.isFinite(Number(balance)) ? Number(balance) : null;
  return <Dialog bridge={bridge} title="Préparer le rapprochement bancaire" onClose={onClose} footer={close => <><button className="btn" onClick={close}>Fermer</button><button className="btn btn-primary" type="submit" form="banking-form">Vérifier le rapprochement</button></>}><form id="banking-form" onSubmit={e => { e.preventDefault(); setError(''); try { statementAmount(balance); setReview(true); } catch (cause) { setError(message(cause)); } }}><div className="business-form-grid"><Field label="Date du relevé" type="date" required value={day} onChange={setDay} /><Field label="Solde du relevé (USD)" type="number" step="0.01" required value={balance} onChange={setBalance} /></div><p>Compte {data.compte} · {selected.length} nouvelles lignes · Solde pointé cumulé {number(pointed)} USD.</p><p>Écart relevé / pointé : {amount === null ? 'à renseigner' : `${number(amount - pointed)} USD`}.</p>{!selected.length && <p className="banner">Aucune nouvelle ligne n’est sélectionnée. Un instantané sera enregistré avec le solde déjà rapproché.</p>}<SelectionSummary lines={selected} /><ErrorNotice error={error} /></form>
    {review && <Confirmation bridge={bridge} title="Confirmer le rapprochement bancaire" actionLabel="Enregistrer le rapprochement" onClose={() => setReview(false)} onSaved={onSaved} run={async () => { const fresh = await bridge.api<BankingData>(path); const ids = verifyMatchingSelection(selected, fresh.lignes); if (fresh.solde_rapproche !== data.solde_rapproche || fresh.solde_comptable !== data.solde_comptable) throw new Error('Le solde du compte a changé. Fermez les fenêtres et actualisez avant de recommencer.'); const r = await bridge.api<Reconciliation>('/comptabilite/rapprochement', { method: 'POST', body: { societe_id: state.companyId, compte: data.compte, date_releve: day, solde_releve: statementAmount(balance), ligne_ids: ids } }); return `Rapprochement du ${r.date_releve} enregistré · Écart ${number(r.ecart)} USD.`; }}><p>Compte {data.compte} · Relevé du {day} · {selected.length} nouvelles lignes.</p><p>Solde du relevé {number(amount)} USD · Solde pointé cumulé {number(pointed)} USD · Écart {number((amount ?? 0) - pointed)} USD.</p>{amount !== pointed && <p className="banner">L’écart sera conservé pour analyse. Aucune régularisation ne sera générée automatiquement.</p>}</Confirmation>}
  </Dialog>;
}
