'use client';
import { ScreenTitle } from './screen-presentation';
import { useCallback, useState } from 'react';
import { amount } from '../../lib/operation-data';
import { ArticleEditor, type Article } from './articles';
import { DataTable } from './data-table';
import { OperationForm } from './operation-form';
import { Dialog, ErrorNotice, dateTime, number, useResource, type ScreenProps } from './shared';
interface Advance { id: string; numero: string; beneficiaire: string; type_avance: string; nature: string; objet: string; montant_avance_usd: number; statut: string; echeance_justif: string }
export function Advances(props: ScreenProps) {
  const load = useCallback(() => props.bridge.api<Advance[]>(`/avances?societe_id=${props.state.companyId}`), [props.bridge, props.state.companyId]), result = useResource(load), [selected, setSelected] = useState<Advance | null>(null), [success, setSuccess] = useState('');
  return <><div className="audit-head"><ScreenTitle>Avances à justifier</ScreenTitle><button className="btn" disabled={result.busy} onClick={result.refresh}><i className="ti ti-refresh" aria-hidden="true" /> Actualiser</button></div><ErrorNotice error={result.error} />{success && <p role="status" className="business-success">{success}</p>}{result.busy && <p>Lecture des avances…</p>}{result.data && !result.busy && !result.error && <DataTable {...props} title="Avances à justifier" subtitle="Société active · suivi des fonds confiés" columns={['Numéro', 'Bénéficiaire', 'Objet', 'Nature', 'Type', 'Montant USD', 'Échéance', 'Statut']} rows={result.data.map(a => [a.numero, a.beneficiaire || '', a.objet || '', a.nature, a.type_avance || '', a.montant_avance_usd, dateTime(a.echeance_justif), a.statut])} actions={(_, i) => ['a_justifier', 'en_retard'].includes(result.data![i].statut) && <button className="btn" onClick={() => setSelected(result.data![i])}>Justifier</button>} />}{selected && <JustifyAdvance {...props} advance={selected} onClose={() => setSelected(null)} onSaved={label => { setSelected(null); setSuccess(label); result.refresh(); void props.bridge.refreshAccountingBadge(); }} />}</>;
}
function JustifyAdvance({ advance, onClose, onSaved, ...props }: ScreenProps & { advance: Advance; onClose: () => void; onSaved: (label: string) => void }) {
  const load = useCallback(() => props.bridge.api<Article[]>(`/commercial/articles?societe_id=${props.state.companyId}`), [props.bridge, props.state.companyId]), result = useResource(load), [added, setAdded] = useState<Article[]>([]), [createArticle, setCreateArticle] = useState(false);
  if (!result.data || result.busy || result.error) return <Dialog bridge={props.bridge} title="Justifier les fonds" onClose={onClose}><ErrorNotice error={result.error} />{result.busy ? <p>Lecture du catalogue…</p> : <button className="btn" onClick={result.refresh}>Réessayer</button>}</Dialog>;
  const articles = [...result.data.filter(a => !added.some(n => n.id === a.id)), ...added];
  return <><OperationForm bridge={props.bridge} title={`Justification · ${advance.numero}`} onClose={onClose} note={`Bénéficiaire : ${advance.beneficiaire}. Avance reçue : ${number(advance.montant_avance_usd)} USD. Les marchandises justifiées entrent en stock. Le serveur convertit les montants CDF au taux du jour et détermine l’écart final.`} initial={{ solde_retourne: '0', devise_solde: 'USD', repartition: 'quantite' }} fields={[{ key: 'solde_retourne', label: 'Solde rendu', type: 'number', min: 0, required: true }, { key: 'devise_solde', label: 'Devise du solde', options: [['USD', 'USD'], ['CDF', 'CDF']] }, { key: 'repartition', label: 'Répartition des frais annexes', options: [['quantite', 'Par quantité'], ['valeur', 'Par valeur']] }]} extra={<button className="btn" type="button" onClick={() => setCreateArticle(true)}>Créer ou retrouver un article</button>} sections={[
    { key: 'lignes', title: 'Charges', minimum: 0, initial: { nature: '', devise: 'USD', montant: '' }, fields: [{ key: 'nature', label: 'Nature de la dépense', required: true }, { key: 'devise', label: 'Devise de la charge', options: [['USD', 'USD'], ['CDF', 'CDF']] }, { key: 'montant', label: 'Montant de la charge', type: 'number', min: 0.01, required: true }] },
    { key: 'marchandises', title: 'Marchandises', minimum: 0, initial: { article_id: '', qte: '1', prix_unitaire: '', taux_tva: '0' }, fields: [{ key: 'article_id', label: 'Article', required: true, options: [['', 'Sélectionner un article'], ...articles.filter(a => a.actif).map(a => [a.id, `${a.code} · ${a.designation}`] as [string, string])] }, { key: 'qte', label: 'Quantité', required: true, type: 'number', min: 0.000001 }, { key: 'prix_unitaire', label: 'Prix unitaire HT USD', required: true, type: 'number', min: 0 }, { key: 'taux_tva', label: 'TVA %', required: true, type: 'number', min: 0, max: 100 }], onChange: (row, key, value) => { const a = key === 'article_id' ? articles.find(a => a.id === value) : null; return a ? { ...row, [key]: value, prix_unitaire: String(a.prix_achat), taux_tva: String(a.assujetti_tva ? a.taux_tva : 0) } : { ...row, [key]: value }; } },
    { key: 'frais', title: 'Frais annexes', minimum: 0, initial: { libelle: '', montant_ht: '', taux_tva: '0' }, fields: [{ key: 'libelle', label: 'Libellé du frais', required: true }, { key: 'montant_ht', label: 'Montant HT USD', required: true, type: 'number', min: 0.01 }, { key: 'taux_tva', label: 'TVA du frais %', required: true, type: 'number', min: 0, max: 100 }] }
  ]} submitLabel="Soumettre la justification" save={async (v, rows) => {
    const lignes = rows.lignes.map(l => { if (!l.nature.trim()) throw new Error('Précisez chaque charge.'); return { ...l, nature: l.nature.trim(), montant: amount(l.montant, 'Charge', 0.01) }; });
    const marchandises = rows.marchandises.map(l => { const a = articles.find(a => a.id === l.article_id && a.actif); if (!a) throw new Error('Sélectionnez un article actif de cette société.'); const tax = a.assujetti_tva ? amount(l.taux_tva, 'TVA') : 0; if (tax > 100) throw new Error('TVA supérieure à 100 %.'); return { article_id: a.id, designation: a.designation, qte: amount(l.qte, 'Quantité', 0.000001), prix_unitaire: amount(l.prix_unitaire, 'Prix unitaire'), taux_tva: tax }; });
    const frais = rows.frais.map(l => { if (!l.libelle.trim()) throw new Error('Précisez chaque frais.'); const tax = amount(l.taux_tva, 'TVA du frais'); if (tax > 100) throw new Error('TVA supérieure à 100 %.'); return { libelle: l.libelle.trim(), montant_ht: amount(l.montant_ht, 'Frais', 0.01), taux_tva: tax }; });
    if (frais.length && !marchandises.length) throw new Error('Les frais annexes doivent être rattachés à des marchandises.');
    const solde = amount(v.solde_retourne, 'Solde rendu'); if (!lignes.length && !marchandises.length && !solde) throw new Error('Ajoutez une dépense, des marchandises ou un solde rendu.');
    const r = await props.bridge.api<{ numero: string; ecart_usd: number; complement_demande: boolean }>('/avances/justifier', { method: 'POST', body: { avance_id: advance.id, solde_retourne: solde, devise_solde: v.devise_solde, repartition: v.repartition, lignes, marchandises, frais } }); onSaved(`Justification ${r.numero} enregistrée. Écart : ${number(r.ecart_usd)} USD.${r.complement_demande ? ' Un complément reste à demander.' : ''}`);
  }} />{createArticle && <ArticleEditor {...props} article={null} articles={articles} onClose={() => setCreateArticle(false)} onSaved={a => { setAdded(all => [...all, a]); setCreateArticle(false); }} onExisting={a => { setAdded(all => [...all.filter(p => p.id !== a.id), a]); setCreateArticle(false); }} />}</>;
}
