'use client';
import { useCallback, useRef, useState } from 'react';
import { Dialog, ErrorNotice, message, number, useResource, type ScreenProps } from './shared';
interface Attachment { id: string; nom_fichier: string; taille_octets: number }
export function Attachments({ bridge, state, documentType, documentId, title, onClose }: ScreenProps & { documentType: string; documentId: string; title: string; onClose: () => void }) {
  const load = useCallback(() => bridge.api<Attachment[]>(`/pieces-jointes?${new URLSearchParams({ document_type: documentType, document_id: documentId })}`), [bridge, documentType, documentId]);
  const result = useResource(load), [file, setFile] = useState<File | null>(null), [busy, setBusy] = useState(false), [error, setError] = useState(''), [failed, setFailed] = useState(false), [notice, setNotice] = useState('');
  const input = useRef<HTMLInputElement>(null), pending = useRef(false);
  return <Dialog bridge={bridge} title={title} busy={busy} onClose={onClose} footer={close => <><button className="btn" disabled={busy} onClick={close}>Fermer</button><button className="btn btn-primary" disabled={busy || failed || !file || result.busy || !!result.error} onClick={async () => { if (pending.current || !file) return; if (file.size > 10 * 1024 * 1024) { setError('Le fichier dépasse 10 Mo.'); return; } pending.current = true; setBusy(true); setError(''); const body = new FormData(); body.append('document_type', documentType); body.append('document_id', documentId); body.append('file', file); try { await bridge.api('/pieces-jointes', { method: 'POST', body }); setNotice('Justificatif ajouté.'); setFile(null); if (input.current) input.current.value = ''; result.refresh(); } catch (e) { setError(message(e) + ' Fermez puis rouvrez les justificatifs pour vérifier l’envoi avant de recommencer.'); setFailed(true); } finally { pending.current = false; setBusy(false); } }}>Ajouter le justificatif</button></>}><ErrorNotice error={result.error || error} />{notice && <p className="business-success" role="status">{notice}</p>}{result.busy && <p role="status">Lecture des justificatifs…</p>}<ul>{result.data?.map(p => <li key={p.id}><span>{p.nom_fichier} · {number(p.taille_octets / 1024)} Ko </span><button className="btn btn-sm" disabled={busy} onClick={async () => { setBusy(true); setError(''); try { await bridge.download(`/pieces-jointes/${p.id}/download`, p.nom_fichier); } catch (e) { setError(message(e)); } finally { setBusy(false); } }}>Télécharger {p.nom_fichier}</button></li>)}</ul>{result.data?.length === 0 && <p>Aucun justificatif joint à cette pièce.</p>}<label className="business-field">Fichier à joindre (maximum 10 Mo)<input ref={input} className="form-input" type="file" disabled={busy || failed} onChange={e => { setFile(e.target.files?.[0] || null); setError(''); }} /></label><p className="muted">Les justificatifs sont enregistrés dans ce dossier dès leur ajout.</p></Dialog>;
}
