'use client';
import { useCallback, useState } from 'react';
import { ArticleEditor, type Article } from './articles';
import { AccountingPartyPicker } from './accounting-party';
import { partyLabel, type Party } from '../../lib/accounting-data';
import { commercialLines, commercialNumber, commercialTotals, lineDiscountForEdit } from '../../lib/commercial-data';
import { OperationForm, type LineSection, type Values } from './operation-form';
import type { FormField } from './resource-editor';
import { Dialog, ErrorNotice, number, today, useResource, type ScreenProps } from './shared';
export interface NamedAccount { id: string; libelle: string; session_ouverte?: boolean }
export interface CommercialLine { id: string; article_id?: string; article?: string; designation: string; qte: number; prix_unitaire: number; taux_tva: number; montant_ht: number; remise_pct?: number }
export interface CommercialDocument { id: string; numero: string; tiers_id: string; date: string; date_livraison_prevue?: string; reference_fournisseur?: string; destination?: string; transporteur_societe_id?: string; intra_groupe?: boolean; validite?: string; remise_globale_pct?: number; conditions?: string; note?: string; lignes: CommercialLine[] }
export function FeeSection(parties: Party[], banks: NamedAccount[], cashes: NamedAccount[]): LineSection {
  return { key: 'frais', title: 'Frais accessoires', initial: { libelle: '', compte: '6085', montant_ht: '', taux_tva: '0', mode: 'credit', tiers_id: '', banque_id: '', caisse_id: '' }, fields: [
    { key: 'libelle', label: 'Libellé du frais', required: true }, { key: 'compte', label: 'Compte de charge', required: true }, { key: 'montant_ht', label: 'Montant HT USD', type: 'number', min: 0.01, required: true }, { key: 'taux_tva', label: 'TVA % du frais', type: 'number', min: 0, max: 100, required: true },
    { key: 'mode', label: 'Contrepartie', options: [['credit', 'Crédit fournisseur'], ['banque', 'Banque'], ['caisse', 'Caisse']] }, { key: 'tiers_id', label: 'Fournisseur du frais', options: [['', 'Même fournisseur'], ...parties.map(p => [p.id, partyLabel(p)] as [string, string])], visible: v => v.mode === 'credit' },
    { key: 'banque_id', label: 'Compte bancaire', required: true, options: [['', 'Choisir…'], ...banks.map(b => [b.id, b.libelle] as [string, string])], visible: v => v.mode === 'banque' }, { key: 'caisse_id', label: 'Caisse du frais', required: true, options: [['', 'Choisir…'], ...cashes.map(b => [b.id, b.libelle] as [string, string])], visible: v => v.mode === 'caisse' }] };
}
export function feePayload(rows: Values[]) { return rows.map(r => { const montant_ht = commercialNumber(r.montant_ht, 'Frais HT'); if (!montant_ht || !r.libelle.trim() || !r.compte.trim()) throw new Error('Complétez chaque frais ou retirez sa ligne.'); if (r.mode !== 'credit' && !r[r.mode === 'banque' ? 'banque_id' : 'caisse_id']) throw new Error('Indiquez la contrepartie du frais.'); return { libelle: r.libelle.trim(), compte: r.compte.trim(), montant_ht, taux_tva: commercialNumber(r.taux_tva, 'TVA du frais', 100), mode: r.mode, tiers_id: r.mode === 'credit' ? r.tiers_id || null : null, banque_id: r.mode === 'banque' ? r.banque_id : null, caisse_id: r.mode === 'caisse' ? r.caisse_id : null }; }); }
export function CommercialEditor(props: ScreenProps & { kind: 'achat' | 'vente' | 'commande' | 'devis'; document?: CommercialDocument; onClose: () => void; onSaved: () => void }) {
  const { bridge, state, kind, document, onClose, onSaved } = props, buying = kind === 'achat' || kind === 'commande';
  const load = useCallback(async () => { const [articles, parties, banks, cashes] = await Promise.all([bridge.api<Article[]>(`/commercial/articles?societe_id=${state.companyId}`), bridge.api<Party[]>(`/commercial/tiers?societe_id=${state.companyId}&type=${buying ? 'fournisseur' : 'client'}`), kind === 'achat' ? bridge.api<NamedAccount[]>(`/comptes-bancaires?societe_id=${state.companyId}`) : [], kind === 'achat' ? bridge.api<NamedAccount[]>(`/caisses?societe_id=${state.companyId}`) : []]); return { articles, parties, banks, cashes }; }, [bridge, state.companyId, buying, kind]);
  const r = useResource(load);
  return r.data && !r.busy && !r.error ? <Composer {...props} catalog={r.data} /> : <Dialog bridge={bridge} title="Préparation du document" onClose={onClose}><ErrorNotice error={r.error} />{r.busy && <p>Chargement des articles et des tiers…</p>}</Dialog>;
}
function Composer({ bridge, state, kind, document: doc, onClose, onSaved, catalog }: ScreenProps & { kind: 'achat' | 'vente' | 'commande' | 'devis'; document?: CommercialDocument; onClose: () => void; onSaved: () => void; catalog: { articles: Article[]; parties: Party[]; banks: NamedAccount[]; cashes: NamedAccount[] } }) {
  const buying = kind === 'achat' || kind === 'commande', [articles, setArticles] = useState(catalog.articles), [parties, setParties] = useState(catalog.parties.filter(p => kind !== 'devis' || p.code !== 'COMPTANT')), [newArticle, setNewArticle] = useState(false), [newParty, setNewParty] = useState(false), [selectedParty, setSelectedParty] = useState<Party | null>(null), [notice, setNotice] = useState('');
  const initial: Values = { tiers_id: doc?.tiers_id || '', date: doc?.date || today(), date_livraison_prevue: doc?.date_livraison_prevue || '', reference_fournisseur: doc?.reference_fournisseur || '', destination: doc?.destination || '', transporteur_societe_id: doc?.transporteur_societe_id || '', intra_groupe: doc?.intra_groupe ? 'oui' : 'non', validite: doc?.validite || '', remise_globale_pct: String(doc?.remise_globale_pct || 0), conditions: doc?.conditions || '', note: doc?.note || '', repartition: 'quantite' };
  const fields: FormField[] = [{ key: 'tiers_id', label: buying ? 'Fournisseur' : 'Client', required: !selectedParty, options: [['', selectedParty ? partyLabel(selectedParty) : 'Choisir…'], ...parties.map(p => [p.id, partyLabel(p)] as [string, string])] }, { key: 'date', label: 'Date du document', type: 'date', required: true }];
  if (kind === 'commande') fields.push({ key: 'date_livraison_prevue', label: 'Livraison prévue', type: 'date' }, { key: 'reference_fournisseur', label: 'Référence fournisseur' }, { key: 'destination', label: 'Destination', visible: () => !doc }, { key: 'transporteur_societe_id', label: 'Transporteur du groupe', visible: () => !doc, options: [['', 'Aucun'], ...state.companies.filter(c => c.id !== state.companyId).map(c => [c.id, c.nom] as [string, string])] });
  if (kind !== 'devis') fields.push({ key: 'intra_groupe', label: 'Opération intragroupe', options: [['non', 'Non'], ['oui', 'Oui']] });
  if (kind === 'devis') fields.push({ key: 'validite', label: 'Validité du devis', type: 'date' }, { key: 'remise_globale_pct', label: 'Remise globale %', type: 'number', min: 0, max: 100 }, { key: 'conditions', label: 'Conditions', type: 'textarea' }, { key: 'note', label: 'Note', type: 'textarea' });
  if (kind === 'achat') fields.push({ key: 'repartition', label: 'Répartition des frais', options: [['quantite', 'Par quantité'], ['valeur', 'Par valeur']] });
  const section: LineSection = { key: 'lignes', title: 'Articles', minimum: 1, initial: { article_id: '', designation: '', qte: '1', prix_unitaire: '0', taux_tva: '0', remise_pct: '0' }, fields: [{ key: 'article_id', label: 'Article du catalogue', options: [['', 'Ligne libre / service'], ...articles.filter(a => a.actif && (buying || a.nature === 'marchandise')).map(a => [a.id, `${a.code} · ${a.designation}`] as [string, string])] }, { key: 'designation', label: 'Désignation', required: true }, { key: 'qte', label: 'Quantité', type: 'number', min: 0.000001, required: true }, { key: 'prix_unitaire', label: 'Prix unitaire HT USD', type: 'number', min: 0, required: true }, { key: 'taux_tva', label: 'TVA %', type: 'number', min: 0, max: 100, required: true }, ...(kind === 'devis' ? [{ key: 'remise_pct', label: 'Remise ligne %', type: 'number' as const, min: 0, max: 100 }] : [])], onChange: (row, key, value) => { const a = key === 'article_id' ? articles.find(a => a.id === value) : null; return a ? { ...row, article_id: a.id, designation: a.designation, prix_unitaire: String(buying ? a.prix_achat : a.prix_vente), taux_tva: String(a.assujetti_tva ? a.taux_tva : 0) } : { ...row, [key]: value }; } };
  return <><OperationForm bridge={bridge} title={`${doc ? 'Modifier' : 'Nouveau document'} · ${kind === 'commande' ? 'Commande fournisseur' : kind === 'devis' ? 'Devis client' : kind === 'achat' ? 'Facture d’achat' : 'Facture de vente'}`} initial={initial} externalSelection={selectedParty ? { key: 'tiers_id', value: selectedParty.id } : undefined} fields={fields} sections={[section, ...(kind === 'achat' ? [FeeSection(parties, catalog.banks, catalog.cashes)] : [])]} initialRows={doc ? { lignes: doc.lignes.map(l => ({ article_id: l.article_id || '', designation: l.designation, qte: String(l.qte), prix_unitaire: String(l.prix_unitaire), taux_tva: String(l.taux_tva), remise_pct: String(kind === 'devis' ? lineDiscountForEdit(Number(l.remise_pct || 0), Number(doc.remise_globale_pct || 0)) : l.remise_pct || 0) })) } : {}} note={kind === 'achat' || kind === 'vente' ? 'La validation enregistre la facture, les mouvements de stock et les écritures dans le circuit comptable existant. Montants en USD.' : `Les articles appartiennent à la société active. Les fiches de tiers partagées restent clairement identifiées.${doc && Number(doc.remise_globale_pct) >= 100 ? ' Ce devis était entièrement remisé : la remise de ligne initiale ne peut pas être retrouvée ; renseignez-la si vous réduisez la remise globale.' : ''}`} extra={<><button type="button" className="btn" onClick={() => setNewParty(true)}>Choisir ou créer {buying ? 'un fournisseur' : 'un client'}</button><button type="button" className="btn" onClick={() => setNewArticle(true)}><i className="ti ti-plus" aria-hidden="true" /> Créer un article</button>{selectedParty && <p>Tiers choisi : {partyLabel(selectedParty)}.</p>}{notice && <p role="status">{notice}</p>}</>} summary={(v, rows) => { try { const t = commercialTotals(rows.lignes, kind === 'devis' ? v.remise_globale_pct : '0'); return <p className="banner">HT {number(t.ht)} · TVA {number(t.tva)} · TTC {number(t.ttc)} USD · hors frais accessoires</p>; } catch { return <p>Complétez les lignes pour obtenir le total.</p>; } }} onClose={onClose} save={async (v, rows) => {
    const tiers_id = v.tiers_id || selectedParty?.id; if (!tiers_id) throw new Error('Choisissez un tiers.');
    const lignes = commercialLines(rows.lignes, kind === 'devis'); let path: string, body: object;
    if (kind === 'commande') { path = `/commercial/commandes${doc ? `/${doc.id}` : `?societe_id=${state.companyId}`}`; body = { tiers_id, lignes, date_commande: v.date, date_livraison_prevue: v.date_livraison_prevue || null, reference_fournisseur: v.reference_fournisseur || null, destination: v.destination || null, transporteur_societe_id: v.transporteur_societe_id || null, intra_groupe: v.intra_groupe === 'oui' }; }
    else if (kind === 'devis') { path = `/ventes/devis${doc ? `/${doc.id}` : `?societe_id=${state.companyId}`}`; body = { tiers_id, lignes, date_devis: v.date, validite: v.validite || null, remise_globale_pct: commercialNumber(v.remise_globale_pct, 'Remise', 100), conditions: v.conditions || null, note: v.note || null }; }
    else { path = `/commercial/factures?societe_id=${state.companyId}`; body = { type: kind, tiers_id, lignes, date_facture: v.date, intra_groupe: v.intra_groupe === 'oui', frais: kind === 'achat' ? feePayload(rows.frais) : [], repartition: v.repartition }; }
    await bridge.api(path, { method: doc ? 'PUT' : 'POST', body }); onSaved();
  }} />{newParty && <AccountingPartyPicker bridge={bridge} state={state} allowedKind={buying ? 'fournisseur' : 'client'} parties={parties} onClose={() => setNewParty(false)} onSelected={p => { setParties(all => [...all.filter(x => x.id !== p.id), p]); setSelectedParty(p); setNewParty(false); }} />}{newArticle && <ArticleEditor bridge={bridge} state={state} article={null} articles={articles} onClose={() => setNewArticle(false)} onExisting={a => { setNotice(`Article existant : ${a.code}, sélectionnez-le dans la ligne concernée.`); setNewArticle(false); }} onSaved={a => { setArticles(all => [...all, a]); setNotice(`Article ${a.code} ajouté au catalogue, sélectionnez-le dans la ligne concernée.`); setNewArticle(false); }} />}</>;
}
