'use client';
import { ScreenTitle } from './screen-presentation';
import { useCallback, useState } from 'react';
import { DataTable } from './data-table';
import { Dialog, ErrorNotice, number, ReportPreview, useResource, type ScreenProps } from './shared';

interface StockArrival { reference: string; date: string; origine: string; tiers: string | null; total_valeur: number; total_qte: number; articles: { code: string; qte: number; cout: number }[] }
interface SalesSummary { chiffre_affaires: number; marge: number; tva_collectee: number; nb_factures: number; taux_marge: number; palmares: { code: string; qte: number; cout: number }[] }
const arrivalNote = 'Historique des entrées en stock regroupées par référence, selon le rapport existant. Les entrées d’inventaire, de transfert ou d’autres origines peuvent être incluses : ce total ne représente pas exclusivement les dépenses d’achat. Les quantités de différents articles ne sont pas directement comparables.';
const salesNote = 'Tout l’historique, tous statuts de factures selon le calcul commercial existant, avec déduction des avoirs. Ces indicateurs ne sont pas limités aux pièces comptables validées. La TVA affichée ne constitue pas une déclaration. Le palmarès porte sur les huit premières quantités sorties en vente ; les retours ne sont pas compensés dans ce classement.';
export function CommercialReports({ bridge, state }: ScreenProps) {
  const [tab, setTab] = useState('achats');
  return <><div className="audit-head"><div><ScreenTitle>Analyse des achats & ventes</ScreenTitle><p className="muted">Société active · Historique complet · Montants USD</p></div></div><div className="business-toolbar" role="group" aria-label="Rapports commerciaux">{[['achats', 'Historique des entrées en stock'], ['ventes', 'Synthèse des ventes']].map(([key, label]) => <button key={key} className={`btn ${tab === key ? 'btn-primary' : ''}`} aria-pressed={tab === key} onClick={() => setTab(key)}>{label}</button>)}</div>{tab === 'achats' ? <Arrivals bridge={bridge} state={state} /> : <Sales bridge={bridge} state={state} />}</>;
}
function Arrivals({ bridge, state }: ScreenProps) {
  const load = useCallback(() => bridge.api<StockArrival[]>(`/commercial/achats-historique?societe_id=${state.companyId}`), [bridge, state.companyId]);
  const result = useResource(load), [origin, setOrigin] = useState(''), [detail, setDetail] = useState<StockArrival | null>(null), disabled = result.busy || !!result.error;
  const rows = result.data?.filter(r => !origin || r.origine === origin) || [];
  return <><p className="banner">{arrivalNote}</p><div className="business-toolbar"><label className="business-field">Origine<select className="form-select" value={origin} onChange={e => setOrigin(e.target.value)}><option value="">Toutes origines</option>{Array.from(new Set(result.data?.map(r => r.origine))).sort().map(o => <option key={o}>{o}</option>)}</select></label><button className="btn" disabled={result.busy} onClick={result.refresh}><i className="ti ti-refresh" aria-hidden="true" /> Actualiser</button></div><ErrorNotice error={result.error} />{result.busy && <p role="status">Lecture des entrées en stock…</p>}{result.data && <><p>Valeur des entrées pour l’origine choisie, avant recherche : <strong>{disabled ? '—' : number(rows.reduce((s, r) => s + r.total_valeur, 0))} USD</strong>.</p><DataTable bridge={bridge} state={state} title="Historique des entrées en stock" subtitle={`${origin || 'Toutes origines'} · Tout l’historique · USD`} disabled={disabled} reportNote={arrivalNote} columns={['Date', 'Origine', 'Référence', 'Fournisseur / bénéficiaire', 'Articles', 'Quantité cumulée', 'Valeur au coût USD']} precision={{ 5: 3 }} rows={rows.map(r => [r.date, r.origine, r.reference, r.tiers || '', r.articles.map(a => `${a.code || 'Non renseigné'} × ${new Intl.NumberFormat('fr-FR', { maximumFractionDigits: 3 }).format(a.qte)}`).join(' ; '), r.total_qte, r.total_valeur])} actions={(_, i) => <button className="btn btn-sm" disabled={disabled} onClick={() => setDetail(rows[i])}>Détail articles</button>} /></>}{detail && <Dialog bridge={bridge} title={`Articles — ${detail.reference}`} onClose={() => setDetail(null)}><DataTable bridge={bridge} state={state} title={`Détail ${detail.reference}`} subtitle={`${detail.date} · ${detail.origine} · ${detail.tiers || 'Tiers non renseigné'}`} columns={['Article', 'Quantité', 'Valeur au coût USD']} precision={{ 1: 3 }} rows={detail.articles.map(a => [a.code || 'Non renseigné', a.qte, a.cout])} reportNote={arrivalNote} /></Dialog>}</>;
}
function Sales({ bridge, state }: ScreenProps) {
  const load = useCallback(() => bridge.api<SalesSummary>(`/commercial/ventes-synthese?societe_id=${state.companyId}`), [bridge, state.companyId]);
  const result = useResource(load), [preview, setPreview] = useState(false), data = result.data, disabled = result.busy || !!result.error;
  const indicators: (string | number)[][] = data ? [['Chiffre d’affaires HT', data.chiffre_affaires, 'USD'], ['Marge commerciale', data.marge, 'USD'], ['Taux de marge / CA', data.taux_marge, '%'], ['TVA des ventes nette des avoirs', data.tva_collectee, 'USD'], ['Factures de vente', data.nb_factures, 'Nombre']] : [];
  return <><p className="banner">{salesNote}</p><div className="business-toolbar"><button className="btn" disabled={result.busy} onClick={result.refresh}><i className="ti ti-refresh" aria-hidden="true" /> Actualiser</button><button className="btn" disabled={disabled || !data} onClick={() => setPreview(true)}>Synthèse PDF / Excel</button></div><ErrorNotice error={result.error} />{result.busy && <p role="status">Lecture des ventes…</p>}{data && <><div className="caisse-cards">{indicators.map(([label, value, unit]) => <article className="caisse-card" key={label}><p>{label}</p><strong>{disabled ? '—' : `${number(value)} ${unit === 'Nombre' ? '' : unit}`}</strong></article>)}</div><DataTable bridge={bridge} state={state} title="Palmarès des articles vendus" subtitle="Huit premières quantités sorties en vente · Tout l’historique" disabled={disabled} columns={['Article', 'Quantité sortie', 'Coût des ventes USD']} precision={{ 1: 3 }} rows={data.palmares.map(a => [a.code || 'Non renseigné', a.qte, a.cout])} reportNote={salesNote} /></>}{preview && data && <ReportPreview bridge={bridge} state={state} onClose={() => setPreview(false)} report={{ title: 'Synthèse commerciale des ventes', subtitle: 'Historique complet · Tous statuts de factures · Calcul commercial existant', columns: ['Indicateur', 'Valeur', 'Unité'], rows: indicators, note: salesNote }} />}</>;
}
