'use client';
import { useState, type ReactNode } from 'react';
import { selectTableRows, tableCSV, type Cell } from '../../lib/table-data';
import { ReportPreview, ErrorNotice, exportReport, message, number, type Report, type ScreenProps } from './shared';

const statusTone=(value:string)=>/^(valide|validée?|payee?|payée?|terminee?|terminée?|libre|actif|ouverte?|recue?|reçue?|approuvee?|approuvée?)$/i.test(value)?'st-payee':/^(rejete.*|rejeté.*|annule.*|annulé.*|erreur|bloque.*|bloqué.*)$/i.test(value)?'st-rejetee':/attente|brouillon|soumis|due|a_|à /i.test(value)?'st-due':'st-envoye';
const statusColumn=(name:string)=>/^(statut|état|etat)$/i.test(name);
const moneyColumn=(name:string)=>/USD|CDF|\b(HT|TTC)\b|^(montant|solde|prix|tarif|valeur|total|net|brut)/i.test(name)&&!/%|quantité|quantite|nombre|taux|points/i.test(name);

export function DataTable({ bridge, state, title, columns, rows, subtitle, disabled = false, actions, precision = {}, reportNote = '' }: ScreenProps & { title: string; columns: string[]; rows: Cell[][]; subtitle: string; disabled?: boolean; precision?: Record<number, number>; reportNote?: string; actions?: (row: Cell[], sourceIndex: number) => ReactNode }) {
  const [search, setSearch] = useState(''), [sort, setSort] = useState(-1), [direction, setDirection] = useState(1), [size, setSize] = useState(25), [page, setPage] = useState(1), [preview, setPreview] = useState(false), [exporting, setExporting] = useState(false), [error, setError] = useState('');
  const selected = selectTableRows(rows, search, sort, direction), pages = Math.max(1, Math.ceil(selected.length / size)), current = Math.min(page, pages);
  const reset = () => { setSearch(''); setSort(-1); setDirection(1); setPage(1); };
  const csv = () => { const url = URL.createObjectURL(new Blob([tableCSV(columns, selected)], { type: 'text/csv;charset=utf-8' })); const a = document.createElement('a'); a.href = url; a.download = title + '.csv'; a.click(); setTimeout(() => URL.revokeObjectURL(url), 30000); };
  const report: Report = { title, subtitle: `${subtitle} · Recherche : ${search || 'aucune'} · ${selected.length} lignes`, columns, rows: selected.map(row => row.map((cell, index) => typeof cell === 'number' && precision[index] !== undefined ? new Intl.NumberFormat('fr-FR', { maximumFractionDigits: precision[index] }).format(cell) : cell ?? '')), note: `Ce rapport reprend toute la sélection filtrée, y compris les autres pages. ${reportNote}`.trim() };
  const download = async (format:'pdf'|'xlsx') => { if(exporting)return; const release=bridge.holdNavigation();setExporting(true);setError('');try{await exportReport(bridge,state.companyId,report,format);}catch(e){setError(message(e));}finally{release();setExporting(false);} };
  return <section className="business-grid card native-list" aria-label={title}>
    <header className="card-hdr"><h3 className="card-hdr-title">{title}</h3><button type="button" className="btn btn-sm" title="Aperçu du rapport" aria-label={`Aperçu · ${title}`} disabled={disabled || exporting || !selected.length} onClick={()=>setPreview(true)}><i className="ti ti-printer" aria-hidden="true" /></button></header>
    <div className="list-tools"><div className="list-tools-controls"><label className="list-search"><span className="sr-only">Rechercher · {title}</span><input className="form-input" type="search" value={search} onChange={e => { setSearch(e.target.value); setPage(1); }} placeholder="Rechercher dans cette liste…" /></label><button type="button" className="btn btn-sm" onClick={reset}>Réinitialiser</button>{state.user?.super_administrateur ? <button type="button" className="btn btn-sm" disabled={disabled || exporting || !selected.length} onClick={()=>setPreview(true)}>Aperçu & impression</button> : <><button type="button" className="btn btn-sm" disabled={disabled || exporting || !selected.length} onClick={()=>download('xlsx')}><i className="ti ti-file-spreadsheet" aria-hidden="true" /> Excel</button><button type="button" className="btn btn-sm" disabled={disabled || exporting || !selected.length} onClick={()=>download('pdf')}><i className="ti ti-file-type-pdf" aria-hidden="true" /> PDF</button></>}<button type="button" className="btn btn-sm list-csv" disabled={disabled || exporting || !selected.length} onClick={csv}>CSV</button></div><div className="list-tools-caption"><span role="status">{selected.length} / {rows.length} résultat(s)</span><span>{subtitle}</span></div></div>
    <ErrorNotice error={error} />{exporting&&<p role="status" className="muted">Préparation du document…</p>}
    <div className="list-table-scroll business-table"><table className="managed-list"><thead><tr>{columns.map((col, index) => <th key={col} aria-sort={sort === index ? direction === 1 ? 'ascending' : 'descending' : 'none'}><button type="button" className="list-sort" onClick={() => { setDirection(sort === index ? -direction : 1); setSort(index); setPage(1); }}>{col}</button></th>)}{actions && <th>Actions</th>}</tr></thead><tbody>{selected.slice((current - 1) * size, current * size).map((row, i) => <tr key={i}>{row.map((cell, index) => <td key={index} className={typeof cell === 'number' ? 'right num-cell' : /^(numéro|n°|pièce|référence|code)$/i.test(columns[index]) ? 'num-cell' : undefined}>{typeof cell === 'number' ? precision[index] !== undefined ? new Intl.NumberFormat('fr-FR', { maximumFractionDigits: precision[index] }).format(cell) : moneyColumn(columns[index]) ? new Intl.NumberFormat('fr-FR', {minimumFractionDigits:2, maximumFractionDigits:2}).format(cell) : number(cell) : statusColumn(columns[index]) && cell ? <span className={`pill ${statusTone(String(cell))}`}>{cell}</span> : cell}</td>)}{actions && <td className="native-list-actions"><div>{actions(row, rows.indexOf(row))}</div></td>}</tr>)}{!selected.length && <tr><td colSpan={columns.length + (actions ? 1 : 0)} className="audit-empty">Aucune ligne pour cette recherche.</td></tr>}</tbody></table></div>
    <div className="list-pagination"><label>Lignes par page<select className="form-select" value={size} onChange={e => { setSize(Number(e.target.value)); setPage(1); }}>{[25,50,100].map(n=><option key={n}>{n}</option>)}</select></label><div><button type="button" className="btn btn-sm" aria-label={`Page précédente · ${title}`} disabled={current<=1} onClick={()=>setPage(current-1)}>←</button><span>Page {current} / {pages}</span><button type="button" className="btn btn-sm" aria-label={`Page suivante · ${title}`} disabled={current>=pages} onClick={()=>setPage(current+1)}>→</button></div></div>
    {preview && <ReportPreview bridge={bridge} state={state} onClose={() => setPreview(false)} report={report} />}
  </section>;
}
