'use client';
import { ScreenTitle } from './screen-presentation';
import { useCallback, useRef, useState } from 'react';
import { inventoryStatus, quantity, transferPayload, type Depot, type DepotState, type Inventory, type Transfer } from '../../lib/stock-forms';
import { ArticleEditor, type Article } from './articles';
import { DataTable } from './data-table';
import { Field } from './field';
import { CountDialog, InventoryDetail } from './inventories';
import { Dialog, ErrorNotice, ReportPreview, message, number, useResource, type ScreenProps, type Report } from './shared';

export function Depots({ bridge, state }: ScreenProps) {
  const load = useCallback(async () => { const [depots, transfers, inventories] = await Promise.all([bridge.api<Depot[]>(`/stock/depots?societe_id=${state.companyId}&toutes=1`), bridge.api<Transfer[]>(`/stock/transferts?societe_id=${state.companyId}`), bridge.api<Inventory[]>(`/stock/inventaires?societe_id=${state.companyId}`)]); return { depots, transfers, inventories }; }, [bridge, state.companyId]);
  const result = useResource(load), disabled = result.busy || !!result.error;
  const [editing, setEditing] = useState<Depot | 'new' | null>(null), [stock, setStock] = useState<Depot | null>(null), [count, setCount] = useState<Depot | null>(null), [transferring, setTransferring] = useState(false), [inventory, setInventory] = useState<Inventory | null>(null), [report, setReport] = useState<Report | null>(null), [inactive, setInactive] = useState(false), [success, setSuccess] = useState('');
  const roles = state.companies.find(c => c.id === state.companyId)?.roles || [], manager = roles.some(r => ['DFI', 'PRESIDENT', 'ADMIN_SYS', 'DG'].includes(r));
  const active = result.data?.depots.filter(d => d.actif) || [];
  return <>
    <div className="audit-head"><div><ScreenTitle>Dépôts & transferts</ScreenTitle><p className="muted">Le dépôt central approvisionne les dépôts dédiés : cuisine, bar, restaurant…</p></div><div className="audit-actions"><button className="btn" disabled={result.busy} onClick={result.refresh}><i className="ti ti-refresh" aria-hidden="true" /> Actualiser</button>{manager && <button className="btn" disabled={disabled} onClick={() => setEditing('new')}>Nouveau dépôt</button>}<button className="btn btn-primary" disabled={disabled || active.length < 2} onClick={() => setTransferring(true)}>Nouveau transfert</button></div></div>
    <ErrorNotice error={result.error} />{success && <p className="business-success" role="status">{success}</p>}{result.busy && <p role="status">Chargement des dépôts…</p>}
    <label className="business-check"><input type="checkbox" checked={inactive} onChange={e => setInactive(e.target.checked)} /> Inclure les dépôts inactifs</label>
    <div className="caisse-cards">{result.data?.depots.filter(d => inactive || d.actif).map(d => <article className="caisse-card" key={d.id}><div className="cc-top"><b>{d.libelle}</b><span className="tag">{d.type === 'central' ? 'Central' : 'Dédié'}</span>{!d.actif && <span className="tag">Inactif</span>}</div><p><strong>{number(d.valeur_stock_usd)} USD</strong> · {d.nb_references} références en stock</p><p className="muted">{d.point_vente ? `Point de vente : ${d.point_vente}` : 'Aucun point de vente associé'}</p><div className="business-toolbar"><button className="btn btn-sm" disabled={disabled} onClick={() => setStock(d)} aria-label={`Voir le stock · ${d.libelle}`}>Voir le stock</button>{d.actif && <button className="btn btn-sm" disabled={disabled} onClick={() => setCount(d)} aria-label={`Compter · ${d.libelle}`}>Compter</button>}{manager && d.type !== 'central' && <button className="btn btn-sm" disabled={disabled} onClick={() => setEditing(d)} aria-label={`Modifier le dépôt ${d.libelle}`}><i className="ti ti-edit" aria-hidden="true" /> Modifier</button>}</div></article>)}</div>
    {result.data && <><DataTable bridge={bridge} state={state} title="Transferts entre dépôts" subtitle="100 derniers transferts · valorisation au coût du dépôt source" disabled={disabled} columns={['Numéro', 'Date', 'Source', 'Destination', 'Lignes', 'Valeur (USD)', 'Note']} rows={result.data.transfers.map(t => [t.numero, t.date, t.source, t.cible, t.lignes.length, t.valeur_totale, t.note || ''])} actions={row => <button className="btn btn-sm" disabled={disabled} onClick={() => { const t = result.data!.transfers.find(t => t.numero === row[0])!; setReport({ title: `Bon de transfert ${t.numero}`, subtitle: `${t.date} · ${t.source} → ${t.cible}`, columns: ['Code', 'Article', 'Quantité', 'Valeur USD'], rows: t.lignes.map(l => [l.code, l.designation, quantity(l.qte), l.valeur]), note: `Total : ${number(t.valeur_totale)} USD. ${t.note || ''} · Magasinier : __________________ · Réceptionnaire : __________________` }); }}>Bon de transfert</button>} />
    <DataTable bridge={bridge} state={state} title="Derniers comptages" subtitle="50 derniers inventaires · consultez Inventaires & écarts pour les périodes antérieures" disabled={disabled} columns={['Numéro', 'Date', 'Dépôt', 'État', 'Écart (USD)']} rows={result.data.inventories.map(i => [i.numero, i.date, i.depot, inventoryStatus[i.statut], i.ecart_valeur])} actions={row => <button className="btn btn-sm" disabled={disabled} onClick={() => setInventory(result.data!.inventories.find(i => i.numero === row[0])!)}><i className="ti ti-eye" aria-hidden="true" /> Consulter</button>} /></>}
    {editing && <DepotEditor bridge={bridge} state={state} depot={editing === 'new' ? null : editing} onClose={() => setEditing(null)} onSaved={() => { setEditing(null); setSuccess('Dépôt enregistré.'); result.refresh(); }} />}
    {stock && <DepotStock bridge={bridge} state={state} depot={stock} onClose={() => setStock(null)} />}
    {count && <CountDialog bridge={bridge} state={state} depots={active} initialDepot={count.id} onClose={() => setCount(null)} onSaved={i => { setCount(null); setSuccess(`${i.numero} préparé : stock inchangé, en attente de validation.`); result.refresh(); }} />}
    {transferring && <TransferDialog bridge={bridge} state={state} depots={active} onClose={() => setTransferring(false)} onSaved={t => { setTransferring(false); setSuccess(`${t.numero} effectué · ${number(t.valeur_totale)} USD transférés.`); result.refresh(); }} />}
    {inventory && <InventoryDetail bridge={bridge} state={state} inventory={inventory} onClose={() => setInventory(null)} onChanged={i => { setInventory(i); result.refresh(); }} />}
    {report && <ReportPreview bridge={bridge} state={state} report={report} onClose={() => setReport(null)} />}
  </>;
}
function DepotEditor({ bridge, state, depot, onClose, onSaved }: ScreenProps & { depot: Depot | null; onClose: () => void; onSaved: () => void }) {
  const [name, setName] = useState(depot?.libelle || ''), [active, setActive] = useState(depot?.actif ?? true), [busy, setBusy] = useState(false), [error, setError] = useState('');
  const pending = useRef(false);
  return <Dialog bridge={bridge} title={depot ? `Dépôt ${depot.libelle}` : 'Nouveau dépôt dédié'} onClose={onClose} busy={busy} footer={close => <><button className="btn" disabled={busy} onClick={close}><i className="ti ti-x" aria-hidden="true" /> Annuler</button><button className="btn btn-primary" type="submit" form="depot-form" disabled={busy}><i className="ti ti-device-floppy" aria-hidden="true" /> Enregistrer</button></>}><form id="depot-form" onSubmit={async e => { e.preventDefault(); if (pending.current) return; setError(''); if (name.trim().length < 2) { setError('Le libellé doit contenir au moins deux caractères.'); return; } pending.current = true; setBusy(true); try { await bridge.api(depot ? `/stock/depots/${depot.id}?societe_id=${state.companyId}` : `/stock/depots?societe_id=${state.companyId}`, { method: depot ? 'PATCH' : 'POST', body: { libelle: name.trim(), ...(depot ? { actif: active } : {}) } }); onSaved(); } catch (cause) { setError(message(cause)); } finally { pending.current = false; setBusy(false); } }}><fieldset className="business-fieldset" disabled={busy}><Field label="Libellé du dépôt" value={name} onChange={setName} required minLength={2} maxLength={100} />{depot && <label className="business-check"><input type="checkbox" checked={active} onChange={e => setActive(e.target.checked)} /> Dépôt actif</label>}<p className="muted">Le dépôt central reçoit les achats. Approvisionnez ensuite ce dépôt par transfert. L’association à un point de vente se règle dans « Tarifs & points de vente ». Un dépôt lié à un point de vente actif ne peut pas être fermé.</p><ErrorNotice error={error} /></fieldset></form></Dialog>;
}
function DepotStock({ bridge, state, depot, onClose }: ScreenProps & { depot: Depot; onClose: () => void }) {
  const load = useCallback(() => bridge.api<DepotState>(`/stock/depots-etat?societe_id=${state.companyId}&depot_id=${depot.id}`), [bridge, state.companyId, depot.id]);
  const result = useResource(load);
  return <Dialog bridge={bridge} title={`Stock · ${depot.libelle}`} onClose={onClose}><ErrorNotice error={result.error} />{result.error && <button className="btn" onClick={result.refresh}>Réessayer</button>}{result.busy && <p role="status">Lecture du stock…</p>}{result.data && <DataTable bridge={bridge} state={state} title={`Stock ${depot.libelle}`} subtitle={`Valeur totale : ${number(result.data.valeur_totale)} USD`} disabled={result.busy || !!result.error} columns={['Code', 'Article', 'Quantité', 'Unité', 'CUMP (USD)', 'Valeur (USD)']} precision={{ 2: 3, 4: 4 }} rows={result.data.articles.map(a => [a.code, a.designation, a.qte, a.unite, a.cump, a.valeur || 0])} />}</Dialog>;
}
function TransferDialog({ bridge, state, depots, onClose, onSaved }: ScreenProps & { depots: Depot[]; onClose: () => void; onSaved: (t: Transfer) => void }) {
  const sourceDefault = depots.find(d => d.type === 'central')?.id || depots[0]?.id || '';
  const [source, setSource] = useState(sourceDefault), [target, setTarget] = useState(depots.find(d => d.id !== sourceDefault)?.id || ''), [note, setNote] = useState(''), [lines, setLines] = useState([{ key: 0, article_id: '', qte: '' }]), [error, setError] = useState(''), [busy, setBusy] = useState(false), [creatingFor, setCreatingFor] = useState<number | null>(null), [added, setAdded] = useState<Article[]>([]);
  const pending = useRef(false), nextKey = useRef(1);
  const loadArticles = useCallback(() => bridge.api<Article[]>(`/commercial/articles?societe_id=${state.companyId}`), [bridge, state.companyId]);
  const articles = useResource(loadArticles);
  const loadSource = useCallback(() => bridge.api<DepotState>(`/stock/depots-etat?societe_id=${state.companyId}&depot_id=${source}`), [bridge, state.companyId, source]);
  const stock = useResource(loadSource);
  const catalogue = [...(articles.data || []).filter(a => !added.some(b => b.id === a.id)), ...added];
  const eligible = catalogue.filter(a => a.gere_stock && a.actif);
  const roles = state.companies.find(c => c.id === state.companyId)?.roles || [], canCreate = roles.some(r => ['DFI', 'COMPTABLE'].includes(r));
  const update = (key: number, patch: Partial<{ article_id: string; qte: string }>) => setLines(old => old.map(l => l.key === key ? { ...l, ...patch } : l));
  const chooseCreated = (a: Article) => { setAdded(old => [...old.filter(x => x.id !== a.id), a]); if (a.gere_stock && a.actif && creatingFor !== null) { update(creatingFor, { article_id: a.id }); setError(''); } else setError('La fiche doit être active et gérée en stock pour être transférée.'); setCreatingFor(null); };
  const unavailable = busy || articles.busy || stock.busy || !!articles.error || !!stock.error;
  return <><Dialog bridge={bridge} title="Transfert entre dépôts" busy={busy} onClose={onClose} footer={close => <><button className="btn" disabled={busy} onClick={close}><i className="ti ti-x" aria-hidden="true" /> Annuler</button><button className="btn btn-primary" type="submit" form="transfer-form" disabled={unavailable}>{busy ? 'Transfert…' : 'Effectuer le transfert'}</button></>}>
    <p className="banner">Le transfert déplace immédiatement le stock au coût moyen du dépôt source. Le stock total de la société reste inchangé, sans écriture comptable.</p><ErrorNotice error={articles.error || stock.error} />{(articles.error || stock.error) && <button className="btn" onClick={() => { articles.refresh(); stock.refresh(); }}>Réessayer le chargement</button>}
    <form id="transfer-form" onSubmit={async e => { e.preventDefault(); if (pending.current || unavailable) return; setError(''); try { const lignes = transferPayload(source, target, lines); for (const l of lignes) { const available = stock.data?.articles.find(a => a.article_id === l.article_id)?.qte || 0; if (l.qte > available + 0.000001) throw new Error(`Stock insuffisant pour ${eligible.find(a => a.id === l.article_id)?.code || 'cet article'} : ${quantity(available)} disponible(s).`); } pending.current = true; setBusy(true); const saved = await bridge.api<Transfer>(`/stock/transferts?societe_id=${state.companyId}`, { method: 'POST', body: { depot_source_id: source, depot_cible_id: target, note: note.trim(), lignes } }); onSaved(saved); } catch (cause) { setError(message(cause)); } finally { pending.current = false; setBusy(false); } }}>
      <fieldset className="business-fieldset" disabled={busy}><div className="business-form-grid"><label>Dépôt source<select className="form-select" value={source} onChange={e => setSource(e.target.value)}>{depots.map(d => <option key={d.id} value={d.id}>{d.libelle}</option>)}</select></label><label>Dépôt destination<select className="form-select" value={target} onChange={e => setTarget(e.target.value)}>{depots.map(d => <option key={d.id} value={d.id} disabled={d.id === source}>{d.libelle}</option>)}</select></label></div>
      {lines.map((l, index) => { const a = eligible.find(a => a.id === l.article_id), available = stock.data?.articles.find(s => s.article_id === l.article_id)?.qte || 0; return <section className="stock-transfer-line" key={l.key}><label>Article {index + 1}<select className="form-select" required value={l.article_id} onChange={e => update(l.key, { article_id: e.target.value })}><option value="">Choisir un article…</option>{eligible.map(a => <option value={a.id} key={a.id} disabled={lines.some(other => other.key !== l.key && other.article_id === a.id)}>{a.code} — {a.designation}</option>)}</select></label><Field label={`Quantité ${index + 1}`} type="number" required min="0.001" step="0.001" value={l.qte} onChange={qte => update(l.key, { qte })} /><p className="muted">{stock.busy ? 'Lecture du stock source…' : a ? `Disponible : ${quantity(available)} ${a.unite}` : 'Sélectionnez un article'}</p><div className="business-toolbar">{canCreate && <button className="btn btn-sm" type="button" disabled={articles.busy || !!articles.error} onClick={() => setCreatingFor(l.key)}><i className="ti ti-plus" aria-hidden="true" /> Créer un article</button>}<button className="btn btn-sm" type="button" disabled={lines.length === 1} onClick={() => setLines(old => old.filter(row => row.key !== l.key))}>Retirer la ligne {index + 1}</button></div></section>; })}
      <button className="btn" type="button" onClick={() => setLines(old => [...old, { key: nextKey.current++, article_id: '', qte: '' }])}>Ajouter une ligne</button><Field label="Note du transfert" value={note} onChange={setNote} maxLength={255} /><ErrorNotice error={error} /></fieldset>
    </form>
  </Dialog>{creatingFor !== null && <ArticleEditor bridge={bridge} state={state} article={null} articles={catalogue} onClose={() => setCreatingFor(null)} onSaved={chooseCreated} onExisting={chooseCreated} />}</>;
}
