'use client';
import { ScreenTitle } from './screen-presentation';
import { useCallback, useState } from 'react';
import { DataTable } from './data-table';
import { PaymentEditor, type Order } from './cash-executions';
import { MoneyReceipt } from './money-receipt';
import { ApprovalDecision } from './requisitions';
import { ErrorNotice, useResource, type ScreenProps } from './shared';
export function ExpenseOrders(props: ScreenProps) {
  const load = useCallback(() => props.bridge.api<Order[]>(`/ordres-depense?societe_id=${props.state.companyId}`), [props.bridge, props.state.companyId]), result = useResource(load), [payment, setPayment] = useState<Order | null>(null), [decision, setDecision] = useState<Order | null>(null), [receipt, setReceipt] = useState<{ orderId: string; bonNumber?: string; movementId?: string } | null>(null), [status, setStatus] = useState('');
  const rows = result.data?.filter(o => !status || o.statut === status) || [], roles = props.state.companies.find(c => c.id === props.state.companyId)?.roles || [];
  return <><div className="audit-head"><ScreenTitle>Ordres de dépense</ScreenTitle><button className="btn" disabled={result.busy} onClick={result.refresh}><i className="ti ti-refresh" aria-hidden="true" /> Actualiser</button></div><label className="business-field">Statut<select className="form-select" value={status} onChange={e => setStatus(e.target.value)}>{[['', 'Tous'], ['a_valider', 'À valider'], ['valide', 'À décaisser'], ['execute', 'Exécuté'], ['paye', 'Payé'], ['rejete', 'Rejeté']].map(([v, l]) => <option key={v} value={v}>{l}</option>)}</select></label><ErrorNotice error={result.error} />{result.busy && <p>Lecture des ordres…</p>}{result.data && !result.busy && !result.error && <DataTable {...props} title="Ordres de dépense" subtitle="Société active" columns={['Ordre', 'Réquisition', 'Objet', 'Bénéficiaire', 'Mode', 'Palier', 'Autorisé USD', 'Payé USD', 'Reste USD', 'Statut']} rows={rows.map(o => [o.numero, o.requisition_numero || '', o.requisition_objet || o.motif || '', o.beneficiaire || '', o.mode_paiement, o.palier_applique || '', o.montant_autorise_usd, o.montant_paye_usd, o.reste_usd, o.statut])} actions={(_, i) => { const o = rows[i], canPay = (o.mode_paiement === 'banque' ? ['COMPTABLE', 'DFI'] : ['CAISSIER_CENTRAL', 'CAISSIER_VENDEUR']).some(r => roles.includes(r)); return <div className="audit-actions">{o.statut === 'a_valider' && <button className="btn" onClick={() => setDecision(o)}>Valider à mon niveau</button>}{o.statut === 'valide' && canPay && <button className="btn" onClick={() => setPayment(o)}>Décaisser</button>}{(o.montant_paye_usd > 0 || ['execute', 'paye'].includes(o.statut)) && <button className="btn" onClick={() => setReceipt({ orderId: o.id })}>Dernier bon de sortie</button>}</div>; }} />}{decision && <ApprovalDecision {...props} kind="ordre" id={decision.id} decision="valide" label={decision.numero} onClose={() => setDecision(null)} onSaved={() => { setDecision(null); result.refresh(); }} />}{payment && <PaymentEditor {...props} order={payment} onClose={() => setPayment(null)} onSaved={r => { setReceipt({ orderId: payment.id, bonNumber: r.bon_reception, movementId: r.mouvement_id }); setPayment(null); result.refresh(); void props.bridge.refreshAccountingBadge(); }} />}{receipt && <MoneyReceipt {...props} {...receipt} onClose={() => setReceipt(null)} />}</>;
}
