'use client';
import { ScreenTitle } from './screen-presentation';
import { useCallback, useState } from 'react';
import { accountingStatuses } from '../../lib/accounting-data';
import { balanceSheetRows, cashFlowRows, incomeRows, type BalanceSheet, type CashFlowStatement, type FinancialOverview, type IncomeStatement, type StatementRow } from '../../lib/financial-data';
import { ErrorNotice, ReportPreview, number, useResource, type ScreenProps, type Report } from './shared';

export function FinancialStatements({ bridge, state }: ScreenProps) {
  const [tab, setTab] = useState('resultat'), [status, setStatus] = useState(''), [preview, setPreview] = useState<Report | null>(null);
  const load = useCallback(async () => { const suffix = `?${new URLSearchParams({ societe_id: state.companyId!, statut: status })}`; const [income, balance, cashflow] = await Promise.all([bridge.api<IncomeStatement>('/comptabilite/compte-resultat' + suffix), bridge.api<BalanceSheet>('/comptabilite/bilan' + suffix), bridge.api<CashFlowStatement>('/comptabilite/tft' + suffix)]); return { income, balance, cashflow }; }, [bridge, state.companyId, status]);
  const result = useResource(load), data = result.data, disabled = result.busy || !!result.error;
  const title = tab === 'resultat' ? 'Compte de résultat' : tab === 'bilan' ? 'Bilan' : 'Flux de trésorerie';
  const rows: StatementRow[] = !data ? [] : tab === 'resultat' ? incomeRows(data.income) : tab === 'bilan' ? balanceSheetRows(data.balance) : cashFlowRows(data.cashflow);
  const year = data?.income.annee, columns = tab === 'tft' ? [title, 'Montant USD'] : [title, `${year} USD`, `${Number(year) - 1} USD`];
  const note = `${accountingStatuses[status]}. ${tab === 'bilan' ? 'Soldes cumulés jusqu’à chaque exercice.' : tab === 'tft' ? 'Tableau issu des regroupements comptables existants. Le contrôle affiché vérifie le calcul de variation ; il ne remplace pas un rapprochement bancaire.' : 'Produits et charges de chaque exercice, présentés séparément.'} Les sous-totaux et leurs détails ne doivent pas être additionnés une seconde fois.`;
  return <><div className="audit-head"><div><ScreenTitle>États financiers</ScreenTitle><p className="muted">{year ? `Exercice ${year} · ` : ''}Montants USD · {accountingStatuses[status]}</p></div><div className="audit-actions"><button className="btn" disabled={result.busy} onClick={result.refresh}><i className="ti ti-refresh" aria-hidden="true" /> Actualiser</button><button className="btn" onClick={() => bridge.navigate('balance')}>Balance générale</button><button className="btn btn-primary" disabled={disabled || !data} onClick={() => setPreview({ title, subtitle: `Exercice ${year} · ${accountingStatuses[status]} · USD`, columns, rows: rows.map(r => [r.label, ...r.values]), note })}>PDF / Excel / imprimer</button></div></div>
    <div className="business-toolbar"><div className="business-toolbar" role="group" aria-label="États disponibles">{[['resultat', 'Compte de résultat'], ['bilan', 'Bilan'], ['tft', 'Flux de trésorerie']].map(([key, label]) => <button className={`btn ${key === tab ? 'btn-primary' : ''}`} key={key} aria-pressed={key === tab} onClick={() => setTab(key)}>{label}</button>)}</div><label className="business-field">Statut des écritures<select className="form-select" value={status} onChange={e => setStatus(e.target.value)}>{Object.entries(accountingStatuses).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label></div>
    <ErrorNotice error={result.error} />{result.busy && <p role="status">Calcul des états financiers…</p>}{status === '' && <p className="banner">Les pièces en attente de validation sont incluses. Choisissez « Écritures validées » pour les exclure.</p>}
    {data && !disabled && <><h3>{title} — {year}</h3>{tab === 'resultat' && <p>Chiffre d’affaires : <b>{number(data.income.chiffre_affaires)} USD</b> · Résultat net : <b>{number(data.income.resultat_net)} USD</b>.</p>}{tab === 'bilan' && <p className={data.balance.equilibre ? 'business-success' : 'business-error'}>{data.balance.equilibre ? 'Bilan équilibré' : `Écart actif / passif : ${number(data.balance.ecart)} USD — à contrôler`}</p>}{tab === 'tft' && <p className={data.cashflow.controle ? 'banner' : 'business-error'}>Contrôle du calcul de variation : {data.cashflow.controle ? 'cohérent' : 'écart à contrôler'}.</p>}<div className="card business-table"><table><thead><tr>{columns.map(c => <th key={c}>{c}</th>)}</tr></thead><tbody>{rows.map((r, i) => <tr key={i} className={r.kind === 'total' ? 'et-net' : r.kind === 'section' ? 'et-sec' : 'et-l'}><td>{r.label}</td>{r.values.map((v, index) => <td className="right" key={index}>{number(v)}</td>)}</tr>)}</tbody></table></div><p className="muted">{note}</p></>}
    {preview && <ReportPreview bridge={bridge} state={state} report={preview} onClose={() => setPreview(null)} />}
  </>;
}
export function FinancialCockpit({ bridge, state }: ScreenProps) {
  const load = useCallback(async () => ({ data: await bridge.api<FinancialOverview>(`/comptabilite/cockpit?societe_id=${state.companyId}`), readAt: new Date().toLocaleTimeString('fr-FR', { timeZone: 'Africa/Lubumbashi' }) }), [bridge, state.companyId]);
  const result = useResource(load, 60000), disabled = result.busy || !!result.error, data = result.data?.data;
  const [preview, setPreview] = useState(false);
  const indicators: [string, number, string][] = !data ? [] : [['Trésorerie totale', data.tresorerie.total, 'Comptes caisse et banque'], ['Caisse', data.tresorerie.caisse, 'Comptes 57'], ['Banque', data.tresorerie.banque, 'Comptes 52'], ['Chiffre d’affaires', data.chiffre_affaires, 'Comptes 70'], ['Charges', data.charges, 'Classe 6'], ['Résultat', data.resultat, data.resultat >= 0 ? 'Bénéfice' : 'Perte'], ['Créances clients', data.creances_clients, 'Soldes débiteurs des comptes 41'], ['Dettes fournisseurs', data.dettes_fournisseurs, 'Soldes créditeurs des comptes 40'], ['TVA nette', data.tva_a_payer, data.tva_a_payer >= 0 ? 'Collectée moins déductible' : 'Crédit de TVA selon les soldes comptables'], ['Avances en cours', data.avances_en_cours, 'Soldes débiteurs 421 / 409']];
  return <><div className="audit-head"><div><ScreenTitle>Synthèse financière</ScreenTitle><p className="muted">Tout l’historique · Toutes les écritures · USD{result.data ? ` · Lu à ${result.data.readAt}` : ''}</p></div><div className="audit-actions"><button className="btn" disabled={result.busy} onClick={result.refresh}><i className="ti ti-refresh" aria-hidden="true" /> Actualiser</button><button className="btn" onClick={() => bridge.navigate('etats')}>États financiers</button><button className="btn btn-primary" disabled={disabled || !data} onClick={() => setPreview(true)}>Rapport PDF / Excel</button></div></div><ErrorNotice error={result.error} />{result.busy && <p role="status">Actualisation des indicateurs…</p>}<p className="banner">Cette synthèse cumule l’historique, y compris les écritures en attente. Elle ne représente pas un exercice isolé ni une déclaration fiscale. Actualisation chaque minute lorsque la page est visible.</p>
    {data && <><div className="caisse-cards">{indicators.map(([label, value, detail]) => <article key={label} className="caisse-card"><p className="muted">{label}</p><strong>{disabled ? '—' : `${number(value)} USD`}</strong><p className="muted">{detail}</p></article>)}</div><div className="business-toolbar"><p>{disabled ? '—' : data.pieces_en_attente} pièces comptables en attente de validation.</p><button className="btn btn-primary" onClick={() => bridge.navigate('compta')}>Traiter les pièces</button><button className="btn" onClick={() => bridge.navigate('grand-livre')}>Consulter le grand livre</button></div></>}
    {preview && data && <ReportPreview bridge={bridge} state={state} onClose={() => setPreview(false)} report={{ title: 'Synthèse financière', subtitle: `Tout l’historique · Toutes les écritures · USD · Lecture ${result.data?.readAt}`, columns: ['Indicateur', 'Valeur', 'Périmètre'], rows: [...indicators, ['Pièces en attente', data.pieces_en_attente, 'Nombre de pièces']], note: 'Les écritures en attente sont incluses. Les indicateurs ne sont pas limités à l’exercice courant. La TVA nette affichée ne constitue pas une déclaration.' }} />}
  </>;
}
