'use client';
import { ScreenTitle } from './screen-presentation';
import { useCallback, useState } from 'react';
import { DataTable } from './data-table';
import { ResourceEditor, type FormField } from './resource-editor';
import { ErrorNotice, useResource, type ScreenProps } from './shared';
export interface Vehicle { id: string; type: string; nom: string; statut: string }
export interface Intervention { id: string; numero: string; vehicule: string; type: string; description: string; prestataire: string | null; date_prevue: string | null; date_signalement: string; date_fin: string | null; cout_estime: number | null; cout_reel: number | null; statut: string; immobilise: boolean; requisition?: string | null }
export const interventionStatuses: Record<string, string> = { planifiee: 'Planifiée', en_cours: 'En cours', terminee: 'Terminée' };
export const interventionFields: FormField[] = [{ key: 'date_prevue', label: 'Date prévue (vide = maintenant)', type: 'date' }, { key: 'prestataire', label: 'Prestataire' }, { key: 'cout_estime', label: 'Coût estimé USD', type: 'number', min: 0 }, { key: 'immobilise', label: 'Immobiliser pendant l’intervention', options: [['oui', 'Oui'], ['non', 'Non']] }];
export function InterventionEditor({ vehicles, ...props }: ScreenProps & { vehicles: Vehicle[]; onClose: () => void; onSaved: () => void }) {
  return <ResourceEditor bridge={props.bridge} title="Signaler / planifier une intervention" initial={{ vehicle: vehicles[0] ? `${vehicles[0].type}:${vehicles[0].id}` : '', type: 'reparation', description: '', prestataire: '', cout_estime: '', date_prevue: '', immobilise: 'oui' }} fields={[{ key: 'vehicle', label: 'Véhicule', required: true, options: vehicles.map(v => [`${v.type}:${v.id}`, `${v.nom} · ${v.type} · ${v.statut}`]) }, { key: 'type', label: 'Type d’intervention', options: [['reparation', 'Réparation'], ['entretien', 'Entretien préventif'], ['controle', 'Contrôle technique'], ['accident', 'Accident']] }, { key: 'description', label: 'Description', required: true }, ...interventionFields]} onClose={props.onClose} note="Une date future planifie l’intervention. Le véhicule reste disponible jusqu’au démarrage. Le financement suit le circuit habituel de réquisition et d’avance." save={async v => { const vehicle = vehicles.find(x => `${x.type}:${x.id}` === v.vehicle); if (!vehicle || v.description.trim().length < 3) throw new Error('Sélectionnez le véhicule et décrivez l’intervention.'); await props.bridge.api(`/transport/interventions?societe_id=${props.state.companyId}`, { method: 'POST', body: { [`${vehicle.type}_id`]: vehicle.id, type: v.type, description: v.description.trim(), prestataire: v.prestataire.trim() || null, cout_estime: v.cout_estime === '' ? null : Number(v.cout_estime), date_prevue: v.date_prevue || null, immobilise: v.immobilise === 'oui' } }); props.onSaved(); }} />;
}
export function InterventionTable({ entries, refresh, ...props }: ScreenProps & { entries: Intervention[]; refresh: () => void }) {
  const [action, setAction] = useState<{ entry: Intervention; kind: 'demarrer' | 'terminer' } | null>(null), [status, setStatus] = useState('');
  const rows = entries.filter(i => !status || i.statut === status);
  return <><label className="business-field">Statut des interventions<select className="form-select" value={status} onChange={e => setStatus(e.target.value)}><option value="">Toutes</option>{Object.entries(interventionStatuses).map(([v, label]) => <option key={v} value={v}>{label}</option>)}</select></label><DataTable {...props} title="Interventions de maintenance" subtitle={interventionStatuses[status] || 'Tous les statuts'} columns={['Numéro', 'Véhicule', 'Type', 'Description', 'Prestataire', 'Prévue le', 'Signalée le', 'Terminée le', 'Coût estimé USD', 'Coût réel USD', 'Statut', 'Immobilisation', 'Réquisition']} rows={rows.map(i => [i.numero, i.vehicule || '', i.type, i.description, i.prestataire || '', i.date_prevue || '', i.date_signalement, i.date_fin || '', i.cout_estime ?? '', i.cout_reel ?? '', interventionStatuses[i.statut] || i.statut, i.immobilise ? 'Oui' : 'Non', i.requisition || ''])} actions={(_, n) => <div className="audit-actions">{rows[n].statut === 'planifiee' && <button className="btn btn-sm" onClick={() => setAction({ entry: rows[n], kind: 'demarrer' })}>Démarrer</button>}{rows[n].statut !== 'terminee' && <button className="btn btn-sm" onClick={() => setAction({ entry: rows[n], kind: 'terminer' })}>Terminer</button>}</div>} />{action && <ResourceEditor bridge={props.bridge} title={`${action.kind === 'demarrer' ? 'Démarrer' : 'Terminer'} — ${action.entry.numero}`} initial={{ cout_reel: '' }} fields={action.kind === 'terminer' ? [{ key: 'cout_reel', label: 'Coût réel USD (vide = justification liée)', type: 'number', min: 0 }] : []} onClose={() => setAction(null)} note={action.kind === 'demarrer' ? 'L’immobilisation sera appliquée si elle a été demandée.' : 'Le véhicule redevient disponible si aucune autre intervention ne l’immobilise. Les plans liés sont réinitialisés selon l’usage actuel.'} save={async v => { await props.bridge.api(`/transport/interventions/${action.entry.id}/${action.kind}?societe_id=${props.state.companyId}`, { method: 'POST', body: action.kind === 'terminer' ? { cout_reel: v.cout_reel === '' ? null : Number(v.cout_reel) } : {} }); setAction(null); refresh(); }} />}</>;
}
export function FleetInterventions(props: ScreenProps) {
  const { bridge, state } = props, load = useCallback(async () => { const q = `societe_id=${state.companyId}`; const [entries, parc] = await Promise.all([bridge.api<Intervention[]>(`/transport/interventions?${q}`), bridge.api<{ vehicules: Vehicle[] }>(`/maintenance/parc?${q}`)]); return { entries, vehicles: parc.vehicules }; }, [bridge, state.companyId]), result = useResource(load), [creating, setCreating] = useState(false);
  return <><div className="audit-head"><ScreenTitle>Interventions de maintenance</ScreenTitle><div className="audit-actions"><button className="btn" disabled={result.busy} onClick={result.refresh}><i className="ti ti-refresh" aria-hidden="true" /> Actualiser</button><button className="btn btn-primary" disabled={result.busy || !!result.error || !result.data?.vehicles.length} onClick={() => setCreating(true)}>Signaler / planifier</button></div></div><ErrorNotice error={result.error} />{result.busy && <p role="status">Lecture des interventions…</p>}{result.data && !result.busy && !result.error && <InterventionTable {...props} entries={result.data.entries} refresh={result.refresh} />}{creating && <InterventionEditor {...props} vehicles={result.data!.vehicles} onClose={() => setCreating(false)} onSaved={() => { setCreating(false); result.refresh(); }} />}</>;
}
