'use client';
import { useCallback, useRef, useState } from 'react';
import { paymentPieces, stayStatuses, type Extra, type Folio, type HotelRoom } from '../../lib/hotel-data';
import { Dialog, ErrorNotice, ReportPreview, message, number, useResource, type ScreenProps, type Report } from './shared';
import { Field } from './field';
import { StayEditor } from './hotel-stay';
import { HotelPayment } from './hotel-payment';

function folioReport(f: Folio): Report {
  const s = f.sejour, invoice = f.facture_sejour;
  return { title: `Note de séjour ${s.numero}${invoice ? ` · facture ${invoice.numero}` : ' · pro forma'}`, subtitle: `${s.client_nom}${s.client_telephone ? ` · ${s.client_telephone}` : ''} · Chambre ${s.chambre} · ${s.date_arrivee} → ${s.date_depart || s.date_depart_prevue} · ${s.nb_personnes} personne(s) · ${stayStatuses[s.statut]}`, columns: ['Date', 'Désignation', 'Quantité', 'Prix unitaire USD', 'Montant USD'], rows: [[s.date_arrivee, `Hébergement (${f.nuits} nuitées, hors TVA)`, f.nuits, s.tarif_nuit_usd, f.montant_nuitees], ...f.extras.map(e => [e.date, `${e.designation} · ${e.origine} (hors TVA)`, e.qte, e.prix_unitaire, e.montant_usd]), ...f.tickets_pos.map(t => [t.date, `${t.designation} (déjà facturé au point de vente, TTC)`, 1, t.montant_usd, t.montant_usd])], note: `${invoice ? `Facture hébergement : HT ${number(invoice.total_ht)} USD · TVA ${number(invoice.total_tva)} USD · TTC ${number(invoice.total_ttc)} USD. Total séjour, tickets compris : ${number(invoice.total_ttc + f.total_tickets_pos)} USD. Solde à encaisser : ${number(paymentPieces(f).reduce((sum, p) => sum + p.amount, 0))} USD.` : `Hébergement et extras à facturer : ${number(f.total_a_facturer)} USD hors TVA. Tickets déjà facturés : ${number(f.total_tickets_pos)} USD TTC. Document provisoire ; les taxes et la facture définitive sont établies au départ.`} Les tickets du point de vente ne sont pas refacturés sur l’hébergement. Client : __________________ · Réception : __________________` };
}
export function StayDetail({ bridge, state, stayId, rooms, onClose, onChanged }: ScreenProps & { stayId: string; rooms: HotelRoom[]; onClose: () => void; onChanged: () => void }) {
  const load = useCallback(() => bridge.api<Folio>(`/hotel/sejours/${stayId}/folio?societe_id=${state.companyId}`), [bridge, state.companyId, stayId]);
  const result = useResource(load), f = result.data, s = f?.sejour;
  const [busy, setBusy] = useState(false), [error, setError] = useState(''), [success, setSuccess] = useState(''), [editing, setEditing] = useState(false), [preview, setPreview] = useState(false), [paying, setPaying] = useState(false), [service, setService] = useState<{ designation: string; origine: string; price: number } | null>(null), [decision, setDecision] = useState<{ type: 'checkout' | 'cancel' | 'delete'; line?: Extra } | null>(null), [uncertain, setUncertain] = useState(false);
  const pending = useRef(false), blocked = busy || result.busy || !!result.error || uncertain;
  const refresh = () => { result.refresh(); onChanged(); };
  const act = async (path: string, body: unknown, label: string, method = 'POST') => { if (pending.current || blocked) return; pending.current = true; setBusy(true); setError(''); setSuccess(''); try { await bridge.api(`/hotel/sejours/${stayId}${path}?societe_id=${state.companyId}`, { method, body }); setDecision(null); setSuccess(label); refresh(); } catch (cause) { setError(message(cause)); setUncertain(true); } finally { pending.current = false; setBusy(false); } };
  const canPay = (state.companies.find(c => c.id === state.companyId)?.roles || []).some(r => ['DFI', 'COMPTABLE', 'CAISSIER_CENTRAL'].includes(r));
  return <><Dialog bridge={bridge} title={s ? `Fiche de séjour ${s.numero}` : 'Fiche de séjour'} busy={busy} onClose={onClose} footer={close => <><button className="btn" disabled={busy} onClick={close}>Fermer</button>{s && <><button className="btn" disabled={blocked} onClick={() => setPreview(true)}>Note PDF / Excel</button>{['reservee', 'arrivee'].includes(s.statut) && <button className="btn" disabled={blocked} onClick={() => setEditing(true)}>Modifier le séjour</button>}{s.statut === 'reservee' && <><button className="btn" disabled={blocked} onClick={() => setDecision({ type: 'cancel' })}>Annuler / non présenté</button><button className="btn btn-primary" disabled={blocked} onClick={() => act('/checkin', {}, 'Arrivée enregistrée ; la chambre est occupée.')}>Effectuer le check-in</button></>}{s.statut === 'arrivee' && <button className="btn btn-primary" disabled={blocked} onClick={() => setDecision({ type: 'checkout' })}>Check-out & facturer</button>}{s.statut === 'terminee' && f && paymentPieces(f).length > 0 && canPay && <button className="btn btn-primary" disabled={blocked} onClick={() => setPaying(true)}>Encaisser le solde</button>}</>}</>}>
    <ErrorNotice error={result.error || error} />{(result.error || uncertain) && <button className="btn" disabled={busy || result.busy} onClick={() => { setError(''); setUncertain(false); setDecision(null); result.refresh(); }}>Relire la situation du séjour</button>}{success && <p className="business-success" role="status">{success}</p>}{result.busy && <p role="status">Lecture de la fiche de séjour…</p>}
    {f && s && <><div className="business-form-grid"><p><b>{s.client_nom}</b><br />{s.client_telephone || 'Téléphone non renseigné'}</p><p>Chambre <b>{s.chambre}</b> · {stayStatuses[s.statut]}<br />{s.date_arrivee} → {s.date_depart || s.date_depart_prevue} · {s.nb_personnes} personne(s)</p></div>{s.note && <p>{s.note}</p>}
    {s.statut === 'reservee' && <p className="banner">Client pas encore arrivé. Le check-in ouvre la note à la date du jour ; si nécessaire, le départ est reporté au lendemain selon le circuit existant.</p>}
    {s.statut === 'arrivee' && <div className="business-toolbar">{([['Repassage', 'blanchisserie', 2], ['Blanchisserie', 'blanchisserie', 5], ['Petit-déjeuner', 'restaurant', 8], ['Transport / course', 'divers', 10]] as const).map(([designation, origine, price]) => <button className="btn btn-sm" key={designation} disabled={blocked} onClick={() => setService({ designation, origine, price })}>{designation}</button>)}<button className="btn" disabled={blocked} onClick={() => setService({ designation: '', origine: 'divers', price: 0 })}>Autre service</button></div>}
    <div className="business-table"><table><thead><tr><th>Date</th><th>Prestation</th><th>Quantité</th><th>Prix unitaire USD</th><th>Montant USD</th><th>Action</th></tr></thead><tbody><tr><td>{s.date_arrivee}</td><td>Hébergement hors TVA · {f.nuits} nuitée(s)</td><td>{f.nuits}</td><td>{number(s.tarif_nuit_usd)}</td><td>{number(f.montant_nuitees)}</td><td /></tr>{f.extras.map(e => <tr key={e.id}><td>{e.date}</td><td>{e.designation} · {e.origine} · hors TVA</td><td>{number(e.qte)}</td><td>{number(e.prix_unitaire)}</td><td>{number(e.montant_usd)}</td><td>{s.statut === 'arrivee' && <button className="btn btn-sm" disabled={blocked} onClick={() => setDecision({ type: 'delete', line: e })} aria-label={`Retirer ${e.designation}`}>Retirer</button>}</td></tr>)}{f.tickets_pos.map(t => <tr key={t.id}><td>{t.date}</td><td>{t.designation} · {t.origine} · déjà facturé TTC</td><td>1</td><td>{number(t.montant_usd)}</td><td>{number(t.montant_usd)}</td><td>{t.solde_du_usd > 0 ? 'À encaisser' : 'Réglé'}</td></tr>)}</tbody></table></div>
    {f.facture_sejour ? <div className="business-confirm"><b>Facture {f.facture_sejour.numero}</b><p>Hébergement et extras : HT {number(f.facture_sejour.total_ht)} USD · TVA {number(f.facture_sejour.total_tva)} USD · TTC {number(f.facture_sejour.total_ttc)} USD</p><p>Tickets du point de vente : {number(f.total_tickets_pos)} USD TTC · Total séjour : {number(f.facture_sejour.total_ttc + f.total_tickets_pos)} USD</p><strong>Solde à encaisser : {number(paymentPieces(f).reduce((sum, p) => sum + p.amount, 0))} USD</strong>{!canPay && paymentPieces(f).length > 0 && <p>L’encaissement est effectué par un compte habilité à régler les factures clients.</p>}</div> : <p>Hébergement et extras à facturer : <b>{number(f.total_a_facturer)} USD hors TVA</b> · Tickets déjà facturés : {number(f.total_tickets_pos)} USD TTC.</p>}
    {decision && <section className="business-confirm"><h3>{decision.type === 'checkout' ? 'Confirmer le départ' : decision.type === 'cancel' ? 'Annulation de la réservation' : 'Retirer une prestation'}</h3><p>{decision.type === 'checkout' ? 'Le séjour sera clôturé à la date du jour. La facture des nuitées et extras sera générée avec les taxes applicables ; la chambre passera « à nettoyer ». Les tickets déjà facturés ne seront pas refacturés. L’encaissement reste une opération séparée.' : decision.type === 'cancel' ? `Réservation de ${s.client_nom}, chambre ${s.chambre}. Choisissez annulation ou client non présenté.` : `Retirer « ${decision.line?.designation} » de la note ?`}</p><div className="business-toolbar"><button className="btn" disabled={busy} onClick={() => setDecision(null)}>Revenir</button>{decision.type === 'checkout' ? <button className="btn btn-primary" disabled={blocked} onClick={() => act('/checkout', {}, 'Départ enregistré ; facture générée et chambre à nettoyer.')}>Confirmer le départ et facturer</button> : decision.type === 'cancel' ? <><button className="btn" disabled={blocked} onClick={() => act('/annuler', { no_show: true }, 'Client déclaré non présenté.')}>Client non présenté</button><button className="btn btn-primary" disabled={blocked} onClick={() => act('/annuler', { no_show: false }, 'Réservation annulée.')}>Confirmer l’annulation</button></> : <button className="btn btn-primary" disabled={blocked} onClick={() => act(`/lignes/${decision.line!.id}`, undefined, 'Prestation retirée.', 'DELETE')}>Confirmer le retrait</button>}</div></section>}
    </>}
  </Dialog>{editing && s && <StayEditor bridge={bridge} state={state} stay={s} rooms={rooms} onClose={() => setEditing(false)} onSaved={() => { setEditing(false); refresh(); }} />}{service && <ServiceEditor bridge={bridge} state={state} stayId={stayId} initial={service} onClose={() => { setService(null); result.refresh(); }} onSaved={() => { setService(null); refresh(); }} />}{preview && f && <ReportPreview bridge={bridge} state={state} report={folioReport(f)} onClose={() => setPreview(false)} />}{paying && <HotelPayment bridge={bridge} state={state} stayId={stayId} onClose={() => { setPaying(false); refresh(); }} onSaved={() => { setPaying(false); setSuccess('Encaissement enregistré.'); refresh(); }} />}</>;
}
function ServiceEditor({ bridge, state, stayId, initial, onClose, onSaved }: ScreenProps & { stayId: string; initial: { designation: string; origine: string; price: number }; onClose: () => void; onSaved: () => void }) {
  const [name, setName] = useState(initial.designation), [origin, setOrigin] = useState(initial.origine), [qty, setQty] = useState('1'), [price, setPrice] = useState(String(initial.price)), [busy, setBusy] = useState(false), [error, setError] = useState(''), [uncertain, setUncertain] = useState(false);
  const pending = useRef(false);
  return <Dialog bridge={bridge} title="Ajouter une prestation au séjour" busy={busy} onClose={onClose} footer={close => <><button className="btn" disabled={busy} onClick={close}>Fermer</button><button className="btn btn-primary" type="submit" form="hotel-service-form" disabled={busy || uncertain}>Ajouter à la note</button></>}><form id="hotel-service-form" onSubmit={async e => { e.preventDefault(); if (pending.current || uncertain) return; setError(''); if (name.trim().length < 2 || !Number.isFinite(Number(qty)) || Number(qty) <= 0 || !price.trim() || !Number.isFinite(Number(price)) || Number(price) < 0) { setError('Renseignez la prestation, une quantité positive et un prix positif ou nul.'); return; } pending.current = true; setBusy(true); try { await bridge.api(`/hotel/sejours/${stayId}/lignes?societe_id=${state.companyId}`, { method: 'POST', body: { designation: name.trim(), origine: origin, qte: Number(qty), prix_unitaire: Number(price) } }); onSaved(); } catch (cause) { setError(`${message(cause)} Fermez la fenêtre et vérifiez la note avant une nouvelle tentative.`); setUncertain(true); } finally { pending.current = false; setBusy(false); } }}><fieldset className="business-fieldset" disabled={busy || uncertain}><Field label="Désignation de la prestation" required minLength={2} maxLength={255} value={name} onChange={setName} /><div className="business-form-grid"><Field label="Quantité" type="number" required min="0.01" step="0.01" value={qty} onChange={setQty} /><Field label="Prix unitaire USD hors TVA" type="number" required min={0} step="0.01" value={price} onChange={setPrice} /></div><label className="business-field">Origine<select className="form-select" value={origin} onChange={e => setOrigin(e.target.value)}><option value="divers">Divers</option><option value="blanchisserie">Blanchisserie</option><option value="restaurant">Restaurant</option><option value="bar">Bar</option></select></label></fieldset><ErrorNotice error={error} /></form></Dialog>;
}
