'use client';
import { useCallback, useRef, useState } from 'react';
import { clientLabel, roomStatuses, shiftDay, staySources, validateStay, type HotelClient, type HotelRoom, type Stay } from '../../lib/hotel-data';
import { Dialog, ErrorNotice, message, number, today, useResource, type ScreenProps } from './shared';
import { Field } from './field';
import { HotelClientPicker } from './hotel-client';

export function StayEditor({ bridge, state, stay, rooms, walkIn = false, onClose, onSaved }: ScreenProps & { stay?: Stay; rooms: HotelRoom[]; walkIn?: boolean; onClose: () => void; onSaved: (s: Stay) => void }) {
  const load = useCallback(() => bridge.api<HotelClient[]>(`/hotel/clients?societe_id=${state.companyId}`), [bridge, state.companyId]);
  const clients = useResource(load);
  const [busy, setBusy] = useState(false);
  return <Dialog bridge={bridge} title={stay ? `Modifier ${stay.numero}` : walkIn ? 'Walk-in — arrivée directe' : 'Nouvelle réservation'} onClose={onClose} busy={busy} footer={close => <><button className="btn" disabled={busy} onClick={close}><i className="ti ti-x" aria-hidden="true" /> Annuler</button><button className="btn btn-primary" type="submit" form="hotel-stay-form" disabled={busy || clients.busy || !!clients.error || !rooms.length}>{busy ? 'Enregistrement…' : stay ? 'Enregistrer' : walkIn ? 'Check-in immédiat' : 'Réserver'}</button></>}>
    <ErrorNotice error={clients.error} />{clients.error && <button className="btn" onClick={clients.refresh}>Réessayer</button>}{clients.busy && <p role="status">Chargement des clients…</p>}{clients.data && !clients.busy && !clients.error && <StayForm bridge={bridge} state={state} stay={stay} rooms={rooms} walkIn={walkIn} clients={clients.data} busy={busy} setBusy={setBusy} onSaved={onSaved} />}
  </Dialog>;
}
function StayForm({ bridge, state, stay, rooms, walkIn, clients, busy, setBusy, onSaved }: ScreenProps & { stay?: Stay; rooms: HotelRoom[]; walkIn: boolean; clients: HotelClient[]; busy: boolean; setBusy: (b: boolean) => void; onSaved: (s: Stay) => void }) {
  const selectable = rooms.filter(r => r.actif || r.id === stay?.chambre_id);
  const initialRoom = selectable.find(r => r.id === stay?.chambre_id) || selectable[0];
  const [roomId, setRoomId] = useState(initialRoom?.id || ''), [clientId, setClientId] = useState(stay?.tiers_id || ''), [name, setName] = useState(stay?.client_nom || ''), [phone, setPhone] = useState(stay?.client_telephone || ''), [source, setSource] = useState(stay?.source || 'directe'), [people, setPeople] = useState(String(stay?.nb_personnes || 1)), [arrival, setArrival] = useState(stay?.date_arrivee || today()), [departure, setDeparture] = useState(stay?.date_depart_prevue || shiftDay(today(), 1)), [rate, setRate] = useState(String(stay?.tarif_nuit_usd ?? initialRoom?.tarif_nuit_usd ?? 0)), [note, setNote] = useState(stay?.note || ''), [picking, setPicking] = useState(false), [added, setAdded] = useState<HotelClient[]>([]), [error, setError] = useState('');
  const pending = useRef(false), allClients = [...clients.filter(c => !added.some(a => a.id === c.id)), ...added];
  const selected = allClients.find(c => c.id === clientId);
  const pick = (c: HotelClient) => { setAdded(old => [...old.filter(a => a.id !== c.id), c]); setClientId(c.id); setName(c.nom); setPicking(false); };
  return <><form id="hotel-stay-form" onSubmit={async e => { e.preventDefault(); if (pending.current) return; setError(''); try { validateStay(arrival, departure, people, rate); if (!roomId || (selected?.nom || name).trim().length < 2) throw new Error('Choisissez une chambre et renseignez le nom du client.'); pending.current = true; setBusy(true); const common = { client_nom: selected?.nom || name.trim(), client_telephone: phone.trim() || null, nb_personnes: Number(people), date_depart_prevue: departure, tarif_nuit_usd: Number(rate), note: note.trim() || null, ...(clientId ? { tiers_id: clientId } : {}), ...(stay?.statut === 'arrivee' ? {} : { date_arrivee: arrival }) }; const saved = await bridge.api<Stay>(stay ? `/hotel/sejours/${stay.id}?societe_id=${state.companyId}` : `/hotel/sejours?societe_id=${state.companyId}`, { method: stay ? 'PATCH' : 'POST', body: stay ? common : { ...common, chambre_id: roomId, source, arrivee_immediate: walkIn } }); onSaved(saved); } catch (cause) { setError(message(cause)); } finally { pending.current = false; setBusy(false); } }}>
    <fieldset className="business-fieldset" disabled={busy}><div className="business-form-grid"><label className="business-field">Chambre<select className="form-select" required disabled={!!stay} value={roomId} onChange={e => { setRoomId(e.target.value); setRate(String(selectable.find(r => r.id === e.target.value)?.tarif_nuit_usd ?? 0)); }}>{selectable.map(r => <option value={r.id} key={r.id}>{r.numero} · {r.categorie || 'Chambre'} · {number(r.tarif_nuit_usd)} USD/nuit · {roomStatuses[r.etat] || r.etat}</option>)}</select></label><label className="business-field">Source<select className="form-select" disabled={!!stay} value={source} onChange={e => setSource(e.target.value)}>{Object.entries(staySources).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label></div>
    <label className="business-field">Fiche client<select className="form-select" disabled={!!stay?.tiers_id} value={clientId} onChange={e => { const c = allClients.find(c => c.id === e.target.value); setClientId(e.target.value); if (c) setName(c.nom); }}><option value="">Saisie du nom / client à identifier</option>{allClients.filter(c => c.actif || c.id === stay?.tiers_id).map(c => <option value={c.id} key={c.id}>{clientLabel(c)}</option>)}</select></label>{!stay?.tiers_id && <button type="button" className="btn" onClick={() => setPicking(true)}>Rechercher / créer un client</button>}
    {selected && <p className="catalogue-scope">{selected.societe_id === null ? 'Fiche client partagée entre sociétés. Ce séjour et sa facturation appartiennent à la société active.' : 'Fiche client propre à la société active.'}</p>}
    <div className="business-form-grid"><Field label="Nom du client" required minLength={2} readOnly={!!selected || !!stay?.tiers_id} value={name} onChange={setName} /><Field label="Téléphone du séjour" value={phone} onChange={setPhone} /><Field label="Personnes" type="number" required min={1} step={1} value={people} onChange={setPeople} /><Field label="Arrivée" type="date" required readOnly={walkIn || stay?.statut === 'arrivee'} value={arrival} onChange={setArrival} /><Field label="Départ prévu" type="date" required min={arrival ? shiftDay(arrival, 1) : undefined} value={departure} onChange={setDeparture} /><Field label="Tarif par nuit (USD, hors TVA)" type="number" required min={0} step="0.01" value={rate} onChange={setRate} /></div><Field label="Note du séjour" value={note} onChange={setNote} maxLength={255} />
    <p className="banner">{walkIn ? 'L’arrivée directe ouvre immédiatement le séjour et passe la chambre en occupation.' : 'La disponibilité de la chambre aux dates choisies est vérifiée à l’enregistrement.'} {!clientId && 'Sans fiche sélectionnée, le système retrouve ou crée le client au check-in, avec contrôle des homonymes.'}</p><ErrorNotice error={error} /></fieldset>
  </form>{picking && <HotelClientPicker bridge={bridge} state={state} clients={allClients} onClose={() => setPicking(false)} onSelected={pick} />}</>;
}
