'use client';
import { ScreenTitle } from './screen-presentation';
import { useCallback, useState } from 'react';
import { roomStatuses, shiftDay, staySources, stayStatuses, type HotelPlanning, type HotelReport, type HotelRoom, type Stay } from '../../lib/hotel-data';
import { DataTable } from './data-table';
import { Field } from './field';
import { ErrorNotice, number, today, useResource, type ScreenProps } from './shared';
import { StayEditor } from './hotel-stay';
import { StayDetail } from './hotel-folio';

export function Hotel({ bridge, state }: ScreenProps) {
  const [start, setStart] = useState(today), [days, setDays] = useState(14), [filter, setFilter] = useState('arrivee'), [creating, setCreating] = useState<'reservation' | 'walkin' | null>(null), [detail, setDetail] = useState<string | null>(null), [success, setSuccess] = useState('');
  const load = useCallback(async () => { const [rooms, stays, report] = await Promise.all([bridge.api<HotelRoom[]>(`/hotel/chambres?societe_id=${state.companyId}`), bridge.api<Stay[]>(`/hotel/sejours?societe_id=${state.companyId}`), bridge.api<HotelReport>(`/hotel/rapport?societe_id=${state.companyId}`)]); return { rooms, stays, report }; }, [bridge, state.companyId]);
  const result = useResource(load);
  const loadPlanning = useCallback(() => bridge.api<HotelPlanning>(`/hotel/planning?societe_id=${state.companyId}&du=${start}&jours=${days}`), [bridge, state.companyId, start, days]);
  const planning = useResource(loadPlanning), disabled = result.busy || !!result.error, day = today();
  const refresh = () => { result.refresh(); planning.refresh(); };
  const active = result.data?.rooms.filter(r => r.actif) || [], stays = result.data?.stays || [], arrivals = stays.filter(s => s.statut === 'reservee' && s.date_arrivee <= day), departures = stays.filter(s => s.statut === 'arrivee' && s.date_depart_prevue <= day);
  const rows = stays.filter(s => filter === 'attendues' ? s.statut === 'reservee' && s.date_arrivee <= day : filter === 'departs' ? s.statut === 'arrivee' && s.date_depart_prevue <= day : !filter || s.statut === filter);
  const dates = planning.data ? Array.from({ length: planning.data.jours }, (_, n) => shiftDay(planning.data!.du, n)) : [];
  const saved = (s: Stay) => { setCreating(null); setSuccess(`${s.numero} enregistré · ${stayStatuses[s.statut]}.`); refresh(); setDetail(s.id); };
  return <>
    <div className="audit-head"><div><ScreenTitle>Réception & séjours</ScreenTitle><p className="muted">Situation du {day} · {state.companies.find(c => c.id === state.companyId)?.nom}</p></div><div className="audit-actions"><button className="btn" disabled={result.busy || planning.busy} onClick={refresh}><i className="ti ti-refresh" aria-hidden="true" /> Actualiser</button><button className="btn" disabled={disabled || !active.length} onClick={() => setCreating('walkin')}><i className="ti ti-user-check" aria-hidden="true" /> Walk-in</button><button className="btn btn-primary" disabled={disabled || !active.length} onClick={() => setCreating('reservation')}><i className="ti ti-plus" aria-hidden="true" /> Nouvelle réservation</button></div></div>
    <ErrorNotice error={result.error} />{success && <p className="business-success" role="status">{success}</p>}{result.busy && <p role="status">Chargement de la réception…</p>}
    <div className="caisse-cards">{[['Chambres libres', `${active.filter(c => c.etat === 'libre').length} / ${active.length}`], ['Arrivées attendues', arrivals.length], ['Départs à effectuer', departures.length], ['Occupation du mois', `${number(result.data?.report.taux_occupation_pct)} %`], ['Revenu hébergement du mois', `${number(result.data?.report.revenu_hebergement_usd)} USD`]].map(([label, value]) => <article className="caisse-card" key={label}><p className="muted">{label}</p><strong>{disabled ? '—' : value}</strong></article>)}</div>
    {result.data && <p className="muted">Indicateurs du {result.data.report.du} au {result.data.report.au} · {result.data.report.nuitees_vendues} nuitées · Prix moyen : {number(result.data.report.adr_usd)} USD · Revenu par chambre disponible : {number(result.data.report.revpar_usd)} USD. Les listes portent sur les 300 derniers séjours.</p>}
    <div className="business-toolbar hotel-room-chips">{active.map(r => <button className="btn" key={r.id} disabled={disabled} onClick={() => r.sejour ? setDetail(r.sejour.id) : bridge.navigate('hotel-chambres')}>{r.numero} · {roomStatuses[r.etat] || r.etat}{r.sejour ? ` · ${r.sejour.client}` : ''}</button>)}</div>
    <section className="card"><div className="card-body"><h3>Planning des chambres</h3><div className="business-toolbar"><button className="btn" disabled={planning.busy} onClick={() => setStart(shiftDay(start, -days))} aria-label="Période précédente">←</button><Field label="Planning à partir du" type="date" value={start} onChange={v => { if (v) setStart(v); }} /><label>Période<select className="form-select" value={days} onChange={e => setDays(Number(e.target.value))}>{[7, 14, 31].map(n => <option key={n} value={n}>{n} jours</option>)}</select></label><button className="btn" disabled={planning.busy} onClick={() => setStart(shiftDay(start, days))} aria-label="Période suivante">→</button><button className="btn" onClick={() => setStart(day)}>Aujourd’hui</button></div><ErrorNotice error={planning.error} />{planning.busy && <p role="status">Actualisation du planning…</p>}
    {planning.data && <div className="business-table hotel-react-planning"><table><thead><tr><th>Chambre</th>{dates.map(d => <th key={d} className={d === day ? 'hotel-today' : undefined}>{new Date(d + 'T12:00:00Z').toLocaleDateString('fr-FR', { weekday: 'short', day: '2-digit', month: '2-digit', timeZone: 'Africa/Lubumbashi' })}</th>)}</tr></thead><tbody>{planning.data.chambres.map(r => <tr key={r.id}><th>{r.numero}<br /><small>{roomStatuses[r.etat]}</small></th>{dates.map(d => { const o = r.occupations.find(o => o.du <= d && d < o.au); return <td key={d} className={d === day ? 'hotel-today' : undefined}>{o && <button className={`hotel-occupation ${o.statut === 'arrivee' ? 'hotel-inhouse' : ''}`} disabled={planning.busy || !!planning.error} title={`${o.client} · ${o.du} → ${o.au}`} aria-label={`${o.client} · ${d} · ${stayStatuses[o.statut]}`} onClick={() => setDetail(o.sejour_id)}>{d === dates[0] || d === o.du ? o.client : '•'}</button>}</td>; })}</tr>)}</tbody></table></div>}
    <p className="muted">Réservé : bleu-vert · En séjour : vert. Cliquez une occupation pour ouvrir sa fiche. Le jour du départ prévu est disponible pour une nouvelle arrivée.</p>{departures.some(s => s.date_depart_prevue < day) && <p className="banner">Certains clients sont encore en séjour après leur départ prévu. Consultez les départs à effectuer : le planning représente les dates enregistrées.</p>}</div></section>
    <div className="business-toolbar"><label>Afficher les séjours<select className="form-select" value={filter} onChange={e => setFilter(e.target.value)}><option value="">Tous les séjours</option><option value="attendues">Arrivées attendues / en retard</option><option value="departs">Départs à effectuer / en retard</option>{Object.entries(stayStatuses).map(([key, label]) => <option value={key} key={key}>{label}</option>)}</select></label></div>
    {result.data && <DataTable bridge={bridge} state={state} title="Registre des séjours" subtitle={`${filter ? ({ attendues: 'Arrivées attendues', departs: 'Départs à effectuer' } as Record<string, string>)[filter] || stayStatuses[filter] : 'Tous les statuts'} · Tarifs par nuit en USD hors TVA`} disabled={disabled} columns={['Numéro', 'Client', 'Téléphone', 'Chambre', 'Arrivée', 'Départ', 'Personnes', 'Tarif / nuit', 'État', 'Source', 'Facture']} rows={rows.map(s => [s.numero, s.client_nom, s.client_telephone || '', s.chambre, s.date_arrivee, s.date_depart || s.date_depart_prevue, s.nb_personnes, s.tarif_nuit_usd, stayStatuses[s.statut] || s.statut, staySources[s.source] || s.source, s.facture || ''])} actions={row => <button className="btn btn-sm" disabled={disabled} onClick={() => setDetail(rows.find(s => s.numero === row[0])!.id)}>Fiche séjour</button>} />}
    {creating && result.data && <StayEditor bridge={bridge} state={state} rooms={active} walkIn={creating === 'walkin'} onClose={() => setCreating(null)} onSaved={saved} />}
    {detail && result.data && <StayDetail key={detail} bridge={bridge} state={state} stayId={detail} rooms={result.data.rooms} onClose={() => setDetail(null)} onChanged={refresh} />}
  </>;
}
