'use client';
import { ScreenTitle } from './screen-presentation';
import { useCallback, useState } from 'react';
import { amount } from '../../lib/operation-data';
import { DataTable } from './data-table';
import { rhPath, type Employee, type EmployeeFile, type HrRequest } from './hr-personnel';
import { ChooseEmployee } from './hr-simulation';
import { OperationForm } from './operation-form';
import { Dialog, ErrorNotice, ReportPreview, message, number, today, useResource, type Report, type ScreenProps } from './shared';
export interface HrDebt { id: string; nom: string; matricule: string; nature: string; montant: number; devise: string; statut: string; source_numero: string; motif: string; salaire_reference: number; plafond_pct: number; echeancier: { mois: string; montant: number }[]; rembourse: number; solde: number; remboursements: { mois: string; montant: number }[]; decisions: { date: string; nom: string; etape: string; action: string; commentaire: string }[]; accord_nom: string; revision: string }
const labels: Record<string, string> = { avance_salaire: 'Avance sur salaire', pret_personnel: 'Prêt au personnel', recouvrement: 'Avance à justifier · recouvrement', attente_dfi: 'Validation DFI', attente_drh: 'Validation DRH', attente_direction: 'Validation DG / Administrateur', approuve: 'Approuvé', rejete: 'Rejeté', verse: 'Versé' };
export function HrFinances(props: ScreenProps) {
  const load = useCallback(async () => { const [policy, debts] = await Promise.all([props.bridge.api<{ plafond_avance_pct: number; revision: string }>(rhPath('politique', props.state.companyId)), props.bridge.api<HrDebt[]>(rhPath('dettes', props.state.companyId))]); return { policy, debts }; }, [props.bridge, props.state.companyId]), result = useResource(load), [policy, setPolicy] = useState(false), [create, setCreate] = useState(false), [employee, setEmployee] = useState<Employee | null>(null), [detail, setDetail] = useState<HrDebt | null>(null);
  const roles = props.state.companies.find(c => c.id === props.state.companyId)?.roles || [], d = !result.busy && !result.error ? result.data : null;
  const saved = () => { setCreate(false); setEmployee(null); setDetail(null); setPolicy(false); result.refresh(); };
  return <><div className="audit-head"><ScreenTitle>Avances & prêts au personnel</ScreenTitle><button className="btn" disabled={result.busy} onClick={result.refresh}><i className="ti ti-refresh" aria-hidden="true" /> Actualiser</button></div><ErrorNotice error={result.error} />{result.busy && <p>Lecture des accords…</p>}{d && <><p className="banner">Plafond des avances du mois : {number(d.policy.plafond_avance_pct)} % du net contractuel. Au-delà : prêt avec échéancier. Les avances à justifier sont admissibles après 30 jours avec accord écrit ; leur validation ne déclenche aucune retenue automatique.</p><div className="audit-actions">{roles.some(r => ['RH', 'DRH', 'DFI'].includes(r)) && <button className="btn btn-primary" onClick={() => setCreate(true)}>Préparer un accord</button>}{roles.some(r => ['DFI', 'DRH'].includes(r)) && <button className="btn" onClick={() => setPolicy(true)}>Plafond de la société</button>}</div><DataTable {...props} title="Accords avec les agents" subtitle="Avance : DFI · prêt et recouvrement : DFI, DRH, puis DG ou Administrateur" columns={['Agent', 'Matricule', 'Nature', 'Source', 'Montant', 'Devise', 'Remboursé', 'Solde', 'État']} rows={d.debts.map(a => [a.nom, a.matricule, labels[a.nature] || a.nature, a.source_numero || '', a.montant, a.devise, a.rembourse, a.solde, labels[a.statut] || a.statut])} actions={(_, i) => <button className="btn" onClick={() => setDetail(d.debts[i])}>Ouvrir l’accord</button>} /><p>Les remboursements des avances et prêts sont repris dans la paie suivant les accords. Les recouvrements d’avances à justifier attendent la confirmation du circuit de rapprochement.</p></>}{policy && d && <OperationForm bridge={props.bridge} title="Plafond des avances sur salaire" onClose={() => setPolicy(false)} initial={{ plafond_avance_pct: String(d.policy.plafond_avance_pct) }} fields={[{ key: 'plafond_avance_pct', label: 'Pourcentage du net contractuel', type: 'number', min: 0, max: 100, required: true }]} note="Ce plafond détermine le circuit d’octroi. Les limites légales de retenue sur salaire sont distinctes." save={async v => { const pct = amount(v.plafond_avance_pct, 'Plafond'); if (pct > 100) throw new Error('Le plafond ne peut dépasser 100 %.'); await props.bridge.api(rhPath('politique', props.state.companyId), { method: 'POST', body: { plafond_avance_pct: pct, revision: d.policy.revision } }); saved(); }} />}{create && !employee && <ChooseEmployee {...props} title="Choisir l’agent pour cet accord" onClose={() => setCreate(false)} onSelected={setEmployee} />}{create && employee && <AgreementEditor {...props} employee={employee} onClose={() => { setCreate(false); setEmployee(null); }} onSaved={saved} />}{detail && <DebtDetail {...props} debt={detail} onClose={() => setDetail(null)} onSaved={saved} />}</>;
}
function AgreementEditor({ employee, onClose, onSaved, ...props }: ScreenProps & { employee: Employee; onClose: () => void; onSaved: () => void }) {
  const load = useCallback(async () => { const [dossier, requests, advances] = await Promise.all([props.bridge.api<EmployeeFile>(rhPath(`agents/${employee.id}/dossier`, props.state.companyId)), props.bridge.api<HrRequest[]>(rhPath('demandes', props.state.companyId)), props.bridge.api<{ id: string; numero: string; montant: number; devise: string; eligible: boolean }[]>(rhPath(`avances-a-justifier?agent_id=${employee.id}`, props.state.companyId))]); return { dossier, sources: [...requests.filter(r => r.agent_id === employee.id && r.nature === 'avance_salaire' && r.statut === 'soumis').map(r => ({ id: `demande:${r.id}`, label: 'Demande d’avance', montant: r.montant, devise: r.devise })), ...advances.filter(a => a.eligible).map(a => ({ ...a, id: `avance:${a.id}`, label: a.numero }))] }; }, [props.bridge, props.state.companyId, employee.id]), result = useResource(load), d = result.data;
  if (!d || result.busy || result.error) return <Dialog bridge={props.bridge} title="Préparer l’accord" onClose={onClose}><ErrorNotice error={result.error} />{result.busy ? <p>Lecture de l’accord écrit et des sources admissibles…</p> : <button className="btn" onClick={result.refresh}>Réessayer</button>}</Dialog>;
  return <OperationForm bridge={props.bridge} title={`Accord & échéancier · ${employee.nom}`} onClose={onClose} initial={{ source: '', accord_id: '', motif: '' }} note={!d.dossier.documents.length ? 'Ajoutez d’abord l’accord écrit signé dans le dossier agent.' : !d.sources.length ? 'Aucune demande disponible ni avance à justifier admissible après 30 jours.' : 'Reportez l’échéancier convenu et signé. Le total doit couvrir le montant de l’accord, avec une seule échéance par mois.'} fields={[{ key: 'source', label: 'Demande / avance à recouvrer', required: true, options: [['', 'Choisir'], ...d.sources.map(s => [s.id, `${s.label} · ${number(s.montant)} ${s.devise}`] as [string, string])] }, { key: 'accord_id', label: 'Accord écrit signé', required: true, options: [['', 'Choisir'], ...d.dossier.documents.map(f => [f.id, f.nom] as [string, string])] }, { key: 'motif', label: 'Objet et modalités convenues', type: 'textarea' }]} sections={[{ key: 'echeancier', title: 'Mensualités', minimum: 1, initial: { mois: today().slice(0, 7), montant: '' }, fields: [{ key: 'mois', label: 'Mois de remboursement', type: 'month', required: true }, { key: 'montant', label: 'Montant de la mensualité', type: 'number', min: 0.01, required: true }] }]} summary={(v, rows) => { const s = d.sources.find(s => s.id === v.source); return <p>Total de l’échéancier : {number(rows.echeancier.reduce((n, r) => n + Number(r.montant), 0))} {s?.devise || ''} · accord : {s ? `${number(s.montant)} ${s.devise}` : 'choisir la source'}</p>; }} save={async (v, rows) => { const source = d.sources.find(s => s.id === v.source); if (!source) throw new Error('Choisissez une source admissible.'); const echeancier = rows.echeancier.map(r => ({ mois: r.mois, montant: amount(r.montant, 'Mensualité', 0.01) })); if (new Set(echeancier.map(r => r.mois)).size !== echeancier.length) throw new Error('Un mois ne peut apparaître deux fois.'); if (Math.round(echeancier.reduce((n, r) => n + r.montant, 0) * 100) !== Math.round(source.montant * 100)) throw new Error('Le total de l’échéancier doit égaler le montant de l’accord.'); const [type, id] = v.source.split(':'); await props.bridge.api(rhPath('dettes', props.state.companyId), { method: 'POST', body: { agent_id: employee.id, accord_id: v.accord_id, motif: v.motif, [type === 'demande' ? 'demande_id' : 'avance_source_id']: id, echeancier } }); onSaved(); }} />;
}
function DebtDetail({ debt: d, onClose, onSaved, ...props }: ScreenProps & { debt: HrDebt; onClose: () => void; onSaved: () => void }) {
  const [decision, setDecision] = useState(''), [report, setReport] = useState(false), [busy, setBusy] = useState(false), [error, setError] = useState(''), roles = props.state.companies.find(c => c.id === props.state.companyId)?.roles || [], eligible = ({ attente_dfi: ['DFI'], attente_drh: ['DRH'], attente_direction: ['DG', 'ADMIN'] } as Record<string, string[]>)[d.statut] || [];
  const document: Report = { title: `Dossier RH · ${d.nom}`, subtitle: `${labels[d.nature]} · ${number(d.montant)} ${d.devise} · ${labels[d.statut]}`, columns: ['Élément', 'Détail'], rows: [['Motif', d.motif], ['Accord signé', d.accord_nom], ['Net de référence', `${number(d.salaire_reference)} ${d.devise}`], ['Plafond à la préparation', `${d.plafond_pct} %`], ...d.echeancier.map(e => [`Échéance ${e.mois}`, `${number(e.montant)} ${d.devise}`]), ['Remboursé', `${number(d.rembourse)} ${d.devise}`], ['Solde', `${number(d.solde)} ${d.devise}`], ...d.remboursements.map(e => [`Retenue validée ${e.mois}`, `${number(e.montant)} ${d.devise}`]), ...d.decisions.map(e => [`${e.date} · ${labels[e.etape] || e.etape}`, `${e.nom} · ${e.action} · ${e.commentaire}`])], note: 'Échéancier convenu — ce document ne prouve pas un versement ni un remboursement.' };
  return <Dialog bridge={props.bridge} title={`${labels[d.nature]} · ${d.nom}`} busy={busy} onClose={onClose}><p>{number(d.montant)} {d.devise} · {labels[d.statut]}</p><p>{d.motif}</p><p>Net de référence : {number(d.salaire_reference)} {d.devise} · plafond : {d.plafond_pct} %</p><DataTable {...props} title="Échéancier convenu" subtitle={`${number(d.rembourse)} ${d.devise} remboursés · solde ${number(d.solde)} ${d.devise}`} columns={['Mois', `Montant ${d.devise}`]} rows={d.echeancier.map(e => [e.mois, e.montant])} /><h3>Décisions</h3>{d.decisions.map((e, i) => <p key={i}>{e.date} · {e.nom} · {labels[e.etape] || e.etape} · {e.action}<br />{e.commentaire}</p>)}<ErrorNotice error={error} /><div className="audit-actions"><button className="btn" disabled={busy} onClick={async () => { setBusy(true); setError(''); try { await props.bridge.download(rhPath(`dettes/${d.id}/accord`, props.state.companyId), d.accord_nom); } catch (e) { setError(message(e)); } finally { setBusy(false); } }}>Accord signé</button><button className="btn" onClick={() => setReport(true)}>Dossier & impression</button>{roles.some(r => eligible.includes(r)) && <><button className="btn" onClick={() => setDecision('rejeter')}>Rejeter</button><button className="btn btn-primary" onClick={() => setDecision('valider')}>Valider à mon niveau</button></>}</div>{report && <ReportPreview {...props} report={document} onClose={() => setReport(false)} />}{decision && <OperationForm bridge={props.bridge} title={`${decision === 'valider' ? 'Valider' : 'Rejeter'} l’accord`} onClose={() => setDecision('')} initial={{ commentaire: '' }} fields={[{ key: 'commentaire', label: 'Motif et vérifications effectuées', required: true, type: 'textarea' }]} note={`${d.nom} · ${number(d.montant)} ${d.devise} · ${labels[d.statut]}`} save={async v => { if (!v.commentaire.trim()) throw new Error('Le commentaire est obligatoire.'); await props.bridge.api(rhPath(`dettes/${d.id}/decision`, props.state.companyId), { method: 'POST', body: { commentaire: v.commentaire, action: decision, revision: d.revision } }); onSaved(); }} />}</Dialog>;
}
export function HrPayments(props: ScreenProps) {
  const load = useCallback(() => props.bridge.api<HrDebt[]>(rhPath('a-payer', props.state.companyId)), [props.bridge, props.state.companyId]), result = useResource(load), [pay, setPay] = useState<HrDebt | null>(null), [report, setReport] = useState<Report | null>(null), roles = props.state.companies.find(c => c.id === props.state.companyId)?.roles || [], canPay = roles.some(r => r.startsWith('CAISSIER_'));
  return <><div className="audit-head"><ScreenTitle>Paiements RH</ScreenTitle><button className="btn" disabled={result.busy} onClick={result.refresh}><i className="ti ti-refresh" aria-hidden="true" /> Actualiser</button></div><p className="banner">Seuls les accords approuvés peuvent être versés. La caisse doit être ouverte et approvisionnée dans la devise de l’accord. Le bénéficiaire reste l’agent titulaire.</p><ErrorNotice error={result.error} />{result.busy && <p>Lecture des accords à payer…</p>}{result.data && !result.busy && !result.error && <DataTable {...props} title="Accords RH à verser" subtitle="Société active" columns={['Agent', 'Nature', 'Montant', 'Devise', 'État']} rows={result.data.map(d => [d.nom, labels[d.nature], d.montant, d.devise, labels[d.statut]])} actions={(_, i) => canPay && result.data![i].statut === 'approuve' && <button className="btn" onClick={() => setPay(result.data![i])}>Verser</button>} />}{pay && <PayAgreement {...props} debt={pay} onClose={() => setPay(null)} onSaved={r => { setPay(null); setReport(r); result.refresh(); void props.bridge.refreshAccountingBadge(); }} />}{report && <ReportPreview {...props} report={report} onClose={() => setReport(null)} />}</>;
}
function PayAgreement({ debt, onClose, onSaved, ...props }: ScreenProps & { debt: HrDebt; onClose: () => void; onSaved: (r: Report) => void }) {
  const load = useCallback(() => props.bridge.api<{ id: string; libelle: string; session_ouverte: boolean }[]>(`/caisses?societe_id=${props.state.companyId}`), [props.bridge, props.state.companyId]), result = useResource(load);
  return result.data && !result.busy && !result.error ? <OperationForm bridge={props.bridge} title={`Verser · ${debt.nom}`} onClose={onClose} note={`${number(debt.montant)} ${debt.devise} seront décaissés au nom de cet agent avec leur pièce comptable.`} initial={{ caisse_id: '', reference: '' }} fields={[{ key: 'caisse_id', label: 'Caisse ouverte', required: true, options: [['', 'Choisir'], ...result.data.filter(c => c.session_ouverte).map(c => [c.id, c.libelle] as [string, string])] }, { key: 'reference', label: 'Référence du reçu signé', required: true }]} submitLabel="Confirmer le versement" save={async v => { if (!v.reference.trim() || v.reference.length > 64) throw new Error('Référence obligatoire, limitée à 64 caractères.'); const r = await props.bridge.api<{ numero: string; date: string; nom: string; montant: number; devise: string; ecriture: string }>(rhPath(`dettes/${debt.id}/verser`, props.state.companyId), { method: 'POST', body: { ...v, revision: debt.revision } }); onSaved({ title: `Versement RH · ${r.numero}`, subtitle: r.date, columns: ['Agent', 'Montant', 'Devise', 'Référence comptable'], rows: [[r.nom, r.montant, r.devise, r.ecriture]], note: `Référence reçu : ${v.reference}. Signature du bénéficiaire : ____________________` }); }} /> : <Dialog bridge={props.bridge} title="Caisses de paiement" onClose={onClose}><ErrorNotice error={result.error} />{result.busy ? <p>Lecture…</p> : <button className="btn" onClick={result.refresh}>Réessayer</button>}</Dialog>;
}
