'use client';
import { ModuleGuide } from './module-guide';
import { ScreenPresentation } from './screen-presentation';
import { OperationsDashboard } from './operations-dashboard';
import { ModuleConfiguration } from './module-configuration';
import { TransportContracts } from './transport-contracts';
import { FleetDocuments } from './fleet-documents';
import { EngineReport } from './engine-report';
import { Fleet } from './fleet';
import { EngineHours } from './engine-hours';
import { MaintenancePark } from './maintenance-park';
import { FleetInterventions } from './fleet-interventions';
import { Fuel } from './fuel';
import { PosSettings } from './pos-settings';
import { MoneyTransfers } from './money-transfers';
import { CashExecutions } from './cash-executions';
import { Intercompany } from './intercompany';
import { NewRequisition, Requisitions, RequisitionDetail } from './requisitions';
import { Approvals } from './approvals';
import { ExpenseOrders } from './expense-orders';
import { Advances } from './advances';
import { TransportCourses } from './transport-courses';
import { GeneralSettings } from './general-settings';
import { Administration } from './administration';
import { SystemAdmin } from './system-admin';
import { HrPersonnel } from './hr-personnel';
import { HrSimulation, HrFinalSettlements } from './hr-simulation';
import { HrFinances, HrPayments } from './hr-finances';
import { HrPayroll } from './hr-payroll';
import { Invoices } from './invoices';
import { PurchaseOrders, Receptions } from './purchasing';
import { SalesQuotes } from './sales-quotes';
import { PointOfSale } from './point-of-sale';
import { Cash } from './cash';
import { Audit } from './audit';
import { Rates } from './rates';
import { Stock } from './stock';
import { Tasks } from './tasks';
import { Articles } from './articles';
import { Rooms } from './rooms';
import { Depots } from './depots';
import { Inventories } from './inventories';
import { Hotel } from './hotel';
import { Kitchen } from './kitchen';
import { Balance, GrandLedger } from './accounting-reports';
import { AccountingEntry } from './accounting-entry';
import { CommercialReports } from './commercial-reports';
import { AccountingReview } from './accounting-review';
import { AccountingVat } from './accounting-vat';
import { AccountingAnalytic } from './accounting-analytic';
import { AccountingPlan } from './accounting-plan';
import { FinancialCockpit, FinancialStatements } from './financial-statements';
import { Matching, BankReconciliation } from './accounting-matching';
import type { ScreenProps } from './shared';

export const BUSINESS_VIEWS = ['pilotage', 'audit', 'stock', 'taux', 'articles', 'hotel-chambres', 'depots', 'inventaires', 'hotel-reception', 'cuisine', 'balance', 'grand-livre', 'saisie-od', 'plan-comptable', 'lettrage', 'rapprochement', 'cockpit', 'etats', 'analytique', 'tva', 'compta', 'rapports-commercial', 'dashboard', 'config-hotel', 'config-engins', 'config-transport', 'config-maintenance', 'contrats-transport', 'flotte-documents', 'engins-rpe', 'flotte', 'engins-parc', 'engins-heures', 'maintenance-parc', 'maintenance-interventions', 'carburant', 'tarifs-pos', 'transferts', 'caisse-exec', 'intersociete', 'nouvelle-req', 'requisitions', 'approbation', 'ordres', 'avances', 'caisse', 'courses', 'config', 'administration', 'systeme', 'rh', 'rh-simulateur', 'rh-decomptes', 'rh-finances', 'rh-paiements', 'rh-mensuel', 'achats', 'ventes', 'commandes', 'receptions', 'devis', 'pos'];
export function BusinessScreen(props: ScreenProps) {
  const target = (props.state as typeof props.state & { taskTarget?: { view: string; documentId: string } | null }).taskTarget;
  return <ScreenPresentation state={props.state}><ModuleGuide {...props} /><CurrentScreen {...props} />{target && target.view === props.state.view && <RequisitionDetail {...props} id={target.documentId} onClose={() => props.bridge.clearTask()} />}</ScreenPresentation>;
}
function CurrentScreen(props: ScreenProps) {
  switch (props.state.view) {
    case 'rh': return <HrPersonnel {...props} />;
    case 'rh-simulateur': return <HrSimulation {...props} />;
    case 'rh-decomptes': return <HrFinalSettlements {...props} />;
    case 'rh-finances': return <HrFinances {...props} />;
    case 'rh-paiements': return <HrPayments {...props} />;
    case 'rh-mensuel': return <HrPayroll {...props} />;
    case 'achats': case 'ventes': return <Invoices key={props.state.view} {...props} />;
    case 'commandes': return <PurchaseOrders {...props} />;
    case 'receptions': return <Receptions {...props} />;
    case 'devis': return <SalesQuotes {...props} />;
    case 'pos': return <PointOfSale {...props} />;
    case 'pilotage': return <Tasks {...props} />;
    case 'audit': return <Audit {...props} />;
    case 'stock': return <Stock {...props} />;
    case 'taux': return <Rates {...props} />;
    case 'articles': return <Articles {...props} />;
    case 'hotel-chambres': return <Rooms {...props} />;
    case 'depots': return <Depots {...props} />;
    case 'inventaires': return <Inventories {...props} />;
    case 'hotel-reception': return <Hotel {...props} />;
    case 'cuisine': return <Kitchen {...props} />;
    case 'balance': return <Balance {...props} />;
    case 'grand-livre': return <GrandLedger {...props} />;
    case 'saisie-od': return <AccountingEntry {...props} />;
    case 'plan-comptable': return <AccountingPlan {...props} />;
    case 'lettrage': return <Matching {...props} />;
    case 'rapprochement': return <BankReconciliation {...props} />;
    case 'cockpit': return <FinancialCockpit {...props} />;
    case 'etats': return <FinancialStatements {...props} />;
    case 'analytique': return <AccountingAnalytic {...props} />;
    case 'tva': return <AccountingVat {...props} />;
    case 'compta': return <AccountingReview {...props} />;
    case 'rapports-commercial': return <CommercialReports {...props} />;
    case 'dashboard': return <OperationsDashboard {...props} />;
    case 'config-hotel': case 'config-engins': case 'config-transport': case 'config-maintenance': return <ModuleConfiguration key={props.state.view} {...props} />;
    case 'contrats-transport': return <TransportContracts {...props} />;
    case 'flotte-documents': return <FleetDocuments {...props} />;
    case 'engins-rpe': return <EngineReport {...props} />;
    case 'flotte': case 'engins-parc': return <Fleet key={props.state.view} {...props} />;
    case 'engins-heures': return <EngineHours {...props} />;
    case 'maintenance-parc': return <MaintenancePark {...props} />;
    case 'maintenance-interventions': return <FleetInterventions {...props} />;
    case 'carburant': return <Fuel {...props} />;
    case 'tarifs-pos': return <PosSettings {...props} />;
    case 'transferts': return <MoneyTransfers {...props} />;
    case 'caisse-exec': return <CashExecutions {...props} />;
    case 'intersociete': return <Intercompany {...props} />;
    case 'nouvelle-req': return <NewRequisition {...props} />;
    case 'requisitions': return <Requisitions {...props} />;
    case 'approbation': return <Approvals {...props} />;
    case 'ordres': return <ExpenseOrders {...props} />;
    case 'avances': return <Advances {...props} />;
    case 'caisse': return <Cash {...props} />;
    case 'courses': return <TransportCourses {...props} />;
    case 'config': return <GeneralSettings {...props} />;
    case 'administration': return <Administration {...props} />;
    case 'systeme': return <SystemAdmin {...props} />;
    default: return null;
  }
}
