'use client';
import { ScreenTitle } from './screen-presentation';
import { useCallback, useState } from 'react';
import { DataTable } from './data-table';
import { Field } from './field';
import { ResourceEditor, type FormField } from './resource-editor';
import { Dialog, ErrorNotice, number, useResource, type ScreenProps } from './shared';
import type { Party } from '../../lib/accounting-data';
interface Position { creancier: string; debiteur: string; vu_par: string; montant_usd: number; miroir_usd: number; ecart_usd: number }
interface Invoice { id: string; numero: string; date: string; vendeur: string; acheteur: string; vendeur_societe_id: string; acheteur_societe_id: string | null; total_ttc: number; miroir_numero: string | null; miroir_statut: string | null; statut_reglement: string; solde_du_usd: number }
interface Link { id: string; societe_liee: { id: string; nom: string } | null }
interface Trace { reference_producteur: string; commande: { numero: string; statut: string; date: string; acheteur: string; vendeur: string; qte_commandee: number; total_ht: number; destination: string }; prise_en_charge?: { numero: string; statut: string; date: string }; chargements: { numero: string; date: string; qte: number }[]; transport?: { transporteur: string; course: string; statut: string; camion: string; depart: string }; reception?: { totaux: { bon: number; mauvais: number; manquant: number }; valeur_manquants_usd: number; toutes_confirmees: boolean; receptions: unknown[] }; factures_vendeur: { numero: string; date: string; ttc: number; statut: string }[] }
export function Intercompany(props: ScreenProps) {
  const [tab, setTab] = useState('positions');
  return <><div className="audit-head"><ScreenTitle>Opérations intersociétés</ScreenTitle></div><div className="business-toolbar" role="group" aria-label="Vues intersociétés">{[['positions', 'Positions'], ['factures', 'Factures intra-groupe'], ['trace', 'Traçabilité'], ['liaisons', 'Liaisons']].map(([id, label]) => <button className={`btn ${tab === id ? 'btn-primary' : ''}`} aria-pressed={tab === id} key={id} onClick={() => setTab(id)}>{label}</button>)}</div>{tab === 'positions' ? <Positions {...props} /> : tab === 'factures' ? <Invoices {...props} /> : tab === 'trace' ? <Tracing {...props} /> : <Links {...props} />}</>;
}
function Positions(props: ScreenProps) {
  const load = useCallback(() => props.bridge.api<Position[]>('/intersociete/positions'), [props.bridge]), result = useResource(load);
  return <><p className="banner">Vue transversale des positions rattachées à vos sociétés accessibles. Chaque ligne précise le créancier et le débiteur ; les écarts sont à rapprocher.</p><button className="btn" disabled={result.busy} onClick={result.refresh}><i className="ti ti-refresh" aria-hidden="true" /> Actualiser</button><ErrorNotice error={result.error} />{result.busy && <p role="status">Calcul des positions…</p>}{result.data && !result.busy && !result.error && <DataTable {...props} title="Positions intersociétés" subtitle="Périmètre des sociétés accessibles au compte connecté" columns={['Créancier', 'Débiteur', 'Vu par', 'Montant USD', 'Miroir USD', 'Écart USD']} rows={result.data.map(p => [p.creancier, p.debiteur, p.vu_par, p.montant_usd, p.miroir_usd, p.ecart_usd])} />}</>;
}
function Invoices(props: ScreenProps) {
  const load = useCallback(() => props.bridge.api<Invoice[]>('/intersociete/factures'), [props.bridge]), result = useResource(load), [selected, setSelected] = useState<Invoice | null>(null), [success, setSuccess] = useState('');
  return <><p className="banner">Factures intra-groupe des sociétés accessibles. Le règlement exige les droits nécessaires chez l’acheteur et chez le vendeur.</p><button className="btn" onClick={result.refresh} disabled={result.busy}><i className="ti ti-refresh" aria-hidden="true" /> Actualiser</button><ErrorNotice error={result.error} />{success && <p role="status" className="business-success">{success}</p>}{result.busy && <p>Lecture des factures…</p>}{result.data && !result.busy && !result.error && <DataTable {...props} title="Factures intra-groupe" subtitle="Périmètre des sociétés accessibles" columns={['Facture', 'Date', 'Vendeur', 'Acheteur', 'TTC USD', 'Facture miroir', 'Statut miroir', 'Règlement', 'Solde dû USD']} rows={result.data.map(f => [f.numero, f.date, f.vendeur, f.acheteur, f.total_ttc, f.miroir_numero || 'Absente', f.miroir_statut || '', f.statut_reglement, f.solde_du_usd])} actions={(_, i) => { const f = result.data![i], allowed = [f.acheteur_societe_id, f.vendeur_societe_id].every(id => props.state.companies.find(c => c.id === id)?.roles.some(r => ['DFI', 'COMPTABLE', 'PRESIDENT'].includes(r))); return f.solde_du_usd > 0.009 ? <button className="btn" disabled={!allowed || !f.acheteur_societe_id} onClick={() => setSelected(f)}>Régler</button> : <span>Réglée</span>; }} />}{selected && <Settlement {...props} invoice={selected} onClose={() => setSelected(null)} onSaved={remaining => { setSuccess(`Règlement enregistré chez les deux sociétés. Solde restant : ${number(remaining)} USD. Les écritures restent à valider.`); setSelected(null); result.refresh(); void props.bridge.refreshAccountingBadge(); }} />}</>;
}
function Settlement({ invoice, onClose, onSaved, ...props }: ScreenProps & { invoice: Invoice; onClose: () => void; onSaved: (n: number) => void }) {
  const load = useCallback(async () => { const result = await Promise.all(['acheteur', 'vendeur'].map(side => props.bridge.api<{ id: string; libelle: string; session_ouverte: boolean }[]>(`/caisses?societe_id=${side === 'acheteur' ? invoice.acheteur_societe_id : invoice.vendeur_societe_id}`))); return result; }, [props.bridge, invoice]), result = useResource(load);
  if (result.busy || result.error || !result.data) return <Dialog bridge={props.bridge} title="Préparer le règlement" onClose={onClose}><ErrorNotice error={result.error} />{result.busy ? <p>Lecture des caisses des deux sociétés…</p> : <button className="btn" onClick={result.refresh}>Réessayer</button>}</Dialog>;
  const fields: FormField[] = [{ key: 'montant_usd', label: 'Montant à régler (USD)', type: 'number', min: 0.01, max: invoice.solde_du_usd, required: true }];
  ['acheteur', 'vendeur'].forEach((side, i) => { const label = side === 'acheteur' ? `${invoice.acheteur} — sortie` : `${invoice.vendeur} — entrée`; fields.push({ key: `${side}_mode`, label: `${label} · mode`, options: [['banque', 'Banque'], ['espece', 'Espèces']] }, { key: `${side}_caisse_id`, label: `${label} · caisse ouverte`, required: true, visible: v => v[`${side}_mode`] === 'espece', options: [['', 'Sélectionner'], ...result.data![i].filter(c => c.session_ouverte).map(c => [c.id, c.libelle] as [string, string])] }); }); fields.push({ key: 'reference', label: 'Référence du règlement' });
  return <ResourceEditor bridge={props.bridge} title={`Règlement · ${invoice.numero}`} onClose={onClose} fields={fields} initial={{ montant_usd: String(invoice.solde_du_usd), acheteur_mode: 'banque', vendeur_mode: 'banque', acheteur_caisse_id: '', vendeur_caisse_id: '', reference: '' }} submitLabel="Confirmer le règlement des deux côtés" note={`Cette action enregistre une sortie chez ${invoice.acheteur} et une entrée chez ${invoice.vendeur}. Les pièces comptables passent ensuite par la validation habituelle.`} save={async v => { if (!Number.isFinite(Number(v.montant_usd)) || Number(v.montant_usd) <= 0 || Number(v.montant_usd) > invoice.solde_du_usd) throw new Error('Indiquez un montant positif inférieur ou égal au solde.'); const r = await props.bridge.api<{ solde_du_usd: number }>(`/intersociete/factures/${invoice.id}/regler`, { method: 'POST', body: { ...v, montant_usd: Number(v.montant_usd), acheteur_caisse_id: v.acheteur_mode === 'espece' ? v.acheteur_caisse_id : null, vendeur_caisse_id: v.vendeur_mode === 'espece' ? v.vendeur_caisse_id : null, reference: v.reference.trim() || null } }); onSaved(r.solde_du_usd); }} />;
}
function Links(props: ScreenProps) {
  const { bridge, state } = props, load = useCallback(async () => { const q = `societe_id=${state.companyId}`; const [links, parties] = await Promise.all([bridge.api<{ societes: { id: string; nom: string }[]; tiers: Link[] }>(`/intersociete/liaisons?${q}`), bridge.api<Party[]>(`/commercial/tiers?${q}`)]); return { ...links, parties: parties.filter(p => p.societe_id === state.companyId && p.code !== 'COMPTANT' && ['client', 'fournisseur'].includes(p.type)) }; }, [bridge, state.companyId]), result = useResource(load), [selected, setSelected] = useState<Party | null>(null), [success, setSuccess] = useState('');
  return <><p className="banner">Liaisons des clients et fournisseurs propres à la société active. Les fiches partagées restent disponibles dans les autres menus ; elles ne portent pas de liaison propre à cette société.</p><button className="btn" onClick={result.refresh} disabled={result.busy}><i className="ti ti-refresh" aria-hidden="true" /> Actualiser</button><ErrorNotice error={result.error} />{success && <p role="status">{success}</p>}{result.busy && <p>Lecture des liaisons…</p>}{result.data && !result.busy && !result.error && <DataTable {...props} title="Liaisons intersociétés" subtitle="Société active" columns={['Code', 'Tiers', 'Type', 'Société liée']} rows={result.data.parties.map(p => [p.code, p.nom, p.type, result.data!.tiers.find(l => l.id === p.id)?.societe_liee?.nom || 'Aucune'])} actions={(_, i) => <button className="btn" onClick={() => setSelected(result.data!.parties[i])}>Modifier la liaison</button>} />}{selected && result.data && <ResourceEditor bridge={bridge} title={`Liaison · ${selected.nom}`} onClose={() => setSelected(null)} initial={{ societe_liee_id: result.data.tiers.find(l => l.id === selected.id)?.societe_liee?.id || '' }} fields={[{ key: 'societe_liee_id', label: 'Société représentée par ce tiers', options: [['', 'Aucune liaison'], ...result.data.societes.filter(c => c.id !== state.companyId).map(c => [c.id, c.nom] as [string, string])] }]} note="La liaison détermine la création des factures miroir pour les prochaines opérations. Vérifiez la société avant de confirmer." save={async v => { await bridge.api('/intersociete/lier', { method: 'POST', body: { tiers_id: selected.id, societe_liee_id: v.societe_liee_id || null } }); setSelected(null); setSuccess('Liaison enregistrée.'); result.refresh(); }} />}</>;
}
function Tracing(props: ScreenProps) {
  const [search, setSearch] = useState(''), [query, setQuery] = useState(''), load = useCallback(() => query ? props.bridge.api<Trace[]>(`/intersociete/tracer?societe_id=${props.state.companyId}&q=${encodeURIComponent(query)}`) : Promise.resolve([]), [props.bridge, props.state.companyId, query]), result = useResource(load);
  return <><form className="business-toolbar" onSubmit={e => { e.preventDefault(); if (search.trim() === query) result.refresh(); else setQuery(search.trim()); }}><Field label="Numéro producteur ou commande" required value={search} onChange={setSearch} /><button className="btn btn-primary" disabled={result.busy}>Rechercher le dossier</button></form><ErrorNotice error={result.error} />{query && result.busy && <p>Recherche du dossier…</p>}{query && !result.busy && !result.error && !result.data?.length && <p>Aucun dossier trouvé.</p>}{query && !result.busy && !result.error && result.data?.map((d, i) => { const rows: (string | number)[][] = [['Commande', `${d.commande.numero} · ${d.commande.date} · ${d.commande.statut}`], ['Acheteur', d.commande.acheteur], ['Vendeur', d.commande.vendeur], ['Quantité commandée', d.commande.qte_commandee], ['Total HT USD', d.commande.total_ht], ['Destination', d.commande.destination || '']]; if (d.prise_en_charge) rows.push(['Prise en charge', `${d.prise_en_charge.numero} · ${d.prise_en_charge.statut} · ${d.prise_en_charge.date || ''}`]); d.chargements?.forEach(c => rows.push(['Chargement', `${c.numero} · ${c.date} · ${number(c.qte)}`])); if (d.transport) rows.push(['Transport', `${d.transport.transporteur || ''} · ${d.transport.course} · ${d.transport.statut} · ${d.transport.camion || ''} · ${d.transport.depart || ''}`]); if (d.reception) rows.push(['Reçus en bon état', d.reception.totaux.bon], ['Reçus en mauvais état', d.reception.totaux.mauvais], ['Manquants', d.reception.totaux.manquant], ['Valeur des manquants USD', d.reception.valeur_manquants_usd], ['Confirmation transporteur', d.reception.toutes_confirmees ? 'Confirmée' : d.reception.receptions.length ? 'À confirmer' : 'Non reçue']); d.factures_vendeur?.forEach(f => rows.push(['Facture vendeur', `${f.numero} · ${f.date} · ${number(f.ttc)} USD · ${f.statut}`])); return <DataTable key={`${query}-${i}`} {...props} title={`Traçabilité ${d.commande.numero}`} subtitle={`Référence producteur : ${d.reference_producteur || 'non renseignée'}`} columns={['Étape / rubrique', 'Détail']} rows={rows} />; })}</>;
}
