'use client';
import { ScreenTitle } from './screen-presentation';
import { useCallback, useState } from 'react';
import { DataTable } from './data-table';
import { CommercialEditor, type CommercialLine, type NamedAccount } from './commercial-common';
import { OperationForm } from './operation-form';
import { commercialNumber } from '../../lib/commercial-data';
import { Dialog, ErrorNotice, ReportPreview, number, useResource, type Report, type ScreenProps } from './shared';
export interface Invoice { id: string; numero: string; type: string; date: string; tiers: string; reference?: string; echeance?: string; total_ht: number; total_tva: number; total_ttc: number; total_frais: number; marge?: number; cout_ventes?: number; statut: string; statut_reglement?: string; solde_du_usd?: number; regle_usd?: number; lignes: CommercialLine[]; frais?: { libelle: string; montant_ht: number; montant_tva: number; contrepartie: string }[] }
export function invoiceReport(d: Invoice): Report { return { title: `Facture ${d.numero}`, subtitle: `${d.date} · ${d.tiers} · Référence : ${d.reference || '—'} · Échéance : ${d.echeance || 'Non précisée'}`, columns: ['Désignation', 'Quantité', 'P.U. HT USD', 'Remise %', 'TVA %', 'Montant HT USD'], rows: [...d.lignes.map(l => [l.designation, l.qte, l.prix_unitaire, l.remise_pct || 0, l.taux_tva, l.montant_ht]), ['TOTAL HT', '', '', '', '', d.total_ht], ['TVA', '', '', '', '', d.total_tva], ['TOTAL TTC', '', '', '', '', d.total_ttc]], note: `Montants en USD. Règlement : ${d.statut_reglement || d.statut}. ${d.solde_du_usd != null ? `Solde à régler : ${number(d.solde_du_usd)} USD.` : ''}` }; }
export function Invoices(props: ScreenProps) {
  const { bridge, state } = props, kind = state.view === 'achats' ? 'achat' : 'vente', load = useCallback(() => bridge.api<Invoice[]>(`/commercial/factures?societe_id=${state.companyId}&type=${kind}`), [bridge, state.companyId, kind]), r = useResource(load), [create, setCreate] = useState(false), [selected, setSelected] = useState('');
  return <><div className="audit-head"><ScreenTitle>{kind === 'achat' ? 'Factures fournisseurs' : 'Factures clients'}</ScreenTitle><button className="btn" disabled={r.busy} onClick={r.refresh}><i className="ti ti-refresh" aria-hidden="true" /> Actualiser</button><button className="btn btn-primary" disabled={r.busy || !!r.error} onClick={() => setCreate(true)}>Nouvelle facture</button></div><ErrorNotice error={r.error} />{r.busy && <p>Chargement…</p>}{r.data && <DataTable {...props} title={kind === 'achat' ? 'Achats' : 'Ventes'} subtitle="Société active · montants USD" disabled={r.busy || !!r.error} columns={['Numéro', 'Date', 'Tiers', 'HT', 'TVA', 'TTC', 'Règlement', 'Solde dû']} rows={r.data.map(d => [d.numero, d.date, d.tiers, d.total_ht, d.total_tva, d.total_ttc, d.statut_reglement || d.statut, d.solde_du_usd ?? '—'])} actions={(_, i) => <button className="btn" disabled={r.busy || !!r.error} onClick={() => setSelected(r.data![i].id)}><i className="ti ti-eye" aria-hidden="true" /> Consulter</button>} />}{create && <CommercialEditor {...props} kind={kind} onClose={() => setCreate(false)} onSaved={() => { setCreate(false); r.refresh(); }} />}{selected && <InvoiceDetail {...props} id={selected} onClose={() => setSelected('')} onSaved={r.refresh} />}</>;
}
export function InvoiceDetail({ id, onClose, onSaved, ...props }: ScreenProps & { id: string; onClose: () => void; onSaved?: () => void }) {
  const load = useCallback(() => props.bridge.api<Invoice>(`/commercial/factures/${id}`), [props.bridge, id]), r = useResource(load), [pay, setPay] = useState(false), [report, setReport] = useState(false), d = r.data;
  return <><Dialog bridge={props.bridge} title={d?.numero || 'Facture'} onClose={onClose}><ErrorNotice error={r.error} />{r.busy && <p>Chargement…</p>}{d && !r.busy && !r.error && <><p>{d.tiers} · {d.date} · TTC {number(d.total_ttc)} USD</p><p>Règlement : {d.statut_reglement || d.statut} · Solde : {number(d.solde_du_usd)} USD</p><DataTable {...props} title="Lignes de facture" subtitle="USD" columns={['Désignation', 'Quantité', 'Prix HT', 'Remise %', 'TVA %', 'HT']} rows={d.lignes.map(l => [l.designation, l.qte, l.prix_unitaire, l.remise_pct || 0, l.taux_tva, l.montant_ht])} /><button className="btn" onClick={() => setReport(true)}>Facture PDF / Excel</button>{d.type === 'vente' && Number(d.solde_du_usd) > 0 && <button className="btn btn-primary" onClick={() => setPay(true)}>Enregistrer un règlement</button>}{!!d.frais?.length && <DataTable {...props} title="Frais accessoires" subtitle="Contreparties des frais · USD" columns={['Libellé', 'HT', 'TVA', 'Contrepartie']} rows={d.frais.map(f => [f.libelle, f.montant_ht, f.montant_tva, f.contrepartie])} />}{d.marge != null && <p className="muted">Information interne : coût des ventes {number(d.cout_ventes)} USD · marge {number(d.marge)} USD. Ces données ne figurent pas sur la facture client.</p>}</>}</Dialog>{report && d && <ReportPreview {...props} report={invoiceReport(d)} onClose={() => setReport(false)} />}{pay && d && <InvoicePayment {...props} invoice={d} onClose={() => setPay(false)} onSaved={() => { setPay(false); r.refresh(); onSaved?.(); }} />}</>;
}
function InvoicePayment({ invoice, onClose, onSaved, ...props }: ScreenProps & { invoice: Invoice; onClose: () => void; onSaved: () => void }) {
  const load = useCallback(() => props.bridge.api<NamedAccount[]>(`/caisses?societe_id=${props.state.companyId}`), [props.bridge, props.state.companyId]), r = useResource(load);
  return r.data && !r.busy && !r.error ? <OperationForm bridge={props.bridge} title={`Règlement · ${invoice.numero}`} initial={{ mode: 'espece', devise: 'USD', montant: String(invoice.solde_du_usd), caisse_id: '', reference: '' }} note={`Solde affiché : ${number(invoice.solde_du_usd)} USD. Pour un paiement en CDF, saisissez le montant réellement reçu en CDF ; le serveur applique le taux enregistré. Aucun virement bancaire externe n’est déclenché.`} fields={[{ key: 'mode', label: 'Mode', options: [['espece', 'Espèces'], ['banque', 'Banque'], ['mobile_money', 'Mobile Money']] }, { key: 'devise', label: 'Devise', options: [['USD', 'USD'], ['CDF', 'CDF']] }, { key: 'montant', label: 'Montant dans la devise choisie', type: 'number', min: 0.01, required: true }, { key: 'caisse_id', label: 'Caisse ouverte', required: true, visible: v => v.mode === 'espece', options: [['', 'Choisir…'], ...r.data.filter(c => c.session_ouverte).map(c => [c.id, c.libelle] as [string, string])] }, { key: 'reference', label: 'Référence du règlement' }]} onChange={(v, key, value) => ({ ...v, [key]: value, ...(key === 'devise' ? { montant: '' } : {}) })} onClose={onClose} save={async v => { const montant = commercialNumber(v.montant, 'Montant'); if (!montant) throw new Error('Montant requis.'); await props.bridge.api(`/ventes/factures/${invoice.id}/regler`, { method: 'POST', body: { ...v, montant, caisse_id: v.mode === 'espece' ? v.caisse_id : null, reference: v.reference || null } }); onSaved(); }} /> : <Dialog bridge={props.bridge} title="Règlement" onClose={onClose}><ErrorNotice error={r.error} />{r.busy && <p>Chargement des caisses…</p>}</Dialog>;
}
