'use client';
import { useCallback, useRef, useState } from 'react';
import { recipePayload, type Recipe } from '../../lib/kitchen-data';
import { ArticleEditor, type Article } from './articles';
import { Dialog, ErrorNotice, message, useResource, type ScreenProps } from './shared';
import { Field } from './field';

export function RecipeEditor({ bridge, state, recipe, recipes, onClose, onSaved }: ScreenProps & { recipe: Recipe | null; recipes: Recipe[]; onClose: () => void; onSaved: () => void }) {
  const load = useCallback(() => bridge.api<Article[]>(`/commercial/articles?societe_id=${state.companyId}`), [bridge, state.companyId]);
  const articles = useResource(load), [busy, setBusy] = useState(false);
  return <Dialog bridge={bridge} title={recipe ? `Recette · ${recipe.plat}` : 'Nouvelle fiche technique'} busy={busy} onClose={onClose} footer={close => <><button className="btn" disabled={busy} onClick={close}><i className="ti ti-x" aria-hidden="true" /> Annuler</button><button className="btn btn-primary" type="submit" form="recipe-form" disabled={busy || articles.busy || !!articles.error}>Enregistrer la fiche</button></>}><ErrorNotice error={articles.error} />{articles.error && <button className="btn" onClick={articles.refresh}>Réessayer</button>}{articles.busy && <p role="status">Lecture du catalogue…</p>}{articles.data && !articles.busy && !articles.error && <RecipeForm bridge={bridge} state={state} recipe={recipe} recipes={recipes} articles={articles.data} busy={busy} setBusy={setBusy} onSaved={onSaved} />}</Dialog>;
}
function RecipeForm({ bridge, state, recipe, recipes, articles, busy, setBusy, onSaved }: ScreenProps & { recipe: Recipe | null; recipes: Recipe[]; articles: Article[]; busy: boolean; setBusy: (b: boolean) => void; onSaved: () => void }) {
  const [dish, setDish] = useState(recipe?.article_id || ''), [portions, setPortions] = useState(String(recipe?.portions || 1)), [note, setNote] = useState(recipe?.note || ''), [lines, setLines] = useState(recipe?.lignes.map((l, key) => ({ key, article_id: l.article_id, qte: String(l.qte) })) || [{ key: 0, article_id: '', qte: '' }]), [added, setAdded] = useState<Article[]>([]), [creating, setCreating] = useState<number | 'dish' | null>(null), [error, setError] = useState('');
  const pending = useRef(false), nextKey = useRef(lines.length);
  const catalogue = [...articles.filter(a => !added.some(b => b.id === a.id)), ...added], dishes = catalogue.filter(a => a.actif && a.nature === 'marchandise' || a.id === recipe?.article_id), ingredients = catalogue.filter(a => a.actif && a.gere_stock);
  const canCreate = (state.companies.find(c => c.id === state.companyId)?.roles || []).some(r => ['DFI', 'COMPTABLE'].includes(r));
  const update = (key: number, change: Partial<{ article_id: string; qte: string }>) => setLines(old => old.map(l => l.key === key ? { ...l, ...change } : l));
  const created = (a: Article) => { setAdded(old => [...old.filter(b => b.id !== a.id), a]); if (!a.actif || (creating === 'dish' ? a.nature !== 'marchandise' || recipes.some(r => r.article_id === a.id) : !a.gere_stock)) setError('Cette fiche ne correspond pas à la sélection : vérifiez la nature, la gestion du stock et les recettes déjà présentes.'); else { if (creating === 'dish') setDish(a.id); else if (creating !== null) update(creating, { article_id: a.id }); setError(''); } setCreating(null); };
  return <><form id="recipe-form" onSubmit={async e => { e.preventDefault(); if (pending.current) return; setError(''); try { const body = recipePayload(dish, portions, lines); pending.current = true; setBusy(true); await bridge.api(`/cuisine/fiches?societe_id=${state.companyId}`, { method: 'POST', body: { ...body, note: note.trim() } }); onSaved(); } catch (cause) { setError(message(cause)); } finally { pending.current = false; setBusy(false); } }}><fieldset className="business-fieldset" disabled={busy}>
    <div className="business-form-grid"><label className="business-field">Plat vendu<select className="form-select" required disabled={!!recipe} value={dish} onChange={e => setDish(e.target.value)}><option value="">Choisir un plat…</option>{dishes.map(a => <option key={a.id} value={a.id} disabled={!recipe && recipes.some(r => r.article_id === a.id)}>{a.code} — {a.designation}{!recipe && recipes.some(r => r.article_id === a.id) ? ' · fiche déjà existante' : ''}</option>)}</select></label><Field label="Recette pour combien de portions" type="number" required min="0.0001" step="any" value={portions} onChange={setPortions} /></div>{canCreate && !recipe && <button type="button" className="btn" onClick={() => setCreating('dish')}>Créer l’article du plat</button>}
    <p className="muted">Saisissez les quantités de la recette entière, pour le nombre de portions indiqué. Le coût par portion est calculé au coût moyen du dépôt cuisine.</p>
    {lines.map((l, index) => <section className="stock-transfer-line" key={l.key}><label>Ingrédient {index + 1}<select className="form-select" required value={l.article_id} onChange={e => update(l.key, { article_id: e.target.value })}><option value="">Choisir un ingrédient…</option>{ingredients.map(a => <option key={a.id} value={a.id} disabled={a.id === dish || lines.some(other => other.key !== l.key && other.article_id === a.id)}>{a.code} — {a.designation} ({a.unite})</option>)}</select></label><Field label={`Quantité ingrédient ${index + 1}`} type="number" min="0.0001" step="any" required value={l.qte} onChange={qte => update(l.key, { qte })} /><div className="business-toolbar">{canCreate && <button type="button" className="btn btn-sm" onClick={() => setCreating(l.key)}>Créer un ingrédient</button>}<button type="button" className="btn btn-sm" disabled={lines.length === 1} onClick={() => setLines(old => old.filter(row => row.key !== l.key))}>Retirer l’ingrédient {index + 1}</button></div></section>)}
    <button type="button" className="btn" onClick={() => { const key = nextKey.current++; setLines(old => [...old, { key, article_id: '', qte: '' }]); }}>Ajouter un ingrédient</button><Field label="Préparation / note" value={note} onChange={setNote} maxLength={255} /><ErrorNotice error={error} /></fieldset>
  </form>{creating !== null && <ArticleEditor bridge={bridge} state={state} article={null} articles={catalogue} onClose={() => setCreating(null)} onSaved={created} onExisting={created} />}</>;
}
