'use client';
import { ScreenTitle } from './screen-presentation';
import { useCallback, useRef, useState } from 'react';
import type { Consumption, KitchenConfig, KitchenReport, Recipe } from '../../lib/kitchen-data';
import { cost, quantity, type Depot } from '../../lib/stock-forms';
import { DataTable } from './data-table';
import { Field } from './field';
import { RecipeEditor } from './kitchen-recipe';
import { Dialog, ErrorNotice, ReportPreview, message, number, today, useResource, type ScreenProps, type Report } from './shared';

export function Kitchen({ bridge, state }: ScreenProps) {
  const load = useCallback(async () => { const [config, recipes, consumptions, report] = await Promise.all([bridge.api<KitchenConfig>(`/cuisine/config?societe_id=${state.companyId}`), bridge.api<Recipe[]>(`/cuisine/fiches?societe_id=${state.companyId}`), bridge.api<Consumption[]>(`/cuisine/consommations?societe_id=${state.companyId}`), bridge.api<KitchenReport>(`/cuisine/rapport?societe_id=${state.companyId}`)]); return { config, recipes, consumptions, report }; }, [bridge, state.companyId]);
  const result = useResource(load), disabled = result.busy || !!result.error;
  const [editing, setEditing] = useState<Recipe | 'new' | null>(null), [settings, setSettings] = useState(false), [generating, setGenerating] = useState(false), [deleting, setDeleting] = useState<Recipe | null>(null), [preview, setPreview] = useState<Report | null>(null), [success, setSuccess] = useState(''), [alerts, setAlerts] = useState<string[]>([]);
  const manager = (state.companies.find(c => c.id === state.companyId)?.roles || []).some(r => ['DFI', 'PRESIDENT', 'ADMIN_SYS', 'DG'].includes(r));
  const data = result.data;
  return <>
    <div className="audit-head"><div><ScreenTitle>Cuisine & coûts des plats</ScreenTitle><p className="muted">{data ? `Dépôt : ${data.config.depot} · Période ${data.report.du} → ${data.report.au}` : 'Fiches techniques et consommations théoriques'}</p></div><div className="audit-actions"><button className="btn" disabled={result.busy} onClick={result.refresh}><i className="ti ti-refresh" aria-hidden="true" /> Actualiser</button><button className="btn" onClick={() => bridge.navigate('inventaires')}>Inventaires & écarts</button>{manager && <button className="btn" disabled={disabled || !data} onClick={() => setSettings(true)}>Réglages cuisine</button>}<button className="btn btn-primary" disabled={disabled || !data} onClick={() => setGenerating(true)}>Générer la consommation</button></div></div>
    <ErrorNotice error={result.error} />{result.busy && <p role="status">Lecture des coûts et consommations…</p>}{success && <p className="business-success" role="status">{success}</p>}{alerts.length > 0 && <div className="business-error" role="alert"><b>La consommation est enregistrée, avec des alertes de stock :</b><ul>{alerts.map((a, n) => <li key={n}>{a}</li>)}</ul></div>}
    {data && <>{data.config.depot_est_central && <p className="banner">Les ingrédients sont actuellement consommés depuis le dépôt central. Les réglages permettent de choisir un dépôt dédié à la cuisine.</p>}<p className="banner">Inventaires validés du dépôt « {data.report.depot_inventaire} » : {data.report.inventaires_valides} · Manquants : {number(data.report.manquants_inventaire)} USD · Excédents : {number(data.report.excedents_inventaire)} USD. Les écarts réels sont présentés séparément des coûts théoriques.</p>{data.report.alerte && <p className="business-error">Coût des ingrédients : {number(data.report.food_cost_pct)} % du chiffre d’affaires, au-dessus du seuil de {number(data.report.seuil_pct)} %.</p>}
    <div className="caisse-cards">{[['Coût / chiffre d’affaires', data.report.food_cost_pct == null ? 'Non calculable' : `${number(data.report.food_cost_pct)} %`], ['Coût théorique', `${number(data.report.cout_theorique)} USD`], ['Chiffre d’affaires des plats', `${number(data.report.ca_plats)} USD`], ['Jours générés', data.report.jours_generes]].map(([label, value]) => <article className="caisse-card" key={label}><p className="muted">{label}</p><strong>{disabled ? '—' : value}</strong></article>)}</div>
    <div className="business-toolbar"><button className="btn btn-primary" disabled={disabled} onClick={() => setEditing('new')}>Nouvelle fiche technique</button><button className="btn" disabled={disabled} onClick={() => setPreview({ title: 'Rapport cuisine', subtitle: `${data.report.du} → ${data.report.au} · ${data.config.depot}`, columns: ['Indicateur', 'Valeur'], rows: [['Coût théorique USD', data.report.cout_theorique], ['CA plats USD', data.report.ca_plats], ['Nombre de plats', data.report.nb_plats], ['Ratio coût / CA (%)', data.report.food_cost_pct ?? 'Non calculable'], ['Seuil alerte (%)', data.report.seuil_pct], ['Jours générés', data.report.jours_generes], ['Inventaires validés', data.report.inventaires_valides], ['Manquants inventaire USD', data.report.manquants_inventaire], ['Excédents inventaire USD', data.report.excedents_inventaire]], note: 'Les coûts théoriques sont ceux des consommations générées. Les écarts d’inventaire validés sont présentés séparément.' })}>Rapport de la cuisine</button></div>
    <DataTable bridge={bridge} state={state} title="Fiches techniques" subtitle="Coût moyen des ingrédients au dépôt cuisine · montants par portion en USD" disabled={disabled} columns={['Code', 'Plat', 'Prix vente', 'Coût portion', 'Coût / CA (%)', 'Marge portion', 'Ingrédients']} rows={data.recipes.map(r => [r.code, r.plat, r.prix_vente, r.cout_portion, r.food_cost_pct, r.marge_portion, r.lignes.map(l => `${l.designation} : ${cost(l.qte_par_portion)} ${l.unite}`).join(' · ')])} actions={row => { const r = data.recipes.find(r => r.code === row[0])!; return <div className="business-toolbar"><button className="btn btn-sm" disabled={disabled} onClick={() => setEditing(r)}><i className="ti ti-edit" aria-hidden="true" /> Modifier</button><button className="btn btn-sm" disabled={disabled} onClick={() => setPreview({ title: `Fiche technique ${r.code} — ${r.plat}`, subtitle: `${r.portions} portions par recette · ${data.config.depot}`, columns: ['Code', 'Ingrédient', 'Unité', 'Quantité recette', 'Quantité / portion', 'CUMP USD', 'Coût / portion USD'], rows: r.lignes.map(l => [l.code, l.designation, l.unite, cost(l.qte), cost(l.qte_par_portion), cost(l.cump), cost(l.cout_par_portion)]), note: `Coût par portion : ${number(r.cout_portion)} USD. ${r.note || ''}` })}>Fiche / imprimer</button><button className="btn btn-sm" disabled={disabled} onClick={() => setDeleting(r)}>Désactiver</button></div>; }} />
    <DataTable bridge={bridge} state={state} title="Consommations théoriques" subtitle="60 dernières générations · montants en USD" disabled={disabled} columns={['Numéro', 'Date', 'Dépôt', 'Plats', 'Coût', 'Chiffre d’affaires', 'Coût / CA (%)', 'Alerte']} rows={data.consumptions.map(c => [c.numero, c.date, c.depot, c.nb_plats, c.cout_total, c.ca_total, c.food_cost_pct, c.alerte ? 'Seuil dépassé' : ''])} actions={row => <button className="btn btn-sm" disabled={disabled} onClick={() => { const c = data.consumptions.find(c => c.numero === row[0])!; setPreview({ title: `Bon de consommation ${c.numero}`, subtitle: `${c.date} · ${c.depot}`, columns: ['Code', 'Ingrédient', 'Quantité consommée', 'Valeur USD'], rows: c.lignes.map(l => [l.code, l.designation, quantity(l.qte), l.valeur]), note: `Coût théorique : ${number(c.cout_total)} USD · ${number(c.nb_plats)} plats · CA : ${number(c.ca_total)} USD. Ce bon ne remplace pas le comptage physique des ingrédients.` }); }}>Détail / bon</button>} />
    {editing && <RecipeEditor bridge={bridge} state={state} recipe={editing === 'new' ? null : editing} recipes={data.recipes} onClose={() => setEditing(null)} onSaved={() => { setEditing(null); setSuccess('Fiche technique enregistrée. Les coûts sont recalculés au dépôt cuisine.'); result.refresh(); }} />}
    {settings && <KitchenSettings bridge={bridge} state={state} config={data.config} onClose={() => setSettings(false)} onSaved={() => { setSettings(false); setSuccess('Réglages cuisine enregistrés.'); result.refresh(); }} />}
    {generating && <GenerateConsumption bridge={bridge} state={state} config={data.config} onClose={() => setGenerating(false)} onSaved={c => { setGenerating(false); setSuccess(`${c.numero} enregistré : ${number(c.nb_plats)} plats, coût ${number(c.cout_total)} USD.`); setAlerts(c.alertes || []); result.refresh(); }} />}
    {deleting && <DisableRecipe bridge={bridge} state={state} recipe={deleting} onClose={() => setDeleting(null)} onSaved={() => { setDeleting(null); setSuccess('Fiche technique désactivée. Les consommations passées sont conservées.'); result.refresh(); }} />}</>}
    {preview && <ReportPreview bridge={bridge} state={state} report={preview} onClose={() => setPreview(null)} />}
  </>;
}
function KitchenSettings({ bridge, state, config, onClose, onSaved }: ScreenProps & { config: KitchenConfig; onClose: () => void; onSaved: () => void }) {
  const load = useCallback(() => bridge.api<Depot[]>(`/stock/depots?societe_id=${state.companyId}`), [bridge, state.companyId]);
  const depots = useResource(load), [depot, setDepot] = useState(config.depot_id), [threshold, setThreshold] = useState(String(config.seuil_food_cost_pct)), [busy, setBusy] = useState(false), [error, setError] = useState('');
  const pending = useRef(false);
  return <Dialog bridge={bridge} title="Réglages cuisine" busy={busy} onClose={onClose} footer={close => <><button className="btn" disabled={busy} onClick={close}><i className="ti ti-x" aria-hidden="true" /> Annuler</button><button className="btn btn-primary" type="submit" form="kitchen-settings" disabled={busy || depots.busy || !!depots.error}><i className="ti ti-device-floppy" aria-hidden="true" /> Enregistrer</button></>}><ErrorNotice error={depots.error} />{depots.error && <button className="btn" onClick={depots.refresh}>Réessayer</button>}<form id="kitchen-settings" onSubmit={async e => { e.preventDefault(); if (pending.current) return; setError(''); if (!depot || !Number.isFinite(Number(threshold)) || Number(threshold) < 1 || Number(threshold) > 100) { setError('Choisissez un dépôt et un seuil entre 1 et 100 %.'); return; } pending.current = true; setBusy(true); try { await bridge.api(`/cuisine/config?societe_id=${state.companyId}`, { method: 'POST', body: { depot_id: depot, seuil_food_cost_pct: Number(threshold) } }); onSaved(); } catch (cause) { setError(message(cause)); } finally { pending.current = false; setBusy(false); } }}><fieldset className="business-fieldset" disabled={busy || depots.busy || !!depots.error}><label className="business-field">Dépôt cuisine<select className="form-select" required value={depot} onChange={e => setDepot(e.target.value)}>{depots.data?.map(d => <option key={d.id} value={d.id}>{d.libelle}{d.type === 'central' ? ' (central)' : ''}</option>)}</select></label><Field label="Seuil d’alerte coût / CA (%)" type="number" required min={1} max={100} step="any" value={threshold} onChange={setThreshold} /></fieldset><ErrorNotice error={error} /></form></Dialog>;
}
function GenerateConsumption({ bridge, state, config, onClose, onSaved }: ScreenProps & { config: KitchenConfig; onClose: () => void; onSaved: (c: Consumption) => void }) {
  const [day, setDay] = useState(today), [busy, setBusy] = useState(false), [error, setError] = useState(''); const pending = useRef(false);
  return <Dialog bridge={bridge} title="Générer la consommation théorique" busy={busy} onClose={onClose} footer={close => <><button className="btn" disabled={busy} onClick={close}><i className="ti ti-x" aria-hidden="true" /> Annuler</button><button className="btn btn-primary" type="submit" form="kitchen-generate" disabled={busy}>Confirmer et générer</button></>}><form id="kitchen-generate" onSubmit={async e => { e.preventDefault(); if (pending.current) return; pending.current = true; setBusy(true); setError(''); try { const c = await bridge.api<Consumption>(`/cuisine/consommations?societe_id=${state.companyId}`, { method: 'POST', body: { date: day } }); onSaved(c); } catch (cause) { setError(message(cause)); } finally { pending.current = false; setBusy(false); } }}><Field label="Journée à consommer" type="date" required max={today()} disabled={busy} value={day} onChange={setDay} /><p className="banner">Les ventes de plats de cette journée sont multipliées par les fiches techniques. Les ingrédients sortent immédiatement du dépôt « {config.depot} » avec une pièce comptable suivant les règles de validation de la société. Une seule génération est permise par jour.</p><p>Terminez et vérifiez les ventes de la journée avant de générer. Les stocks négatifs éventuels seront signalés et devront être régularisés par inventaire.</p><ErrorNotice error={error} /></form></Dialog>;
}
function DisableRecipe({ bridge, state, recipe, onClose, onSaved }: ScreenProps & { recipe: Recipe; onClose: () => void; onSaved: () => void }) {
  const [busy, setBusy] = useState(false), [error, setError] = useState(''); const pending = useRef(false);
  return <Dialog bridge={bridge} title="Désactiver la fiche technique" busy={busy} onClose={onClose} footer={close => <><button className="btn" disabled={busy} onClick={close}>Revenir</button><button className="btn btn-primary" disabled={busy} onClick={async () => { if (pending.current) return; pending.current = true; setBusy(true); setError(''); try { await bridge.api(`/cuisine/fiches/${recipe.id}?societe_id=${state.companyId}`, { method: 'DELETE' }); onSaved(); } catch (cause) { setError(message(cause)); } finally { pending.current = false; setBusy(false); } }}>Confirmer la désactivation</button></>}><p>La recette « {recipe.plat} » ne sera plus utilisée pour les prochaines consommations. Les bons déjà générés restent conservés.</p><ErrorNotice error={error} /></Dialog>;
}
