'use client';
import { ScreenTitle } from './screen-presentation';
import { useCallback, useState } from 'react';
import { partyLabel, type Party } from '../../lib/accounting-data';
import { ArticleEditor, type Article } from './articles';
import { RoomEditor, type Room } from './rooms';
import { ContractEditor } from './transport-contracts';
import { EngineSettings, type EngineConfig } from './engine-report';
import { ResourceEditor, type FormField } from './resource-editor';
import { Dialog, ErrorNotice, message, normalize, useResource, type ScreenProps } from './shared';
interface Section { title: string; description: string; endpoint?: string; active?: boolean; dedicated?: boolean; view?: string; label?: string; create?: string; createLabel?: string }
const sections: Record<string, Section[]> = {
  'config-hotel': [
    { title: 'Chambres & tarifs', description: 'Numéro, catégorie, prix par nuit et capacité des chambres.', endpoint: '/hotel/chambres', active: true, view: 'hotel-chambres', label: 'Chambres & ménage', create: 'room', createLabel: 'Nouvelle chambre' },
    { title: 'Caisses', description: 'Une caisse par point d’encaissement. Liez ensuite la caisse au point de vente.', endpoint: '/caisses', view: 'caisse', label: 'Journal & soldes', create: 'cash', createLabel: 'Nouvelle caisse' },
    { title: 'Articles bar & restaurant', description: 'Boissons, plats et services ; catégories, prix et TVA propres à cette société.', endpoint: '/commercial/articles', view: 'articles', label: 'Référentiel articles', create: 'article', createLabel: 'Nouvel article' },
    { title: 'Dépôts dédiés', description: 'Créez un dépôt par comptoir et approvisionnez-le depuis le dépôt central.', endpoint: '/stock/depots', dedicated: true, view: 'depots', label: 'Dépôts & transferts' },
    { title: 'Points de vente', description: 'Associez la liste de prix, la caisse et le dépôt du restaurant ou du bar.', endpoint: '/commercial/points-vente', view: 'tarifs-pos', label: 'Tarifs & points de vente' },
    { title: 'Cuisine & fiches techniques', description: 'Dépôt cuisine, ingrédients et coût de préparation de chaque plat.', endpoint: '/cuisine/fiches', view: 'cuisine', label: 'Cuisine & food cost' },
    { title: 'Équipe & rôles', description: 'Affectez les réceptionnistes et caissiers à la société concernée.', view: 'administration', label: 'Administration' },
    { title: 'Comptes & TVA', description: 'Comptes de produits d’hébergement et règles fiscales de la société.', view: 'config', label: 'Paramétrage général' },
  ],
  'config-engins': [
    { title: 'Réglages des prestations', description: 'Forfait mensuel, arrondi par pas de 5 minutes, préfixe des relevés et locataire.', create: 'engine-settings', createLabel: 'Modifier les réglages' },
    { title: 'Parc d’engins & tarifs', description: 'Tarif mensuel, heure supplémentaire et consommation théorique par engin.', endpoint: '/engins/engins', active: true, view: 'engins-parc', label: 'Parc d’engins', create: 'engine', createLabel: 'Nouvel engin' },
    { title: 'Clients locataires', description: 'Clients de la société ou fiches partagées accessibles, identifiés lors de la facturation.', endpoint: '/commercial/tiers?type=client', view: 'administration', label: 'Administration des tiers' },
    { title: 'Entretien préventif', description: 'Plans d’entretien suivant les heures prestées ou la périodicité en jours.', view: 'maintenance-parc', label: 'Parc & échéances' },
  ],
  'config-transport': [
    { title: 'Validation des courses', description: 'Rôle chargé de valider les fiches avant le départ, propre à cette société.', create: 'transport-settings', createLabel: 'Modifier les réglages' },
    { title: 'Camions', description: 'Flotte propre ou sous-traitée, capacité, propriétaire et consommation théorique.', endpoint: '/transport/camions', active: true, view: 'flotte', label: 'Flotte & maintenance', create: 'truck', createLabel: 'Nouveau camion' },
    { title: 'Chauffeurs', description: 'Identité, téléphone et permis. Le tiers personnel est créé pour les avances à justifier.', endpoint: '/transport/chauffeurs', create: 'driver', createLabel: 'Nouveau chauffeur' },
    { title: 'Contrats de transport', description: 'Contrats-cadres clients et tarifs par trajet, à la tonne ou au voyage.', endpoint: '/transport/contrats', view: 'contrats-transport', label: 'Contrats de transport', create: 'contract', createLabel: 'Nouveau contrat' },
    { title: 'Documents & échéances', description: 'Assurances, contrôles techniques et permis, avec alertes avant expiration.', view: 'flotte-documents', label: 'Documents du parc' },
  ],
  'config-maintenance': [
    { title: 'Équipe & rôles', description: 'Affectez les maintenanciers et le directeur technique aux sociétés concernées.', view: 'administration', label: 'Administration' },
    { title: 'Plans d’entretien préventif', description: 'Échéances calculées sur l’usage réel : heures, courses, kilomètres ou jours.', endpoint: '/maintenance/plans', active: true, view: 'maintenance-parc', label: 'Parc & échéances' },
    { title: 'Consommations théoriques', description: 'Litres par 100 km des camions et litres par heure des engins pour le suivi carburant.', view: 'carburant', label: 'Suivi carburant' },
    { title: 'Conformité documentaire', description: 'Assurances, contrôles techniques et permis ; renouvellement et fichiers justificatifs.', endpoint: '/flotte/documents', view: 'flotte-documents', label: 'Documents & échéances' },
  ],
};
const titles: Record<string, string> = { 'config-hotel': 'Configuration de l’hôtel', 'config-engins': 'Configuration des engins', 'config-transport': 'Configuration du transport', 'config-maintenance': 'Configuration de la maintenance' };
export function ModuleConfiguration(props: ScreenProps) {
  const { bridge, state } = props, items = sections[state.view], [editor, setEditor] = useState(''), [success, setSuccess] = useState('');
  const load = useCallback(async () => Promise.all(items.map(async s => { if (!s.endpoint) return { count: null, error: '' }; try { const raw = await bridge.api<({ actif?: boolean; type?: string })[] | { documents: unknown[] }>(`${s.endpoint}${s.endpoint.includes('?') ? '&' : '?'}societe_id=${state.companyId}`); const rows = Array.isArray(raw) ? raw : raw.documents as { actif?: boolean; type?: string }[]; return { count: rows.filter(r => (!s.active || r.actif) && (!s.dedicated || r.type !== 'central')).length, error: '' }; } catch (e) { return { count: null, error: message(e) }; } })), [bridge, items, state.companyId]);
  const result = useResource(load), canNavigate = (view?: string) => view && state.groups.some(g => g.items.some(i => i.view === view));
  const saved = () => { setEditor(''); setSuccess('Informations enregistrées pour la société active.'); result.refresh(); };
  return <><div className="audit-head"><div><ScreenTitle>{titles[state.view]}</ScreenTitle><p className="muted">{state.companies.find(c => c.id === state.companyId)?.nom} · Préparez les données nécessaires à ce module.</p></div><button className="btn" disabled={result.busy} onClick={result.refresh}><i className="ti ti-refresh" aria-hidden="true" /> Actualiser</button></div>{success && <p className="business-success" role="status">{success}</p>}<ErrorNotice error={result.error} />{result.busy && <p role="status">Lecture de la configuration…</p>}<div className="caisse-cards">{items.map((s, i) => <article className="caisse-card" key={s.title}><div className="cc-top"><b>{i + 1}. {s.title}</b>{s.endpoint && <span className="tag">{result.busy ? '…' : result.data?.[i].count == null ? 'Indisponible' : `${result.data[i].count} enregistré(s)`}</span>}</div><p className="muted">{s.description}</p><ErrorNotice error={!result.busy ? result.data?.[i].error || '' : ''} /><div className="business-toolbar">{s.create && <button className="btn btn-primary" disabled={result.busy || !!result.data?.[i].error} onClick={() => setEditor(s.create!)}>{s.createLabel}</button>}{canNavigate(s.view) && <button className="btn" onClick={() => bridge.navigate(s.view!)}>{s.label}</button>}</div></article>)}</div>{editor && (editor === 'contract' ? <ContractEditor {...props} onClose={() => setEditor('')} onSaved={saved} /> : <ConfigurationEditor {...props} kind={editor} onClose={() => setEditor('')} onSaved={saved} />)}</>;
}
type EditorProps = ScreenProps & { kind: string; onClose: () => void; onSaved: () => void };
export function ConfigurationEditor(props: EditorProps) {
  const { bridge, state, kind, onClose, onSaved } = props;
  const endpoint: Record<string, string> = { room: '/hotel/chambres', article: '/commercial/articles', cash: '/caisses', engine: '/engins/engins', driver: '/transport/chauffeurs', truck: '/commercial/tiers?type=fournisseur', 'engine-settings': '/engins/config', 'transport-settings': '/transport/config' };
  const load = useCallback(() => bridge.api<unknown>(`${endpoint[kind]}${endpoint[kind].includes('?') ? '&' : '?'}societe_id=${state.companyId}`), [bridge, state.companyId, kind]); // eslint-disable-line react-hooks/exhaustive-deps
  const result = useResource(load), [article, setArticle] = useState<Article | null>(null);
  if (result.busy || result.error || !result.data) return <Dialog bridge={bridge} title="Préparer la saisie" onClose={onClose}><ErrorNotice error={result.error} />{result.busy ? <p>Chargement des données de la société…</p> : <button className="btn" onClick={result.refresh}>Réessayer</button>}</Dialog>;
  if (kind === 'room') return <RoomEditor {...props} room={null} rooms={result.data as Room[]} />;
  if (kind === 'article') return <ArticleEditor key={article?.id || 'new'} {...props} article={article} articles={result.data as Article[]} onExisting={setArticle} />;
  if (kind === 'engine-settings') return <EngineSettings {...props} config={result.data as EngineConfig} />;
  if (kind === 'transport-settings') { const cfg = result.data as { role_validation: string; roles: { code: string; libelle: string }[] }; return <ResourceEditor bridge={bridge} title="Réglages transport" onClose={onClose} initial={{ role_validation: cfg.role_validation }} fields={[{ key: 'role_validation', label: 'Rôle validateur des fiches de course', required: true, options: cfg.roles.map(r => [r.code, `${r.code} — ${r.libelle}`]) }]} note="Le rôle enregistré s’applique à la validation avant départ dans cette société. Aucun changement ne sera appliqué avant votre enregistrement." save={async body => { await bridge.api(`/transport/config?societe_id=${state.companyId}`, { method: 'POST', body }); onSaved(); }} />; }
  if (kind === 'truck') return <TruckEditor {...props} suppliers={result.data as Party[]} />;
  const engine = kind === 'engine', driver = kind === 'driver';
  const fields: FormField[] = engine ? [{ key: 'nom', label: 'Nom de l’engin', required: true }, { key: 'categorie', label: 'Catégorie' }, { key: 'immatriculation', label: 'Immatriculation / numéro de série' }, { key: 'tarif_mensuel_usd', label: 'Tarif mensuel USD', type: 'number', min: 0, required: true }, { key: 'tarif_heure_supp_usd', label: 'Heure supplémentaire USD', type: 'number', min: 0, required: true }, { key: 'consommation_l_heure', label: 'Consommation (litres par heure)', type: 'number', min: 0 }] : driver ? [{ key: 'nom', label: 'Nom complet du chauffeur', required: true }, { key: 'telephone', label: 'Téléphone' }, { key: 'numero_permis', label: 'Numéro du permis' }] : [{ key: 'libelle', label: 'Libellé de la caisse', required: true }, { key: 'compte_comptable', label: 'Compte comptable 57x (vide = automatique)' }];
  return <ResourceEditor bridge={bridge} title={engine ? 'Nouvel engin' : driver ? 'Nouveau chauffeur' : 'Nouvelle caisse'} onClose={onClose} fields={fields} initial={Object.fromEntries(fields.map(f => [f.key, engine && f.key.startsWith('tarif_') ? '0' : '']))} note={driver ? 'Un tiers personnel sera créé pour le suivi des avances à justifier.' : engine ? 'Les tarifs alimentent les relevés mensuels. La consommation sert au suivi du carburant.' : 'Le sous-compte 57x est créé automatiquement si vous ne renseignez pas de compte. Liez ensuite la caisse au point de vente.'} save={async v => { const name = (v.nom || v.libelle || '').trim(); if (name.length < 2) throw new Error('Renseignez au moins deux caractères.'); const key = driver || engine ? 'nom' : 'libelle'; if ((result.data as Record<string, string>[]).some(r => normalize(r[key] || '') === normalize(name))) throw new Error('Cette fiche existe déjà dans la société. Consultez la liste avant de la recréer.'); const body: Record<string, string | number | null> = Object.fromEntries(Object.entries(v).map(([k, value]) => [k, value.trim() || null])); if (engine) { body.tarif_mensuel_usd = Number(v.tarif_mensuel_usd); body.tarif_heure_supp_usd = Number(v.tarif_heure_supp_usd); body.consommation_l_heure = v.consommation_l_heure ? Number(v.consommation_l_heure) : null; } await bridge.api(`${endpoint[kind]}?societe_id=${state.companyId}`, { method: 'POST', body }); onSaved(); }} />;
}
function TruckEditor({ suppliers, ...props }: EditorProps & { suppliers: Party[] }) {
  const subcontracted = (v: Record<string, string>) => v.type === 'sous_traite';
  return <ResourceEditor bridge={props.bridge} title="Nouveau camion" onClose={props.onClose} initial={{ immatriculation: '', marque: '', capacite_tonnes: '30', consommation_l_100km: '', type: 'propre', proprietaire_tiers_id: '', remuneration_mode: 'forfait', remuneration_valeur: '' }} fields={[{ key: 'immatriculation', label: 'Immatriculation', required: true }, { key: 'marque', label: 'Marque' }, { key: 'capacite_tonnes', label: 'Capacité (tonnes)', type: 'number', min: 0, required: true }, { key: 'consommation_l_100km', label: 'Consommation (litres / 100 km)', type: 'number', min: 0 }, { key: 'type', label: 'Type de camion', options: [['propre', 'Flotte propre'], ['sous_traite', 'Sous-traité']] }, { key: 'proprietaire_tiers_id', label: 'Propriétaire fournisseur', required: true, visible: subcontracted, options: [['', 'Sélectionner un fournisseur'], ...suppliers.filter(p => p.actif).map(p => [p.id, partyLabel(p)] as [string, string])] }, { key: 'remuneration_mode', label: 'Rémunération du propriétaire', visible: subcontracted, options: [['forfait', 'Forfait par voyage USD'], ['pourcentage', 'Pourcentage du prix client']] }, { key: 'remuneration_valeur', label: 'Valeur de la rémunération', visible: subcontracted, type: 'number', min: 0, required: true }]} note="Pour un camion sous-traité, le circuit existant crée la dette envers le propriétaire lorsque la course est livrée." save={async v => { const st = subcontracted(v); if (v.immatriculation.trim().length < 2) throw new Error('Renseignez l’immatriculation.'); if (st && !suppliers.some(p => p.id === v.proprietaire_tiers_id && p.actif)) throw new Error('Sélectionnez un fournisseur disponible.'); if (st && v.remuneration_mode === 'pourcentage' && Number(v.remuneration_valeur) > 100) throw new Error('Le pourcentage ne peut pas dépasser 100 %.'); await props.bridge.api(`/transport/camions?societe_id=${props.state.companyId}`, { method: 'POST', body: { immatriculation: v.immatriculation.trim(), marque: v.marque.trim() || null, capacite_tonnes: Number(v.capacite_tonnes), consommation_l_100km: v.consommation_l_100km ? Number(v.consommation_l_100km) : null, type: v.type, proprietaire_tiers_id: st ? v.proprietaire_tiers_id : null, remuneration_mode: st ? v.remuneration_mode : null, remuneration_valeur: st ? Number(v.remuneration_valeur) : null } }); props.onSaved(); }} />;
}
