'use client';
import { useCallback } from 'react';
import { Dialog, ErrorNotice, ReportPreview, dateTime, useResource, type Report, type ScreenProps } from './shared';
interface CashReceipt { numero: string; sens: string; societe: string; caisse: string; date: string; nature: string; tiers: string; caissier: string; reference: string | null; legs: { montant: number; devise: string; billetage?: Record<string, number> }[]; lien?: { type: string; requisition?: string; objet?: string; ordre?: string; transfert?: string } }
interface OrderReceipt { bon_numero: string; ordre_numero: string; societe: string; date: string; beneficiaire: string; mode: string; moyen: string; reference_paiement: string; motif: string; montant: number; devise: string; montant_usd: number; executant: string }
export function MoneyReceipt({ movementId, orderId, bonNumber, onClose, ...props }: ScreenProps & { movementId?: string; orderId?: string; bonNumber?: string; onClose: () => void }) {
  const { bridge } = props;
  const load = useCallback(async (): Promise<Report> => { if (movementId) { const d = await bridge.api<CashReceipt>(`/caisse/mouvement/${movementId}/bon`); const rows: (string | number)[][] = [['Société', d.societe], ['Caisse', d.caisse], ['Date', dateTime(d.date)], ['Nature', d.nature], [d.sens === 'entree' ? 'Provenance' : 'Bénéficiaire', d.tiers || ''], ['Caissier', d.caissier || '']]; if (d.lien?.requisition) rows.push(['Réquisition', `${d.lien.requisition} · ${d.lien.objet || ''}`]); if (d.lien?.ordre) rows.push(['Ordre', d.lien.ordre]); if (d.lien?.transfert) rows.push(['Transfert', d.lien.transfert]); if (d.reference) rows.push(['Référence', d.reference]); for (const l of d.legs) { rows.push([`Montant ${l.devise}`, l.montant]); if (l.billetage) for (const [denomination, count] of Object.entries(l.billetage)) rows.push([`Billets ${denomination} ${l.devise}`, count]); } return { title: `${d.sens === 'entree' ? 'Bon d’entrée' : 'Bon de sortie'} de caisse ${d.numero}`, subtitle: `${d.societe} · ${d.caisse}`, columns: ['Rubrique', 'Valeur'], rows, note: `Signatures : ${d.sens === 'entree' ? 'Remettant' : 'Bénéficiaire'} ____________________    Caissier ____________________` }; }
    const d = await bridge.api<OrderReceipt>(`/ordres-depense/${orderId}/bon-sortie${bonNumber ? `?bon_numero=${encodeURIComponent(bonNumber)}` : ''}`); return { title: `${d.mode === 'banque' ? 'Ordre de paiement / chèque' : 'Bon de sortie'} ${d.bon_numero}`, subtitle: d.societe, columns: ['Rubrique', 'Valeur'], rows: [['Ordre de dépense', d.ordre_numero], ['Date', dateTime(d.date)], ['Bénéficiaire', d.beneficiaire || ''], ['Moyen', d.moyen || ''], ['Référence OP / chèque', d.reference_paiement || ''], ['Motif', d.motif || ''], [`Montant ${d.devise}`, d.montant], ['Contre-valeur USD', d.montant_usd], ['Exécutant', d.executant || '']], note: 'Signatures : Bénéficiaire ____________________    Exécutant ____________________' };
  }, [bridge, movementId, orderId, bonNumber]);
  const result = useResource(load);
  return result.data && !result.busy && !result.error ? <ReportPreview {...props} report={result.data} onClose={onClose} /> : <Dialog bridge={bridge} title="Pièce de trésorerie" onClose={onClose}><ErrorNotice error={result.error} />{result.busy ? <p>Préparation de la pièce…</p> : <button className="btn" onClick={result.refresh}>Réessayer</button>}</Dialog>;
}
