'use client';
import { ScreenTitle } from './screen-presentation';
import { useCallback, useState } from 'react';
import { ErrorNotice, ReportPreview, number, useResource, type ScreenProps } from './shared';
export function OperationsDashboard({ bridge, state }: ScreenProps) {
  const load = useCallback(() => bridge.api<Record<string, number>>(`/dashboard?societe_id=${state.companyId}`), [bridge, state.companyId]), result = useResource(load, 60000), [preview, setPreview] = useState(false);
  const available = !result.busy && !result.error && result.data;
  const indicators = [['Réquisitions soumises', 'requisitions_soumises', 'En attente de validation'], ['Ordres à valider', 'ordres_a_valider', 'Sorties de fonds'], ['Avances en cours', 'avances_en_cours', available ? `${number(result.data?.avances_montant_usd)} USD` : 'Montant indisponible'], ['Avances en retard', 'avances_en_retard', 'Justification attendue'], ['Bénéficiaires bloqués', 'beneficiaires_bloques', 'Selon les règles de gestion existantes']];
  return <><div className="audit-head"><div><ScreenTitle>Suivi des opérations</ScreenTitle><p className="muted">Société active · actualisation chaque minute lorsque la page est visible.</p></div><div className="audit-actions"><button className="btn" disabled={result.busy} onClick={result.refresh}><i className="ti ti-refresh" aria-hidden="true" /> Actualiser</button><button className="btn" disabled={!available} onClick={() => setPreview(true)}>Rapport PDF / Excel</button></div></div><ErrorNotice error={result.error} />{result.busy && <p role="status">Actualisation des indicateurs…</p>}<div className="kpi-row">{indicators.map(([label, key, sub]) => <article className="kpi-card" key={key}><div className="kpi-label">{label}</div><div className="kpi-val">{available ? number(result.data?.[key]) : '—'}</div><div className="kpi-sub">{sub}</div></article>)}</div><div className="business-toolbar">{[['nouvelle-req', 'Nouvelle réquisition'], ['approbation', 'Centre d’approbation'], ['avances', 'Avances'], ['pilotage', 'Suivi des tâches']].filter(([view]) => state.groups.some(g => g.items.some(i => i.view === view))).map(([view, label]) => <button className="btn" key={view} onClick={() => bridge.navigate(view)}>{label}</button>)}</div>{preview && available && <ReportPreview bridge={bridge} state={state} onClose={() => setPreview(false)} report={{ title: 'Suivi des opérations', subtitle: 'Situation de la société active au moment de la consultation', columns: ['Indicateur', 'Nombre', 'Précision'], rows: indicators.map(([label, key, sub]) => [label, result.data![key], sub]), note: 'Ces indicateurs de suivi ne remplacent pas les états comptables.' }} />}</>;
}
