'use client';
import { useEffect, useId, useRef, useState, type ReactNode } from 'react';
import { Field } from './field';
import { Dialog, ErrorNotice, message, type ScreenProps } from './shared';
import type { FormField } from './resource-editor';
export type Values = Record<string, string>;
export interface LineSection { key: string; title: string; fields: FormField[]; initial: Values; minimum?: number; onChange?: (row: Values, key: string, value: string) => Values }
export function Inputs({ fields, values, change }: { fields: FormField[]; values: Values; change: (key: string, value: string) => void }) {
  return <div className="business-form-grid">{fields.filter(f => !f.visible || f.visible(values)).map(f => f.options ? <label className="business-field" key={f.key}>{f.label}<select className="form-select" required={f.required} value={values[f.key] ?? ''} onChange={e => change(f.key, e.target.value)}>{f.options.map(([v, label]) => <option key={v} value={v}>{label}</option>)}</select></label> : f.type === 'textarea' ? <label className="business-field" key={f.key}>{f.label}<textarea className="form-input" required={f.required} value={values[f.key] ?? ''} onChange={e => change(f.key, e.target.value)} /></label> : <Field key={f.key} label={f.label} type={f.type || 'text'} required={f.required} min={f.min} max={f.max} step={f.type === 'number' ? 'any' : undefined} value={values[f.key] ?? ''} onChange={v => change(f.key, v)} />)}</div>;
}
export function OperationForm({ bridge, title, initial = {}, fields = [], sections = [], initialRows = {}, note, extra, summary, onChange, externalSelection, onClose, save, submitLabel = 'Enregistrer' }: Pick<ScreenProps, 'bridge'> & { title: string; initial?: Values; fields?: FormField[]; sections?: LineSection[]; initialRows?: Record<string, Values[]>; note?: ReactNode; extra?: ReactNode; summary?: (v: Values, rows: Record<string, Values[]>) => ReactNode; onChange?: (v: Values, key: string, value: string) => Values; externalSelection?: { key: string; value: string }; onClose: () => void; save: (v: Values, rows: Record<string, Values[]>) => Promise<void>; submitLabel?: string }) {
  const id = useId(), [values, setValues] = useState(initial), [rows, setRows] = useState<Record<string, Values[]>>(() => Object.fromEntries(sections.map(s => [s.key, initialRows[s.key] || Array.from({ length: s.minimum || 0 }, () => ({ ...s.initial }))]))), [busy, setBusy] = useState(false), [uncertain, setUncertain] = useState(false), [error, setError] = useState(''), pending = useRef(false);
  useEffect(() => { if (externalSelection) setValues(v => ({ ...v, [externalSelection.key]: externalSelection.value })); }, [externalSelection?.key, externalSelection?.value]);
  return <Dialog bridge={bridge} title={title} busy={busy} onClose={onClose} footer={close => <><button className="btn" disabled={busy} onClick={close}><i className="ti ti-x" aria-hidden="true" /> Annuler</button><button className="btn btn-primary" type="submit" form={id} disabled={busy || uncertain}>{busy ? 'Enregistrement…' : submitLabel}</button></>}><form id={id} onSubmit={async e => { e.preventDefault(); if (pending.current || uncertain) return; pending.current = true; setBusy(true); setError(''); try { await save(values, rows); } catch (cause) { const unknown = !!(cause as { uncertain?: boolean }).uncertain || ((cause as { status?: number }).status || 0) >= 500; setUncertain(unknown); setError(message(cause) + (unknown ? ' Fermez et vérifiez le résultat avant toute nouvelle tentative.' : '')); } finally { pending.current = false; setBusy(false); } }}><fieldset className="business-fieldset" disabled={busy || uncertain}>{note && <div className="banner">{note}</div>}<Inputs fields={fields} values={values} change={(key, value) => setValues(v => onChange ? onChange(v, key, value) : ({ ...v, [key]: value }))} />{extra}{sections.map(section => <section key={section.key} aria-label={section.title}><h3>{section.title}</h3>{rows[section.key].map((row, i) => <fieldset key={i} className="card"><legend>{section.title} · {i + 1}</legend><Inputs fields={section.fields} values={row} change={(key, value) => setRows(all => ({ ...all, [section.key]: all[section.key].map((r, j) => j === i ? section.onChange ? section.onChange(r, key, value) : { ...r, [key]: value } : r) }))} /><button className="btn" type="button" disabled={rows[section.key].length <= (section.minimum || 0)} onClick={() => setRows(all => ({ ...all, [section.key]: all[section.key].filter((_, j) => j !== i) }))}>Retirer {section.title.toLowerCase()} {i + 1}</button></fieldset>)}<button className="btn" type="button" onClick={() => setRows(all => ({ ...all, [section.key]: [...all[section.key], { ...section.initial }] }))}>Ajouter · {section.title}</button></section>)}{summary?.(values, rows)}<ErrorNotice error={error} /></fieldset></form></Dialog>;
}
