'use client';
import { useId, useRef, useState, type ReactNode } from 'react';
import { Field } from './field';
import { Dialog, ErrorNotice, message, type ScreenProps } from './shared';
export interface FormField { key: string; label: string; type?: string; required?: boolean; min?: number | string; max?: number | string; options?: [string, string][]; visible?: (v: Record<string, string>) => boolean }
export function ResourceEditor({ bridge, title, initial, fields, save, onClose, note, submitLabel = 'Enregistrer' }: Pick<ScreenProps, 'bridge'> & { title: string; initial: Record<string, string>; fields: FormField[]; save: (v: Record<string, string>) => Promise<void>; onClose: () => void; note?: ReactNode; submitLabel?: string }) {
  const id = useId(), [values, setValues] = useState(initial), [busy, setBusy] = useState(false), [error, setError] = useState(''), [uncertain, setUncertain] = useState(false), pending = useRef(false);
  return <Dialog bridge={bridge} title={title} busy={busy} onClose={onClose} footer={close => <><button className="btn" disabled={busy} onClick={close}><i className="ti ti-x" aria-hidden="true" /> Annuler</button><button type="submit" form={id} className="btn btn-primary" disabled={busy || uncertain}>{busy ? 'Enregistrement…' : submitLabel}</button></>}><form id={id} onSubmit={async e => { e.preventDefault(); if (pending.current || uncertain) return; pending.current = true; setBusy(true); setError(''); try { await save(values); } catch (cause) { const status = (cause as { status?: number }).status; const unknown = !(cause instanceof Error) || (!!status && status >= 500) || (cause instanceof TypeError) || !!(cause as { uncertain?: boolean }).uncertain; setUncertain(unknown); setError(message(cause) + (unknown ? ' Fermez et actualisez la liste pour vérifier le résultat avant de recommencer.' : '')); } finally { setBusy(false); pending.current = false; } }}><fieldset disabled={busy || uncertain} className="business-fieldset"><div className="business-form-grid">{fields.filter(f => !f.visible || f.visible(values)).map(f => f.options ? <label className="business-field" key={f.key}>{f.label}<select className="form-select" required={f.required} value={values[f.key] || ''} onChange={e => setValues(v => ({ ...v, [f.key]: e.target.value }))}>{f.options.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label> : <Field key={f.key} label={f.label} type={f.type || 'text'} required={f.required} min={f.min} max={f.max} step={f.type === 'number' ? 'any' : undefined} value={values[f.key] || ''} onChange={value => setValues(v => ({ ...v, [f.key]: value }))} />)}</div>{note && <div className="banner">{note}</div>}<ErrorNotice error={error} /></fieldset></form></Dialog>;
}
