'use client';
import { useCallback, useRef, useState } from 'react';
import { Field } from './field';
import { Dialog, ErrorNotice, ReportPreview, message, normalize, number, type ScreenProps, useResource } from './shared';

interface Room { id: string; numero: string; categorie: string; tarif_nuit_usd: number; capacite: number; note: string; actif: boolean; etat: string; sejour?: { client: string; date_depart_prevue: string } }
const statuses: Record<string, string> = { libre: 'Libre', occupee: 'Occupée', sale: 'Sale', nettoyage: 'Nettoyage', maintenance: 'Maintenance' };
const actions: Record<string, [string, string][]> = { sale: [['nettoyage', 'Lancer nettoyage'], ['libre', 'Marquer propre']], nettoyage: [['libre', 'Marquer propre']], libre: [['maintenance', 'Maintenance']], maintenance: [['libre', 'Remettre en service']] };
export function Rooms({ bridge, state }: ScreenProps) {
  const load = useCallback(() => bridge.api<Room[]>(`/hotel/chambres?societe_id=${state.companyId}`), [bridge, state.companyId]);
  const result = useResource(load);
  const [editing, setEditing] = useState<Room | 'new' | null>(null), [search, setSearch] = useState(''), [status, setStatus] = useState(''), [inactive, setInactive] = useState(false), [preview, setPreview] = useState(false), [saving, setSaving] = useState(false), [error, setError] = useState(''), [success, setSuccess] = useState('');
  const pending = useRef(false);
  const rows = (result.data || []).filter(r => (inactive || r.actif) && (!status || r.etat === status) && normalize([r.numero, r.categorie, r.note, statuses[r.etat], r.sejour?.client].join(' ')).includes(normalize(search)));
  const changeStatus = async (room: Room, etat: string) => {
    if (pending.current) return; pending.current = true; const release = bridge.holdNavigation(); setSaving(true); setError(''); setSuccess('');
    try { await bridge.api(`/hotel/chambres/${room.id}?societe_id=${state.companyId}`, { method: 'PATCH', body: { etat } }); setSuccess(`Chambre ${room.numero} : ${statuses[etat]}.`); result.refresh(); } catch (e) { setError(message(e)); } finally { release(); pending.current = false; setSaving(false); }
  };
  return <>
    <div className="audit-head"><div><h2>Chambres & ménage</h2><p className="muted">{result.data?.filter(r => r.actif).length ?? '—'} chambres actives · {state.companies.find(c => c.id === state.companyId)?.nom}</p></div><div className="audit-actions"><button className="btn" disabled={saving || result.busy} onClick={result.refresh}>Actualiser</button><button className="btn" disabled={!result.data || result.busy || !!result.error} onClick={() => setPreview(true)}>Rapport PDF / Excel</button><button className="btn btn-primary" disabled={saving || result.busy || !!result.error} onClick={() => setEditing('new')}>Nouvelle chambre</button></div></div>
    <ErrorNotice error={result.error || error} />{success && <p className="business-success" role="status">{success}</p>}{result.busy && <p role="status">Actualisation des chambres…</p>}
    <div className="business-toolbar"><label>Rechercher une chambre<input className="form-input" type="search" placeholder="Numéro, catégorie, client…" value={search} onChange={e => setSearch(e.target.value)} /></label><label>État<select className="form-select" value={status} onChange={e => setStatus(e.target.value)}><option value="">Tous les états</option>{Object.entries(statuses).map(([key, label]) => <option value={key} key={key}>{label}</option>)}</select></label><label className="business-check"><input type="checkbox" checked={inactive} onChange={e => setInactive(e.target.checked)} /> Inclure les chambres inactives</label><button className="btn" onClick={() => { setSearch(''); setStatus(''); setInactive(false); }}>Effacer les filtres</button></div>
    <div className="caisse-cards">{rows.map(room => <article className="caisse-card" key={room.id}><div className="cc-top"><b>Ch. {room.numero}</b>{room.categorie && <span className="tag">{room.categorie}</span>}<span className={`pill ${room.etat === 'libre' ? 'st-payee' : room.etat === 'occupee' ? 'st-envoye' : 'st-due'}`}>{statuses[room.etat] || room.etat}</span>{!room.actif && <span className="tag">Inactive</span>}<button className="btn btn-sm" disabled={saving || result.busy || !!result.error} aria-label={`Modifier la chambre ${room.numero}`} onClick={() => setEditing(room)}>Modifier</button></div><p className="muted">{number(room.tarif_nuit_usd)} USD / nuit · {room.capacite} personnes</p>{room.note && <p>{room.note}</p>}{room.sejour && <p className="muted">{room.sejour.client} — départ prévu {room.sejour.date_depart_prevue}</p>}<div className="business-toolbar">{room.actif && (actions[room.etat] || []).map(([next, label]) => <button className="btn btn-sm" key={next} disabled={saving || result.busy || !!result.error} onClick={() => changeStatus(room, next)} aria-label={`${label} · chambre ${room.numero}`}>{label}</button>)}</div></article>)}{result.data && !rows.length && <p className="empty">Aucune chambre pour cette sélection.</p>}</div>
    {editing && <RoomEditor bridge={bridge} state={state} key={editing === 'new' ? 'new' : editing.id} room={editing === 'new' ? null : editing} rooms={result.data || []} onClose={() => setEditing(null)} onSaved={() => { setEditing(null); setSuccess('Chambre enregistrée.'); result.refresh(); }} />}
    {preview && <ReportPreview bridge={bridge} state={state} onClose={() => setPreview(false)} report={{ title: 'État des chambres', subtitle: `Recherche : ${search || 'aucune'} · ${status ? statuses[status] : 'tous les états'} · ${inactive ? 'actives et inactives' : 'chambres actives'} · ${rows.length} chambres`, columns: ['Numéro', 'Catégorie', 'État', 'Active', 'Tarif / nuit USD', 'Capacité', 'Client en séjour', 'Départ prévu', 'Note'], rows: rows.map(r => [r.numero, r.categorie || '', statuses[r.etat] || r.etat, r.actif ? 'Oui' : 'Non', r.tarif_nuit_usd, r.capacite, r.sejour?.client || '', r.sejour?.date_depart_prevue || '', r.note || '']), note: 'Situation enregistrée dans le logiciel. L’occupation se met à jour par les arrivées et départs en réception.' }} />}
  </>;
}
function RoomEditor({ bridge, state, room, rooms, onClose, onSaved }: ScreenProps & { room: Room | null; rooms: Room[]; onClose: () => void; onSaved: () => void }) {
  const [values, setValues] = useState({ numero: room?.numero || '', categorie: room?.categorie || '', tarif: String(room?.tarif_nuit_usd ?? 0), capacite: String(room?.capacite ?? 2), note: room?.note || '' });
  const [active, setActive] = useState(room?.actif ?? true), [busy, setBusy] = useState(false), [error, setError] = useState('');
  const pending = useRef(false);
  const update = (key: keyof typeof values, value: string) => setValues(previous => ({ ...previous, [key]: value }));
  return <Dialog bridge={bridge} title={room ? `Modifier la chambre ${room.numero}` : 'Nouvelle chambre'} busy={busy} onClose={onClose} footer={close => <><button className="btn" disabled={busy} onClick={close}>Annuler</button><button className="btn btn-primary" type="submit" form="room-form" disabled={busy}>{busy ? 'Enregistrement…' : room ? 'Enregistrer' : 'Créer'}</button></>}>
    <form id="room-form" onSubmit={async e => { e.preventDefault(); if (pending.current) return; setError(''); const numero = values.numero.trim(); if (active && rooms.some(r => r.id !== room?.id && r.actif && normalize(r.numero) === normalize(numero))) { setError('Une chambre active porte déjà ce numéro dans cette société.'); return; } pending.current = true; setBusy(true); try { const body = { numero, categorie: values.categorie.trim(), tarif_nuit_usd: Number(values.tarif), capacite: Number(values.capacite), note: values.note.trim(), ...(room ? { actif: active } : {}) }; await bridge.api(room ? `/hotel/chambres/${room.id}?societe_id=${state.companyId}` : `/hotel/chambres?societe_id=${state.companyId}`, { method: room ? 'PATCH' : 'POST', body }); onSaved(); } catch (e) { setError(message(e)); } finally { pending.current = false; setBusy(false); } }}>
      <fieldset disabled={busy} className="business-fieldset"><div className="business-form-grid"><Field label="Numéro" required value={values.numero} onChange={v => update('numero', v)} /><Field label="Catégorie" value={values.categorie} onChange={v => update('categorie', v)} /><Field label="Tarif par nuit (USD)" required type="number" min={0} step="any" value={values.tarif} onChange={v => update('tarif', v)} /><Field label="Capacité (personnes)" required type="number" min={1} step={1} value={values.capacite} onChange={v => update('capacite', v)} /></div><Field label="Note" value={values.note} onChange={v => update('note', v)} />{room && <label className="business-check"><input type="checkbox" checked={active} onChange={e => setActive(e.target.checked)} /> Chambre active</label>}<ErrorNotice error={error} /></fieldset>
    </form>
  </Dialog>;
}
