'use client';
import { useCallback, useRef, useState } from 'react';
import { filterTasks, levels, validateRules, type Task, type TaskFilters } from '../../lib/task-filters';
import { Dialog, ErrorNotice, Pages, ReportPreview, dateTime, exportReport, message, useResource, type ScreenProps, type Report } from './shared';

interface TaskData { actualise_a: string; portee: string; compteurs: Record<string, number>; taches: Task[]; utilisateurs: { id: string; nom: string }[] }
const emptyFilters: TaskFilters = { q: '', module: '', user: '', niveau: '' };
const age = (hours: number | null) => hours === null ? 'Date indisponible' : hours < 24 ? `${Math.floor(hours)} h` : `${Math.floor(hours / 24)} j ${Math.floor(hours % 24)} h`;
export function Tasks({ bridge, state }: ScreenProps) {
  const dfi = !!state.companies.find(c => c.id === state.companyId)?.roles.includes('DFI');
  const [scope, setScope] = useState(dfi ? 'equipe' : 'moi');
  return <TaskScope key={scope} bridge={bridge} state={state} scope={scope} dfi={dfi} changeScope={setScope} />;
}
function TaskScope({ bridge, state, scope, dfi, changeScope }: ScreenProps & { scope: string; dfi: boolean; changeScope: (scope: string) => void }) {
  const load = useCallback(() => bridge.api<TaskData>(`/pilotage/taches?societe_id=${state.companyId}&portee=${scope}`), [bridge, state.companyId, scope]);
  const { data, error, busy, refresh } = useResource(load, 30000);
  const [filters, setFilters] = useState<TaskFilters>(emptyFilters), [page, setPage] = useState(1), [task, setTask] = useState<Task | null>(null), [policy, setPolicy] = useState(false), [preview, setPreview] = useState<Report | null>(null), [exportError, setExportError] = useState(''), [exporting, setExporting] = useState(false);
  const update = (key: keyof TaskFilters, value: string) => { setFilters(previous => ({ ...previous, [key]: value })); setPage(1); };
  const rows = filterTasks(data?.taches || [], filters), pages = Math.max(1, Math.ceil(rows.length / 50)), current = Math.min(page, pages);
  const summaries = data?.utilisateurs.map(user => { const tasks = rows.filter(t => t.responsables.some(u => u.id === user.id)); return { ...user, total: tasks.length, alerts: tasks.filter(t => ['escalade', 'relance'].includes(t.niveau)).length }; }).filter(u => u.total).sort((a, b) => b.alerts - a.alerts || b.total - a.total) || [];
  const report = (excel: boolean): Report => ({
    title: 'Suivi des tâches', subtitle: `Situation au ${dateTime(data?.actualise_a)} · ${scope === 'equipe' ? 'Supervision DFI' : 'Mes tâches'} · ${rows.length} actions. Filtres : ${filters.module || 'tous modules'} ; ${levels[filters.niveau] || 'toutes priorités'} ; ${data?.utilisateurs.find(u => u.id === filters.user)?.nom || 'tous utilisateurs'} ; recherche : ${filters.q || 'aucune'}.`,
    columns: excel ? ['Priorité', 'Module', 'Dossier', 'Action attendue', 'Utilisateurs habilités', 'Affectation / rôles', 'Depuis', 'Base de la date', 'Ancienneté (h)', 'Échéance métier', 'Relance interne', 'Remontée DFI', 'Étape dépendante', 'Observation'] : ['Priorité', 'Dossier / module', 'Action attendue', 'Intervenants habilités', 'Depuis / ancienneté', 'Suite attendue'],
    rows: rows.map(r => excel ? [levels[r.niveau], r.module, r.reference, r.action, r.responsables.map(u => u.nom).join(', '), r.affectation === 'nominative' ? 'Nominative' : r.roles.join(' / '), dateTime(r.debut), r.base_date, r.age_heures ?? '', r.echeance ? dateTime(r.echeance) : '', r.relance_at ? dateTime(r.relance_at) : '', r.escalade_at ? dateTime(r.escalade_at) : '', r.impact, [r.blocage, r.detail].filter(Boolean).join(' · ')] : [levels[r.niveau], r.reference + ' · ' + r.module, r.action + (r.blocage ? ' — ' + r.blocage : ''), r.responsables.map(u => u.nom).join(', ') || 'Affectation à vérifier', dateTime(r.debut) + ' · ' + age(r.age_heures), r.impact]),
    note: 'Les files par utilisateur peuvent se recouper. Ce suivi des tâches enregistrées ne constitue pas une évaluation individuelle. Les opérations non saisies ne sont pas évaluées ici.',
  });
  const excel = async () => { if (exporting || !data) return; const release = bridge.holdNavigation(); setExporting(true); setExportError(''); try { await exportReport(bridge, state.companyId, report(true), 'xlsx'); } catch (e) { setExportError(message(e)); } finally { release(); setExporting(false); } };
  return <>
    <div className="pilot-hero"><div><span className="pilot-kicker">Pilotage opérationnel</span><h2>Voir ce qui attend. Débloquer ce qui suit.</h2><p>Les dossiers enregistrés, les personnes habilitées et les étapes à terminer.</p></div><div className="pilot-live" role="status">{busy ? 'Actualisation…' : error ? 'Données non actualisées' : 'Mis à jour à ' + new Date(data?.actualise_a || '').toLocaleTimeString('fr-FR')}</div></div>
    <div className="pilot-toolbar"><label>Périmètre<select className="form-select" value={scope} disabled={exporting} onChange={e => changeScope(e.target.value)}><option value="moi">Mes tâches</option>{dfi && <option value="equipe">Équipe · supervision DFI</option>}</select></label><button className="btn" disabled={busy} onClick={refresh}><i className="ti ti-refresh" aria-hidden="true" /> Actualiser</button>{dfi && <button className="btn" onClick={() => setPolicy(true)}>Régler les délais</button>}<button className="btn" disabled={!data || !!error || busy || exporting} onClick={() => setPreview(report(false))}>Rapport PDF / imprimer</button><button className="btn" disabled={!data || !!error || busy || exporting} onClick={excel}>{exporting ? 'Export…' : 'Excel'}</button></div>
    <ErrorNotice error={error ? `Actualisation impossible : ${error} Les données précédentes restent affichées.` : exportError} />
    {data && <>
      <div className="pilot-kpis">{[['', 'total', 'Actions en attente', `${data.compteurs.dossiers} dossiers distincts`], ['escalade', 'escalade', 'Remontées DFI', 'Délai ou échéance dépassé'], ['relance', 'relance', 'Relances internes', 'À traiter en priorité'], ['a_attribuer', 'a_attribuer', 'À clarifier', 'Affectation ou circuit à vérifier']].map(([level, key, label, sub]) => <button key={key} className={`pilot-kpi ${level}`} aria-pressed={filters.niveau === level} onClick={() => update('niveau', level)}><strong>{data.compteurs[key]}</strong><span>{label}</span><small>{sub}</small></button>)}</div>
      <div className="pilot-filters"><label>Recherche<input className="form-input" type="search" placeholder="Dossier, tâche, responsable…" value={filters.q} onChange={e => update('q', e.target.value)} /></label><label>Module<select className="form-select" value={filters.module} onChange={e => update('module', e.target.value)}><option value="">Tous les modules</option>{Array.from(new Set(data.taches.map(t => t.module))).sort().map(m => <option key={m}>{m}</option>)}{filters.module && !data.taches.some(t => t.module === filters.module) && <option>{filters.module}</option>}</select></label><label>Utilisateur habilité<select className="form-select" value={filters.user} onChange={e => update('user', e.target.value)}><option value="">Tous les utilisateurs</option>{[...data.utilisateurs].sort((a, b) => a.nom.localeCompare(b.nom)).map(u => <option key={u.id} value={u.id}>{u.nom}</option>)}</select></label><label>Priorité<select className="form-select" value={filters.niveau} onChange={e => update('niveau', e.target.value)}><option value="">Toutes les priorités</option>{Object.entries(levels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label><button className="btn" onClick={() => { setFilters(emptyFilters); setPage(1); }}>Effacer les filtres</button></div>
      {scope === 'equipe' && <details className="pilot-summary"><summary>Répartition par utilisateur habilité · {summaries.length} personnes</summary><p className="muted">Les files peuvent se recouper : ne pas additionner ces nombres comme des dossiers uniques.</p><div className="pilot-people">{summaries.map(u => <button key={u.id} className="btn" onClick={() => update('user', u.id)}><b>{u.nom}</b><span>{u.total} actions · {u.alerts} alertes</span></button>)}{!summaries.length && <p>Aucune affectation active dans ce filtre.</p>}</div></details>}
      <div className="pilot-count"><b>{rows.length} actions dans cette sélection</b></div><div className="pilot-table"><table><thead><tr><th>Priorité / ancienneté</th><th>Action attendue</th><th>Qui peut intervenir ?</th><th>Ce qui attend ensuite</th><th>Détail</th></tr></thead><tbody>{rows.slice((current - 1) * 50, current * 50).map(r => <tr key={r.id}><td><span className={`pilot-status ${r.niveau}`}>{levels[r.niveau]}</span><div className="muted">{age(r.age_heures)}</div>{r.echeance_depassee && <small>Échéance métier dépassée</small>}</td><td><b>{r.action}</b><div>{r.reference} · {r.module}</div></td><td>{r.responsables.map(u => u.nom).slice(0, 3).join(', ') || 'Affectation à vérifier'}{r.responsables.length > 3 && ` +${r.responsables.length - 3}`}<div className="muted">{r.affectation === 'nominative' ? 'Responsabilité nominative' : 'Équipe habilitée · ' + r.roles.join(' / ')}</div></td><td>{r.impact}</td><td><button className="btn btn-sm" onClick={() => setTask(r)}>Examiner</button></td></tr>)}{!rows.length && <tr><td colSpan={5} className="pilot-empty">Aucune tâche dans cette sélection. Les opérations non saisies ne sont pas évaluées ici.</td></tr>}</tbody></table></div><Pages page={current} pages={pages} change={setPage} />
    </>}
    <details className="pilot-help"><summary>Comment lire ce suivi ?</summary><p>Une tâche peut attendre une personne nommée ou une équipe habilitée. Sa présence ne prouve pas une faute personnelle : plusieurs validateurs peuvent intervenir sur le même dossier.</p><p>Les délais sont en heures calendaires, nuits et week-ends compris. Une échéance métier dépassée remonte au DFI ; elle reste prioritaire. Lorsqu’une date d’étape manque, la date de création est utilisée et signalée.</p><p>Les relances sont internes à l’ERP, sans courriel ni notification téléphone. Ce suivi s’actualise toutes les 30 secondes lorsque cet écran est visible ; le compteur général s’actualise toutes les 2 minutes.</p><p>Couverture : réquisitions, ordres, avances, transferts, comptabilité, inventaires, réceptions fournisseurs, pointages saisis, demandes d’avance et paie ; courses à valider ou facturer, interventions ouvertes, documents de flotte, arrivées et départs prévus, commandes clients hors groupe à facturer et TVA sauvegardée sans référence de dépôt. Les tâches jamais saisies, congés, déclarations sociales, facturation des engins et certaines étapes intersociétés ne sont pas toutes couvertes. Un tableau vide ne certifie pas la clôture de l’activité.</p></details>
    {task && <Dialog bridge={bridge} title={task.reference} onClose={() => setTask(null)} footer={close => <><button className="btn" onClick={close}>Fermer</button><button className="btn btn-primary" disabled={!state.groups.some(g => g.items.some(i => i.view === task.vue))} onClick={() => { close(); void bridge.openTask(task.vue, task.type, task.document_id).catch(e => setExportError(message(e))); }}>Ouvrir le module concerné</button></>}><div className="pilot-detail"><span className={`pilot-status ${task.niveau}`}>{levels[task.niveau]}</span><h3>{task.action}</h3><p>{task.detail}</p>{task.blocage && <p className="banner">{task.blocage}</p>}<dl>{[
      ['Qui peut intervenir ?', task.responsables.map(u => u.nom).join(', ') || 'Affectation à vérifier'], ['Type de responsabilité', task.affectation === 'nominative' ? 'Personne liée au dossier' : 'Équipe habilitée ; aucune personne désignée exclusivement'], ['Ancienneté calculée depuis', dateTime(task.debut) + ' · ' + task.base_date], ['Relance interne à partir du', task.relance_at ? dateTime(task.relance_at) : 'Délai non configuré ou date indisponible'], ['Remontée au DFI à partir du', task.escalade_at ? dateTime(task.escalade_at) : 'Délai non configuré ou date indisponible'], ['Échéance métier enregistrée', dateTime(task.echeance)], ['Étape dépendante', task.impact],
    ].map(([key, value]) => <div className="business-definition" key={key}><dt>{key}</dt><dd>{value}</dd></div>)}</dl></div></Dialog>}
    {preview && <ReportPreview bridge={bridge} state={state} report={preview} onClose={() => setPreview(null)} />}
    {policy && <Policy bridge={bridge} state={state} onClose={() => setPolicy(false)} onSaved={() => { setPolicy(false); refresh(); }} />}
  </>;
}
interface RulesData { version: string; regles: Record<string, { relance_h: number; escalade_h: number } | null>; types: Record<string, { action: string; module: string }> }
function Policy({ bridge, state, onClose, onSaved }: ScreenProps & { onClose: () => void; onSaved: () => void }) {
  const load = useCallback(() => bridge.api<RulesData>(`/pilotage/delais?societe_id=${state.companyId}`), [bridge, state.companyId]);
  const { data, error, busy, refresh } = useResource(load);
  const [saving, setSaving] = useState(false);
  return <Dialog bridge={bridge} title="Délais de suivi · société active" busy={saving} onClose={onClose} footer={close => <><button className="btn" disabled={saving} onClick={close}><i className="ti ti-x" aria-hidden="true" /> Annuler</button><button className="btn btn-primary" form="policy-form" type="submit" disabled={busy || !data || !!error || saving}>{saving ? 'Enregistrement…' : 'Enregistrer les délais'}</button></>}><ErrorNotice error={error} />{busy ? <p role="status">Chargement des délais…</p> : error ? <button className="btn" onClick={refresh}>Réessayer</button> : data && <PolicyForm key={data.version} bridge={bridge} state={state} data={data} setSaving={setSaving} onSaved={onSaved} />}</Dialog>;
}
function PolicyForm({ bridge, state, data, setSaving, onSaved }: ScreenProps & { data: RulesData; setSaving: (value: boolean) => void; onSaved: () => void }) {
  const [rules, setRules] = useState(() => Object.fromEntries(Object.keys(data.types).map(key => [key, { enabled: !!data.regles[key], relance_h: String(data.regles[key]?.relance_h || 24), escalade_h: String(data.regles[key]?.escalade_h || 48) }])));
  const [error, setError] = useState('');
  const pending = useRef(false);
  return <form id="policy-form" onSubmit={async e => { e.preventDefault(); if (pending.current) return; const regles = Object.fromEntries(Object.entries(rules).map(([key, rule]) => [key, rule.enabled ? { relance_h: Number(rule.relance_h), escalade_h: Number(rule.escalade_h) } : null])); if (!validateRules(regles)) { setError('Relance : au moins 1 h ; remontée DFI après la relance et au plus 8 760 h.'); return; } pending.current = true; setSaving(true); setError(''); try { await bridge.api(`/pilotage/delais?societe_id=${state.companyId}`, { method: 'PUT', body: { version: data.version, regles } }); onSaved(); } catch (e) { setError(message(e)); } finally { pending.current = false; setSaving(false); } }}>
    <p>Les délais sont exprimés en <b>heures calendaires</b> et s’appliquent aussi aux dossiers déjà ouverts. Aucun paiement ni blocage n’est déclenché.</p><p className="banner">Les relances apparaissent dans l’ERP, puis dans la supervision du DFI. Les échéances métier enregistrées restent prioritaires.</p>
    <div className="pilot-policy">{Object.entries(data.types).map(([key, type]) => <div key={key}><label><input type="checkbox" checked={rules[key].enabled} onChange={e => setRules(previous => ({ ...previous, [key]: { ...previous[key], enabled: e.target.checked } }))} /> {type.action}<small>{type.module}</small></label><label>Relance (h)<input className="form-input" type="number" min={1} max={8759} step={1} required disabled={!rules[key].enabled} value={rules[key].relance_h} onChange={e => setRules(previous => ({ ...previous, [key]: { ...previous[key], relance_h: e.target.value } }))} /></label><label>Remontée DFI (h)<input className="form-input" type="number" min={2} max={8760} step={1} required disabled={!rules[key].enabled} value={rules[key].escalade_h} onChange={e => setRules(previous => ({ ...previous, [key]: { ...previous[key], escalade_h: e.target.value } }))} /></label></div>)}</div><ErrorNotice error={error} />
  </form>;
}
