'use client';
import { ScreenTitle } from './screen-presentation';
import { useCallback, useState } from 'react';
import { amount } from '../../lib/operation-data';
import { partyLabel, type Party } from '../../lib/accounting-data';
import { AccountingPartyPicker } from './accounting-party';
import { DataTable } from './data-table';
import { ConfigurationEditor } from './module-configuration';
import { OperationForm, type Values } from './operation-form';
import type { FormField } from './resource-editor';
import { Dialog, ErrorNotice, ReportPreview, number, today, useResource, type Report, type ScreenProps } from './shared';
interface Course { id: string; numero: string; date: string; client: string; client_tiers_id: string; camion: string; camion_type: string; chauffeur: string; origine: string; destination: string; marchandise: string; tonnage_prevu: number; tonnage_livre: number | null; unite: string; prix_unitaire: number; tarif_mode: string; recette_usd: number; marge_usd: number | null; statut: string; deblocable: boolean; commande_origine: string; requisitions: { id: string; numero: string; statut: string }[]; frais_route_usd: number; st_cout_usd: number; st_facture: string; facture: string; incidents: string; km_depart: number | null; heure_depart: string; heure_retour: string; contrat: string; reception_po?: { recu: number; livre: number; manquant: number; valeur_manquants_usd: number; a_confirmer: { id: string; numero: string; date: string; note: string }[] } }
interface Truck { id: string; immatriculation: string; statut: string; actif: boolean; capacite_tonnes: number }
interface Contract { id: string; libelle: string; client_tiers_id: string; statut: string; tarifs: { trajet: string; mode: string; prix: number }[] }
const states = [['', 'Toutes'], ['demande', 'Demandes'], ['brouillon', 'Brouillons'], ['validee', 'Validées'], ['en_cours', 'En route'], ['arrivee', 'Arrivées'], ['receptionnee', 'Réceptionnées'], ['livree', 'À facturer'], ['facturee', 'Facturées'], ['annulee', 'Annulées']];
export function TransportCourses(props: ScreenProps) {
  const [filter, setFilter] = useState(''), [create, setCreate] = useState(false), [settings, setSettings] = useState(false), [action, setAction] = useState<{ course: Course; kind: string } | null>(null), [invoice, setInvoice] = useState(false), [profit, setProfit] = useState(false), [report, setReport] = useState<Report | null>(null), [success, setSuccess] = useState('');
  const load = useCallback(async () => { const q = `societe_id=${props.state.companyId}`; const [courses, config] = await Promise.all([props.bridge.api<Course[]>(`/transport/courses?${q}&statut=${filter}`), props.bridge.api<{ role_validation: string }>(`/transport/config?${q}`)]); return { courses, config }; }, [props.bridge, props.state.companyId, filter]), result = useResource(load);
  const roles = props.state.companies.find(c => c.id === props.state.companyId)?.roles || [], ready = result.data && !result.busy && !result.error;
  const saved = (label = 'Opération enregistrée.') => { setCreate(false); setAction(null); setInvoice(false); setSuccess(label); result.refresh(); void props.bridge.refreshAccountingBadge(); };
  const commands = (c: Course) => <div className="audit-actions"><button className="btn" onClick={() => setReport(courseReport(c))}>Fiche & impression</button>{c.statut === 'demande' && <button className="btn" disabled={!c.deblocable} title={c.deblocable ? '' : 'La confirmation du vendeur est attendue.'} onClick={() => setAction({ course: c, kind: 'prendre-en-charge' })}>Prendre en charge</button>}{!['demande', 'facturee', 'annulee'].includes(c.statut) && <button className="btn" onClick={() => setAction({ course: c, kind: 'lier-requisition' })}>Lier une réquisition</button>}{c.statut === 'brouillon' && roles.includes(result.data!.config.role_validation || 'DFI') && <button className="btn" onClick={() => setAction({ course: c, kind: 'valider' })}><i className="ti ti-check" aria-hidden="true" /> Valider</button>}{c.statut === 'validee' && <button className="btn" onClick={() => setAction({ course: c, kind: 'depart' })}>Départ</button>}{c.statut === 'en_cours' && <button className="btn" onClick={() => setAction({ course: c, kind: 'arrivee' })}>Arrivée</button>}{['en_cours', 'arrivee', 'receptionnee'].includes(c.statut) && <button className="btn" onClick={() => setAction({ course: c, kind: 'retour' })}>Retour & clôture</button>}{c.reception_po?.a_confirmer?.map(r => <button key={r.id} className="btn" onClick={() => setAction({ course: c, kind: `confirm:${r.id}` })}>Confirmer {r.numero}</button>)}{(['brouillon', 'validee'].includes(c.statut) || (['en_cours', 'arrivee'].includes(c.statut) && !(c.reception_po && c.reception_po.recu > 0))) && <button className="btn" onClick={() => setAction({ course: c, kind: 'annuler' })}>{['en_cours', 'arrivee'].includes(c.statut) ? 'Interrompre' : 'Annuler'}</button>}</div>;
  return <><div className="audit-head"><ScreenTitle>Courses de transport</ScreenTitle><div className="audit-actions"><button className="btn" disabled={result.busy} onClick={result.refresh}><i className="ti ti-refresh" aria-hidden="true" /> Actualiser</button><button className="btn" onClick={() => setProfit(true)}>Rentabilité</button><button className="btn" onClick={() => setInvoice(true)}>Facturer les livrées</button>{roles.some(r => ['DFI', 'PRESIDENT', 'ADMIN_SYS'].includes(r)) && <button className="btn" onClick={() => setSettings(true)}>Réglages</button>}<button className="btn btn-primary" onClick={() => setCreate(true)}>Nouvelle course</button></div></div><label className="business-field">Statut<select className="form-select" value={filter} onChange={e => setFilter(e.target.value)}>{states.map(([v, l]) => <option key={v} value={v}>{l}</option>)}</select></label><ErrorNotice error={result.error} />{success && <p role="status" className="business-success">{success}</p>}{result.busy && <p>Lecture des courses…</p>}{ready && <DataTable {...props} title="Fiches de course" subtitle={states.find(s => s[0] === filter)?.[1] || ''} columns={['Numéro', 'Date', 'Client', 'Camion', 'Origine', 'Destination', 'Marchandise', 'Quantité', 'Unité', 'Recette USD', 'Marge USD', 'Statut', 'Commande']} rows={result.data!.courses.map(c => [c.numero, c.date, c.client || '', c.camion || '', c.origine, c.destination, c.marchandise, c.tonnage_livre ?? c.tonnage_prevu, c.unite || 't', c.recette_usd, c.marge_usd ?? 'En cours', c.statut, c.commande_origine || ''])} actions={(_, i) => commands(result.data!.courses[i])} />}{create && <CourseEditor {...props} onClose={() => setCreate(false)} onSaved={saved} />}{action && (action.kind === 'prendre-en-charge' ? <CourseEditor {...props} course={action.course} onClose={() => setAction(null)} onSaved={saved} /> : action.kind === 'lier-requisition' ? <LinkRequest {...props} course={action.course} onClose={() => setAction(null)} onSaved={saved} /> : <CourseAction {...props} {...action} onClose={() => setAction(null)} onSaved={saved} />)}{invoice && <InvoiceCourses {...props} onClose={() => setInvoice(false)} onSaved={saved} />}{profit && <TransportProfit {...props} onClose={() => setProfit(false)} />}{report && <ReportPreview {...props} report={report} onClose={() => setReport(null)} />}{settings && <ConfigurationEditor {...props} kind="transport-settings" onClose={() => setSettings(false)} onSaved={() => { setSettings(false); result.refresh(); }} />}</>;
}
function CourseEditor({ course, onClose, onSaved, ...props }: ScreenProps & { course?: Course; onClose: () => void; onSaved: (label?: string) => void }) {
  const load = useCallback(async () => { const q = `societe_id=${props.state.companyId}`; const [trucks, drivers, contracts, clients] = await Promise.all([props.bridge.api<Truck[]>(`/transport/camions?${q}`), props.bridge.api<{ id: string; nom: string }[]>(`/transport/chauffeurs?${q}`), props.bridge.api<Contract[]>(`/transport/contrats?${q}`), course ? Promise.resolve([] as Party[]) : props.bridge.api<Party[]>(`/commercial/tiers?${q}&type=client`)]); return { trucks, drivers, contracts: contracts.filter(c => c.statut === 'actif'), clients }; }, [props.bridge, props.state.companyId, course]), result = useResource(load), [picker, setPicker] = useState(false), [added, setAdded] = useState<Party | null>(null);
  if (!result.data || result.busy || result.error) return <Dialog bridge={props.bridge} title="Préparer la course" onClose={onClose}><ErrorNotice error={result.error} />{result.busy ? <p>Lecture des camions, chauffeurs et contrats…</p> : <button className="btn" onClick={result.refresh}>Réessayer</button>}</Dialog>;
  const d = result.data, clients = added ? [...d.clients.filter(c => c.id !== added.id), added] : d.clients;
  const fields: FormField[] = [...(!course ? [{ key: 'client_tiers_id', label: 'Client', required: true, options: [['', 'Choisir'], ...clients.filter(c => c.code !== 'COMPTANT').map(c => [c.id, partyLabel(c)])] as [string, string][] }, { key: 'date_course', label: 'Date de départ', type: 'date', required: true }, { key: 'origine', label: 'Origine', required: true }, { key: 'destination', label: 'Destination', required: true }, { key: 'marchandise', label: 'Marchandise', required: true }] : []), { key: 'contrat_id', label: 'Contrat', options: [['', 'Hors contrat'], ...d.contracts.map(c => [c.id, c.libelle] as [string, string])] }, { key: 'tarif', label: 'Appliquer un tarif de contrat', options: [['', 'Saisie manuelle'], ...d.contracts.flatMap(c => c.tarifs.map((t, i) => [`${c.id}:${i}`, `${c.libelle} · ${t.trajet} · ${number(t.prix)} USD / ${t.mode}`] as [string, string]))] }, { key: 'camion_id', label: 'Camion disponible', required: true, options: [['', 'Sélectionner'], ...d.trucks.filter(c => c.actif && c.statut === 'disponible').map(c => [c.id, `${c.immatriculation} · ${number(c.capacite_tonnes)} t`] as [string, string])] }, { key: 'chauffeur_id', label: 'Chauffeur', options: [['', 'Non affecté'], ...d.drivers.map(c => [c.id, c.nom] as [string, string])] }, { key: 'tonnage_prevu', label: 'Quantité prévue pour ce voyage', type: 'number', min: 0.000001, required: true }, ...(course ? [{ key: 'unite', label: 'Unité', required: true }] : []), { key: 'tarif_mode', label: 'Tarification', options: [['tonne', 'Prix à la tonne'], ['voyage', 'Forfait au voyage']] }, { key: 'prix_unitaire', label: 'Prix USD', type: 'number', required: true, min: 0 }];
  return <><OperationForm bridge={props.bridge} title={course ? `Prendre en charge · ${course.numero}` : 'Nouvelle course'} onClose={onClose} initial={{ client_tiers_id: '', date_course: today(), origine: '', destination: '', marchandise: '', contrat_id: '', tarif: '', camion_id: '', chauffeur_id: '', tonnage_prevu: String(course?.tonnage_prevu ?? 30), unite: course?.unite || 'tonnes', tarif_mode: course?.tarif_mode || 'tonne', prix_unitaire: String(course?.prix_unitaire ?? 0) }} fields={fields} note={course ? `${course.marchandise} · ${course.origine} → ${course.destination}. Ajustez la quantité au chargement de ce voyage.` : 'La fiche suit la validation configurée pour cette société. Vous pouvez ensuite lier les réquisitions de carburant et de frais de route.'} extra={!course && <button type="button" className="btn" onClick={() => setPicker(true)}>Créer ou retrouver un client</button>} onChange={(v, key, value) => { const next = { ...v, [key]: value }; if (key === 'contrat_id') { const c = d.contracts.find(c => c.id === value); return { ...next, tarif: '', ...(c ? { client_tiers_id: c.client_tiers_id } : {}) }; } if (key === 'tarif' && value) { const [id, index] = value.split(':'), c = d.contracts.find(c => c.id === id), t = c?.tarifs[Number(index)]; if (c && t) { const [origine, destination] = t.trajet.split('→').map(s => s.trim()); return { ...next, contrat_id: id, client_tiers_id: c.client_tiers_id, tarif_mode: t.mode, prix_unitaire: String(t.prix), ...(origine && destination ? { origine, destination } : {}) }; } } return next; }} save={async v => { const body: Record<string, unknown> = { camion_id: v.camion_id, chauffeur_id: v.chauffeur_id || null, contrat_id: v.contrat_id || null, tonnage_prevu: amount(v.tonnage_prevu, 'Quantité', 0.000001), tarif_mode: v.tarif_mode, prix_unitaire: amount(v.prix_unitaire, 'Prix') }; const client = course?.client_tiers_id || v.client_tiers_id; if (v.contrat_id && d.contracts.find(c => c.id === v.contrat_id)?.client_tiers_id !== client) throw new Error('Ce contrat appartient à un autre client.'); if (course) body.unite = v.unite.trim(); else Object.assign(body, { client_tiers_id: client, date_course: v.date_course, origine: v.origine.trim(), destination: v.destination.trim(), marchandise: v.marchandise.trim() }); await props.bridge.api(course ? `/transport/courses/${course.id}/prendre-en-charge` : `/transport/courses?societe_id=${props.state.companyId}`, { method: 'POST', body }); onSaved('Fiche enregistrée, à faire valider avant le départ.'); }} />{picker && <AccountingPartyPicker {...props} parties={clients} allowedKind="client" onClose={() => setPicker(false)} onSelected={p => { setAdded(p); setPicker(false); }} />}</>;
}
function CourseAction({ course: c, kind, onClose, onSaved, ...props }: ScreenProps & { course: Course; kind: string; onClose: () => void; onSaved: (label?: string) => void }) {
  const interrupted = ['en_cours', 'arrivee'].includes(c.statut), subcontract = c.camion_type === 'sous_traite', confirm = kind.startsWith('confirm:');
  const fields: FormField[] = kind === 'depart' ? [{ key: 'km_depart', label: 'Compteur km départ (facultatif)', type: 'number', min: 0 }] : kind === 'retour' ? [{ key: 'tonnage_livre', label: `Quantité réellement livrée (${c.unite})`, type: 'number', min: 0, required: true }, { key: 'km_retour', label: `Compteur km retour (départ : ${c.km_depart ?? 'non renseigné'})`, type: 'number', min: c.km_depart ?? 0 }, { key: 'incidents', label: 'Incidents', type: 'textarea' }, ...(subcontract ? [{ key: 'st_mode', label: 'Rémunération sous-traitant', options: [['forfait', 'Forfait USD'], ['pourcentage', '% du prix client']] as [string, string][] }, { key: 'st_valeur', label: 'Valeur de rémunération', type: 'number', min: 0, required: true }] : [])] : kind === 'annuler' ? [{ key: 'motif', label: 'Motif', type: 'textarea', required: interrupted }] : [];
  return <OperationForm bridge={props.bridge} title={`${confirm ? 'Confirmer la réception' : ({ valider: 'Valider la course', depart: 'Confirmer le départ', arrivee: 'Confirmer l’arrivée', retour: 'Retour & clôture', annuler: interrupted ? 'Interrompre la course' : 'Annuler la course' } as Record<string, string>)[kind]} · ${c.numero}`} onClose={onClose} initial={{ km_depart: '', km_retour: '', tonnage_livre: String(c.reception_po?.recu ?? c.tonnage_prevu), incidents: '', motif: '', st_mode: 'forfait', st_valeur: '' }} fields={fields} note={confirm ? `Constat acheteur : ${number(c.reception_po?.recu)} reçus sur ${number(c.reception_po?.livre)} chargés ; ${number(c.reception_po?.manquant)} manquants, ${number(c.reception_po?.valeur_manquants_usd)} USD à charge du transporteur. La confirmation débloque la facturation.` : kind === 'annuler' && interrupted ? 'L’interruption libère le camion. Une demande liée à une commande sera recréée pour réorganiser son transport.' : kind === 'retour' && subcontract ? 'La clôture génère également la dette envers le sous-traitant.' : 'Confirmez cette étape. Les contrôles du circuit de transport restent appliqués par le serveur.'} submitLabel="Confirmer" save={async v => { const body: Record<string, unknown> = {}; if (kind === 'depart') body.km_depart = v.km_depart === '' ? null : amount(v.km_depart, 'Compteur départ'); if (kind === 'retour') { body.tonnage_livre = amount(v.tonnage_livre, 'Quantité livrée'); body.km_retour = v.km_retour === '' ? null : amount(v.km_retour, 'Compteur retour', c.km_depart ?? 0); body.incidents = v.incidents.trim() || null; if (subcontract) { body.st_mode = v.st_mode; body.st_valeur = amount(v.st_valeur, 'Rémunération'); if (v.st_mode === 'pourcentage' && Number(body.st_valeur) > 100) throw new Error('Le pourcentage ne peut dépasser 100 %.'); } } if (kind === 'annuler') { if (interrupted && !v.motif.trim()) throw new Error('Le motif est obligatoire.'); body.motif = v.motif.trim() || null; } await props.bridge.api(confirm ? `/intersociete/receptions/${kind.split(':')[1]}/confirmer` : `/transport/courses/${c.id}/${kind}`, { method: 'POST', body }); onSaved(); }} />;
}
function LinkRequest({ course, onClose, onSaved, ...props }: ScreenProps & { course: Course; onClose: () => void; onSaved: () => void }) {
  const load = useCallback(() => props.bridge.api<{ id: string; numero: string; objet: string; statut: string }[]>(`/requisitions?societe_id=${props.state.companyId}`), [props.bridge, props.state.companyId]), result = useResource(load);
  return result.data && !result.busy && !result.error ? <OperationForm bridge={props.bridge} title={`Lier une réquisition · ${course.numero}`} onClose={onClose} initial={{ requisition_id: '' }} fields={[{ key: 'requisition_id', label: 'Réquisition', required: true, options: [['', 'Sélectionner'], ...result.data.filter(r => !course.requisitions.some(l => l.numero === r.numero)).map(r => [r.id, `${r.numero} · ${r.objet} · ${r.statut}`] as [string, string])] }]} note="Les frais justifiés alimentent le coût de revient de cette course. Le départ attend le décaissement des avances liées." save={async v => { await props.bridge.api(`/transport/courses/${course.id}/lier-requisition`, { method: 'POST', body: v }); onSaved(); }} /> : <Dialog bridge={props.bridge} title="Réquisitions disponibles" onClose={onClose}><ErrorNotice error={result.error} />{result.busy ? <p>Chargement…</p> : <button className="btn" onClick={result.refresh}>Réessayer</button>}</Dialog>;
}
function InvoiceCourses({ onClose, onSaved, ...props }: ScreenProps & { onClose: () => void; onSaved: (label: string) => void }) {
  const load = useCallback(() => props.bridge.api<Course[]>(`/transport/courses?societe_id=${props.state.companyId}&statut=livree`), [props.bridge, props.state.companyId]), result = useResource(load), [selected, setSelected] = useState<string[]>([]);
  if (!result.data || result.busy || result.error) return <Dialog bridge={props.bridge} title="Facturer les courses livrées" onClose={onClose}><ErrorNotice error={result.error} />{result.busy ? <p>Lecture…</p> : <button className="btn" onClick={result.refresh}>Réessayer</button>}</Dialog>;
  return <OperationForm bridge={props.bridge} title="Facturer les courses livrées" onClose={onClose} initial={{ echeance: '' }} fields={[{ key: 'echeance', label: 'Échéance (facultatif)', type: 'date' }]} note="Sélectionnez les courses d’un même client. Pour un client du groupe, la facture d’achat miroir est créée automatiquement." extra={<>{!result.data.length && <p>Aucune course livrée à facturer.</p>}{result.data.map(c => <label className="business-field" key={c.id}><input type="checkbox" checked={selected.includes(c.id)} onChange={e => setSelected(s => e.target.checked ? [...s, c.id] : s.filter(id => id !== c.id))} />{c.numero} · {c.client} · {c.origine} → {c.destination} · {number(c.recette_usd)} USD</label>)}</>} submitLabel="Générer la facture" save={async v => { const rows = result.data!.filter(c => selected.includes(c.id)); if (!rows.length) throw new Error('Sélectionnez au moins une course.'); if (new Set(rows.map(c => c.client_tiers_id)).size !== 1) throw new Error('Les courses doivent appartenir au même client.'); const r = await props.bridge.api<{ facture: { numero: string; total_ttc: number; intra_groupe: boolean } }>(`/transport/facturer?societe_id=${props.state.companyId}`, { method: 'POST', body: { course_ids: rows.map(c => c.id), echeance: v.echeance || null } }); onSaved(`Facture ${r.facture.numero} créée : ${number(r.facture.total_ttc)} USD${r.facture.intra_groupe ? ' et achat miroir intersociété' : ''}.`); }} />;
}
function TransportProfit({ onClose, ...props }: ScreenProps & { onClose: () => void }) {
  interface Totals { courses: number; tonnage: number; recettes: number; frais: number; sous_traitance: number; maintenance: number; marge: number; camion?: string; contrat?: string }
  const load = useCallback(() => props.bridge.api<{ total: Totals; par_camion: Totals[]; par_contrat: Totals[] }>(`/transport/rapport?societe_id=${props.state.companyId}`), [props.bridge, props.state.companyId]), result = useResource(load), d = result.data;
  return d && !result.busy && !result.error ? <ReportPreview {...props} onClose={onClose} report={{ title: 'Rentabilité du transport', subtitle: 'Société active · montants USD', columns: ['Périmètre', 'Courses', 'Quantité', 'Recettes', 'Frais de route', 'Sous-traitance', 'Maintenance', 'Marge'], rows: [['TOTAL SOCIÉTÉ', d.total.courses, d.total.tonnage, d.total.recettes, d.total.frais, d.total.sous_traitance, d.total.maintenance, d.total.marge], ...d.par_camion.map(c => [c.camion || '', c.courses, c.tonnage, c.recettes, c.frais, c.sous_traitance, c.maintenance, c.marge]), ...d.par_contrat.map(c => [c.contrat || '', c.courses, '', c.recettes, '', '', '', c.marge])], note: 'Les regroupements par camion et par contrat présentent deux lectures des mêmes opérations ; ne pas les additionner entre eux.' }} /> : <Dialog bridge={props.bridge} title="Rentabilité transport" onClose={onClose}><ErrorNotice error={result.error} />{result.busy ? <p>Calcul du rapport…</p> : <button className="btn" onClick={result.refresh}>Réessayer</button>}</Dialog>;
}
function courseReport(c: Course): Report { return { title: `Fiche de course ${c.numero}`, subtitle: `${c.client} · ${c.date} · ${c.statut}`, columns: ['Rubrique', 'Détail'], rows: [['Camion', c.camion || 'À affecter'], ['Type de camion', c.camion_type || ''], ['Chauffeur', c.chauffeur || ''], ['Trajet', `${c.origine} → ${c.destination}`], ['Marchandise', c.marchandise], ['Quantité prévue', `${number(c.tonnage_prevu)} ${c.unite}`], ['Quantité livrée', c.tonnage_livre == null ? 'Non renseignée' : `${number(c.tonnage_livre)} ${c.unite}`], ['Tarification', `${number(c.prix_unitaire)} USD / ${c.tarif_mode}`], ['Recette USD', c.recette_usd], ['Contrat', c.contrat || ''], ['Commande', c.commande_origine || ''], ['Réquisitions', (c.requisitions || []).map(r => `${r.numero} (${r.statut})`).join(', ')], ['Frais de route USD', c.frais_route_usd || 0], ['Sous-traitance USD', c.st_cout_usd || 0], ['Facture sous-traitant', c.st_facture || ''], ['Marge USD', c.marge_usd ?? 'En cours'], ['Départ', c.heure_depart || ''], ['Retour', c.heure_retour || ''], ['Incidents', c.incidents || ''], ['Facture client', c.facture || ''], ...(c.reception_po ? [['Réception acheteur', `${number(c.reception_po.recu)} reçus / ${number(c.reception_po.livre)} chargés · ${number(c.reception_po.manquant)} manquants (${number(c.reception_po.valeur_manquants_usd)} USD)`]] : [])], note: 'Signatures : Chauffeur ____________________    Dispatch ____________________    Contrôle ____________________' }; }
