# Generated by Django 5.1.4 on 2026-09-20 12:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_rh_paie_mensuelle'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Article',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('societe_id', models.UUIDField()),
                        ('code', models.CharField(max_length=32)),
                        ('designation', models.CharField(max_length=255)),
                        ('unite', models.CharField(default='unité', max_length=32)),
                        ('prix_achat', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                        ('prix_vente', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                        ('assujetti_tva', models.BooleanField(default=True)),
                        ('taux_tva', models.DecimalField(decimal_places=2, default=16, max_digits=6)),
                        ('categorie', models.CharField(blank=True, max_length=64, null=True)),
                        ('code_barres', models.CharField(blank=True, max_length=64, null=True)),
                        ('taux_commission', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                        ('points_fidelite', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                        ('compte_achat', models.CharField(default='601', max_length=16)),
                        ('compte_vente', models.CharField(default='701', max_length=16)),
                        ('compte_stock', models.CharField(default='31', max_length=16)),
                        ('gere_stock', models.BooleanField(default=True)),
                        ('stock_qte', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                        ('stock_valeur', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                        ('actif', models.BooleanField(default=True)),
                        ('nature', models.CharField(default='marchandise', max_length=20)),
                    ],
                    options={
                        'db_table': 'article',
                        'managed': True,
                        'indexes': [],
                        'constraints': [],
                    },
                ),
                migrations.CreateModel(
                    name='MouvementStock',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('societe_id', models.UUIDField()),
                        ('article_id', models.UUIDField()),
                        ('date_mvt', models.DateField()),
                        ('sens', models.CharField(max_length=16)),
                        ('qte', models.DecimalField(decimal_places=3, max_digits=18)),
                        ('cout_unitaire', models.DecimalField(decimal_places=4, max_digits=18)),
                        ('valeur', models.DecimalField(decimal_places=2, max_digits=18)),
                        ('type_operation', models.CharField(max_length=32)),
                        ('reference', models.CharField(blank=True, max_length=64, null=True)),
                        ('created_at', models.DateTimeField(blank=True, null=True)),
                        ('depot_id', models.UUIDField(blank=True, null=True)),
                    ],
                    options={
                        'db_table': 'mouvement_stock',
                        'managed': True,
                        'indexes': [],
                        'constraints': [],
                    },
                ),
                migrations.CreateModel(
                    name='Depot',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('societe_id', models.UUIDField()),
                        ('code', models.CharField(max_length=20)),
                        ('libelle', models.CharField(max_length=128)),
                        ('type', models.CharField(default='dedie', max_length=16)),
                        ('actif', models.BooleanField(default=True)),
                        ('created_by', models.UUIDField(blank=True, null=True)),
                        ('created_at', models.DateTimeField(blank=True, null=True)),
                    ],
                    options={
                        'db_table': 'depot',
                        'managed': True,
                        'indexes': [],
                        'constraints': [],
                    },
                ),
                migrations.CreateModel(
                    name='StockDepot',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('depot_id', models.UUIDField()),
                        ('article_id', models.UUIDField()),
                        ('qte', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                        ('valeur', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                    ],
                    options={
                        'db_table': 'stock_depot',
                        'managed': True,
                        'indexes': [],
                        'constraints': [],
                    },
                ),
                migrations.CreateModel(
                    name='TransfertDepot',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('societe_id', models.UUIDField()),
                        ('numero', models.CharField(max_length=32)),
                        ('depot_source_id', models.UUIDField()),
                        ('depot_cible_id', models.UUIDField()),
                        ('date_transfert', models.DateField()),
                        ('note', models.CharField(blank=True, max_length=255, null=True)),
                        ('created_by', models.UUIDField(blank=True, null=True)),
                        ('created_at', models.DateTimeField(blank=True, null=True)),
                    ],
                    options={
                        'db_table': 'transfert_depot',
                        'managed': True,
                        'indexes': [],
                        'constraints': [],
                    },
                ),
                migrations.CreateModel(
                    name='LigneTransfertDepot',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('transfert_id', models.UUIDField()),
                        ('article_id', models.UUIDField()),
                        ('qte', models.DecimalField(decimal_places=3, max_digits=18)),
                        ('valeur', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                    ],
                    options={
                        'db_table': 'ligne_transfert_depot',
                        'managed': True,
                        'indexes': [],
                        'constraints': [],
                    },
                ),
                migrations.CreateModel(
                    name='InventaireDepot',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('societe_id', models.UUIDField()),
                        ('numero', models.CharField(max_length=32)),
                        ('depot_id', models.UUIDField()),
                        ('date_inventaire', models.DateField()),
                        ('valeur_theorique', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                        ('valeur_reelle', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                        ('ecart_valeur', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                        ('note', models.CharField(blank=True, max_length=255, null=True)),
                        ('ecriture_id', models.UUIDField(blank=True, null=True)),
                        ('created_by', models.UUIDField(blank=True, null=True)),
                        ('created_at', models.DateTimeField(blank=True, null=True)),
                        ('statut', models.CharField(default='valide', max_length=16)),
                        ('valide_at', models.DateTimeField(blank=True, null=True)),
                        ('valide_par', models.UUIDField(blank=True, null=True)),
                    ],
                    options={
                        'db_table': 'inventaire_depot',
                        'managed': True,
                        'indexes': [],
                        'constraints': [],
                    },
                ),
                migrations.CreateModel(
                    name='LigneInventaireDepot',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('inventaire_id', models.UUIDField()),
                        ('article_id', models.UUIDField()),
                        ('qte_theorique', models.DecimalField(decimal_places=3, max_digits=18)),
                        ('qte_reelle', models.DecimalField(decimal_places=3, max_digits=18)),
                        ('cump', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                        ('ecart_qte', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                        ('ecart_valeur', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                        ('valeur_stock_comptee', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                    ],
                    options={
                        'db_table': 'ligne_inventaire_depot',
                        'managed': True,
                        'indexes': [],
                        'constraints': [],
                    },
                ),
            ],
        ),
    ]
