from django.urls import path, include
from apps.commercial import views as commercial_views
from apps.commercial import ventes_views as ventes_views

urlpatterns = [
    path("commercial/articles", commercial_views.ArticleViewSet.as_view({'get': 'list', 'post': 'create'}, http_method_names=['get', 'post', 'options'], detail=False, basename='article')),
    path("commercial/articles/<uuid:article_id>", commercial_views.ArticleViewSet.as_view({'patch': 'partial_update'}, http_method_names=['patch', 'options'], detail=True, basename='article')),
    path("commercial/articles/<uuid:article_id>/prix", commercial_views.ArticleViewSet.as_view({'get': 'prix'}, http_method_names=['get', 'options'], detail=True, basename='article')),
    path("commercial/tiers", commercial_views.TiersViewSet.as_view({'get': 'list', 'post': 'create'}, http_method_names=['get', 'post', 'options'], detail=False, basename='tiers')),
    path("commercial/tiers/<uuid:tiers_id>", commercial_views.TiersViewSet.as_view({'patch': 'partial_update'}, http_method_names=['patch', 'options'], detail=True, basename='tiers')),
    path("commercial/factures", commercial_views.FactureViewSet.as_view({'get': 'list', 'post': 'create'}, http_method_names=['get', 'post', 'options'], detail=False, basename='facture')),
    path("commercial/factures/<uuid:facture_id>", commercial_views.FactureViewSet.as_view({'get': 'retrieve'}, http_method_names=['get', 'options'], detail=True, basename='facture')),
    path("commercial/stock", commercial_views.StockViewSet.as_view({'get': 'etat_stock'}, http_method_names=['get', 'options'], detail=False, basename='stock')),
    path("commercial/stock/mouvements", commercial_views.StockViewSet.as_view({'get': 'mouvements'}, http_method_names=['get', 'options'], detail=False, basename='stock')),
    path("commercial/achats-historique", commercial_views.AchatsHistoriqueViewSet.as_view({'get': 'achats_historique'}, http_method_names=['get', 'options'], detail=False, basename='achats_historique')),
    path("commercial/ventes-synthese", commercial_views.VentesSyntheseViewSet.as_view({'get': 'ventes_synthese'}, http_method_names=['get', 'options'], detail=False, basename='ventes_synthese')),
    path("commercial/commandes", commercial_views.CommandeViewSet.as_view({'get': 'list', 'post': 'create'}, http_method_names=['get', 'post', 'options'], detail=False, basename='commande')),
    path("commercial/commandes/<uuid:commande_id>", commercial_views.CommandeViewSet.as_view({'get': 'retrieve', 'put': 'update'}, http_method_names=['get', 'put', 'options'], detail=True, basename='commande')),
    path("commercial/commandes/<uuid:commande_id>/annuler", commercial_views.CommandeViewSet.as_view({'post': 'annuler'}, http_method_names=['post', 'options'], detail=True, basename='commande')),
    path("commercial/commandes/<uuid:commande_id>/receptionner", commercial_views.CommandeViewSet.as_view({'post': 'receptionner'}, http_method_names=['post', 'options'], detail=True, basename='commande')),
    path("commercial/receptions", commercial_views.ReceptionViewSet.as_view({'get': 'list'}, http_method_names=['get', 'options'], detail=False, basename='reception')),
    path("commercial/receptions/<uuid:reception_id>", commercial_views.ReceptionViewSet.as_view({'get': 'retrieve'}, http_method_names=['get', 'options'], detail=True, basename='reception')),
    path("commercial/receptions/<uuid:reception_id>/facturer", commercial_views.ReceptionViewSet.as_view({'post': 'facturer'}, http_method_names=['post', 'options'], detail=True, basename='reception')),
    path("commercial/listes-prix", commercial_views.ListePrixViewSet.as_view({'get': 'list', 'post': 'create'}, http_method_names=['get', 'post', 'options'], detail=False, basename='liste_prix')),
    path("commercial/listes-prix/<uuid:liste_id>/tarifs", commercial_views.ListePrixViewSet.as_view({'get': 'get_tarifs', 'post': 'post_tarifs'}, http_method_names=['get', 'post', 'options'], detail=True, basename='liste_prix')),
    path("commercial/points-vente", commercial_views.PointVenteViewSet.as_view({'get': 'list', 'post': 'create'}, http_method_names=['get', 'post', 'options'], detail=False, basename='point_vente')),
    path("commercial/points-vente/<uuid:pv_id>", commercial_views.PointVenteViewSet.as_view({'patch': 'partial_update'}, http_method_names=['patch', 'options'], detail=True, basename='point_vente')),
    path("commercial/pos/contexte", commercial_views.PointDeVenteViewSet.as_view({'get': 'contexte'}, http_method_names=['get', 'options'], detail=False, basename='point_de_vente')),
    path("commercial/pos/vente", commercial_views.PointDeVenteViewSet.as_view({'post': 'vente'}, http_method_names=['post', 'options'], detail=False, basename='point_de_vente')),
    path("commercial/pos/tickets", commercial_views.PointDeVenteViewSet.as_view({'get': 'tickets'}, http_method_names=['get', 'options'], detail=False, basename='point_de_vente')),
    path("commercial/pos/ticket/<uuid:facture_id>", commercial_views.PointDeVenteViewSet.as_view({'get': 'ticket'}, http_method_names=['get', 'options'], detail=True, basename='point_de_vente')),
    path("commercial/pos/retour", commercial_views.PointDeVenteViewSet.as_view({'post': 'retour'}, http_method_names=['post', 'options'], detail=False, basename='point_de_vente')),
    path("commercial/pos/rapport", commercial_views.PointDeVenteViewSet.as_view({'get': 'rapport'}, http_method_names=['get', 'options'], detail=False, basename='point_de_vente')),
    path("ventes/devis", ventes_views.DevisViewSet.as_view({'get': 'list', 'post': 'create'}, http_method_names=['get', 'post', 'options'], detail=False, basename='devis')),
    path("ventes/devis/<uuid:devis_id>", ventes_views.DevisViewSet.as_view({'get': 'retrieve', 'put': 'update'}, http_method_names=['get', 'put', 'options'], detail=True, basename='devis')),
    path("ventes/devis/<uuid:devis_id>/envoyer", ventes_views.DevisViewSet.as_view({'post': 'envoyer'}, http_method_names=['post', 'options'], detail=True, basename='devis')),
    path("ventes/devis/<uuid:devis_id>/confirmer", ventes_views.DevisViewSet.as_view({'post': 'confirmer'}, http_method_names=['post', 'options'], detail=True, basename='devis')),
    path("ventes/devis/<uuid:devis_id>/associer", ventes_views.DevisViewSet.as_view({'post': 'associer'}, http_method_names=['post', 'options'], detail=True, basename='devis')),
    path("ventes/devis/<uuid:devis_id>/reference-producteur", ventes_views.DevisViewSet.as_view({'post': 'reference_producteur'}, http_method_names=['post', 'options'], detail=True, basename='devis')),
    path("ventes/devis/<uuid:devis_id>/annuler", ventes_views.DevisViewSet.as_view({'post': 'annuler'}, http_method_names=['post', 'options'], detail=True, basename='devis')),
    path("ventes/devis/<uuid:devis_id>/livrer", ventes_views.DevisViewSet.as_view({'post': 'livrer'}, http_method_names=['post', 'options'], detail=True, basename='devis')),
    path("ventes/devis/<uuid:devis_id>/facturer", ventes_views.DevisViewSet.as_view({'post': 'facturer'}, http_method_names=['post', 'options'], detail=True, basename='devis')),
    path("ventes/factures/<uuid:facture_id>/regler", ventes_views.FactureViewSet.as_view({'post': 'regler'}, http_method_names=['post', 'options'], detail=True, basename='facture')),
    path("ventes/encours", ventes_views.EncoursViewSet.as_view({'get': 'encours_clients'}, http_method_names=['get', 'options'], detail=False, basename='encours')),
]
