# Generated by Django 5.1.4 on 2026-09-20 12:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_rh_paie_mensuelle'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Compte',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('societe_id', models.UUIDField()),
                        ('numero', models.CharField(max_length=16)),
                        ('intitule', models.CharField(max_length=255)),
                        ('classe', models.CharField(blank=True, max_length=4, null=True)),
                        ('auxiliaire', models.BooleanField(default=False)),
                        ('actif', models.BooleanField(default=True)),
                    ],
                    options={
                        'db_table': 'compte',
                        'managed': True,
                        'indexes': [],
                        'constraints': [],
                    },
                ),
                migrations.CreateModel(
                    name='Exercice',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('societe_id', models.UUIDField()),
                        ('annee', models.IntegerField()),
                        ('date_debut', models.DateField()),
                        ('date_fin', models.DateField()),
                        ('statut', models.CharField(default='ouvert', max_length=16)),
                    ],
                    options={
                        'db_table': 'exercice',
                        'managed': True,
                        'indexes': [],
                        'constraints': [],
                    },
                ),
                migrations.CreateModel(
                    name='Journal',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('societe_id', models.UUIDField()),
                        ('code', models.CharField(max_length=8)),
                        ('libelle', models.CharField(max_length=128)),
                        ('type', models.CharField(max_length=32)),
                        ('actif', models.BooleanField(default=True)),
                    ],
                    options={
                        'db_table': 'journal',
                        'managed': True,
                        'indexes': [],
                        'constraints': [],
                    },
                ),
                migrations.CreateModel(
                    name='Ecriture',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('societe_id', models.UUIDField()),
                        ('exercice_id', models.UUIDField()),
                        ('journal_id', models.UUIDField(blank=True, null=True)),
                        ('numero', models.CharField(max_length=32)),
                        ('date_ecriture', models.DateField()),
                        ('numero_piece', models.CharField(blank=True, max_length=64, null=True)),
                        ('libelle', models.TextField()),
                        ('type_operation', models.CharField(blank=True, max_length=48, null=True)),
                        ('source_type', models.CharField(blank=True, max_length=48, null=True)),
                        ('source_id', models.UUIDField(blank=True, null=True)),
                        ('statut', models.CharField(default='valide', max_length=16)),
                        ('created_by', models.UUIDField(blank=True, null=True)),
                        ('created_at', models.DateTimeField(blank=True, null=True)),
                    ],
                    options={
                        'db_table': 'ecriture',
                        'managed': True,
                        'indexes': [],
                        'constraints': [],
                    },
                ),
                migrations.CreateModel(
                    name='LigneEcriture',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('societe_id', models.UUIDField()),
                        ('ordre', models.IntegerField(default=0)),
                        ('sens', models.CharField(max_length=1)),
                        ('compte_numero', models.CharField(max_length=16)),
                        ('tiers_id', models.UUIDField(blank=True, null=True)),
                        ('montant_usd', models.DecimalField(decimal_places=2, max_digits=18)),
                        ('devise_origine', models.CharField(default='USD', max_length=8)),
                        ('montant_origine', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                        ('taux_jour', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                        ('libelle_ligne', models.CharField(blank=True, max_length=255, null=True)),
                        ('lettrage_code', models.CharField(blank=True, max_length=16, null=True)),
                        ('rapprochement_id', models.UUIDField(blank=True, null=True)),
                        ('ecriture', models.ForeignKey(db_column='ecriture_id', on_delete=django.db.models.deletion.DO_NOTHING, to='comptabilite.ecriture')),
                    ],
                    options={
                        'db_table': 'ligne_ecriture',
                        'managed': True,
                        'indexes': [],
                        'constraints': [],
                    },
                ),
                migrations.CreateModel(
                    name='RapprochementBancaire',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('societe_id', models.UUIDField()),
                        ('compte', models.CharField(max_length=16)),
                        ('date_releve', models.DateField()),
                        ('solde_releve_usd', models.DecimalField(decimal_places=2, max_digits=18)),
                        ('solde_comptable_usd', models.DecimalField(decimal_places=2, max_digits=18)),
                        ('solde_rapproche_usd', models.DecimalField(decimal_places=2, max_digits=18)),
                        ('ecart_usd', models.DecimalField(decimal_places=2, max_digits=18)),
                        ('statut', models.CharField(default='cloture', max_length=16)),
                        ('created_by', models.UUIDField(blank=True, null=True)),
                        ('created_at', models.DateTimeField(blank=True, null=True)),
                    ],
                    options={
                        'db_table': 'rapprochement_bancaire',
                        'managed': True,
                        'indexes': [],
                        'constraints': [],
                    },
                ),
                migrations.CreateModel(
                    name='PreparationTVA',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('societe_id', models.UUIDField()),
                        ('mois', models.CharField(max_length=7)),
                        ('donnees', models.JSONField(default=dict)),
                        ('revision', models.PositiveIntegerField(default=1)),
                        ('updated_by', models.UUIDField(blank=True, null=True)),
                        ('updated_at', models.DateTimeField(blank=True, null=True)),
                    ],
                    options={
                        'db_table': 'preparation_tva',
                        'constraints': [models.UniqueConstraint(fields=('societe_id', 'mois'), name='preparation_tva_societe_mois')],
                        'indexes': [],
                    },
                ),
                migrations.CreateModel(
                    name='AxeAnalytique',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('societe_id', models.UUIDField()),
                        ('code', models.CharField(max_length=20)),
                        ('libelle', models.CharField(max_length=128)),
                        ('actif', models.BooleanField(default=True)),
                    ],
                    options={
                        'db_table': 'axe_analytique',
                        'managed': True,
                        'indexes': [],
                        'constraints': [],
                    },
                ),
                migrations.CreateModel(
                    name='SectionAnalytique',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('axe_id', models.UUIDField()),
                        ('societe_id', models.UUIDField()),
                        ('code', models.CharField(max_length=20)),
                        ('libelle', models.CharField(max_length=128)),
                        ('actif', models.BooleanField(default=True)),
                    ],
                    options={
                        'db_table': 'section_analytique',
                        'managed': True,
                        'indexes': [],
                        'constraints': [],
                    },
                ),
                migrations.CreateModel(
                    name='VentilationAnalytique',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('societe_id', models.UUIDField()),
                        ('ligne_ecriture_id', models.UUIDField()),
                        ('axe_id', models.UUIDField()),
                        ('section_id', models.UUIDField()),
                        ('montant_usd', models.DecimalField(decimal_places=2, max_digits=18)),
                    ],
                    options={
                        'db_table': 'ventilation_analytique',
                        'managed': True,
                        'indexes': [],
                        'constraints': [],
                    },
                ),
            ],
        ),
    ]
