from django.urls import path, include
from apps.commercial import views as commercial_views
from apps.commercial import ventes_views as ventes_views

urlpatterns = [
    path("commercial/articles", commercial_views.articles),
    path("commercial/articles/<uuid:article_id>", commercial_views.maj_article),
    path("commercial/articles/<uuid:article_id>/prix", commercial_views.prix_article),
    path("commercial/tiers", commercial_views.tiers_commercial),
    path("commercial/tiers/<uuid:tiers_id>", commercial_views.maj_tiers),
    path("commercial/factures", commercial_views.factures),
    path("commercial/factures/<uuid:facture_id>", commercial_views.detail_facture),
    path("commercial/stock", commercial_views.etat_stock),
    path("commercial/stock/mouvements", commercial_views.mouvements_stock),
    path("commercial/achats-historique", commercial_views.achats_historique),
    path("commercial/ventes-synthese", commercial_views.ventes_synthese),
    path("commercial/commandes", commercial_views.commandes),
    path("commercial/commandes/<uuid:commande_id>", commercial_views.commande_detail),
    path("commercial/commandes/<uuid:commande_id>/annuler", commercial_views.annuler_commande),
    path("commercial/commandes/<uuid:commande_id>/receptionner", commercial_views.receptionner),
    path("commercial/receptions", commercial_views.lister_receptions),
    path("commercial/receptions/<uuid:reception_id>", commercial_views.detail_reception),
    path("commercial/receptions/<uuid:reception_id>/facturer", commercial_views.facturer_reception),
    path("commercial/listes-prix", commercial_views.listes_prix),
    path("commercial/listes-prix/<uuid:liste_id>/tarifs", commercial_views.tarifs_liste),
    path("commercial/points-vente", commercial_views.points_vente),
    path("commercial/points-vente/<uuid:pv_id>", commercial_views.maj_point_vente),
    path("commercial/pos/contexte", commercial_views.pos_contexte),
    path("commercial/pos/vente", commercial_views.pos_vente),
    path("commercial/pos/tickets", commercial_views.pos_tickets),
    path("commercial/pos/ticket/<uuid:facture_id>", commercial_views.pos_ticket),
    path("commercial/pos/retour", commercial_views.pos_retour),
    path("commercial/pos/rapport", commercial_views.pos_rapport),
    path("ventes/devis", ventes_views.devis),
    path("ventes/devis/<uuid:devis_id>", ventes_views.devis_detail),
    path("ventes/devis/<uuid:devis_id>/envoyer", ventes_views.envoyer_devis),
    path("ventes/devis/<uuid:devis_id>/confirmer", ventes_views.confirmer_devis),
    path("ventes/devis/<uuid:devis_id>/associer", ventes_views.associer_articles),
    path("ventes/devis/<uuid:devis_id>/reference-producteur", ventes_views.maj_reference_producteur),
    path("ventes/devis/<uuid:devis_id>/annuler", ventes_views.annuler_devis),
    path("ventes/devis/<uuid:devis_id>/livrer", ventes_views.livrer),
    path("ventes/devis/<uuid:devis_id>/facturer", ventes_views.facturer),
    path("ventes/factures/<uuid:facture_id>/regler", ventes_views.regler_facture),
    path("ventes/encours", ventes_views.encours_clients),
]
