"""Plan comptable SYSCOHADA révisé — portage exact de backend/app/plan_comptable.py.

Référentiel statique (classes 1 à 8) chargé par société ; le comptable l'étend
ensuite via l'écran « Plan comptable ». Les comptes collectifs de tiers sont
marqués `auxiliaire` (grand livre auxiliaire par tiers).
"""
from __future__ import annotations

from apps.comptabilite.models import Compte

# Comptes collectifs pilotant un grand livre auxiliaire (ventilation par tiers)
COMPTES_AUXILIAIRES = {"401", "402", "408", "409", "411", "412", "416", "418", "419", "462"}

# (numéro, intitulé). Ordre = ordre naturel du plan.
PLAN_SYSCOHADA: list[tuple[str, str]] = [
    # ── Classe 1 — Ressources durables ──────────────────────────────
    ("10", "Capital"),
    ("101", "Capital social"),
    ("104", "Primes liées au capital social"),
    ("105", "Écarts de réévaluation"),
    ("106", "Réserves"),
    ("1061", "Réserve légale"),
    ("1068", "Autres réserves"),
    ("11", "Report à nouveau"),
    ("110", "Report à nouveau créditeur"),
    ("119", "Report à nouveau débiteur"),
    ("12", "Résultat net de l'exercice"),
    ("120", "Résultat en instance d'affectation — bénéfice"),
    ("129", "Résultat en instance d'affectation — perte"),
    ("13", "Résultat net de l'exercice"),
    ("131", "Résultat net — bénéfice"),
    ("139", "Résultat net — perte"),
    ("14", "Subventions d'investissement"),
    ("15", "Provisions réglementées et fonds assimilés"),
    ("16", "Emprunts et dettes assimilées"),
    ("161", "Emprunts obligataires"),
    ("162", "Emprunts et dettes auprès des établissements de crédit"),
    ("165", "Dépôts et cautionnements reçus"),
    ("166", "Intérêts courus"),
    ("18", "Comptes de liaison des établissements et sociétés en participation"),
    ("181", "Comptes de liaison (établissements et succursales)"),
    ("19", "Provisions pour risques et charges"),
    ("191", "Provisions pour litiges"),
    # ── Classe 2 — Actif immobilisé ─────────────────────────────────
    ("20", "Charges immobilisées"),
    ("21", "Immobilisations incorporelles"),
    ("211", "Frais de recherche et de développement"),
    ("212", "Brevets, licences, concessions et droits similaires"),
    ("213", "Logiciels"),
    ("215", "Fonds commercial"),
    ("22", "Terrains"),
    ("23", "Bâtiments, installations techniques et agencements"),
    ("231", "Bâtiments industriels, agricoles et administratifs"),
    ("24", "Matériel, mobilier et actifs biologiques"),
    ("241", "Matériel et outillage industriel et commercial"),
    ("244", "Matériel et mobilier de bureau"),
    ("245", "Matériel de transport"),
    ("25", "Avances et acomptes versés sur immobilisations"),
    ("26", "Titres de participation"),
    ("27", "Autres immobilisations financières"),
    ("275", "Dépôts et cautionnements versés"),
    ("28", "Amortissements"),
    ("281", "Amortissements des immobilisations incorporelles"),
    ("2813", "Amortissements des logiciels"),
    ("283", "Amortissements des bâtiments"),
    ("284", "Amortissements du matériel"),
    ("2844", "Amortissements du matériel et mobilier de bureau"),
    ("2845", "Amortissements du matériel de transport"),
    ("29", "Provisions pour dépréciation des immobilisations"),
    # ── Classe 3 — Stocks ───────────────────────────────────────────
    ("31", "Marchandises"),
    ("32", "Matières premières et fournitures liées"),
    ("33", "Autres approvisionnements"),
    ("34", "Produits et travaux en cours"),
    ("35", "Services en cours"),
    ("36", "Produits finis"),
    ("37", "Produits intermédiaires et résiduels"),
    ("38", "Stocks en cours de route, en consignation ou en dépôt"),
    ("39", "Dépréciations des stocks"),
    # ── Classe 4 — Tiers ────────────────────────────────────────────
    ("40", "Fournisseurs et comptes rattachés"),
    ("401", "Fournisseurs, dettes en compte"),
    ("402", "Fournisseurs, effets à payer"),
    ("408", "Fournisseurs, factures non parvenues"),
    ("409", "Fournisseurs débiteurs (avances et acomptes versés)"),
    ("41", "Clients et comptes rattachés"),
    ("411", "Clients"),
    ("412", "Clients, effets à recevoir"),
    ("416", "Clients douteux ou litigieux"),
    ("418", "Clients, produits non encore facturés"),
    ("419", "Clients créditeurs (avances et acomptes reçus)"),
    ("42", "Personnel"),
    ("421", "Personnel, avances et acomptes"),
    ("422", "Personnel, rémunérations dues"),
    ("427", "Personnel — oppositions, saisies-arrêts"),
    ("43", "Organismes sociaux"),
    ("431", "Sécurité sociale"),
    ("44", "État et collectivités publiques"),
    ("441", "État, impôt sur les bénéfices"),
    ("442", "État, autres impôts et taxes"),
    ("443", "État, TVA facturée"),
    ("4431", "État, TVA facturée sur ventes"),
    ("444", "État, TVA due ou crédit de TVA"),
    ("445", "État, TVA récupérable"),
    ("4451", "État, TVA récupérable sur immobilisations"),
    ("4452", "État, TVA récupérable sur achats"),
    ("447", "État, impôts retenus à la source"),
    ("46", "Associés et groupe"),
    ("461", "Associés, opérations sur le capital"),
    ("462", "Associés, comptes courants"),
    ("47", "Débiteurs et créditeurs divers"),
    ("471", "Compte d'attente (à reclasser)"),
    ("476", "Charges constatées d'avance"),
    ("477", "Produits constatés d'avance"),
    ("48", "Créances et dettes hors activités ordinaires (HAO)"),
    ("481", "Fournisseurs d'investissements"),
    ("49", "Dépréciations et provisions pour risques à court terme"),
    # ── Classe 5 — Trésorerie ───────────────────────────────────────
    ("50", "Titres de placement"),
    ("52", "Banques"),
    ("521", "Banques locales"),
    ("522", "Mobile Money"),
    ("53", "Établissements financiers et assimilés"),
    ("531", "Chèques postaux"),
    ("54", "Instruments de trésorerie"),
    ("57", "Caisse"),
    ("571", "Caisse siège social"),
    ("5711", "Caisse points de vente (comptant en attente de remise)"),
    ("58", "Régularisations et virements internes"),
    ("585", "Virements de fonds"),
    ("59", "Dépréciations des comptes de trésorerie"),
    # ── Classe 6 — Charges des activités ordinaires ─────────────────
    ("60", "Achats et variations de stocks"),
    ("601", "Achats de marchandises"),
    ("602", "Achats de matières premières et fournitures liées"),
    ("603", "Variations des stocks de biens achetés"),
    ("604", "Achats stockés de matières et fournitures consommables"),
    ("605", "Autres achats"),
    ("6051", "Fournitures non stockables — eau"),
    ("6052", "Fournitures non stockables — électricité"),
    ("6053", "Fournitures non stockables — carburants"),
    ("6055", "Fournitures de bureau"),
    ("608", "Achats d'emballages"),
    ("6081", "Emballages perdus"),
    ("6085", "Frais sur achats (transport, douane, fret, assurance, transit…)"),
    ("61", "Transports"),
    ("611", "Transports sur achats"),
    ("612", "Transports sur ventes"),
    ("616", "Transport du personnel"),
    ("62", "Services extérieurs A"),
    ("622", "Locations et charges locatives"),
    ("624", "Entretien, réparations et maintenance"),
    ("625", "Primes d'assurance"),
    ("63", "Services extérieurs B"),
    ("631", "Frais bancaires"),
    ("632", "Rémunérations d'intermédiaires et de conseils"),
    ("633", "Frais de formation du personnel"),
    ("64", "Impôts et taxes"),
    ("641", "Impôts et taxes directs"),
    ("645", "Impôts et taxes indirects"),
    ("65", "Autres charges"),
    ("658", "Charges diverses"),
    ("66", "Charges de personnel"),
    ("661", "Rémunérations directes versées au personnel"),
    ("663", "Indemnités et avantages divers"),
    ("664", "Charges sociales"),
    ("67", "Frais financiers et charges assimilées"),
    ("671", "Intérêts des emprunts"),
    ("674", "Autres intérêts"),
    ("676", "Pertes de change"),
    ("68", "Dotations aux amortissements"),
    ("681", "Dotations aux amortissements d'exploitation"),
    ("69", "Dotations aux provisions et dépréciations"),
    # ── Classe 7 — Produits des activités ordinaires ────────────────
    ("70", "Ventes"),
    ("701", "Ventes de marchandises"),
    ("702", "Ventes de produits finis"),
    ("704", "Travaux facturés"),
    ("706", "Services vendus"),
    ("707", "Produits accessoires"),
    ("71", "Subventions d'exploitation"),
    ("72", "Production immobilisée"),
    ("73", "Variations des stocks de produits"),
    ("75", "Autres produits"),
    ("758", "Produits divers"),
    ("77", "Revenus financiers et produits assimilés"),
    ("771", "Intérêts de prêts"),
    ("776", "Gains de change"),
    ("78", "Transferts de charges"),
    ("79", "Reprises de provisions et dépréciations"),
    # ── Classe 8 — Autres charges et produits (HAO) ─────────────────
    ("81", "Valeurs comptables des cessions d'immobilisations"),
    ("82", "Produits des cessions d'immobilisations"),
    ("83", "Charges hors activités ordinaires"),
    ("84", "Produits hors activités ordinaires"),
    ("85", "Dotations hors activités ordinaires"),
    ("86", "Reprises hors activités ordinaires"),
    ("87", "Participation des travailleurs"),
    ("88", "Subventions d'équilibre"),
    ("89", "Impôts sur le résultat"),
    ("891", "Impôt sur les bénéfices de l'exercice"),
]


def charger_plan(societe_id) -> int:
    """Insère les comptes SYSCOHADA manquants — n'écrase jamais un compte présent."""
    existants = set(Compte.objects.filter(societe_id=societe_id)
                    .values_list("numero", flat=True))
    crees = 0
    for numero, intitule in PLAN_SYSCOHADA:
        if numero in existants:
            continue
        Compte.objects.create(
            societe_id=societe_id, numero=numero, intitule=intitule, classe=numero[0],
            auxiliaire=numero in COMPTES_AUXILIAIRES, actif=True)
        crees += 1
    return crees
