# Generated by Django 5.1.4 on 2026-09-20 12:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_rh_paie_mensuelle'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Requisition',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('numero', models.CharField(max_length=32, unique=True)),
                        ('societe_id', models.UUIDField()),
                        ('site_id', models.UUIDField(blank=True, null=True)),
                        ('initiateur_id', models.UUIDField()),
                        ('date_requisition', models.DateField(blank=True, null=True)),
                        ('objet', models.TextField()),
                        ('justification', models.TextField(blank=True, null=True)),
                        ('mode_decaissement', models.CharField(default='avance', max_length=24)),
                        ('nature', models.CharField(default='charge', max_length=16)),
                        ('priorite', models.CharField(default='normal', max_length=16)),
                        ('devise', models.CharField(default='USD', max_length=8)),
                        ('taux_jour', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                        ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                        ('montant_total_usd', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                        ('statut', models.CharField(default='brouillon', max_length=32)),
                        ('created_at', models.DateTimeField(blank=True, null=True)),
                    ],
                    options={
                        'db_table': 'requisition',
                        'managed': True,
                        'indexes': [],
                        'constraints': [],
                    },
                ),
                migrations.CreateModel(
                    name='RequisitionLigne',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('requisition_id', models.UUIDField()),
                        ('ordre', models.IntegerField(default=0)),
                        ('compte_impute', models.CharField(blank=True, max_length=16, null=True)),
                        ('code_article', models.CharField(blank=True, max_length=32, null=True)),
                        ('description', models.TextField()),
                        ('unite', models.CharField(blank=True, max_length=32, null=True)),
                        ('quantite', models.DecimalField(decimal_places=3, default=1, max_digits=18)),
                        ('prix_unitaire', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                        ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                        ('devise', models.CharField(default='USD', max_length=8)),
                        ('montant_usd', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                    ],
                    options={
                        'db_table': 'requisition_ligne',
                        'managed': True,
                        'indexes': [],
                        'constraints': [],
                    },
                ),
                migrations.CreateModel(
                    name='RequisitionCommentaire',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('requisition_id', models.UUIDField()),
                        ('auteur_id', models.UUIDField()),
                        ('type', models.CharField(default='commentaire', max_length=32)),
                        ('message', models.TextField()),
                        ('created_at', models.DateTimeField(blank=True, null=True)),
                    ],
                    options={
                        'db_table': 'requisition_commentaire',
                        'managed': True,
                        'indexes': [],
                        'constraints': [],
                    },
                ),
                migrations.CreateModel(
                    name='PalierValidation',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('societe_id', models.UUIDField(blank=True, null=True)),
                        ('type_document', models.CharField(max_length=32)),
                        ('etape', models.CharField(max_length=32)),
                        ('montant_min_usd', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                        ('montant_max_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                        ('libelle', models.CharField(blank=True, max_length=128, null=True)),
                        ('ordre', models.IntegerField(default=0)),
                    ],
                    options={
                        'db_table': 'palier_validation',
                        'managed': True,
                        'indexes': [],
                        'constraints': [],
                    },
                ),
                migrations.CreateModel(
                    name='PalierApprobateur',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('mode', models.CharField(default='conjoint', max_length=16)),
                        ('ordre', models.IntegerField(default=0)),
                        ('palier', models.ForeignKey(db_column='palier_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='approbateurs', to='approbations.paliervalidation')),
                        ('role', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.DO_NOTHING, to='core.role')),
                    ],
                    options={
                        'db_table': 'palier_approbateur',
                        'managed': True,
                        'indexes': [],
                        'constraints': [],
                    },
                ),
                migrations.CreateModel(
                    name='Validation',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('document_type', models.CharField(max_length=32)),
                        ('document_id', models.UUIDField()),
                        ('etape', models.CharField(max_length=32)),
                        ('palier_id', models.UUIDField(blank=True, null=True)),
                        ('role_attendu_id', models.UUIDField(blank=True, null=True)),
                        ('utilisateur_id', models.UUIDField(blank=True, null=True)),
                        ('decision', models.CharField(default='en_attente', max_length=16)),
                        ('mode', models.CharField(default='conjoint', max_length=16)),
                        ('commentaire', models.TextField(blank=True, null=True)),
                        ('canal', models.CharField(blank=True, max_length=16, null=True)),
                        ('decided_at', models.DateTimeField(blank=True, null=True)),
                        ('created_at', models.DateTimeField(blank=True, null=True)),
                    ],
                    options={
                        'db_table': 'validation',
                        'managed': True,
                        'indexes': [],
                        'constraints': [],
                    },
                ),
                migrations.CreateModel(
                    name='BonReception',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('numero', models.CharField(max_length=32, unique=True)),
                        ('ordre_depense_id', models.UUIDField()),
                        ('caisse_id', models.UUIDField(blank=True, null=True)),
                        ('compte_bancaire_id', models.UUIDField(blank=True, null=True)),
                        ('receveur_tiers_id', models.UUIDField()),
                        ('caissier_id', models.UUIDField()),
                        ('date_reception', models.DateTimeField(blank=True, null=True)),
                        ('mode', models.CharField(default='caisse', max_length=16)),
                        ('reference_paiement', models.CharField(blank=True, max_length=64, null=True)),
                        ('devise', models.CharField(default='USD', max_length=8)),
                        ('taux_jour', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                        ('montant', models.DecimalField(decimal_places=2, max_digits=18)),
                        ('montant_usd', models.DecimalField(decimal_places=2, max_digits=18)),
                        ('statut', models.CharField(default='emis', max_length=16)),
                    ],
                    options={
                        'db_table': 'bon_reception',
                        'managed': True,
                        'indexes': [],
                        'constraints': [],
                    },
                ),
                migrations.CreateModel(
                    name='OrdreDepense',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('numero', models.CharField(max_length=32)),
                        ('requisition_id', models.UUIDField()),
                        ('societe_id', models.UUIDField()),
                        ('beneficiaire_tiers_id', models.UUIDField()),
                        ('motif', models.TextField(blank=True, null=True)),
                        ('mode_paiement', models.CharField(default='caisse', max_length=16)),
                        ('mode_decaissement', models.CharField(default='avance', max_length=24)),
                        ('devise', models.CharField(default='USD', max_length=8)),
                        ('taux_jour', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                        ('montant_autorise', models.DecimalField(decimal_places=2, max_digits=18)),
                        ('montant_autorise_usd', models.DecimalField(decimal_places=2, max_digits=18)),
                        ('montant_paye_usd', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                        ('montant_lettres', models.CharField(blank=True, max_length=255, null=True)),
                        ('palier_applique', models.CharField(blank=True, max_length=32, null=True)),
                        ('statut', models.CharField(default='a_valider', max_length=32)),
                        ('created_by', models.UUIDField(blank=True, null=True)),
                        ('created_at', models.DateTimeField(null=True)),
                    ],
                    options={
                        'db_table': 'ordre_depense',
                        'managed': True,
                        'indexes': [],
                        'constraints': [],
                    },
                ),
            ],
        ),
    ]
