# Generated by Django 5.1.4 on 2026-09-20 12:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_rh_paie_mensuelle'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Chambre',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('societe_id', models.UUIDField()),
                        ('numero', models.CharField(max_length=16)),
                        ('categorie', models.CharField(blank=True, max_length=64, null=True)),
                        ('tarif_nuit_usd', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                        ('capacite', models.IntegerField(default=2)),
                        ('etat', models.CharField(default='libre', max_length=16)),
                        ('note', models.CharField(blank=True, max_length=255, null=True)),
                        ('actif', models.BooleanField(default=True)),
                        ('created_by', models.UUIDField(blank=True, null=True)),
                        ('created_at', models.DateTimeField(blank=True, null=True)),
                    ],
                    options={
                        'db_table': 'chambre',
                        'managed': True,
                        'indexes': [],
                        'constraints': [],
                    },
                ),
                migrations.CreateModel(
                    name='Sejour',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('societe_id', models.UUIDField()),
                        ('numero', models.CharField(max_length=32)),
                        ('chambre_id', models.UUIDField()),
                        ('tiers_id', models.UUIDField(blank=True, null=True)),
                        ('client_nom', models.CharField(max_length=128)),
                        ('client_telephone', models.CharField(blank=True, max_length=32, null=True)),
                        ('nb_personnes', models.IntegerField(default=1)),
                        ('date_arrivee', models.DateField()),
                        ('date_depart_prevue', models.DateField()),
                        ('date_depart', models.DateField(blank=True, null=True)),
                        ('tarif_nuit_usd', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                        ('statut', models.CharField(default='reservee', max_length=16)),
                        ('source', models.CharField(default='directe', max_length=16)),
                        ('note', models.CharField(blank=True, max_length=255, null=True)),
                        ('facture_id', models.UUIDField(blank=True, null=True)),
                        ('created_by', models.UUIDField(blank=True, null=True)),
                        ('created_at', models.DateTimeField(blank=True, null=True)),
                    ],
                    options={
                        'db_table': 'sejour',
                        'managed': True,
                        'indexes': [],
                        'constraints': [],
                    },
                ),
                migrations.CreateModel(
                    name='LigneSejour',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('sejour_id', models.UUIDField()),
                        ('date_ligne', models.DateField()),
                        ('designation', models.CharField(max_length=255)),
                        ('qte', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                        ('prix_unitaire', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                        ('montant_usd', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                        ('origine', models.CharField(default='divers', max_length=16)),
                        ('facture_pos_id', models.UUIDField(blank=True, null=True)),
                        ('created_by', models.UUIDField(blank=True, null=True)),
                        ('created_at', models.DateTimeField(blank=True, null=True)),
                    ],
                    options={
                        'db_table': 'ligne_sejour',
                        'managed': True,
                        'indexes': [],
                        'constraints': [],
                    },
                ),
                migrations.CreateModel(
                    name='FicheTechnique',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('societe_id', models.UUIDField()),
                        ('article_id', models.UUIDField()),
                        ('portions', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                        ('note', models.CharField(blank=True, max_length=255, null=True)),
                        ('actif', models.BooleanField(default=True)),
                        ('created_by', models.UUIDField(blank=True, null=True)),
                        ('created_at', models.DateTimeField(blank=True, null=True)),
                    ],
                    options={
                        'db_table': 'fiche_technique',
                        'managed': True,
                        'indexes': [],
                        'constraints': [],
                    },
                ),
                migrations.CreateModel(
                    name='LigneFicheTechnique',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('fiche_id', models.UUIDField()),
                        ('ingredient_article_id', models.UUIDField()),
                        ('qte', models.DecimalField(decimal_places=4, max_digits=18)),
                    ],
                    options={
                        'db_table': 'ligne_fiche_technique',
                        'managed': True,
                        'indexes': [],
                        'constraints': [],
                    },
                ),
                migrations.CreateModel(
                    name='ConsommationCuisine',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('societe_id', models.UUIDField()),
                        ('numero', models.CharField(max_length=32)),
                        ('depot_id', models.UUIDField()),
                        ('date_conso', models.DateField()),
                        ('cout_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                        ('ca_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                        ('nb_plats', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                        ('ecriture_id', models.UUIDField(blank=True, null=True)),
                        ('created_by', models.UUIDField(blank=True, null=True)),
                        ('created_at', models.DateTimeField(blank=True, null=True)),
                    ],
                    options={
                        'db_table': 'consommation_cuisine',
                        'managed': True,
                        'indexes': [],
                        'constraints': [],
                    },
                ),
                migrations.CreateModel(
                    name='LigneConsommationCuisine',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('consommation_id', models.UUIDField()),
                        ('article_id', models.UUIDField()),
                        ('qte', models.DecimalField(decimal_places=4, max_digits=18)),
                        ('valeur', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                    ],
                    options={
                        'db_table': 'ligne_consommation_cuisine',
                        'managed': True,
                        'indexes': [],
                        'constraints': [],
                    },
                ),
            ],
        ),
    ]
