# Generated by Django 5.1.4 on 2026-09-20 12:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_rh_paie_mensuelle'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Course',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('societe_id', models.UUIDField()),
                        ('numero', models.CharField(max_length=32)),
                        ('date_course', models.DateField()),
                        ('client_tiers_id', models.UUIDField()),
                        ('contrat_id', models.UUIDField(blank=True, null=True)),
                        ('camion_id', models.UUIDField(blank=True, null=True)),
                        ('chauffeur_id', models.UUIDField(blank=True, null=True)),
                        ('origine', models.CharField(max_length=255)),
                        ('destination', models.CharField(max_length=255)),
                        ('marchandise', models.CharField(max_length=255)),
                        ('tonnage_prevu', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                        ('tonnage_livre', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                        ('unite', models.CharField(default='tonnes', max_length=32)),
                        ('tarif_mode', models.CharField(default='tonne', max_length=16)),
                        ('prix_unitaire', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                        ('statut', models.CharField(default='brouillon', max_length=16)),
                        ('commande_origine_id', models.UUIDField(blank=True, null=True)),
                        ('heure_depart', models.DateTimeField(blank=True, null=True)),
                        ('heure_retour', models.DateTimeField(blank=True, null=True)),
                        ('incidents', models.TextField(blank=True, null=True)),
                        ('requisition_id', models.UUIDField(blank=True, null=True)),
                        ('st_mode', models.CharField(blank=True, max_length=16, null=True)),
                        ('st_valeur', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                        ('st_cout', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                        ('st_facture_id', models.UUIDField(blank=True, null=True)),
                        ('facture_id', models.UUIDField(blank=True, null=True)),
                        ('valide_par', models.UUIDField(blank=True, null=True)),
                        ('created_by', models.UUIDField(blank=True, null=True)),
                        ('created_at', models.DateTimeField(blank=True, null=True)),
                        ('km_depart', models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True)),
                        ('km_retour', models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True)),
                    ],
                    options={
                        'db_table': 'course',
                        'managed': True,
                        'indexes': [],
                        'constraints': [],
                    },
                ),
                migrations.CreateModel(
                    name='Camion',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('societe_id', models.UUIDField()),
                        ('immatriculation', models.CharField(max_length=32)),
                        ('marque', models.CharField(blank=True, max_length=64, null=True)),
                        ('capacite_tonnes', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                        ('consommation_l_100km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                        ('type', models.CharField(default='propre', max_length=16)),
                        ('proprietaire_tiers_id', models.UUIDField(blank=True, null=True)),
                        ('remuneration_mode', models.CharField(blank=True, max_length=16, null=True)),
                        ('remuneration_valeur', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                        ('statut', models.CharField(default='disponible', max_length=16)),
                        ('motif_immobilisation', models.CharField(blank=True, max_length=255, null=True)),
                        ('immobilise_depuis', models.DateField(blank=True, null=True)),
                        ('actif', models.BooleanField(default=True)),
                    ],
                    options={
                        'db_table': 'camion',
                        'managed': True,
                        'indexes': [],
                        'constraints': [],
                    },
                ),
                migrations.CreateModel(
                    name='Chauffeur',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('societe_id', models.UUIDField()),
                        ('nom', models.CharField(max_length=128)),
                        ('telephone', models.CharField(blank=True, max_length=32, null=True)),
                        ('numero_permis', models.CharField(blank=True, max_length=64, null=True)),
                        ('tiers_id', models.UUIDField(blank=True, null=True)),
                        ('actif', models.BooleanField(default=True)),
                    ],
                    options={
                        'db_table': 'chauffeur',
                        'managed': True,
                        'indexes': [],
                        'constraints': [],
                    },
                ),
                migrations.CreateModel(
                    name='ContratTransport',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('societe_id', models.UUIDField()),
                        ('numero', models.CharField(max_length=32)),
                        ('libelle', models.CharField(max_length=128)),
                        ('client_tiers_id', models.UUIDField()),
                        ('date_debut', models.DateField()),
                        ('date_fin', models.DateField(blank=True, null=True)),
                        ('statut', models.CharField(default='actif', max_length=16)),
                        ('note', models.TextField(blank=True, null=True)),
                        ('created_by', models.UUIDField(blank=True, null=True)),
                        ('created_at', models.DateTimeField(blank=True, null=True)),
                    ],
                    options={
                        'db_table': 'contrat_transport',
                        'managed': True,
                        'indexes': [],
                        'constraints': [],
                    },
                ),
                migrations.CreateModel(
                    name='TarifContrat',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('contrat_id', models.UUIDField()),
                        ('trajet', models.CharField(max_length=128)),
                        ('mode', models.CharField(default='tonne', max_length=16)),
                        ('prix', models.DecimalField(decimal_places=2, max_digits=18)),
                    ],
                    options={
                        'db_table': 'tarif_contrat',
                        'managed': True,
                        'indexes': [],
                        'constraints': [],
                    },
                ),
                migrations.CreateModel(
                    name='CourseRequisition',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('course_id', models.UUIDField()),
                        ('requisition_id', models.UUIDField()),
                    ],
                    options={
                        'db_table': 'course_requisition',
                        'managed': True,
                        'indexes': [],
                        'constraints': [],
                    },
                ),
                migrations.CreateModel(
                    name='PleinCarburant',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('societe_id', models.UUIDField()),
                        ('camion_id', models.UUIDField(blank=True, null=True)),
                        ('engin_id', models.UUIDField(blank=True, null=True)),
                        ('course_id', models.UUIDField(blank=True, null=True)),
                        ('date_plein', models.DateField()),
                        ('litres', models.DecimalField(decimal_places=2, max_digits=10)),
                        ('prix_litre_usd', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                        ('montant_usd', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                        ('compteur', models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True)),
                        ('fournisseur', models.CharField(blank=True, max_length=128, null=True)),
                        ('note', models.CharField(blank=True, max_length=255, null=True)),
                        ('created_by', models.UUIDField(blank=True, null=True)),
                        ('created_at', models.DateTimeField(blank=True, null=True)),
                    ],
                    options={
                        'db_table': 'plein_carburant',
                        'managed': True,
                        'indexes': [],
                        'constraints': [],
                    },
                ),
            ],
        ),
    ]
