export interface FinancialLine { poste: string; intitule: string; montant: number; montant_n1: number }
export interface IncomeStatement { annee: number; sections: ({ titre: string; lignes: FinancialLine[]; total: number; total_n1: number } | { solde: string; montant: number; montant_n1: number; fort: boolean })[]; resultat_net: number; resultat_net_n1: number; chiffre_affaires: number; chiffre_affaires_n1: number }
export interface BalanceSheet { annee: number; equilibre: boolean; ecart: number; actif: { immobilise: { total: number; total_n1: number; lignes: FinancialLine[] }; circulant: { total: number; total_n1: number; stocks: number; stocks_n1: number; creances: number; creances_n1: number }; tresorerie: number; tresorerie_n1: number; total: number; total_n1: number }; passif: { capitaux_propres: { total: number; total_n1: number; capital_reserves: number; capital_reserves_n1: number; resultat_net: number; resultat_net_n1: number }; dettes_financieres: number; dettes_financieres_n1: number; passif_circulant: number; passif_circulant_n1: number; tresorerie: number; tresorerie_n1: number; total: number; total_n1: number } }
export interface CashFlowStatement { annee: number; tresorerie_ouverture: number; flux: { titre: string; total: number; lignes: { libelle: string; montant: number }[] }[]; variation: number; tresorerie_cloture: number; controle: boolean }
export interface FinancialOverview { tresorerie: { caisse: number; banque: number; total: number }; chiffre_affaires: number; charges: number; resultat: number; creances_clients: number; dettes_fournisseurs: number; tva_a_payer: number; avances_en_cours: number; pieces_en_attente: number }
export interface StatementRow { label: string; values: number[]; kind?: 'section' | 'total' }
export function incomeRows(d: IncomeStatement): StatementRow[] {
  return [...d.sections.flatMap(s => 'solde' in s ? [{ label: s.solde, values: [s.montant, s.montant_n1], kind: 'total' as const }] : [{ label: s.titre, values: [s.total, s.total_n1], kind: 'section' as const }, ...s.lignes.map(l => ({ label: `${l.poste} — ${l.intitule}`, values: [l.montant, l.montant_n1] }))]), { label: 'RÉSULTAT NET DE L’EXERCICE', values: [d.resultat_net, d.resultat_net_n1], kind: 'total' }];
}
export function balanceSheetRows(d: BalanceSheet): StatementRow[] {
  const a = d.actif, p = d.passif;
  return [{ label: 'ACTIF IMMOBILISÉ', values: [a.immobilise.total, a.immobilise.total_n1], kind: 'section' }, ...a.immobilise.lignes.map(l => ({ label: `${l.poste} — ${l.intitule}`, values: [l.montant, l.montant_n1] })),
    { label: 'Actif circulant', values: [a.circulant.total, a.circulant.total_n1], kind: 'section' }, { label: 'Stocks', values: [a.circulant.stocks, a.circulant.stocks_n1] }, { label: 'Créances', values: [a.circulant.creances, a.circulant.creances_n1] }, { label: 'Trésorerie — actif', values: [a.tresorerie, a.tresorerie_n1] }, { label: 'TOTAL ACTIF', values: [a.total, a.total_n1], kind: 'total' },
    { label: 'PASSIF — CAPITAUX PROPRES', values: [p.capitaux_propres.total, p.capitaux_propres.total_n1], kind: 'section' }, { label: 'Capital et réserves', values: [p.capitaux_propres.capital_reserves, p.capitaux_propres.capital_reserves_n1] }, { label: 'Résultat', values: [p.capitaux_propres.resultat_net, p.capitaux_propres.resultat_net_n1] }, { label: 'Dettes financières', values: [p.dettes_financieres, p.dettes_financieres_n1] }, { label: 'Passif circulant', values: [p.passif_circulant, p.passif_circulant_n1] }, { label: 'Trésorerie — passif', values: [p.tresorerie, p.tresorerie_n1] }, { label: 'TOTAL PASSIF', values: [p.total, p.total_n1], kind: 'total' }];
}
export function cashFlowRows(d: CashFlowStatement): StatementRow[] {
  return [{ label: 'Trésorerie nette à l’ouverture', values: [d.tresorerie_ouverture], kind: 'total' }, ...d.flux.flatMap(f => [{ label: f.titre, values: [f.total], kind: 'section' as const }, ...f.lignes.map(l => ({ label: l.libelle, values: [l.montant] }))]), { label: 'VARIATION DE TRÉSORERIE', values: [d.variation], kind: 'total' }, { label: 'TRÉSORERIE NETTE À LA CLÔTURE', values: [d.tresorerie_cloture], kind: 'total' }];
}
