export const moduleGuides = [
    {name:"Suivi & traçabilité", views:["pilotage","audit"],
      purpose:"Repérez les tâches en attente et retrouvez l'historique des actions.",
      tip:"Le suivi conserve les circuits de validation existants. Le journal permet de rechercher les actions selon les droits du compte connecté.", links:["pilotage","audit","approbation"]},
    {name:"Inventaires", views:["inventaires"],
      purpose:"Préparez le comptage physique et examinez les écarts avant validation.",
      tip:"Le comptage ne modifie pas immédiatement le stock. La validation comptable ou DFI applique les écarts selon le circuit existant.", links:["inventaires","stock","depots","compta"]},
    {name:"TVA mensuelle", views:["tva"],
      purpose:"Vérifiez la société, la période et les pièces du dossier mensuel.",
      tip:"Les taux et exonérations restent ceux des articles et documents enregistrés. Contrôlez les pièces en attente avant de finaliser le dossier.", links:["tva","compta","achats","ventes"]},
    {name:"Ressources humaines", views:["rh","rh-simulateur","rh-decomptes","rh-finances","rh-paiements","rh-mensuel"],
      purpose:"Suivez les dossiers agents, les pointages et les étapes de la paie.",
      tip:"Vérifiez la société et la période. Une simulation reste une proposition ; les validations et paiements suivent les circuits autorisés.", links:["rh","rh-simulateur","rh-mensuel","rh-finances","rh-paiements","rh-decomptes"]},
    {name:"Demandes & validations", views:["requisitions","nouvelle-req","approbation"],
      purpose:"Retrouvez la demande, son avancement et les échanges avant d'agir.",
      tip:"Une demande validée passe ensuite à l'ordre de dépense. Les précisions demandées se répondent depuis la réquisition.", links:["requisitions","approbation","ordres"]},
    {name:"Décaissements & avances", views:["ordres","avances","caisse-exec"],
      purpose:"Suivez les autorisations de paiement et les avances restant à justifier.",
      tip:"Un ordre autorise la sortie de fonds ; une avance conserve son échéance de justification. Le paiement direct suit son circuit existant.", links:["ordres","avances","caisse"]},
    {name:"Trésorerie", views:["caisse","transferts"],
      purpose:"Gardez le lien entre les sessions de caisse, leurs mouvements et les transferts.",
      tip:"Vérifiez la caisse et la devise sélectionnées. Les soldes du journal suivent l'ordre chronologique des mouvements.", links:["caisse","transferts","rapprochement"]},
    {name:"Point de vente", views:["pos","tarifs-pos"],
      purpose:"Préparez les articles et les tarifs du point de vente avant l'encaissement.",
      tip:"Contrôlez le point de vente, le client et les modes de règlement dans le panier. Les tarifs et les dépôts restent définis par vos réglages.", links:["pos","tarifs-pos","articles"]},
    {name:"Achats", views:["commandes","receptions","achats"],
      purpose:"Suivez la commande fournisseur, la réception physique et la facture.",
      tip:"La commande, les quantités reçues et la facture sont des étapes distinctes. Utilisez le document d'origine pour poursuivre le circuit.", links:["commandes","receptions","achats","stock"]},
    {name:"Ventes", views:["devis","ventes","rapports-commercial"],
      purpose:"Retrouvez le client, l'avancement de la livraison et les règlements.",
      tip:"Passez du devis à la commande, puis aux livraisons et à la facture selon le circuit existant. Les ventes et les encaissements ne représentent pas le même indicateur.", links:["devis","ventes","rapports-commercial"]},
    {name:"Stocks & dépôts", views:["stock","depots","articles"],
      purpose:"Consultez les quantités, leur valeur et les mouvements par dépôt.",
      tip:"Le coût moyen pondéré valorise le stock. Un transfert déplace des quantités entre dépôts ; l'inventaire compare le physique au théorique.", links:["stock","depots","articles"]},
    {name:"Transport", views:["courses","flotte","contrats-transport","config-transport"],
      purpose:"Gardez le fil entre les courses, les camions et les contrats.",
      tip:"La fiche de course rassemble les étapes de validation, départ, arrivée et retour. Les coûts et la facturation restent associés au circuit existant.", links:["courses","flotte","contrats-transport","carburant"]},
    {name:"Location d'engins", views:["engins-parc","engins-heures","engins-rpe","config-engins"],
      purpose:"Passez du parc aux heures prestées, puis au relevé mensuel.",
      tip:"Vérifiez la période et l'engin avant de saisir des heures ou d'examiner le RPE. Les forfaits et tarifs restent ceux de votre configuration.", links:["engins-parc","engins-heures","engins-rpe"]},
    {name:"Maintenance & documents", views:["maintenance-parc","maintenance-interventions","flotte-documents","config-maintenance"],
      purpose:"Repérez les échéances et retrouvez l'intervention du véhicule concerné.",
      tip:"Les états et seuils affichés proviennent des plans existants. Une intervention et un document administratif ont des échéances distinctes.", links:["maintenance-parc","maintenance-interventions","flotte-documents"]},
    {name:"Carburant", views:["carburant"],
      purpose:"Comparez les pleins, l'usage et la consommation de chaque véhicule.",
      tip:"Vérifiez la période et l'unité : litres aux 100 km pour les camions, litres à l'heure pour les engins. L'écart dépend des relevés enregistrés.", links:["carburant","courses","engins-heures"]},
    {name:"Hôtel", views:["hotel-reception","hotel-chambres","config-hotel"],
      purpose:"Visualisez les séjours et préparez les chambres pour les prochaines arrivées.",
      tip:"Le planning affiche les réservations de la période choisie. Les indicateurs du jour et du mois gardent leur période propre. Ouvrez un séjour pour consulter sa note.", links:["hotel-reception","hotel-chambres","cuisine"]},
    {name:"Cuisine", views:["cuisine"],
      purpose:"Lisez les fiches recettes, leurs coûts et les consommations théoriques.",
      tip:"Le coût théorique repose sur les fiches et les ventes enregistrées. Comparez-le au comptage physique des dépôts pour examiner les écarts.", links:["cuisine","depots","pos"]},
    {name:"Opérations intersociétés", views:["intersociete"],
      purpose:"Rapprochez les deux côtés d'une opération et suivez ses documents liés.",
      tip:"Les positions concernent des sociétés distinctes. Vérifiez les documents d'origine et les réceptions avant d'interpréter un écart.", links:["intersociete","commandes","devis","courses"]},
    {name:"Comptabilité & pilotage", views:["dashboard","compta","balance","grand-livre","saisie-od","plan-comptable","lettrage","rapprochement","analytique","cockpit","etats"],
      purpose:"Retrouvez la pièce d'origine et vérifiez la société, la période et les comptes.",
      tip:"Les pièces en attente suivent la validation comptable existante. Les états et leurs totaux portent sur les critères propres à chaque rapport.", links:["compta","grand-livre","balance","cockpit"]},
    {name:"Administration & paramètres", views:["administration","config","taux"],
      purpose:"Consultez les sociétés, les agents, les rôles et les réglages de gestion.",
      tip:"Une modification des paliers, comptes ou affectations agit sur les opérations futures. Vérifiez la société et la portée du réglage avant de l'enregistrer.", links:["administration","config","taux"]},
  ];
