from django.urls import path, include
from core import config_views as config_views
from core import views as views

urlpatterns = [
    path("auth/login", views.login),
    path("auth/me", views.me),
    path("societes", views.mes_societes),
    path("tiers", views.lister_tiers),
    path("taux", views.definir_taux),
    path("config/roles", config_views.roles),
    path("config/roles/<uuid:role_id>", config_views.role_detail),
    path("config/societes", config_views.societes_config),
    path("config/societes/<uuid:societe_id>", config_views.societe_detail),
    path("config/paliers", config_views.paliers),
    path("config/paliers/<uuid:palier_id>", config_views.palier_detail),
    path("config/parametres", config_views.parametres),
    path("config/parametres/<uuid:parametre_id>", config_views.modifier_parametre),
    path("config/intervenants", config_views.intervenants),
    path("config/utilisateurs", config_views.utilisateurs),
    path("config/utilisateurs/<uuid:utilisateur_id>", config_views.maj_utilisateur),
    path("config/affectations", config_views.affectations),
    path("pieces-jointes", config_views.pieces_jointes),
    path("pieces-jointes/<uuid:piece_id>/download", config_views.telecharger_piece),
    path("", include("apps.approbations.urls")),
    path("", include("apps.tresorerie.urls")),
    path("", include("apps.comptabilite.urls")),
    path("", include("apps.stocks.urls")),
    path("", include("apps.commercial.urls")),
    path("", include("apps.hotel.urls")),
    path("", include("apps.transport.urls")),
    path("", include("apps.maintenance.urls")),
    path("", include("apps.engins.urls")),
    path("", include("apps.groupe.urls")),
    path("", include("apps.rh.urls")),
    path("", include("apps.pilotage.urls")),
    path("", include("apps.editions.urls")),
]
