from django.urls import path
from . import rh_views
from . import rh_finances
from . import rh_paie_views
from . import rh_mensuel_views
from . import editions
from . import pilotage

from . import (analytique_views, beneficiaires, caisse_views, carburant_views, commercial_views,
               compta_views, config_views, cuisine_views, decaissements_views,
               depots_views, documents_views, engins_views, hotel_views,
               intersociete_views, maintenance_views, transport_views,
               ventes_views, views, tva_views, inventaires_views)

urlpatterns = [
    path('pilotage/taches', pilotage.taches),
    path('pilotage/delais', pilotage.parametres),
    path('editions/societe', editions.societe),
    path('editions/telecharger', editions.telecharger),
    path('rh/paies', rh_mensuel_views.periodes),
    path('rh/paies/<uuid:periode_id>', rh_mensuel_views.detail),
    path('rh/paies/<uuid:periode_id>/preparer', rh_mensuel_views.preparer),
    path('rh/paies/<uuid:periode_id>/decision', rh_mensuel_views.decision),
    path('rh/bulletins/<uuid:bulletin_id>/payer', rh_mensuel_views.payer),
    path('rh/contrats/<uuid:contrat_id>/composition', rh_mensuel_views.composition),
    path('rh/simuler', rh_paie_views.simuler),
    path('rh/simulations', rh_paie_views.simulations),
    path('rh/decomptes', rh_paie_views.decomptes),
    path('rh/politique', rh_finances.parametres),
    path('rh/avances-a-justifier', rh_finances.sources),
    path('rh/dettes', rh_finances.dettes),
    path('rh/dettes/<uuid:dette_id>/decision', rh_finances.decision),
    path('rh/dettes/<uuid:dette_id>/accord', rh_finances.accord),
    path('rh/a-payer', rh_finances.a_payer),
    path('rh/dettes/<uuid:dette_id>/verser', rh_finances.verser),
    path('rh/organisation', rh_views.organisation),
    path('rh/agents', rh_views.agents),
    path('rh/agents/<uuid:agent_id>/dossier', rh_views.dossier),
    path('rh/agents/<uuid:agent_id>/documents', rh_views.documents),
    path('rh/documents/<uuid:document_id>', rh_views.document),
    path('rh/pointages', rh_views.pointages),
    path('rh/pointages/<uuid:pointage_id>/decision', rh_views.pointage_decision),
    path('rh/demandes', rh_views.demandes),
    path("comptabilite/tva-mensuelle", tva_views.preparation),
    path("comptabilite/tva-mensuelle/dossier", tva_views.dossier),
    path("beneficiaires", beneficiaires.beneficiaires),
    path("hotel/clients", hotel_views.clients),
    path("auth/login", views.login),
    path("auth/me", views.me),
    path("societes", views.mes_societes),
    path("tiers", views.lister_tiers),
    path("caisses", caisse_views.caisses),
    path("caisses/<uuid:caisse_id>", caisse_views.maj_caisse),
    # ── Dépôts & transferts internes (central → dédiés) ───────────────
    path("stock/depots", depots_views.depots),
    path("stock/depots/<uuid:depot_id>", depots_views.maj_depot),
    path("stock/depots-etat", depots_views.etat_depot),
    path("stock/transferts", depots_views.transferts),
    path("stock/inventaires", inventaires_views.inventaires),
    path("stock/inventaires/<uuid:inventaire_id>/decision", inventaires_views.decision),
    # ── Cuisine : fiches techniques, conso théorique, food cost ───────
    path("cuisine/config", cuisine_views.config_cuisine),
    path("cuisine/fiches", cuisine_views.fiches),
    path("cuisine/fiches/<uuid:fiche_id>", cuisine_views.supprimer_fiche),
    path("cuisine/consommations", cuisine_views.consommations),
    path("cuisine/rapport", cuisine_views.rapport_cuisine),
    path("comptes-bancaires", views.lister_banques),
    path("taux", views.definir_taux),
    # ── Décaissements G01→G04 (parité avec requisitions/ordres_depense/avances) ─
    path("requisitions", decaissements_views.requisitions),
    path("requisitions/<uuid:requisition_id>/detail", decaissements_views.requisition_detail),
    path("requisitions/<uuid:requisition_id>/commentaires", decaissements_views.requisition_commentaires),
    path("requisitions/<uuid:requisition_id>/demander-precisions", decaissements_views.demander_precisions),
    path("requisitions/<uuid:requisition_id>/repondre", decaissements_views.repondre),
    path("requisitions/<uuid:requisition_id>/valider-demande", decaissements_views.valider_demande),
    path("ordres-depense", decaissements_views.ordres_depense),
    path("ordres-depense/<uuid:ordre_id>/valider", decaissements_views.valider_sortie),
    path("ordres-depense/<uuid:ordre_id>/executer", decaissements_views.executer),
    path("ordres-depense/<uuid:ordre_id>/bon-sortie", decaissements_views.bon_sortie),
    path("avances", decaissements_views.lister_avances),
    path("avances/justifier", decaissements_views.justifier),
    path("avances/verifier-retards", decaissements_views.verifier_retards),
    path("avances/blocages/<uuid:blocage_id>/lever", decaissements_views.lever_blocage),
    path("approbations", decaissements_views.centre_approbation),
    path("dashboard", decaissements_views.dashboard),
    # ── Caisses & transferts (parité avec caisse.py + transferts.py) ─
    path("caisse/journal", caisse_views.caisse_journal),
    path("caisse/session/<uuid:session_id>/rapport-z", caisse_views.rapport_z),
    path("caisse/mouvement/<uuid:mvt_id>/bon", caisse_views.bon_mouvement),
    path("caisse/<uuid:caisse_id>/ouvrir", caisse_views.ouvrir),
    path("caisse/<uuid:caisse_id>/session", caisse_views.session_courante),
    path("caisse/<uuid:caisse_id>/mouvement", caisse_views.mouvement),
    path("caisse/<uuid:caisse_id>/operation", caisse_views.operation),
    path("caisse/<uuid:caisse_id>/journal", caisse_views.journal_session),
    path("caisse/<uuid:caisse_id>/cloturer", caisse_views.cloturer),
    path("transferts", caisse_views.transferts),
    path("transferts/<uuid:transfert_id>/valider", caisse_views.valider_transfert),
    path("transferts/<uuid:transfert_id>/rejeter", caisse_views.rejeter_transfert),
    # ── Commercial & POS (parité avec commercial.py) ─────────────────
    path("commercial/articles", commercial_views.articles),
    path("commercial/articles/<uuid:article_id>", commercial_views.maj_article),
    path("commercial/articles/<uuid:article_id>/prix", commercial_views.prix_article),
    path("commercial/tiers", commercial_views.tiers_commercial),
    path("commercial/tiers/<uuid:tiers_id>", commercial_views.maj_tiers),
    path("commercial/factures", commercial_views.factures),
    path("commercial/factures/<uuid:facture_id>", commercial_views.detail_facture),
    path("commercial/stock", commercial_views.etat_stock),
    path("commercial/stock/mouvements", commercial_views.mouvements_stock),
    path("commercial/achats-historique", commercial_views.achats_historique),
    path("commercial/ventes-synthese", commercial_views.ventes_synthese),
    path("commercial/commandes", commercial_views.commandes),
    path("commercial/commandes/<uuid:commande_id>", commercial_views.commande_detail),
    path("commercial/commandes/<uuid:commande_id>/annuler", commercial_views.annuler_commande),
    path("commercial/commandes/<uuid:commande_id>/receptionner", commercial_views.receptionner),
    path("commercial/receptions", commercial_views.lister_receptions),
    path("commercial/receptions/<uuid:reception_id>", commercial_views.detail_reception),
    path("commercial/receptions/<uuid:reception_id>/facturer", commercial_views.facturer_reception),
    path("commercial/listes-prix", commercial_views.listes_prix),
    path("commercial/listes-prix/<uuid:liste_id>/tarifs", commercial_views.tarifs_liste),
    path("commercial/points-vente", commercial_views.points_vente),
    path("commercial/points-vente/<uuid:pv_id>", commercial_views.maj_point_vente),
    path("commercial/pos/contexte", commercial_views.pos_contexte),
    path("commercial/pos/vente", commercial_views.pos_vente),
    path("commercial/pos/tickets", commercial_views.pos_tickets),
    path("commercial/pos/ticket/<uuid:facture_id>", commercial_views.pos_ticket),
    path("commercial/pos/retour", commercial_views.pos_retour),
    path("commercial/pos/rapport", commercial_views.pos_rapport),
    # ── Ventes (parité avec ventes.py) ───────────────────────────────
    path("ventes/devis", ventes_views.devis),
    path("ventes/devis/<uuid:devis_id>", ventes_views.devis_detail),
    path("ventes/devis/<uuid:devis_id>/envoyer", ventes_views.envoyer_devis),
    path("ventes/devis/<uuid:devis_id>/confirmer", ventes_views.confirmer_devis),
    path("ventes/devis/<uuid:devis_id>/associer", ventes_views.associer_articles),
    path("ventes/devis/<uuid:devis_id>/reference-producteur", ventes_views.maj_reference_producteur),
    path("ventes/devis/<uuid:devis_id>/annuler", ventes_views.annuler_devis),
    path("ventes/devis/<uuid:devis_id>/livrer", ventes_views.livrer),
    path("ventes/devis/<uuid:devis_id>/facturer", ventes_views.facturer),
    path("ventes/factures/<uuid:facture_id>/regler", ventes_views.regler_facture),
    path("ventes/encours", ventes_views.encours_clients),
    # ── Intersociétés (parité avec intersociete.py) ──────────────────
    path("intersociete/commandes/<uuid:commande_id>/receptionner", intersociete_views.receptionner_po),
    path("intersociete/receptions", intersociete_views.receptions_intersociete),
    path("intersociete/receptions/<uuid:reception_id>", intersociete_views.reception_detail_ou_annulation),
    path("intersociete/receptions/<uuid:reception_id>/confirmer", intersociete_views.confirmer_reception),
    path("intersociete/tracer", intersociete_views.tracer),
    path("intersociete/badges", intersociete_views.badges),
    path("intersociete/liaisons", intersociete_views.liaisons),
    path("intersociete/lier", intersociete_views.lier_tiers),
    path("intersociete/positions", intersociete_views.positions),
    path("intersociete/factures", intersociete_views.factures_intragroupe),
    path("intersociete/factures/<uuid:facture_id>/regler", intersociete_views.regler_intersociete),
    # ── Transport (parité avec transport.py) ─────────────────────────
    path("transport/config", transport_views.config_transport),
    path("transport/camions", transport_views.camions),
    path("transport/camions/<uuid:camion_id>", transport_views.maj_camion),
    path("transport/chauffeurs", transport_views.chauffeurs),
    path("transport/contrats", transport_views.contrats),
    path("transport/contrats/<uuid:contrat_id>", transport_views.modifier_contrat),
    path("transport/courses", transport_views.courses),
    path("transport/courses/<uuid:course_id>/prendre-en-charge", transport_views.prendre_en_charge),
    path("transport/courses/<uuid:course_id>/lier-requisition", transport_views.lier_requisition),
    path("transport/courses/<uuid:course_id>/valider", transport_views.valider_course),
    path("transport/courses/<uuid:course_id>/depart", transport_views.depart_course),
    path("transport/courses/<uuid:course_id>/arrivee", transport_views.arrivee_course),
    path("transport/courses/<uuid:course_id>/retour", transport_views.retour_course),
    path("transport/courses/<uuid:course_id>/annuler", transport_views.annuler_course),
    path("transport/facturer", transport_views.facturer_courses),
    path("transport/interventions", transport_views.interventions),
    path("transport/interventions/<uuid:intervention_id>/demarrer", transport_views.demarrer_intervention),
    path("transport/interventions/<uuid:intervention_id>/terminer", transport_views.terminer_intervention),
    path("transport/rapport", transport_views.rapport_transport),
    # ── Location d'engins (heures prestées, RPE, facturation) ────────
    path("engins/config", engins_views.config_engins),
    path("engins/engins", engins_views.engins),
    path("engins/engins/<uuid:engin_id>", engins_views.maj_engin),
    path("engins/prestations", engins_views.prestations),
    path("engins/prestations/<uuid:prestation_id>", engins_views.maj_prestation),
    path("engins/rpe", engins_views.rpe),
    path("engins/facturer", engins_views.facturer),
    # ── Maintenance (métier séparé : parc transversal, plans, échéances) ─
    path("maintenance/parc", maintenance_views.parc),
    path("maintenance/plans", maintenance_views.plans),
    path("maintenance/plans/<uuid:plan_id>", maintenance_views.maj_plan),
    path("maintenance/plans/<uuid:plan_id>/planifier", maintenance_views.planifier),
    # ── Documents & échéances de la flotte (camions, engins, chauffeurs) ─
    path("flotte/documents", documents_views.documents),
    path("flotte/documents/<uuid:document_id>", documents_views.maj_document),
    # ── Suivi carburant (pleins + conso réelle vs théorique) ──────────
    path("carburant/pleins", carburant_views.pleins),
    path("carburant/pleins/<uuid:plein_id>", carburant_views.maj_plein),
    path("carburant/rapport", carburant_views.rapport),
    # ── Hôtellerie GHR (chambres, séjours, folio, check-out) ──────────
    path("hotel/chambres", hotel_views.chambres),
    path("hotel/chambres/<uuid:chambre_id>", hotel_views.maj_chambre),
    path("hotel/sejours", hotel_views.sejours),
    path("hotel/sejours/<uuid:sejour_id>", hotel_views.maj_sejour),
    path("hotel/sejours/<uuid:sejour_id>/checkin", hotel_views.checkin),
    path("hotel/sejours/<uuid:sejour_id>/annuler", hotel_views.annuler_sejour),
    path("hotel/sejours/<uuid:sejour_id>/folio", hotel_views.folio),
    path("hotel/sejours/<uuid:sejour_id>/lignes", hotel_views.ajouter_ligne),
    path("hotel/sejours/<uuid:sejour_id>/lignes/<uuid:ligne_id>", hotel_views.supprimer_ligne),
    path("hotel/sejours/<uuid:sejour_id>/checkout", hotel_views.checkout),
    path("hotel/planning", hotel_views.planning),
    path("hotel/rapport", hotel_views.rapport_hotel),
    # ── Paramétrage & administration (parité avec config.py) ─────────
    path("config/roles", config_views.roles),
    path("config/roles/<uuid:role_id>", config_views.role_detail),
    path("config/societes", config_views.societes_config),
    path("config/societes/<uuid:societe_id>", config_views.societe_detail),
    path("config/paliers", config_views.paliers),
    path("config/paliers/<uuid:palier_id>", config_views.palier_detail),
    path("config/parametres", config_views.parametres),
    path("config/parametres/<uuid:parametre_id>", config_views.modifier_parametre),
    path("config/intervenants", config_views.intervenants),
    path("config/utilisateurs", config_views.utilisateurs),
    path("config/utilisateurs/<uuid:utilisateur_id>", config_views.maj_utilisateur),
    path("config/affectations", config_views.affectations),
    # ── Pièces jointes (parité avec pieces_jointes.py) ───────────────
    path("pieces-jointes", config_views.pieces_jointes),
    path("pieces-jointes/<uuid:piece_id>/download", config_views.telecharger_piece),
    # ── Comptabilité (parité avec routers/compta.py) ────────────────
    path("comptabilite/balance", views.balance),
    path("comptabilite/ecritures", compta_views.lister_ecritures),
    path("comptabilite/ecritures/saisie", compta_views.saisir_ecriture),
    path("comptabilite/ecritures/<uuid:ecriture_id>/valider", compta_views.valider_ecriture),
    path("comptabilite/grand-livre", compta_views.grand_livre),
    path("comptabilite/plan-comptable", compta_views.plan_comptable),
    path("comptabilite/plan-comptable/charger-syscohada", compta_views.charger_syscohada),
    path("comptabilite/plan-comptable/<uuid:compte_id>", compta_views.maj_compte),
    path("comptabilite/journaux", compta_views.journaux),
    path("comptabilite/lettrage", compta_views.lettrage),
    path("comptabilite/delettrage", compta_views.delettrer),
    path("comptabilite/rapprochement", compta_views.rapprochement),
    path("comptabilite/rapprochement/a-pointer", compta_views.rappro_a_pointer),
    path("comptabilite/rapprochement/<uuid:rappro_id>/annuler", compta_views.annuler_rapprochement),
    path("comptabilite/compte-resultat", compta_views.compte_resultat),
    path("comptabilite/bilan", compta_views.bilan),
    path("comptabilite/tft", compta_views.tft),
    path("comptabilite/cockpit", compta_views.cockpit),
    path("comptabilite/comptes-config", compta_views.comptes_config),
    path("comptabilite/revue-config", compta_views.revue_config),
    # ── Analytique (parité avec routers/analytique.py) ──────────────
    path("analytique/axes", analytique_views.axes),
    path("analytique/axes/<uuid:axe_id>/sections", analytique_views.creer_section),
    path("analytique/sections/<uuid:section_id>", analytique_views.maj_section),
    path("analytique/lignes", analytique_views.lignes_a_ventiler),
    path("analytique/ventiler", analytique_views.ventiler),
    path("analytique/rapport", analytique_views.rapport),
]
