# Generated by Django 5.1.4 on 2026-09-20 12:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_rh_paie_mensuelle'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='InterventionCamion',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('societe_id', models.UUIDField()),
                        ('camion_id', models.UUIDField(blank=True, null=True)),
                        ('numero', models.CharField(max_length=32)),
                        ('type', models.CharField(default='reparation', max_length=16)),
                        ('statut', models.CharField(default='signalee', max_length=16)),
                        ('description', models.TextField()),
                        ('prestataire', models.CharField(blank=True, max_length=128, null=True)),
                        ('cout_estime', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                        ('cout_reel', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                        ('immobilise', models.BooleanField(default=True)),
                        ('date_signalement', models.DateField()),
                        ('date_fin', models.DateField(blank=True, null=True)),
                        ('requisition_id', models.UUIDField(blank=True, null=True)),
                        ('created_by', models.UUIDField(blank=True, null=True)),
                        ('created_at', models.DateTimeField(blank=True, null=True)),
                        ('date_prevue', models.DateField(blank=True, null=True)),
                        ('engin_id', models.UUIDField(blank=True, null=True)),
                        ('plan_id', models.UUIDField(blank=True, null=True)),
                    ],
                    options={
                        'db_table': 'intervention_camion',
                        'managed': True,
                        'indexes': [],
                        'constraints': [],
                    },
                ),
                migrations.CreateModel(
                    name='DocumentFlotte',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('societe_id', models.UUIDField()),
                        ('camion_id', models.UUIDField(blank=True, null=True)),
                        ('engin_id', models.UUIDField(blank=True, null=True)),
                        ('chauffeur_id', models.UUIDField(blank=True, null=True)),
                        ('type_document', models.CharField(default='autre', max_length=32)),
                        ('libelle', models.CharField(max_length=128)),
                        ('numero', models.CharField(blank=True, max_length=64, null=True)),
                        ('date_emission', models.DateField(blank=True, null=True)),
                        ('date_expiration', models.DateField(blank=True, null=True)),
                        ('note', models.CharField(blank=True, max_length=255, null=True)),
                        ('created_by', models.UUIDField(blank=True, null=True)),
                        ('created_at', models.DateTimeField(blank=True, null=True)),
                    ],
                    options={
                        'db_table': 'document_flotte',
                        'managed': True,
                        'indexes': [],
                        'constraints': [],
                    },
                ),
                migrations.CreateModel(
                    name='PlanEntretien',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('societe_id', models.UUIDField()),
                        ('camion_id', models.UUIDField(blank=True, null=True)),
                        ('engin_id', models.UUIDField(blank=True, null=True)),
                        ('libelle', models.CharField(max_length=128)),
                        ('periodicite_type', models.CharField(default='heures', max_length=16)),
                        ('periodicite_valeur', models.DecimalField(decimal_places=1, max_digits=12)),
                        ('derniere_date', models.DateField(blank=True, null=True)),
                        ('derniere_valeur', models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True)),
                        ('note', models.CharField(blank=True, max_length=255, null=True)),
                        ('actif', models.BooleanField(default=True)),
                        ('created_by', models.UUIDField(blank=True, null=True)),
                        ('created_at', models.DateTimeField(blank=True, null=True)),
                    ],
                    options={
                        'db_table': 'plan_entretien',
                        'managed': True,
                        'indexes': [],
                        'constraints': [],
                    },
                ),
            ],
        ),
    ]
