# Generated by Django 5.1.4 on 2026-09-14 23:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_affectations_installation'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventairedepot',
            name='statut',
            field=models.CharField(default='valide', max_length=16),
        ),
        migrations.AddField(
            model_name='inventairedepot',
            name='valide_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventairedepot',
            name='valide_par',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ligneinventairedepot',
            name='valeur_stock_comptee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.CreateModel(
            name='PreparationTVA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('societe_id', models.UUIDField()),
                ('mois', models.CharField(max_length=7)),
                ('donnees', models.JSONField(default=dict)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'preparation_tva',
                'constraints': [models.UniqueConstraint(fields=('societe_id', 'mois'), name='preparation_tva_societe_mois')],
            },
        ),
    ]
