# Generated by Django 5.1.4 on 2026-09-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_applications_metier'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='categorie',
            field=models.CharField(default='metier', max_length=16),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='champs_modifies',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='chemin',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='methode',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='module',
            field=models.CharField(default='core', max_length=32),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='origine',
            field=models.CharField(default='application', max_length=16),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='requete_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='societe_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['societe_id', '-id'], name='audit_societe_id_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['utilisateur_id', '-id'], name='audit_user_id_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['horodatage'], name='audit_date_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['requete_id'], name='audit_requete_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['table_cible', 'enregistrement_id'], name='audit_document_idx'),
        ),
    ]
